package com.rsi.agp.dao.tables.comisiones.deudaAplazada;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class FaseMult  implements java.io.Serializable {


     private Long id;
     private Integer fase;
     private Integer plan;
     private FicheroMult ficheroMult;
     private Set<DetalleAbonoIndividual> detalleAbonoIndividuals = new HashSet<DetalleAbonoIndividual>(0);
     private Set<DetalleAbonoColectivo> detalleAbonoColectivos = new HashSet<DetalleAbonoColectivo>(0);

    public FaseMult() {
    }

	
    public FaseMult(Long id, FicheroMult ficheroMult, Integer fase, Integer plan) {
        this.id = id;
        this.ficheroMult = ficheroMult;
        this.fase = fase;
        this.plan = plan;
    }
    public FaseMult(Long id, FicheroMult ficheroMult, Integer fase, Integer plan, Set<DetalleAbonoIndividual> detalleAbonoIndividuals, Set<DetalleAbonoColectivo> detalleAbonoColectivos) {
       this.id = id;
       this.ficheroMult = ficheroMult;
       this.fase = fase;
       this.plan = plan;
       this.detalleAbonoIndividuals = detalleAbonoIndividuals;
       this.detalleAbonoColectivos = detalleAbonoColectivos;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getFase() {
        return this.fase;
    }
    
    public void setFase(Integer fase) {
        this.fase = fase;
    }
    public Integer getPlan() {
        return this.plan;
    }
    
    public void setPlan(Integer plan) {
        this.plan = plan;
    }
    public Set<DetalleAbonoIndividual> getDetalleAbonoIndividuals() {
        return this.detalleAbonoIndividuals;
    }
    
    public void setDetalleAbonoIndividuals(Set<DetalleAbonoIndividual> detalleAbonoIndividuals) {
        this.detalleAbonoIndividuals = detalleAbonoIndividuals;
    }
    public Set<DetalleAbonoColectivo> getDetalleAbonoColectivos() {
        return this.detalleAbonoColectivos;
    }
    
    public void setDetalleAbonoColectivos(Set<DetalleAbonoColectivo> detalleAbonoColectivos) {
        this.detalleAbonoColectivos = detalleAbonoColectivos;
    }


	public FicheroMult getFicheroMult() {
		return ficheroMult;
	}


	public void setFicheroMult(FicheroMult ficheroMult) {
		this.ficheroMult = ficheroMult;
	}




}


