package com.rsi.agp.dao.tables.sbp;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class EstadoPlzSbp implements java.io.Serializable {

	private static final long serialVersionUID = -5772053507563713832L;
	private BigDecimal idestado;
	private String descEstado;
	private Set<PolizaSbp> polizaSbps = new HashSet<PolizaSbp>(0);

	public EstadoPlzSbp() {
	}

	public EstadoPlzSbp(BigDecimal idestado) {
		this.idestado = idestado;
	}

	public EstadoPlzSbp(BigDecimal idestado, String descEstado, Set<PolizaSbp> polizaSbps) {
		this.idestado = idestado;
		this.descEstado = descEstado;
		this.polizaSbps = polizaSbps;
	}

	public BigDecimal getIdestado() {
		return this.idestado;
	}

	public void setIdestado(BigDecimal idestado) {
		this.idestado = idestado;
	}

	public String getDescEstado() {
		return this.descEstado;
	}

	public void setDescEstado(String descEstado) {
		this.descEstado = descEstado;
	}

	public Set<PolizaSbp> getPolizaSbps() {
		return this.polizaSbps;
	}

	public void setPolizaSbps(Set<PolizaSbp> polizaSbps) {
		this.polizaSbps = polizaSbps;
	}

}
