package com.rsi.agp.dao.tables.sbp;
// Generated by T-Systems

import java.util.Date;

import com.rsi.agp.dao.tables.cpl.Cultivo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class FechaContratacionSbp implements java.io.Serializable {

	private static final long serialVersionUID = -1490451404076539722L;

	private Long id;
	private Cultivo cultivo;
	private Linea linea;
	private Date fechainicio;
	private Date fechafin;
	private Date fechaFinGarantia;
	private Date fechaFinSuplementos;

	public FechaContratacionSbp() {
		linea = new Linea();
		cultivo = new Cultivo();
	}

	public FechaContratacionSbp(Long id) {
		this.id = id;
	}

	public FechaContratacionSbp(Long id, Cultivo cultivo, Linea linea, Date fechainicio, Date fechafin,
			Date fechaFinGarantia, Date fechaFinSuplementos) {
		this.id = id;
		this.cultivo = cultivo;
		this.linea = linea;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fechaFinGarantia = fechaFinGarantia;
		this.fechaFinSuplementos = fechaFinSuplementos;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Linea getLinea() {
		return this.linea;
	}

	public void setLinea(Linea linea) {
		this.linea = linea;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Date getFechaFinGarantia() {
		return this.fechaFinGarantia;
	}

	public void setFechaFinGarantia(Date fechaFinGarantia) {
		this.fechaFinGarantia = fechaFinGarantia;
	}

	public Cultivo getCultivo() {
		return cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	public Date getFechaFinSuplementos() {
		return fechaFinSuplementos;
	}

	public void setFechaFinSuplementos(Date fechaFinSuplementos) {
		this.fechaFinSuplementos = fechaFinSuplementos;
	}

}
