package com.rsi.agp.dao.tables.sbp;
// Generated by T-Systems

import com.rsi.agp.dao.tables.commons.Comarca;

import com.rsi.agp.dao.tables.cpl.Cultivo;
import com.rsi.agp.dao.tables.copy.Poliza;
import java.math.BigDecimal;

public class ParcelaSbp implements java.io.Serializable {

	private static final long serialVersionUID = -1032735391407691210L;

	private Long id;
	private Comarca comarca;
	private PolizaSbp polizaSbp;
	private Cultivo cultivo;
	private BigDecimal sobreprecio;
	private BigDecimal totalProduccion;
	private BigDecimal tasaIncendio;
	private BigDecimal primaNetaIncendio;
	private BigDecimal tasaPedrisco;
	private BigDecimal primaNetaPedrisco;
	private Poliza polizaByIdcopycom;
	private Poliza polizaByIdcopy;
	private BigDecimal primaNetaIncendioEnv;
	private BigDecimal primaNetaPedriscoEnv;

	public ParcelaSbp() {
		comarca = new Comarca();
		cultivo = new Cultivo();
	}

	public ParcelaSbp(Long id, PolizaSbp polizaSbp, Cultivo cultivo) {
		this.id = id;
		this.polizaSbp = polizaSbp;
		this.cultivo = cultivo;
	}

	public ParcelaSbp(Long id, Comarca comarca, PolizaSbp polizaSbp, Cultivo cultivo, BigDecimal sobreprecio,
			BigDecimal totalProduccion, BigDecimal tasaIncendio, BigDecimal primaNetaIncendio, BigDecimal tasaPedrisco,
			BigDecimal primaNetaPedrisco, Poliza polizaByIdcopycom, Poliza polizaByIdcopy, BigDecimal precioMax,
			BigDecimal precioMin) {
		this.id = id;
		this.comarca = comarca;
		this.polizaSbp = polizaSbp;
		this.cultivo = cultivo;
		this.sobreprecio = sobreprecio;
		this.totalProduccion = totalProduccion;
		this.tasaIncendio = tasaIncendio;
		this.primaNetaIncendio = primaNetaIncendio;
		this.tasaPedrisco = tasaPedrisco;
		this.primaNetaPedrisco = primaNetaPedrisco;
		this.polizaByIdcopycom = polizaByIdcopycom;
		this.polizaByIdcopy = polizaByIdcopy;
		this.polizaByIdcopycom = polizaByIdcopycom;
		this.polizaByIdcopy = polizaByIdcopy;

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Comarca getComarca() {
		return this.comarca;
	}

	public void setComarca(Comarca comarca) {
		this.comarca = comarca;
	}

	public PolizaSbp getPolizaSbp() {
		return this.polizaSbp;
	}

	public void setPolizaSbp(PolizaSbp polizaSbp) {
		this.polizaSbp = polizaSbp;
	}

	public Cultivo getCultivo() {
		return this.cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	public BigDecimal getSobreprecio() {
		return this.sobreprecio;
	}

	public void setSobreprecio(BigDecimal sobreprecio) {
		this.sobreprecio = sobreprecio;
	}

	public BigDecimal getTotalProduccion() {
		return this.totalProduccion;
	}

	public void setTotalProduccion(BigDecimal totalProduccion) {
		this.totalProduccion = totalProduccion;
	}

	public BigDecimal getTasaIncendio() {
		return tasaIncendio;
	}

	public void setTasaIncendio(BigDecimal tasaIncendio) {
		this.tasaIncendio = tasaIncendio;
	}

	public BigDecimal getPrimaNetaIncendio() {
		return primaNetaIncendio;
	}

	public void setPrimaNetaIncendio(BigDecimal primaNetaIncendio) {
		this.primaNetaIncendio = primaNetaIncendio;
	}

	public BigDecimal getTasaPedrisco() {
		return tasaPedrisco;
	}

	public void setTasaPedrisco(BigDecimal tasaPedrisco) {
		this.tasaPedrisco = tasaPedrisco;
	}

	public BigDecimal getPrimaNetaPedrisco() {
		return primaNetaPedrisco;
	}

	public void setPrimaNetaPedrisco(BigDecimal primaNetaPedrisco) {
		this.primaNetaPedrisco = primaNetaPedrisco;
	}

	public Poliza getPolizaByIdcopycom() {
		return polizaByIdcopycom;
	}

	public void setPolizaByIdcopycom(Poliza polizaByIdcopycom) {
		this.polizaByIdcopycom = polizaByIdcopycom;
	}

	public Poliza getPolizaByIdcopy() {
		return polizaByIdcopy;
	}

	public void setPolizaByIdcopy(Poliza polizaByIdcopy) {
		this.polizaByIdcopy = polizaByIdcopy;
	}

	public BigDecimal getPrimaNetaIncendioEnv() {
		return primaNetaIncendioEnv;
	}

	public void setPrimaNetaIncendioEnv(BigDecimal primaNetaIncendioEnv) {
		this.primaNetaIncendioEnv = primaNetaIncendioEnv;
	}

	public BigDecimal getPrimaNetaPedriscoEnv() {
		return primaNetaPedriscoEnv;
	}

	public void setPrimaNetaPedriscoEnv(BigDecimal primaNetaPedriscoEnv) {
		this.primaNetaPedriscoEnv = primaNetaPedriscoEnv;
	}

}
