package com.rsi.agp.dao.tables.sbp;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
* P0073325 -RQ.10, RQ.11 y RQ.12
*/
import com.rsi.agp.dao.tables.ged.GedDocPolizaSbp;
import com.rsi.agp.dao.tables.poliza.Poliza;

public class PolizaSbp implements java.io.Serializable {

	private static final long serialVersionUID = 5090380337184768592L;

	private Long id;
	private EstadoPlzSbp estadoPlzSbp;
	private Poliza polizaPpal;
	private Poliza polizaCpl;
	private TipoEnvio tipoEnvio;
	private Character incSbpComp;
	private Date fechaEnvioSbp;
	private Date fechaDefinitiva;
	private String referencia;
	private Date fechaProvisional;
	private BigDecimal importe;
	private BigDecimal prodTecnico;
	private BigDecimal refPlzOmega;
	private Character genSplCpl;
	private ErrorPlzSbp errorPlzSbp;
	private String usuarioProvisional;
	private String usuarioDefinitiva;
	private Set<ParcelaSbp> parcelaSbps = new HashSet<ParcelaSbp>(0);
	private com.rsi.agp.dao.tables.copy.Poliza polizaPpalCopy;
	private com.rsi.agp.dao.tables.copy.Poliza polizaCplCopy;

	/**
	* P0073325 - RQ.10, RQ.11 y RQ.12
	*/
	private GedDocPolizaSbp gedDocPolizaSbp;
	
	// private Long nSolicitud;

	public PolizaSbp() {
		polizaPpal = new Poliza();
		polizaCpl = new Poliza();
		tipoEnvio = new TipoEnvio();
		estadoPlzSbp = new EstadoPlzSbp();
	}

	public PolizaSbp(Long id, EstadoPlzSbp estadoPlzSbp, Poliza polizaPpal, Character incSbpComp, Poliza polizaCpl) {
		this.id = id;
		this.estadoPlzSbp = estadoPlzSbp;
		this.polizaPpal = polizaPpal;
		this.polizaCpl = polizaCpl;
		this.incSbpComp = incSbpComp;
		// this.nSolicitud = Long.valueOf(this.id.longValue());
	}

	public PolizaSbp(Long id, EstadoPlzSbp estadoPlzSbp, Poliza polizaPpal, Poliza polizaCpl, TipoEnvio tipoEnvio,
			Character incSbpComp, Date fechaEnvioSbp, Date fechaDefinitiva, String referencia, BigDecimal prodTecnico,
			BigDecimal refPlzOmega, Character genSplCpl, ErrorPlzSbp errorPlzSbp, Set<ParcelaSbp> parcelaSbps,
			com.rsi.agp.dao.tables.copy.Poliza polizaCplCopy, com.rsi.agp.dao.tables.copy.Poliza polizaPpalCopy,
			Date fechaProvisional, BigDecimal importe, String usuarioProvisional, String usuarioDefinitiva) {
		this.id = id;
		this.estadoPlzSbp = estadoPlzSbp;
		this.polizaPpal = polizaPpal;
		this.polizaCpl = polizaCpl;
		this.tipoEnvio = tipoEnvio;
		this.incSbpComp = incSbpComp;
		this.fechaEnvioSbp = fechaEnvioSbp;
		this.fechaDefinitiva = fechaDefinitiva;
		this.referencia = referencia;
		this.genSplCpl = genSplCpl;
		this.errorPlzSbp = errorPlzSbp;
		this.parcelaSbps = parcelaSbps;
		this.polizaCplCopy = polizaCplCopy;
		this.polizaPpalCopy = polizaPpalCopy;
		this.fechaProvisional = fechaProvisional;
		this.importe = importe;
		this.prodTecnico = prodTecnico;
		this.refPlzOmega = refPlzOmega;
		this.usuarioDefinitiva = usuarioDefinitiva;
		this.usuarioProvisional = usuarioProvisional;
		// this.nSolicitud = Long.valueOf(this.id.longValue());
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public EstadoPlzSbp getEstadoPlzSbp() {
		return this.estadoPlzSbp;
	}

	public void setEstadoPlzSbp(EstadoPlzSbp estadoPlzSbp) {
		this.estadoPlzSbp = estadoPlzSbp;
	}

	public Poliza getPolizaPpal() {
		return polizaPpal;
	}

	public void setPolizaPpal(Poliza polizaPpal) {
		this.polizaPpal = polizaPpal;
	}

	public TipoEnvio getTipoEnvio() {
		return this.tipoEnvio;
	}

	public void setTipoEnvio(TipoEnvio tipoEnvio) {
		this.tipoEnvio = tipoEnvio;
	}

	public Poliza getPolizaCpl() {
		return polizaCpl;
	}

	public void setPolizaCpl(Poliza polizaCpl) {
		this.polizaCpl = polizaCpl;
	}

	public Character getIncSbpComp() {
		return this.incSbpComp;
	}

	public void setIncSbpComp(Character incSbpComp) {
		this.incSbpComp = incSbpComp;
	}

	public Date getFechaEnvioSbp() {
		return this.fechaEnvioSbp;
	}

	public void setFechaEnvioSbp(Date fechaEnvioSbp) {
		this.fechaEnvioSbp = fechaEnvioSbp;
	}

	public Date getFechaDefinitiva() {
		return this.fechaDefinitiva;
	}

	public void setFechaDefinitiva(Date fechaDefinitiva) {
		this.fechaDefinitiva = fechaDefinitiva;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Set<ParcelaSbp> getParcelaSbps() {
		return this.parcelaSbps;
	}

	public void setParcelaSbps(Set<ParcelaSbp> parcelaSbps) {
		this.parcelaSbps = parcelaSbps;
	}

	public com.rsi.agp.dao.tables.copy.Poliza getPolizaPpalCopy() {
		return polizaPpalCopy;
	}

	public void setPolizaPpalCopy(com.rsi.agp.dao.tables.copy.Poliza polizaPpalCopy) {
		this.polizaPpalCopy = polizaPpalCopy;
	}

	public com.rsi.agp.dao.tables.copy.Poliza getPolizaCplCopy() {
		return polizaCplCopy;
	}

	public void setPolizaCplCopy(com.rsi.agp.dao.tables.copy.Poliza polizaCplCopy) {
		this.polizaCplCopy = polizaCplCopy;
	}

	public Date getFechaProvisional() {
		return fechaProvisional;
	}

	public void setFechaProvisional(Date fechaProvisional) {
		this.fechaProvisional = fechaProvisional;
	}

	public BigDecimal getImporte() {
		return importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Character getGenSplCpl() {
		return this.genSplCpl;
	}

	public void setGenSplCpl(Character genSplCpl) {
		this.genSplCpl = genSplCpl;
	}

	public ErrorPlzSbp getErrorPlzSbp() {
		return errorPlzSbp;
	}

	public void setErrorPlzSbp(ErrorPlzSbp errorPlzSbp) {
		this.errorPlzSbp = errorPlzSbp;
	}

	public void setUsuarioProvisional(String usuarioProvisional) {
		this.usuarioProvisional = usuarioProvisional;
	}

	public void setUsuarioDefinitiva(String usuarioDefinitiva) {
		this.usuarioDefinitiva = usuarioDefinitiva;
	}

	public String getUsuarioProvisional() {
		return usuarioProvisional;
	}

	public String getUsuarioDefinitiva() {
		return usuarioDefinitiva;
	}

	public BigDecimal getProdTecnico() {
		return prodTecnico;
	}

	public void setProdTecnico(BigDecimal prodTecnico) {
		this.prodTecnico = prodTecnico;
	}

	public BigDecimal getRefPlzOmega() {
		return refPlzOmega;
	}

	public void setRefPlzOmega(BigDecimal refPlzOmega) {
		this.refPlzOmega = refPlzOmega;
	}

	/*
	 * public Long getnSolicitud(){ return Long.valueOf(this.id.longValue()); }
	 */
	public Long getnSolicitud() {
		return this.id;
	}

	/**
	* P0073325 - RQ.10, RQ.11 y RQ.12
	*/
	public GedDocPolizaSbp getGedDocPolizaSbp() {
		return gedDocPolizaSbp;
	}

	public void setGedDocPolizaSbp(GedDocPolizaSbp gedDocPolizaSbp) {
		this.gedDocPolizaSbp = gedDocPolizaSbp;
	}
}
