package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

import java.math.BigDecimal;

public class CapAsegRelModulo implements java.io.Serializable {

	private static final long serialVersionUID = 2222392694106556182L;

	private Long id;
	private CapitalAsegurado capitalAsegurado;
	private String codmodulo;
	private BigDecimal precio;
	private BigDecimal produccion;
	private BigDecimal preciomodif;
	private BigDecimal produccionmodif;
	private Long tipoRdto;

	public CapAsegRelModulo() {
	}

	public CapAsegRelModulo(Long id, CapitalAsegurado capitalAsegurado, String codmodulo) {
		this.id = id;
		this.capitalAsegurado = capitalAsegurado;
		this.codmodulo = codmodulo;
	}

	public CapAsegRelModulo(Long id, CapitalAsegurado capitalAsegurado, String codmodulo, BigDecimal precio,
			BigDecimal produccion, BigDecimal preciomodif, BigDecimal produccionmodif, Long tipoRdto) {
		this.id = id;
		this.capitalAsegurado = capitalAsegurado;
		this.codmodulo = codmodulo;
		this.precio = precio;
		this.produccion = produccion;
		this.preciomodif = preciomodif;
		this.produccionmodif = produccionmodif;
		this.tipoRdto = tipoRdto;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public CapitalAsegurado getCapitalAsegurado() {
		return this.capitalAsegurado;
	}

	public void setCapitalAsegurado(CapitalAsegurado capitalAsegurado) {
		this.capitalAsegurado = capitalAsegurado;
	}

	public String getCodmodulo() {
		return this.codmodulo;
	}

	public void setCodmodulo(String codmodulo) {
		this.codmodulo = codmodulo;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getProduccion() {
		return this.produccion;
	}

	public void setProduccion(BigDecimal produccion) {
		this.produccion = produccion;
	}

	public BigDecimal getPreciomodif() {
		return this.preciomodif;
	}

	public void setPreciomodif(BigDecimal preciomodif) {
		this.preciomodif = preciomodif;
	}

	public BigDecimal getProduccionmodif() {
		return this.produccionmodif;
	}

	public void setProduccionmodif(BigDecimal produccionmodif) {
		this.produccionmodif = produccionmodif;
	}

	public Long getTipoRdto() {
		return this.tipoRdto;
	}

	public void setTipoRdto(Long tipoRdto) {
		this.tipoRdto = tipoRdto;
	}

}
