package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

public class HistoricoEstados  implements java.io.Serializable {


     private BigDecimal id;
     private Poliza poliza;
     private String codusuario;
     private Date fecha;
     private BigDecimal estado;

    public HistoricoEstados() {
    }

	
    public HistoricoEstados(BigDecimal id, Poliza poliza, Date fecha, BigDecimal estado) {
        this.id = id;
        this.poliza = poliza;
        this.fecha = fecha;
        this.estado = estado;
    }
    public HistoricoEstados(BigDecimal id, Poliza poliza, String codusuario, Date fecha, BigDecimal estado) {
       this.id = id;
       this.poliza = poliza;
       this.codusuario = codusuario;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }




}


