package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

public class LineaGrupoNegocioId implements java.io.Serializable {

	private static final long serialVersionUID = 1637865090397181365L;

	private long lineaseguroid;
	private Character grupoNegocio;

	public LineaGrupoNegocioId() {
	}

	public LineaGrupoNegocioId(long lineaseguroid, Character grupoNegocio) {
		this.lineaseguroid = lineaseguroid;
		this.grupoNegocio = grupoNegocio;
	}

	public long getLineaseguroid() {
		return this.lineaseguroid;
	}

	public void setLineaseguroid(long lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	public Character getGrupoNegocio() {
		return this.grupoNegocio;
	}

	public void setGrupoNegocio(Character grupoNegocio) {
		this.grupoNegocio = grupoNegocio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineaGrupoNegocioId))
			return false;
		LineaGrupoNegocioId castOther = (LineaGrupoNegocioId) other;

		return (this.getLineaseguroid() == castOther.getLineaseguroid())
				&& ((this.getGrupoNegocio() == castOther.getGrupoNegocio())
						|| (this.getGrupoNegocio() != null && castOther.getGrupoNegocio() != null
								&& this.getGrupoNegocio().equals(castOther.getGrupoNegocio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLineaseguroid();
		result = 37 * result + (getGrupoNegocio() == null ? 0 : this.getGrupoNegocio().hashCode());
		return result;
	}

}
