package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

import java.sql.Clob;
import java.util.Date;

public class ModuloPolizaCoberturaSW implements java.io.Serializable {

	private static final long serialVersionUID = -480653066444527157L;

	private ModuloPolizaId id;
	private transient Clob envio;
	private transient Clob respuesta;
	private String usuario;
	private Date fecha;
	private Integer operacion;
	
	public ModuloPolizaCoberturaSW() {
		super();
	}

	public ModuloPolizaId getId() {
		return this.id;
	}

	public void setId(ModuloPolizaId id) {
		this.id = id;
	}

	public Clob getEnvio() {
		return this.envio;
	}

	public void setEnvio(Clob envio) {
		this.envio = envio;
	}

	public Clob getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(Clob respuesta) {
		this.respuesta = respuesta;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getOperacion() {
		return operacion;
	}

	public void setOperacion(Integer operacion) {
		this.operacion = operacion;
	}
}