package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

import java.math.BigDecimal;

import com.rsi.agp.dao.tables.cgen.ConceptoPpalModulo;
import com.rsi.agp.dao.tables.cpl.RiesgoCubierto;
import com.rsi.agp.dao.tables.org.DiccionarioDatos;

public class ParcelaCobertura implements java.io.Serializable {

	private static final long serialVersionUID = 3156508813289198913L;

	private Long id;
	private DiccionarioDatos diccionarioDatos;
	private ConceptoPpalModulo conceptoPpalModulo;
	private Parcela parcela;
	private RiesgoCubierto riesgoCubierto;
	private BigDecimal codvalor;

	public ParcelaCobertura() {
	}

	public ParcelaCobertura(Long id, DiccionarioDatos diccionarioDatos, ConceptoPpalModulo conceptoPpalModulo,
			Parcela parcela, RiesgoCubierto riesgoCubierto, BigDecimal codvalor) {
		this.id = id;
		this.diccionarioDatos = diccionarioDatos;
		this.conceptoPpalModulo = conceptoPpalModulo;
		this.parcela = parcela;
		this.riesgoCubierto = riesgoCubierto;
		this.codvalor = codvalor;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DiccionarioDatos getDiccionarioDatos() {
		return this.diccionarioDatos;
	}

	public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
		this.diccionarioDatos = diccionarioDatos;
	}

	public ConceptoPpalModulo getConceptoPpalModulo() {
		return this.conceptoPpalModulo;
	}

	public void setConceptoPpalModulo(ConceptoPpalModulo conceptoPpalModulo) {
		this.conceptoPpalModulo = conceptoPpalModulo;
	}

	public Parcela getParcela() {
		return this.parcela;
	}

	public void setParcela(Parcela parcela) {
		this.parcela = parcela;
	}

	public RiesgoCubierto getRiesgoCubierto() {
		return this.riesgoCubierto;
	}

	public void setRiesgoCubierto(RiesgoCubierto riesgoCubierto) {
		this.riesgoCubierto = riesgoCubierto;
	}

	public BigDecimal getCodvalor() {
		return this.codvalor;
	}

	public void setCodvalor(BigDecimal codvalor) {
		this.codvalor = codvalor;
	}

}
