package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

import java.sql.Clob;
import java.util.Date;

public class ParcelaSWZonifSIGPAC implements java.io.Serializable {

	private static final long serialVersionUID = -3006610119054354069L;
	private Long id;
	private Parcela parcela;
	private String usuario;
	private Date fecha;
	private transient Clob xmlEnvio;
	private transient Clob xmlRespuesta;

	public ParcelaSWZonifSIGPAC() {
		super();
	}

	public ParcelaSWZonifSIGPAC(Long id, Parcela parcela, String usuario, Date fecha) {
		this();
		this.id = id;
		this.parcela = parcela;
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Parcela getParcela() {
		return this.parcela;
	}

	public void setParcela(Parcela parcela) {
		this.parcela = parcela;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Clob getXmlEnvio() {
		return this.xmlEnvio;
	}

	public void setXmlEnvio(Clob xmlEnvio) {
		this.xmlEnvio = xmlEnvio;
	}

	public Clob getXmlRespuesta() {
		return this.xmlRespuesta;
	}

	public void setXmlRespuesta(Clob xmlRespuesta) {
		this.xmlRespuesta = xmlRespuesta;
	}

}
