package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems



public class PolizasInfoHojaCampoTipoSituacionId  implements java.io.Serializable {


     private Integer tipoSituacionHoja;
     private Integer tipoHoja;

    public PolizasInfoHojaCampoTipoSituacionId() {
    }

    public PolizasInfoHojaCampoTipoSituacionId(Integer tipoSituacionHoja, Integer tipoHoja) {
       this.tipoSituacionHoja = tipoSituacionHoja;
       this.tipoHoja = tipoHoja;
    }
   
    public Integer getTipoSituacionHoja() {
        return this.tipoSituacionHoja;
    }
    
    public void setTipoSituacionHoja(Integer tipoSituacionHoja) {
        this.tipoSituacionHoja = tipoSituacionHoja;
    }
    public Integer getTipoHoja() {
        return this.tipoHoja;
    }
    
    public void setTipoHoja(Integer tipoHoja) {
        this.tipoHoja = tipoHoja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PolizasInfoHojaCampoTipoSituacionId) ) return false;
		 PolizasInfoHojaCampoTipoSituacionId castOther = ( PolizasInfoHojaCampoTipoSituacionId ) other; 
         
		 return ( (this.getTipoSituacionHoja()==castOther.getTipoSituacionHoja()) || ( this.getTipoSituacionHoja()!=null && castOther.getTipoSituacionHoja()!=null && this.getTipoSituacionHoja().equals(castOther.getTipoSituacionHoja()) ) )
 && ( (this.getTipoHoja()==castOther.getTipoHoja()) || ( this.getTipoHoja()!=null && castOther.getTipoHoja()!=null && this.getTipoHoja().equals(castOther.getTipoHoja()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipoSituacionHoja() == null ? 0 : this.getTipoSituacionHoja().hashCode() );
         result = 37 * result + ( getTipoHoja() == null ? 0 : this.getTipoHoja().hashCode() );
         return result;
   }   


}


