package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems

import java.math.BigDecimal;

public class PolizaPctComisiones implements java.io.Serializable {

	private static final long serialVersionUID = 3751336831481501794L;

	private Long id;
	private Poliza poliza;
	private BigDecimal pctadministracion;
	private BigDecimal pctadquisicion;
	private BigDecimal pctcommax;
	private BigDecimal pctdescmax;
	private BigDecimal pctentidad;
	private BigDecimal pctesmediadora;
	private BigDecimal pctdescelegido;
	private Long estado;
	private BigDecimal pctrecarelegido;
	private Character grupoNegocio;
	private String descGrupoNegocio;

	public PolizaPctComisiones() {
		poliza = new Poliza();
	}

	public PolizaPctComisiones(Long id, Poliza poliza, BigDecimal pctadministracion, BigDecimal pctadquisicion,
			BigDecimal pctcommax, Character grupoNegocio) {
		this.id = id;
		this.poliza = poliza;
		this.pctadministracion = pctadministracion;
		this.pctadquisicion = pctadquisicion;
		this.pctcommax = pctcommax;
		this.grupoNegocio = grupoNegocio;
	}

	public PolizaPctComisiones(Long id, Poliza poliza, BigDecimal pctadministracion, BigDecimal pctadquisicion,
			BigDecimal pctcommax, BigDecimal pctdescmax, BigDecimal pctentidad, BigDecimal pctesmediadora,
			BigDecimal pctdescelegido, Long estado, BigDecimal pctrecarelegido, Character grupoNegocio) {
		this.id = id;
		this.poliza = poliza;
		this.pctadministracion = pctadministracion;
		this.pctadquisicion = pctadquisicion;
		this.pctcommax = pctcommax;
		this.pctdescmax = pctdescmax;
		this.pctentidad = pctentidad;
		this.pctesmediadora = pctesmediadora;
		this.pctdescelegido = pctdescelegido;
		this.estado = estado;
		this.pctrecarelegido = pctrecarelegido;
		this.grupoNegocio = grupoNegocio;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Poliza getPoliza() {
		return this.poliza;
	}

	public void setPoliza(Poliza poliza) {
		this.poliza = poliza;
	}

	public BigDecimal getPctadministracion() {
		return this.pctadministracion;
	}

	public void setPctadministracion(BigDecimal pctadministracion) {
		this.pctadministracion = pctadministracion;
	}

	public BigDecimal getPctadquisicion() {
		return this.pctadquisicion;
	}

	public void setPctadquisicion(BigDecimal pctadquisicion) {
		this.pctadquisicion = pctadquisicion;
	}

	public BigDecimal getPctcommax() {
		return this.pctcommax;
	}

	public void setPctcommax(BigDecimal pctcommax) {
		this.pctcommax = pctcommax;
	}

	public BigDecimal getPctdescmax() {
		return this.pctdescmax;
	}

	public void setPctdescmax(BigDecimal pctdescmax) {
		this.pctdescmax = pctdescmax;
	}

	public BigDecimal getPctentidad() {
		return this.pctentidad;
	}

	public void setPctentidad(BigDecimal pctentidad) {
		this.pctentidad = pctentidad;
	}

	public BigDecimal getPctesmediadora() {
		return this.pctesmediadora;
	}

	public void setPctesmediadora(BigDecimal pctesmediadora) {
		this.pctesmediadora = pctesmediadora;
	}

	public BigDecimal getPctdescelegido() {
		return this.pctdescelegido;
	}

	public void setPctdescelegido(BigDecimal pctdescelegido) {
		this.pctdescelegido = pctdescelegido;
	}

	public Long getEstado() {
		return this.estado;
	}

	public void setEstado(Long estado) {
		this.estado = estado;
	}

	public BigDecimal getPctrecarelegido() {
		return this.pctrecarelegido;
	}

	public void setPctrecarelegido(BigDecimal pctrecarelegido) {
		this.pctrecarelegido = pctrecarelegido;
	}

	public Character getGrupoNegocio() {
		return this.grupoNegocio;
	}

	public void setGrupoNegocio(Character grupoNegocio) {
		this.grupoNegocio = grupoNegocio;
	}

	public String getDescGrupoNegocio() {
		return descGrupoNegocio;
	}

	public void setDescGrupoNegocio(String descGrupoNegocio) {
		this.descGrupoNegocio = descGrupoNegocio;
	}

}
