package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class PolizasInfoHojaCampoTipoSituacion  implements java.io.Serializable {


     private PolizasInfoHojaCampoTipoSituacionId id;
     private PolizasInfoHojaCampoTipoHoja polizasInfoHojaCampoTipoHoja;
     private String descripcion;
     private String abreviado;
     private Set<PolizasInfoHojaCampoSituacion> polizasInfoHojaCampoSituacions = new HashSet<PolizasInfoHojaCampoSituacion>(0);

    public PolizasInfoHojaCampoTipoSituacion() {
    }

	
    public PolizasInfoHojaCampoTipoSituacion(PolizasInfoHojaCampoTipoSituacionId id, PolizasInfoHojaCampoTipoHoja polizasInfoHojaCampoTipoHoja, String descripcion, String abreviado) {
        this.id = id;
        this.polizasInfoHojaCampoTipoHoja = polizasInfoHojaCampoTipoHoja;
        this.descripcion = descripcion;
        this.abreviado = abreviado;
    }
    public PolizasInfoHojaCampoTipoSituacion(PolizasInfoHojaCampoTipoSituacionId id, PolizasInfoHojaCampoTipoHoja polizasInfoHojaCampoTipoHoja, String descripcion, String abreviado, Set<PolizasInfoHojaCampoSituacion> polizasInfoHojaCampoSituacions) {
       this.id = id;
       this.polizasInfoHojaCampoTipoHoja = polizasInfoHojaCampoTipoHoja;
       this.descripcion = descripcion;
       this.abreviado = abreviado;
       this.polizasInfoHojaCampoSituacions = polizasInfoHojaCampoSituacions;
    }
   
    public PolizasInfoHojaCampoTipoSituacionId getId() {
        return this.id;
    }
    
    public void setId(PolizasInfoHojaCampoTipoSituacionId id) {
        this.id = id;
    }
    public PolizasInfoHojaCampoTipoHoja getPolizasInfoHojaCampoTipoHoja() {
        return this.polizasInfoHojaCampoTipoHoja;
    }
    
    public void setPolizasInfoHojaCampoTipoHoja(PolizasInfoHojaCampoTipoHoja polizasInfoHojaCampoTipoHoja) {
        this.polizasInfoHojaCampoTipoHoja = polizasInfoHojaCampoTipoHoja;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviado() {
        return this.abreviado;
    }
    
    public void setAbreviado(String abreviado) {
        this.abreviado = abreviado;
    }
    public Set<PolizasInfoHojaCampoSituacion> getPolizasInfoHojaCampoSituacions() {
        return this.polizasInfoHojaCampoSituacions;
    }
    
    public void setPolizasInfoHojaCampoSituacions(Set<PolizasInfoHojaCampoSituacion> polizasInfoHojaCampoSituacions) {
        this.polizasInfoHojaCampoSituacions = polizasInfoHojaCampoSituacions;
    }




}


