package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems


import com.rsi.agp.dao.tables.admin.Socio;
import com.rsi.agp.dao.tables.cpl.gan.SubvencionEnesaGanado;

public class SubvencionSocioGanado  implements java.io.Serializable {


     private Long id;
     private SubvencionEnesaGanado subvencionEnesaGanado;
     private Poliza poliza;
     private Socio socio;

    public SubvencionSocioGanado() {
    }

    public SubvencionSocioGanado(Long id, SubvencionEnesaGanado subvencionEnesaGanado, Poliza poliza, Socio socio) {
       this.id = id;
       this.subvencionEnesaGanado = subvencionEnesaGanado;
       this.poliza = poliza;
       this.socio = socio;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public SubvencionEnesaGanado getSubvencionEnesaGanado() {
        return this.subvencionEnesaGanado;
    }
    
    public void setSubvencionEnesaGanado(SubvencionEnesaGanado subvencionEnesaGanado) {
        this.subvencionEnesaGanado = subvencionEnesaGanado;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public Socio getSocio() {
        return this.socio;
    }
    
    public void setSocio(Socio socio) {
        this.socio = socio;
    }




}


