package com.rsi.agp.dao.tables.poliza;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

public class VistaPlzHojaCampoActaTasacionId  implements java.io.Serializable {

	
     private Long idpoliza;
     private String referencia;
     private Long plan;
     private Long tipoRegistro;
     private String nif;
     private Long numHojaCampo;
     private Date fechaTasacion;
     private Long tipoHoja;
     private String tipoHojaDesc;
     private Long situacionHoja;
     private String situacionHojaDesc;
     private Long serie;
     private Long numActa;
     private Date fechaActa;
     private Long situacionActa;
     private String situacionActaDes;
     private BigDecimal importe;
     private BigDecimal importeRegularizado;
     private Date fechaPago;

     private Poliza poliza;
    public VistaPlzHojaCampoActaTasacionId() {
    }

    public VistaPlzHojaCampoActaTasacionId(Long idpoliza, String referencia, Long plan, Long tipoRegistro, String nif, Long numHojaCampo, Date fechaTasacion, Long tipoHoja, String tipoHojaDesc, Long situacionHoja, String situacionHojaDesc, Long serie, Long numActa, Date fechaActa, Long situacionActa, String situacionActaDes, BigDecimal importe, BigDecimal importeRegularizado, Date fechaPago) {
       this.idpoliza = idpoliza;
       this.referencia=referencia;
       this.plan=plan;
       this.tipoRegistro = tipoRegistro;
       this.nif = nif;
       this.numHojaCampo = numHojaCampo;
       this.fechaTasacion = fechaTasacion;
       this.tipoHoja = tipoHoja;
       this.tipoHojaDesc = tipoHojaDesc;
       this.situacionHoja = situacionHoja;
       this.situacionHojaDesc = situacionHojaDesc;
       this.serie = serie;
       this.numActa = numActa;
       this.fechaActa = fechaActa;
       this.situacionActa = situacionActa;
       this.situacionActaDes = situacionActaDes;
       this.importe = importe;
       this.importeRegularizado = importeRegularizado;
       this.fechaPago = fechaPago;
    }
   
    public Long getIdpoliza() {
        return this.idpoliza;
    }
    
    public void setIdpoliza(Long idpoliza) {
        this.idpoliza = idpoliza;
    }
    public Long getTipoRegistro() {
        return this.tipoRegistro;
    }
    
    public void setTipoRegistro(Long tipoRegistro) {
        this.tipoRegistro = tipoRegistro;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public Long getNumHojaCampo() {
        return this.numHojaCampo;
    }
    
    public void setNumHojaCampo(Long numHojaCampo) {
        this.numHojaCampo = numHojaCampo;
    }
    public Date getFechaTasacion() {
        return this.fechaTasacion;
    }
    
    public void setFechaTasacion(Date fechaTasacion) {
        this.fechaTasacion = fechaTasacion;
    }
    public Long getTipoHoja() {
        return this.tipoHoja;
    }
    
    public void setTipoHoja(Long tipoHoja) {
        this.tipoHoja = tipoHoja;
    }
    public String getTipoHojaDesc() {
        return this.tipoHojaDesc;
    }
    
    public void setTipoHojaDesc(String tipoHojaDesc) {
        this.tipoHojaDesc = tipoHojaDesc;
    }
    public Long getSituacionHoja() {
        return this.situacionHoja;
    }
    
    public void setSituacionHoja(Long situacionHoja) {
        this.situacionHoja = situacionHoja;
    }
    public String getSituacionHojaDesc() {
        return this.situacionHojaDesc;
    }
    
    public void setSituacionHojaDesc(String situacionHojaDesc) {
        this.situacionHojaDesc = situacionHojaDesc;
    }
    public Long getSerie() {
        return this.serie;
    }
    
    public void setSerie(Long serie) {
        this.serie = serie;
    }
    public Long getNumActa() {
        return this.numActa;
    }
    
    public void setNumActa(Long numActa) {
        this.numActa = numActa;
    }
    public Date getFechaActa() {
        return this.fechaActa;
    }
    
    public void setFechaActa(Date fechaActa) {
        this.fechaActa = fechaActa;
    }
    public Long getSituacionActa() {
        return this.situacionActa;
    }
    
    public void setSituacionActa(Long situacionActa) {
        this.situacionActa = situacionActa;
    }
    public String getSituacionActaDes() {
        return this.situacionActaDes;
    }
    
    public void setSituacionActaDes(String situacionActaDes) {
        this.situacionActaDes = situacionActaDes;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public BigDecimal getImporteRegularizado() {
        return this.importeRegularizado;
    }
    
    public void setImporteRegularizado(BigDecimal importeRegularizado) {
        this.importeRegularizado = importeRegularizado;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }


public Poliza getPoliza() {
	return poliza;
}

public void setPoliza(Poliza poliza) {
	this.poliza = poliza;
}

public String getReferencia() {
	return referencia;
}

public void setReferencia(String referencia) {
	this.referencia = referencia;
}

public Long getPlan() {
	return plan;
}

public void setPlan(Long plan) {
	this.plan = plan;
}

@Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((fechaActa == null) ? 0 : fechaActa.hashCode());
	result = prime * result + ((fechaPago == null) ? 0 : fechaPago.hashCode());
	result = prime * result
			+ ((fechaTasacion == null) ? 0 : fechaTasacion.hashCode());
	result = prime * result + ((idpoliza == null) ? 0 : idpoliza.hashCode());
	result = prime * result + ((importe == null) ? 0 : importe.hashCode());
	result = prime
			* result
			+ ((importeRegularizado == null) ? 0 : importeRegularizado
					.hashCode());
	result = prime * result + ((nif == null) ? 0 : nif.hashCode());
	result = prime * result + ((numActa == null) ? 0 : numActa.hashCode());
	result = prime * result
			+ ((numHojaCampo == null) ? 0 : numHojaCampo.hashCode());
	result = prime * result + ((plan == null) ? 0 : plan.hashCode());
	result = prime * result
			+ ((referencia == null) ? 0 : referencia.hashCode());
	result = prime * result + ((serie == null) ? 0 : serie.hashCode());
	result = prime * result
			+ ((situacionActa == null) ? 0 : situacionActa.hashCode());
	result = prime * result
			+ ((situacionActaDes == null) ? 0 : situacionActaDes.hashCode());
	result = prime * result
			+ ((situacionHoja == null) ? 0 : situacionHoja.hashCode());
	result = prime * result
			+ ((situacionHojaDesc == null) ? 0 : situacionHojaDesc.hashCode());
	result = prime * result + ((tipoHoja == null) ? 0 : tipoHoja.hashCode());
	result = prime * result
			+ ((tipoHojaDesc == null) ? 0 : tipoHojaDesc.hashCode());
	result = prime * result
			+ ((tipoRegistro == null) ? 0 : tipoRegistro.hashCode());
	return result;
}

@Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	VistaPlzHojaCampoActaTasacionId other = (VistaPlzHojaCampoActaTasacionId) obj;
	if (fechaActa == null) {
		if (other.fechaActa != null)
			return false;
	} else if (!fechaActa.equals(other.fechaActa))
		return false;
	if (fechaPago == null) {
		if (other.fechaPago != null)
			return false;
	} else if (!fechaPago.equals(other.fechaPago))
		return false;
	if (fechaTasacion == null) {
		if (other.fechaTasacion != null)
			return false;
	} else if (!fechaTasacion.equals(other.fechaTasacion))
		return false;
	if (idpoliza == null) {
		if (other.idpoliza != null)
			return false;
	} else if (!idpoliza.equals(other.idpoliza))
		return false;
	if (importe == null) {
		if (other.importe != null)
			return false;
	} else if (!importe.equals(other.importe))
		return false;
	if (importeRegularizado == null) {
		if (other.importeRegularizado != null)
			return false;
	} else if (!importeRegularizado.equals(other.importeRegularizado))
		return false;
	if (nif == null) {
		if (other.nif != null)
			return false;
	} else if (!nif.equals(other.nif))
		return false;
	if (numActa == null) {
		if (other.numActa != null)
			return false;
	} else if (!numActa.equals(other.numActa))
		return false;
	if (numHojaCampo == null) {
		if (other.numHojaCampo != null)
			return false;
	} else if (!numHojaCampo.equals(other.numHojaCampo))
		return false;
	if (plan == null) {
		if (other.plan != null)
			return false;
	} else if (!plan.equals(other.plan))
		return false;
	if (referencia == null) {
		if (other.referencia != null)
			return false;
	} else if (!referencia.equals(other.referencia))
		return false;
	if (serie == null) {
		if (other.serie != null)
			return false;
	} else if (!serie.equals(other.serie))
		return false;
	if (situacionActa == null) {
		if (other.situacionActa != null)
			return false;
	} else if (!situacionActa.equals(other.situacionActa))
		return false;
	if (situacionActaDes == null) {
		if (other.situacionActaDes != null)
			return false;
	} else if (!situacionActaDes.equals(other.situacionActaDes))
		return false;
	if (situacionHoja == null) {
		if (other.situacionHoja != null)
			return false;
	} else if (!situacionHoja.equals(other.situacionHoja))
		return false;
	if (situacionHojaDesc == null) {
		if (other.situacionHojaDesc != null)
			return false;
	} else if (!situacionHojaDesc.equals(other.situacionHojaDesc))
		return false;
	if (tipoHoja == null) {
		if (other.tipoHoja != null)
			return false;
	} else if (!tipoHoja.equals(other.tipoHoja))
		return false;
	if (tipoHojaDesc == null) {
		if (other.tipoHojaDesc != null)
			return false;
	} else if (!tipoHojaDesc.equals(other.tipoHojaDesc))
		return false;
	if (tipoRegistro == null) {
		if (other.tipoRegistro != null)
			return false;
	} else if (!tipoRegistro.equals(other.tipoRegistro))
		return false;
	return true;
}   



}


