package com.rsi.agp.dao.tables.mtoinf;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class VistaCampo  implements java.io.Serializable {


     private BigDecimal id;
     private Vista vista;
     private VistaCampoTipo vistaCampoTipo;
     private String nombre;
     private String nombreRealCampo;
     private String tablaOrigen;
     private BigDecimal visible;
     private BigDecimal origen_datos;
     private Set<CamposPermitidos> camposPermitidoses = new HashSet<CamposPermitidos>(0);
     private Set<OperadorCamposPermitido> operadorCamposPermitidos = new HashSet<OperadorCamposPermitido>(0);
     private Set<RelVistaCampos> relVistaCamposesForIdcampo2 = new HashSet<RelVistaCampos>(0);
     private Set<RelVistaCampos> relVistaCamposesForIdcampo1 = new HashSet<RelVistaCampos>(0);

    public VistaCampo() {
    	vista = new Vista();
    	vistaCampoTipo = new VistaCampoTipo();
    }

	
    public VistaCampo(BigDecimal id, Vista vista, VistaCampoTipo vistaCampoTipo, String nombre, String nombreRealCampo, String tablaOrigen, 
    				  BigDecimal visible, BigDecimal origen_datos) {
        this.id = id;
        this.vista = vista;
        this.vistaCampoTipo = vistaCampoTipo;
        this.nombre = nombre;
        this.nombreRealCampo = nombreRealCampo;
        this.tablaOrigen = tablaOrigen;
        this.visible = visible;
        this.origen_datos = origen_datos;
    }
    
    public VistaCampo(BigDecimal id, Vista vista, VistaCampoTipo vistaCampoTipo, String nombre, String nombreRealCampo, String tablaOrigen, 
    					BigDecimal visible, BigDecimal origen_datos, Set<CamposPermitidos> camposPermitidoses, Set<OperadorCamposPermitido> operadorCamposPermitidos, Set<RelVistaCampos> relVistaCamposesForIdcampo2, Set<RelVistaCampos> relVistaCamposesForIdcampo1) {
       this.id = id;
       this.vista = vista;
       this.vistaCampoTipo = vistaCampoTipo;
       this.nombre = nombre;
       this.nombreRealCampo = nombreRealCampo;
       this.tablaOrigen = tablaOrigen;
       this.visible = visible;
       this.origen_datos = origen_datos;
       this.camposPermitidoses = camposPermitidoses;
       this.operadorCamposPermitidos = operadorCamposPermitidos;
       this.relVistaCamposesForIdcampo2 = relVistaCamposesForIdcampo2;
       this.relVistaCamposesForIdcampo1 = relVistaCamposesForIdcampo1;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Vista getVista() {
        return this.vista;
    }
    
    public void setVista(Vista vista) {
        this.vista = vista;
    }
    public VistaCampoTipo getVistaCampoTipo() {
        return this.vistaCampoTipo;
    }
    
    public void setVistaCampoTipo(VistaCampoTipo vistaCampoTipo) {
        this.vistaCampoTipo = vistaCampoTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreRealCampo() {
        return this.nombreRealCampo;
    }
    
    public void setNombreRealCampo(String nombreRealCampo) {
        this.nombreRealCampo = nombreRealCampo;
    }
    public String getTablaOrigen() {
        return this.tablaOrigen;
    }
    
    public void setTablaOrigen(String tablaOrigen) {
        this.tablaOrigen = tablaOrigen;
    }
    public BigDecimal getVisible() {
        return this.visible;
    }
    
    public void setVisible(BigDecimal visible) {
        this.visible = visible;
    }
    public Set<CamposPermitidos> getCamposPermitidoses() {
        return this.camposPermitidoses;
    }
    
    public void setCamposPermitidoses(Set<CamposPermitidos> camposPermitidoses) {
        this.camposPermitidoses = camposPermitidoses;
    }
    public Set<OperadorCamposPermitido> getOperadorCamposPermitidos() {
        return this.operadorCamposPermitidos;
    }
    
    public void setOperadorCamposPermitidos(Set<OperadorCamposPermitido> operadorCamposPermitidos) {
        this.operadorCamposPermitidos = operadorCamposPermitidos;
    }
    public Set<RelVistaCampos> getRelVistaCamposesForIdcampo2() {
        return this.relVistaCamposesForIdcampo2;
    }
    
    public void setRelVistaCamposesForIdcampo2(Set<RelVistaCampos> relVistaCamposesForIdcampo2) {
        this.relVistaCamposesForIdcampo2 = relVistaCamposesForIdcampo2;
    }
    public Set<RelVistaCampos> getRelVistaCamposesForIdcampo1() {
        return this.relVistaCamposesForIdcampo1;
    }
    
    public void setRelVistaCamposesForIdcampo1(Set<RelVistaCampos> relVistaCamposesForIdcampo1) {
        this.relVistaCamposesForIdcampo1 = relVistaCamposesForIdcampo1;
    }


	public BigDecimal getOrigen_datos() {
		return origen_datos;
	}


	public void setOrigen_datos(BigDecimal origen_datos) {
		this.origen_datos = origen_datos;
	}




}


