package com.rsi.agp.dao.tables.mtoinf;
// Generated by T-Systems


import java.math.BigDecimal;

public class VistaMtoinfClasificacionRupturaId  implements java.io.Serializable {


     private BigDecimal permitidocalculado;
     private BigDecimal iddatoInforme;

    public VistaMtoinfClasificacionRupturaId() {
    }

    public VistaMtoinfClasificacionRupturaId(BigDecimal permitidocalculado, BigDecimal iddatoInforme) {
       this.permitidocalculado = permitidocalculado;
       this.iddatoInforme = iddatoInforme;
    }
   
    public BigDecimal getPermitidocalculado() {
        return this.permitidocalculado;
    }
    
    public void setPermitidocalculado(BigDecimal permitidocalculado) {
        this.permitidocalculado = permitidocalculado;
    }
    public BigDecimal getIddatoInforme() {
        return this.iddatoInforme;
    }
    
    public void setIddatoInforme(BigDecimal iddatoInforme) {
        this.iddatoInforme = iddatoInforme;
    }
    


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VistaMtoinfClasificacionRupturaId) ) return false;
		 VistaMtoinfClasificacionRupturaId castOther = ( VistaMtoinfClasificacionRupturaId ) other; 
         
		 return ( (this.getPermitidocalculado()==castOther.getPermitidocalculado()) || ( this.getPermitidocalculado()!=null && castOther.getPermitidocalculado()!=null && this.getPermitidocalculado().equals(castOther.getPermitidocalculado()) ) )
 && ( (this.getIddatoInforme()==castOther.getIddatoInforme()) || ( this.getIddatoInforme()!=null && castOther.getIddatoInforme()!=null && this.getIddatoInforme().equals(castOther.getIddatoInforme()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPermitidocalculado() == null ? 0 : this.getPermitidocalculado().hashCode() );
         result = 37 * result + ( getIddatoInforme() == null ? 0 : this.getIddatoInforme().hashCode() );
         return result;
   }   


}


