package com.rsi.agp.dao.tables.mtoinf;
// Generated by T-Systems


import java.math.BigDecimal;

public class VistaMtoinfCondicionesId  implements java.io.Serializable {


     private BigDecimal permitidocalculado;
     private BigDecimal condid;
     

    public VistaMtoinfCondicionesId() {
    }

    public VistaMtoinfCondicionesId(BigDecimal permitidocalculado, BigDecimal condid) {
       this.permitidocalculado = permitidocalculado;
       this.condid = condid;
    }
   
    public BigDecimal getPermitidocalculado() {
        return this.permitidocalculado;
    }
    
    public void setPermitidocalculado(BigDecimal permitidocalculado) {
        this.permitidocalculado = permitidocalculado;
    }
    public BigDecimal getCondid() {
        return this.condid;
    }
    
    public void setCondid(BigDecimal condid) {
        this.condid = condid;
    }
    


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VistaMtoinfCondicionesId) ) return false;
		 VistaMtoinfCondicionesId castOther = ( VistaMtoinfCondicionesId ) other; 
         
		 return ( (this.getPermitidocalculado()==castOther.getPermitidocalculado()) || ( this.getPermitidocalculado()!=null && castOther.getPermitidocalculado()!=null && this.getPermitidocalculado().equals(castOther.getPermitidocalculado()) ) )
 && ( (this.getCondid()==castOther.getCondid()) || ( this.getCondid()!=null && castOther.getCondid()!=null && this.getCondid().equals(castOther.getCondid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPermitidocalculado() == null ? 0 : this.getPermitidocalculado().hashCode() );
         result = 37 * result + ( getCondid() == null ? 0 : this.getCondid().hashCode() );
         return result;
   }   


}


