package com.rsi.agp.dao.tables.anexo;
// Generated by T-Systems


import java.math.BigDecimal;

public class AnexoModSubvCCAA  implements java.io.Serializable {


     private AnexoModSubvCCAAId id;
     private AnexoModDistribucionCostes anexoModDistribucionCostes;
     private BigDecimal importe;
     private String descripcion;
     
    public AnexoModSubvCCAA() {
    }

    public AnexoModSubvCCAA(AnexoModSubvCCAAId id, AnexoModDistribucionCostes anexoModDistribucionCostes, BigDecimal importe) {
       this.id = id;
       this.anexoModDistribucionCostes = anexoModDistribucionCostes;
       this.importe = importe;
    }
    
    public AnexoModSubvCCAAId getId() {
        return this.id;
    }
    
    public void setId(AnexoModSubvCCAAId id) {
        this.id = id;
    }
    public AnexoModDistribucionCostes getAnexoModDistribucionCostes() {
        return this.anexoModDistribucionCostes;
    }
    
    public void setAnexoModDistribucionCostes(AnexoModDistribucionCostes anexoModDistribucionCostes) {
        this.anexoModDistribucionCostes = anexoModDistribucionCostes;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}


