package com.rsi.agp.dao.tables.anexo;

// Generated by T-Systems

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.rsi.agp.dao.tables.inc.EstadosInc;
import com.rsi.agp.dao.tables.poliza.Comunicaciones;
import com.rsi.agp.dao.tables.poliza.Poliza;
import com.rsi.agp.dao.tables.poliza.explotaciones.ExplotacionAnexo;
import com.rsi.agp.dao.tables.poliza.explotaciones.GrupoRazaAnexo;

public class AnexoModificacion implements java.io.Serializable {

	private static final long serialVersionUID = -1941094123933206007L;

	private Long id;
	private EstadosInc estadoAgroseguro;
	private Cupon cupon;
	private Comunicaciones comunicaciones;
	private Estado estado;
	private Poliza poliza;
	private Long idcopy;
	private Date fechafirmadoc;
	private String asunto;
	private String nomaseg;
	private String apel1aseg;
	private String apel2aseg;
	private String razsocaseg;
	private String calleaseg;
	private String numaseg;
	private BigDecimal codprovincia;
	private BigDecimal codlocalidad;
	private String codposaseg;
	private String pisoaseg;
	private String bloqueaseg;
	private String escaseg;
	private String telffijoaseg;
	private String telfmovilaseg;
	private String email;
	private String numsegsocial;
	private String regimensegsocial;
	private String codmodulo;
	private transient Clob xml;
	private String nomlocalidad;
	private String tipoEnvio;
	private Date fechaAlta;
	private String usuarioAlta;
	private Date fechaBaja;
	private String usuarioBaja;
	private Character revisarSbp;
	private String usuarioDefinitiva;
	private Date fechaDefinitiva;
	private BigDecimal pctadministracion;
	private BigDecimal pctadquisicion;
	private BigDecimal pctcomisionmediador;

	private String ibanAsegOriginal;
	private Integer esIbanAsegModificado;
	private String ibanAsegModificado;
	private String iban2AsegOriginal;
	private Integer esIban2AsegModificado;
	private String iban2AsegModificado;
	/* Pet. 78691 ** MODIF TAM (15.12.2021) */
	private BigDecimal codCaractExplotacion;

	private BigDecimal importePlzFinal;
	private BigDecimal importeModificacion;
	private Date fechaEnvioAnexo;
	private BigDecimal pctdescelegido;
	private BigDecimal pctrecarelegido;

	private BigDecimal pctadministracionResto;
	private BigDecimal pctadquisicionResto;
	private BigDecimal pctcomisionmediadorResto;
	private BigDecimal pctdescelegidoResto;
	private BigDecimal pctrecarelegidoResto;
	
	
	
	private Date fechaSeguimiento;

	private Set<Parcela> parcelas = new HashSet<Parcela>(0);
	private Set<ExplotacionAnexo> explotacionAnexos = new HashSet<ExplotacionAnexo>(
			0);
	private Set<SubvDeclarada> subvDeclaradas = new HashSet<SubvDeclarada>(0);
	private Set<ParcelaAMSWRendimiento> parcelaSWRendimientos = new HashSet<ParcelaAMSWRendimiento>(
			0);
	private Set<Cobertura> coberturas = new HashSet<Cobertura>(0);
	private Set<EnviosSWConfirmacion> enviosSWConfirmacions = new HashSet<EnviosSWConfirmacion>(
			0);
	private Set<AnexoModSWCalculo> anexoModSWCalculos = new HashSet<AnexoModSWCalculo>(
			0);
	private Set<AnexoModDistribucionCostes> anexoModDistribucionCosteses = new HashSet<AnexoModDistribucionCostes>(
			0);
	private Set<AnexoModSWComparativas> anexoModSWComparativases = new HashSet<AnexoModSWComparativas>(
			0);

	public AnexoModificacion() {
		super();
		estado = new Estado();
		poliza = new Poliza();
		comunicaciones = new Comunicaciones();
		cupon = new Cupon();
		estadoAgroseguro = new EstadosInc();
	}

	public AnexoModificacion(Long id) {
		this();
		this.id = id;
	}

	/**
	 * Devuelve un booleano que indica si se ha aplicado un descuento/recargo a
	 * algún grupo de negocio del anexo
	 * 
	 * @return
	 */
	public boolean isDescRecarAplicado() {
		return (this.pctdescelegido != null || this.pctdescelegidoResto != null
				|| this.pctrecarelegido != null || this.pctrecarelegidoResto != null);
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public EstadosInc getEstadoAgroseguro() {
		return this.estadoAgroseguro;
	}

	public void setEstadoAgroseguro(EstadosInc estadoAgroseguro) {
		this.estadoAgroseguro = estadoAgroseguro;
	}

	public Cupon getCupon() {
		return this.cupon;
	}

	public void setCupon(Cupon cupon) {
		this.cupon = cupon;
	}

	public Comunicaciones getComunicaciones() {
		return this.comunicaciones;
	}

	public void setComunicaciones(Comunicaciones comunicaciones) {
		this.comunicaciones = comunicaciones;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Poliza getPoliza() {
		return this.poliza;
	}

	public void setPoliza(Poliza poliza) {
		this.poliza = poliza;
	}

	public Long getIdcopy() {
		return this.idcopy;
	}

	public void setIdcopy(Long idcopy) {
		this.idcopy = idcopy;
	}

	public Date getFechafirmadoc() {
		return this.fechafirmadoc;
	}

	public void setFechafirmadoc(Date fechafirmadoc) {
		this.fechafirmadoc = fechafirmadoc;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getNomaseg() {
		return this.nomaseg;
	}

	public void setNomaseg(String nomaseg) {
		this.nomaseg = nomaseg;
	}

	public String getApel1aseg() {
		return this.apel1aseg;
	}

	public void setApel1aseg(String apel1aseg) {
		this.apel1aseg = apel1aseg;
	}

	public String getApel2aseg() {
		return this.apel2aseg;
	}

	public void setApel2aseg(String apel2aseg) {
		this.apel2aseg = apel2aseg;
	}

	public String getRazsocaseg() {
		return this.razsocaseg;
	}

	public void setRazsocaseg(String razsocaseg) {
		this.razsocaseg = razsocaseg;
	}

	public String getCalleaseg() {
		return this.calleaseg;
	}

	public void setCalleaseg(String calleaseg) {
		this.calleaseg = calleaseg;
	}

	public String getNumaseg() {
		return this.numaseg;
	}

	public void setNumaseg(String numaseg) {
		this.numaseg = numaseg;
	}

	public BigDecimal getCodprovincia() {
		return this.codprovincia;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodlocalidad() {
		return this.codlocalidad;
	}

	public void setCodlocalidad(BigDecimal codlocalidad) {
		this.codlocalidad = codlocalidad;
	}

	public String getCodposaseg() {
		return this.codposaseg;
	}

	public void setCodposaseg(String codposaseg) {
		this.codposaseg = codposaseg;
	}

	public String getCodposasegstr() {
		if (codposaseg == null)
			return "";
		StringBuilder codPostalStr = new StringBuilder(codposaseg);
		while (codPostalStr.length() < 5) {
			codPostalStr.insert(0, "0");
		}
		return codPostalStr.toString();
	}

	public void setCodposasegstr(String codpostalstr) {
		if (codpostalstr != null && !codpostalstr.isEmpty())
			this.codposaseg = codpostalstr;
	}

	public String getPisoaseg() {
		return this.pisoaseg;
	}

	public void setPisoaseg(String pisoaseg) {
		this.pisoaseg = pisoaseg;
	}

	public String getBloqueaseg() {
		return this.bloqueaseg;
	}

	public void setBloqueaseg(String bloqueaseg) {
		this.bloqueaseg = bloqueaseg;
	}

	public String getEscaseg() {
		return this.escaseg;
	}

	public void setEscaseg(String escaseg) {
		this.escaseg = escaseg;
	}

	public String getTelffijoaseg() {
		return this.telffijoaseg;
	}

	public void setTelffijoaseg(String telffijoaseg) {
		this.telffijoaseg = telffijoaseg;
	}

	public String getTelfmovilaseg() {
		return this.telfmovilaseg;
	}

	public void setTelfmovilaseg(String telfmovilaseg) {
		this.telfmovilaseg = telfmovilaseg;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumsegsocial() {
		return this.numsegsocial;
	}

	public void setNumsegsocial(String numsegsocial) {
		this.numsegsocial = numsegsocial;
	}

	public String getRegimensegsocial() {
		return this.regimensegsocial;
	}

	public void setRegimensegsocial(String regimensegsocial) {
		this.regimensegsocial = regimensegsocial;
	}

	public String getCodmodulo() {
		return this.codmodulo;
	}

	public void setCodmodulo(String codmodulo) {
		this.codmodulo = codmodulo;
	}

	public Clob getXml() {
		return this.xml;
	}

	public void setXml(Clob xml) {
		this.xml = xml;
	}

	public String getNomlocalidad() {
		return this.nomlocalidad;
	}

	public void setNomlocalidad(String nomlocalidad) {
		this.nomlocalidad = nomlocalidad;
	}

	public String getTipoEnvio() {
		return this.tipoEnvio;
	}

	public void setTipoEnvio(String tipoEnvio) {
		this.tipoEnvio = tipoEnvio;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(String usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getUsuarioBaja() {
		return this.usuarioBaja;
	}

	public void setUsuarioBaja(String usuarioBaja) {
		this.usuarioBaja = usuarioBaja;
	}

	public Character getRevisarSbp() {
		return this.revisarSbp;
	}

	public void setRevisarSbp(Character revisarSbp) {
		this.revisarSbp = revisarSbp;
	}

	public String getUsuarioDefinitiva() {
		return this.usuarioDefinitiva;
	}

	public void setUsuarioDefinitiva(String usuarioDefinitiva) {
		this.usuarioDefinitiva = usuarioDefinitiva;
	}

	public Date getFechaDefinitiva() {
		return this.fechaDefinitiva;
	}

	public void setFechaDefinitiva(Date fechaDefinitiva) {
		this.fechaDefinitiva = fechaDefinitiva;
	}

	public Set<Parcela> getParcelas() {
		return this.parcelas;
	}

	public void setParcelas(Set<Parcela> parcelas) {
		this.parcelas = parcelas;
	}

	public Set<ExplotacionAnexo> getExplotacionAnexos() {
		return this.explotacionAnexos;
	}

	public void setExplotacionAnexos(Set<ExplotacionAnexo> explotacionAnexos) {
		this.explotacionAnexos = explotacionAnexos;
	}

	public Set<SubvDeclarada> getSubvDeclaradas() {
		return this.subvDeclaradas;
	}

	public void setSubvDeclaradas(Set<SubvDeclarada> subvDeclaradas) {
		this.subvDeclaradas = subvDeclaradas;
	}

	public Set<Cobertura> getCoberturas() {
		return this.coberturas;
	}

	public void setCoberturas(Set<Cobertura> coberturas) {
		this.coberturas = coberturas;
	}

	public Set<EnviosSWConfirmacion> getEnviosSWConfirmacions() {
		return enviosSWConfirmacions;
	}

	public void setEnviosSWConfirmacions(
			Set<EnviosSWConfirmacion> enviosSWConfirmacions) {
		this.enviosSWConfirmacions = enviosSWConfirmacions;
	}

	public BigDecimal getPctadministracion() {
		return pctadministracion;
	}

	public void setPctadministracion(BigDecimal pctadministracion) {
		this.pctadministracion = pctadministracion;
	}

	public BigDecimal getPctadquisicion() {
		return pctadquisicion;
	}

	public void setPctadquisicion(BigDecimal pctadquisicion) {
		this.pctadquisicion = pctadquisicion;
	}

	public BigDecimal getPctcomisionmediador() {
		return pctcomisionmediador;
	}

	public void setPctcomisionmediador(BigDecimal pctcomisionmediador) {
		this.pctcomisionmediador = pctcomisionmediador;
	}

	public Set<ParcelaAMSWRendimiento> getParcelaSWRendimientos() {
		return parcelaSWRendimientos;
	}

	public void setParcelaSWRendimientos(
			Set<ParcelaAMSWRendimiento> parcelaSWRendimientos) {
		this.parcelaSWRendimientos = parcelaSWRendimientos;
	}

	public String getIbanAsegOriginal() {
		return ibanAsegOriginal;
	}

	public void setIbanAsegOriginal(String ibanAsegOriginal) {
		this.ibanAsegOriginal = ibanAsegOriginal;
	}

	public Integer getEsIbanAsegModificado() {
		return esIbanAsegModificado;
	}

	public void setEsIbanAsegModificado(Integer esIbanAsegModificado) {
		this.esIbanAsegModificado = esIbanAsegModificado;
	}

	public String getIbanAsegModificado() {
		return ibanAsegModificado;
	}

	public void setIbanAsegModificado(String ibanAsegModificado) {
		this.ibanAsegModificado = ibanAsegModificado;
	}
	
	public String getIban2AsegOriginal() {
		return iban2AsegOriginal;
	}

	public void setIban2AsegOriginal(String iban2AsegOriginal) {
		this.iban2AsegOriginal = iban2AsegOriginal;
	}

	public Integer getEsIban2AsegModificado() {
		return esIban2AsegModificado;
	}

	public void setEsIban2AsegModificado(Integer esIban2AsegModificado) {
		this.esIban2AsegModificado = esIban2AsegModificado;
	}

	public String getIban2AsegModificado() {
		return iban2AsegModificado;
	}

	public void setIban2AsegModificado(String iban2AsegModificado) {
		this.iban2AsegModificado = iban2AsegModificado;
	}

	public Set<AnexoModSWCalculo> getAnexoModSWCalculos() {
		return anexoModSWCalculos;
	}

	public void setAnexoModSWCalculos(Set<AnexoModSWCalculo> anexoModSWCalculos) {
		this.anexoModSWCalculos = anexoModSWCalculos;
	}

	public Set<AnexoModDistribucionCostes> getAnexoModDistribucionCosteses() {
		return anexoModDistribucionCosteses;
	}

	public void setAnexoModDistribucionCosteses(
			Set<AnexoModDistribucionCostes> anexoModDistribucionCosteses) {
		this.anexoModDistribucionCosteses = anexoModDistribucionCosteses;
	}

	public BigDecimal getImportePlzFinal() {
		return importePlzFinal;
	}

	public void setImportePlzFinal(BigDecimal importePlzFinal) {
		this.importePlzFinal = importePlzFinal;
	}

	public BigDecimal getImporteModificacion() {
		return importeModificacion;
	}

	public void setImporteModificacion(BigDecimal importeModificacion) {
		this.importeModificacion = importeModificacion;
	}

	public Date getFechaEnvioAnexo() {
		return fechaEnvioAnexo;
	}

	public void setFechaEnvioAnexo(Date fechaEnvioAnexo) {
		this.fechaEnvioAnexo = fechaEnvioAnexo;
	}

	public BigDecimal getPctdescelegido() {
		return this.pctdescelegido;
	}

	public void setPctdescelegido(BigDecimal pctdescelegido) {
		this.pctdescelegido = pctdescelegido;
	}

	public BigDecimal getPctrecarelegido() {
		return this.pctrecarelegido;
	}

	public void setPctrecarelegido(BigDecimal pctrecarelegido) {
		this.pctrecarelegido = pctrecarelegido;
	}

	public List<Long> getCodigosTipoAnimalExplotaciones() {
		List<Long> res = null;
		if (this.getExplotacionAnexos() != null
				&& this.getExplotacionAnexos().size() > 0) {
			for (ExplotacionAnexo exp : this.getExplotacionAnexos()) {
				if (exp.getGrupoRazaAnexos() != null
						&& exp.getGrupoRazaAnexos().size() > 0) {
					for (GrupoRazaAnexo gr : exp.getGrupoRazaAnexos()) {
						if (gr.getCodtipoanimal() != null) {
							if (res == null)
								res = new ArrayList<Long>();
							if (!res.contains(gr.getCodtipoanimal()))
								res.add(gr.getCodtipoanimal());
						}
					}
				}
			}

		}
		return res;
	}

	public Set<AnexoModSWComparativas> getAnexoModSWComparativases() {
		return anexoModSWComparativases;
	}

	public void setAnexoModSWComparativases(
			Set<AnexoModSWComparativas> anexoModSWComparativases) {
		this.anexoModSWComparativases = anexoModSWComparativases;
	}

	public BigDecimal getPctadministracionResto() {
		return pctadministracionResto;
	}

	public void setPctadministracionResto(BigDecimal pctadministracionResto) {
		this.pctadministracionResto = pctadministracionResto;
	}

	public BigDecimal getPctadquisicionResto() {
		return pctadquisicionResto;
	}

	public void setPctadquisicionResto(BigDecimal pctadquisicionResto) {
		this.pctadquisicionResto = pctadquisicionResto;
	}

	public BigDecimal getPctcomisionmediadorResto() {
		return pctcomisionmediadorResto;
	}

	public void setPctcomisionmediadorResto(BigDecimal pctcomisionmediadorResto) {
		this.pctcomisionmediadorResto = pctcomisionmediadorResto;
	}

	public BigDecimal getPctdescelegidoResto() {
		return pctdescelegidoResto;
	}

	public void setPctdescelegidoResto(BigDecimal pctdescelegidoResto) {
		this.pctdescelegidoResto = pctdescelegidoResto;
	}

	public BigDecimal getPctrecarelegidoResto() {
		return pctrecarelegidoResto;
	}

	public void setPctrecarelegidoResto(BigDecimal pctrecarelegidoResto) {
		this.pctrecarelegidoResto = pctrecarelegidoResto;
	}

	public Date getFechaSeguimiento() {
		return fechaSeguimiento;
	}

	public void setFechaSeguimiento(Date fechaSeguimiento) {
		this.fechaSeguimiento = fechaSeguimiento;
	}
	
	/* Pet. 78691 ** MODIF TAM (15.12.2021) ** Inicio */
	public BigDecimal getCodCaractExplotacion() {
		return this.codCaractExplotacion;
	}

	public void setCodCaractExplotacion(BigDecimal codCaractExplotacion) {
		this.codCaractExplotacion = codCaractExplotacion;
	}
	/* Pet. 78691 ** MODIF TAM (15.12.2021) ** Fin   */

}
