package com.rsi.agp.dao.tables.anexo;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.rsi.agp.dao.tables.cgen.TipoCapital;

public class CapitalAsegurado implements java.io.Serializable {

	private static final long serialVersionUID = -876468076346494578L;

	private Long id;
	private Parcela parcela;
	private TipoCapital tipoCapital;
	private BigDecimal superficie;
	private BigDecimal precio;
	private BigDecimal produccion;
	private Character altaencomplementario;
	private BigDecimal incrementoproduccion;
	private Character tipomodificacion;
	private BigDecimal incrementoproduccionanterior;
	private BigDecimal valorincremento;
	private String tipoincremento;
	private Set<CapitalDTSVariable> capitalDTSVariables = new HashSet<CapitalDTSVariable>(0);
	private Long tipoRdto;

	public CapitalAsegurado() {
		parcela = new Parcela();
		tipoCapital = new TipoCapital();
	}

	public CapitalAsegurado(Long id, Parcela parcela, TipoCapital tipoCapital) {
		this.id = id;
		this.parcela = parcela;
		this.tipoCapital = tipoCapital;
	}

	public CapitalAsegurado(Long id, Parcela parcela, TipoCapital tipoCapital, BigDecimal superficie, BigDecimal precio,
			BigDecimal produccion, Character altaencomplementario, BigDecimal incrementoproduccion,
			Character tipomodificacion, BigDecimal incrementoproduccionanterior, BigDecimal valorincremento,
			String tipoincremento, Set<CapitalDTSVariable> capitalDTSVariables, Long tipoRdto) {
		this.id = id;
		this.parcela = parcela;
		this.tipoCapital = tipoCapital;
		this.superficie = superficie;
		this.precio = precio;
		this.produccion = produccion;
		this.altaencomplementario = altaencomplementario;
		this.incrementoproduccion = incrementoproduccion;
		this.tipomodificacion = tipomodificacion;
		this.incrementoproduccionanterior = incrementoproduccionanterior;
		this.valorincremento = valorincremento;
		this.tipoincremento = tipoincremento;
		this.capitalDTSVariables = capitalDTSVariables;
		this.tipoRdto = tipoRdto;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Parcela getParcela() {
		return this.parcela;
	}

	public void setParcela(Parcela parcela) {
		this.parcela = parcela;
	}

	public TipoCapital getTipoCapital() {
		return this.tipoCapital;
	}

	public void setTipoCapital(TipoCapital tipoCapital) {
		this.tipoCapital = tipoCapital;
	}

	public BigDecimal getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(BigDecimal superficie) {
		this.superficie = superficie;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getProduccion() {
		return this.produccion;
	}

	public void setProduccion(BigDecimal produccion) {
		this.produccion = produccion;
	}

	public Character getAltaencomplementario() {
		return altaencomplementario;
	}

	public void setAltaencomplementario(Character altaencomplementario) {
		this.altaencomplementario = altaencomplementario;
	}

	public BigDecimal getIncrementoproduccion() {
		return incrementoproduccion;
	}

	public void setIncrementoproduccion(BigDecimal incrementoproduccion) {
		this.incrementoproduccion = incrementoproduccion;
	}

	public Character getTipomodificacion() {
		return tipomodificacion;
	}

	public void setTipomodificacion(Character tipomodificacion) {
		this.tipomodificacion = tipomodificacion;
	}

	public BigDecimal getIncrementoproduccionanterior() {
		return incrementoproduccionanterior;
	}

	public void setIncrementoproduccionanterior(BigDecimal incrementoproduccionanterior) {
		this.incrementoproduccionanterior = incrementoproduccionanterior;
	}

	public BigDecimal getValorincremento() {
		return this.valorincremento;
	}

	public void setValorincremento(BigDecimal valorincremento) {
		this.valorincremento = valorincremento;
	}

	public String getTipoincremento() {
		return this.tipoincremento;
	}

	public void setTipoincremento(String tipoincremento) {
		this.tipoincremento = tipoincremento;
	}

	public Set<CapitalDTSVariable> getCapitalDTSVariables() {
		return this.capitalDTSVariables;
	}

	public void setCapitalDTSVariables(Set<CapitalDTSVariable> capitalDTSVariables) {
		this.capitalDTSVariables = capitalDTSVariables;
	}

	public Long getTipoRdto() {
		return tipoRdto;
	}

	public void setTipoRdto(Long tipoRdto) {
		this.tipoRdto = tipoRdto;
	}

}
