package com.rsi.agp.dao.tables.anexo;
// Generated by T-Systems

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

public class EnviosSWXML implements java.io.Serializable {

	private static final long serialVersionUID = -247477259908299808L;

	private Long id;
	private transient Clob xml;
	private Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlCpl = new HashSet<EnviosSWSolicitud>(0);
	private Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlPpal = new HashSet<EnviosSWSolicitud>(0);
	private Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlCupon = new HashSet<EnviosSWSolicitud>(0);
	private Set<EnviosSWConfirmacion> enviosSWConfirmacionsForIdxmlAcuse = new HashSet<EnviosSWConfirmacion>(0);
	private Set<EnviosSWConfirmacion> enviosSWConfirmacionsForIdxmlPoliza = new HashSet<EnviosSWConfirmacion>(0);
	private Set<EnviosSWAnulacion> enviosSWAnulacions = new HashSet<EnviosSWAnulacion>(0);
	private Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlEstadoContratacion = new HashSet<EnviosSWSolicitud>(0);
	private Set<EnviosSWImpresion> enviosSWImpresions = new HashSet<EnviosSWImpresion>(0);

	public EnviosSWXML() {
	}

	public EnviosSWXML(Long id, Clob xml) {
		this.id = id;
		this.xml = xml;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Clob getXml() {
		return this.xml;
	}

	public void setXml(Clob xml) {
		this.xml = xml;
	}

	public Set<EnviosSWSolicitud> getEnviosSWSolicitudsForIdxmlCpl() {
		return this.enviosSWSolicitudsForIdxmlCpl;
	}

	public void setEnviosSWSolicitudsForIdxmlCpl(Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlCpl) {
		this.enviosSWSolicitudsForIdxmlCpl = enviosSWSolicitudsForIdxmlCpl;
	}

	public Set<EnviosSWSolicitud> getEnviosSWSolicitudsForIdxmlPpal() {
		return this.enviosSWSolicitudsForIdxmlPpal;
	}

	public void setEnviosSWSolicitudsForIdxmlPpal(Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlPpal) {
		this.enviosSWSolicitudsForIdxmlPpal = enviosSWSolicitudsForIdxmlPpal;
	}

	public Set<EnviosSWSolicitud> getEnviosSWSolicitudsForIdxmlCupon() {
		return this.enviosSWSolicitudsForIdxmlCupon;
	}

	public void setEnviosSWSolicitudsForIdxmlCupon(Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlCupon) {
		this.enviosSWSolicitudsForIdxmlCupon = enviosSWSolicitudsForIdxmlCupon;
	}

	public Set<EnviosSWConfirmacion> getEnviosSWConfirmacionsForIdxmlAcuse() {
		return this.enviosSWConfirmacionsForIdxmlAcuse;
	}

	public void setEnviosSWConfirmacionsForIdxmlAcuse(Set<EnviosSWConfirmacion> enviosSWConfirmacionsForIdxmlAcuse) {
		this.enviosSWConfirmacionsForIdxmlAcuse = enviosSWConfirmacionsForIdxmlAcuse;
	}

	public Set<EnviosSWConfirmacion> getEnviosSWConfirmacionsForIdxmlPoliza() {
		return this.enviosSWConfirmacionsForIdxmlPoliza;
	}

	public void setEnviosSWConfirmacionsForIdxmlPoliza(Set<EnviosSWConfirmacion> enviosSWConfirmacionsForIdxmlPoliza) {
		this.enviosSWConfirmacionsForIdxmlPoliza = enviosSWConfirmacionsForIdxmlPoliza;
	}

	public Set<EnviosSWAnulacion> getEnviosSWAnulacions() {
		return this.enviosSWAnulacions;
	}

	public void setEnviosSWAnulacions(Set<EnviosSWAnulacion> enviosSWAnulacions) {
		this.enviosSWAnulacions = enviosSWAnulacions;
	}

	public Set<EnviosSWSolicitud> getEnviosSWSolicitudsForIdxmlEstadoContratacion() {
		return this.enviosSWSolicitudsForIdxmlEstadoContratacion;
	}

	public void setEnviosSWSolicitudsForIdxmlEstadoContratacion(
			Set<EnviosSWSolicitud> enviosSWSolicitudsForIdxmlEstadoContratacion) {
		this.enviosSWSolicitudsForIdxmlEstadoContratacion = enviosSWSolicitudsForIdxmlEstadoContratacion;
	}

	public Set<EnviosSWImpresion> getEnviosSWImpresions() {
		return this.enviosSWImpresions;
	}

	public void setEnviosSWImpresions(Set<EnviosSWImpresion> enviosSWImpresions) {
		this.enviosSWImpresions = enviosSWImpresions;
	}

}
