package com.rsi.agp.dao.tables.anexo;
// Generated by T-Systems


import java.util.Date;

public class HistoricoCupon  implements java.io.Serializable {


     private Long id;
     private EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoPpal;
     private Cupon cupon;
     private EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoCpl;
     private EstadoCupon estadoCupon;
     private Date fecha;
     private String codusuario;

    public HistoricoCupon() {
    }

	
    public HistoricoCupon(Long id, Cupon cupon, EstadoCupon estadoCupon, Date fecha) {
        this.id = id;
        this.cupon = cupon;
        this.estadoCupon = estadoCupon;
        this.fecha = fecha;
    }
    public HistoricoCupon(Long id, EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoPpal, Cupon cupon, EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoCpl, EstadoCupon estadoCupon, Date fecha, String codusuario) {
       this.id = id;
       this.estadoPlzAgroseguroByIdestadoPpal = estadoPlzAgroseguroByIdestadoPpal;
       this.cupon = cupon;
       this.estadoPlzAgroseguroByIdestadoCpl = estadoPlzAgroseguroByIdestadoCpl;
       this.estadoCupon = estadoCupon;
       this.fecha = fecha;
       this.codusuario = codusuario;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public EstadoPlzAgroseguro getEstadoPlzAgroseguroByIdestadoPpal() {
        return this.estadoPlzAgroseguroByIdestadoPpal;
    }
    
    public void setEstadoPlzAgroseguroByIdestadoPpal(EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoPpal) {
        this.estadoPlzAgroseguroByIdestadoPpal = estadoPlzAgroseguroByIdestadoPpal;
    }
    public Cupon getCupon() {
        return this.cupon;
    }
    
    public void setCupon(Cupon cupon) {
        this.cupon = cupon;
    }
    public EstadoPlzAgroseguro getEstadoPlzAgroseguroByIdestadoCpl() {
        return this.estadoPlzAgroseguroByIdestadoCpl;
    }
    
    public void setEstadoPlzAgroseguroByIdestadoCpl(EstadoPlzAgroseguro estadoPlzAgroseguroByIdestadoCpl) {
        this.estadoPlzAgroseguroByIdestadoCpl = estadoPlzAgroseguroByIdestadoCpl;
    }
    public EstadoCupon getEstadoCupon() {
        return this.estadoCupon;
    }
    
    public void setEstadoCupon(EstadoCupon estadoCupon) {
        this.estadoCupon = estadoCupon;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }




}


