package com.rsi.agp.dao.tables.anexo;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

public class HistoricoEstado  implements java.io.Serializable {


     private BigDecimal id;
     private AnexoModificacion anexoModificacion;
     private String codusuario;
     private Date fecha;
     private BigDecimal estado;

    public HistoricoEstado() {
    }

	
    public HistoricoEstado(BigDecimal id, AnexoModificacion anexoModificacion, Date fecha, BigDecimal estado) {
        this.id = id;
        this.anexoModificacion = anexoModificacion;
        this.fecha = fecha;
        this.estado = estado;
    }
    public HistoricoEstado(BigDecimal id, AnexoModificacion anexoModificacion, String codusuario, Date fecha, BigDecimal estado) {
       this.id = id;
       this.anexoModificacion = anexoModificacion;
       this.codusuario = codusuario;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public AnexoModificacion getAnexoModificacion() {
        return this.anexoModificacion;
    }
    
    public void setAnexoModificacion(AnexoModificacion anexoModificacion) {
        this.anexoModificacion = anexoModificacion;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }




}


