package com.rsi.agp.dao.tables.comisiones;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

import com.rsi.agp.core.util.Constants;
import com.rsi.agp.dao.tables.admin.Entidad;
import com.rsi.agp.dao.tables.commons.Oficina;

public class DescuentosHistorico  implements java.io.Serializable {

	 private static final long serialVersionUID = -6655835392014174991L;
	 
	 private Long id;
     private Descuentos descuentos;
     private Entidad entidad;
     private BigDecimal codentmed;
     private BigDecimal codsubentmed;
     private Oficina oficina;
     private BigDecimal delegacion;
     private BigDecimal pctDescMax;
     private BigDecimal operacion;
     private Date fecha;
     private String usuario;
     private Integer permitirRecargo;
     private Integer verComisiones;
     private Long lineaseguroid;
     
    public DescuentosHistorico() {
    	entidad = new Entidad();
    	oficina = new Oficina();
    }

	
    public DescuentosHistorico(Long id, Descuentos descuentos, Entidad entidad, BigDecimal codentmed, BigDecimal codsubentmed, Oficina oficina, BigDecimal pctDescMax, BigDecimal operacion, Date fecha, String usuario, Integer permitirRecargo, Integer verComisiones) {
        this.id = id;
        this.descuentos = descuentos;
        this.entidad = entidad;
        this.codentmed = codentmed;
        this.codsubentmed = codsubentmed;
        this.oficina = oficina;
        this.pctDescMax = pctDescMax;
        this.operacion = operacion;
        this.fecha = fecha;
        this.usuario = usuario;
        this.permitirRecargo = permitirRecargo;
        this.verComisiones = verComisiones;
      }
    
    public DescuentosHistorico(Long id, Descuentos descuentos, Entidad entidad, BigDecimal codentmed, BigDecimal codsubentmed, Oficina oficina, 
    						   BigDecimal delegacion, BigDecimal pctDescMax, BigDecimal operacion, Date fecha, String usuario, 
    						   Integer permitirRecargo, Integer verComisiones, Long lineaseguroid) {
       this.id = id;
       this.descuentos = descuentos;
       this.entidad = entidad;
       this.codentmed = codentmed;
       this.codsubentmed = codsubentmed;
       this.oficina = oficina;
       this.delegacion = delegacion;
       this.pctDescMax = pctDescMax;
       this.operacion = operacion;
       this.fecha = fecha;
       this.usuario = usuario;
       this.permitirRecargo = permitirRecargo;
       this.verComisiones = verComisiones;
       this.lineaseguroid = lineaseguroid;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Descuentos getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Descuentos descuentos) {
        this.descuentos = descuentos;
    }
    public BigDecimal getCodentmed() {
        return this.codentmed;
    }
    
    public void setCodentmed(BigDecimal codentmed) {
        this.codentmed = codentmed;
    }
    public BigDecimal getCodsubentmed() {
        return this.codsubentmed;
    }
    
    public void setCodsubentmed(BigDecimal codsubentmed) {
        this.codsubentmed = codsubentmed;
    }
    public BigDecimal getDelegacion() {
        return this.delegacion;
    }
    
    public void setDelegacion(BigDecimal delegacion) {
        this.delegacion = delegacion;
    }
    public BigDecimal getPctDescMax() {
        return this.pctDescMax;
    }
    
    public void setPctDescMax(BigDecimal pctDescMax) {
        this.pctDescMax = pctDescMax;
    }
    public BigDecimal getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(BigDecimal operacion) {
        this.operacion = operacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }


	public Entidad getEntidad() {
		return entidad;
	}


	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}


	public Oficina getOficina() {
		return oficina;
	}


	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}


	public Integer getPermitirRecargo() {
		return permitirRecargo;
	}


	public void setPermitirRecargo(Integer permitirRecargo) {
		this.permitirRecargo = permitirRecargo;
	}


	public Integer getVerComisiones() {
		return verComisiones;
	}


	public void setVerComisiones(Integer verComisiones) {
		this.verComisiones = verComisiones;
	}


	public Long getLineaseguroid() {
		return lineaseguroid;
	}


	public void setLineaseguroid(Long lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	


}


