package com.rsi.agp.dao.tables.comisiones;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class Fase  implements java.io.Serializable {


     private Long id;
     private Cierre cierre;
     private String fase;
     private BigDecimal plan;
     private Date fechaemision;
     private Set<Fichero> ficheros = new HashSet<Fichero>(0);

    public Fase() {
    }

	
    public Fase(Long id, String fase, BigDecimal plan, Date fechaemision) {
        this.id = id;
        this.fase = fase;
        this.plan = plan;
        this.fechaemision = fechaemision;
    }
    public Fase(Long id, Cierre cierre, String fase, BigDecimal plan, Date fechaemision, Set<Fichero> ficheros) {
       this.id = id;
       this.cierre = cierre;
       this.fase = fase;
       this.plan = plan;
       this.fechaemision = fechaemision;
       this.ficheros = ficheros;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cierre getCierre() {
        return this.cierre;
    }
    
    public void setCierre(Cierre cierre) {
        this.cierre = cierre;
    }
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }
    public BigDecimal getPlan() {
        return this.plan;
    }
    
    public void setPlan(BigDecimal plan) {
        this.plan = plan;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public Set<Fichero> getFicheros() {
        return this.ficheros;
    }
    
    public void setFicheros(Set<Fichero> ficheros) {
        this.ficheros = ficheros;
    }




}


