package com.rsi.agp.dao.tables.comisiones;
// Generated by T-Systems

public class FicheroContenido implements java.io.Serializable {

	private static final long serialVersionUID = 5059013547687273439L;

	private Long idfichero;
	private Fichero fichero;
	private String contenido;

	public FicheroContenido() {
	}

	public FicheroContenido(Fichero fichero, String contenido) {
		this.fichero = fichero;
		this.contenido = contenido;
	}

	public Long getIdfichero() {
		return this.idfichero;
	}

	public void setIdfichero(Long idfichero) {
		this.idfichero = idfichero;
	}

	public Fichero getFichero() {
		return this.fichero;
	}

	public void setFichero(Fichero fichero) {
		this.fichero = fichero;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

}
