package com.rsi.agp.dao.tables.comisiones;
// Generated by T-Systems


import com.rsi.agp.dao.tables.commons.Usuario;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class GGEEntidades  implements java.io.Serializable {


     private Long id;
     private Usuario usuario;
     private Long plan;
     private BigDecimal pctsectoragricola;
     private BigDecimal pctentidades;
     private BigDecimal pctrga;
     private Date fecModificacion;
     private Set<GGEEntidadesHistorico> GGEEntidadesHistoricos = new HashSet<GGEEntidadesHistorico>(0);

    public GGEEntidades() {
    }

	
    public GGEEntidades(Long id, Long plan) {
        this.id = id;
        this.plan = plan;
    }
    public GGEEntidades(Long id, Usuario usuario, Long plan, BigDecimal pctsectoragricola, BigDecimal pctentidades, BigDecimal pctrga, Date fecModificacion, Set<GGEEntidadesHistorico> GGEEntidadesHistoricos) {
       this.id = id;
       this.usuario = usuario;
       this.plan = plan;
       this.pctsectoragricola = pctsectoragricola;
       this.pctentidades = pctentidades;
       this.pctrga = pctrga;
       this.fecModificacion = fecModificacion;
       this.GGEEntidadesHistoricos = GGEEntidadesHistoricos;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Long getPlan() {
        return this.plan;
    }
    
    public void setPlan(Long plan) {
        this.plan = plan;
    }
    public BigDecimal getPctsectoragricola() {
        return this.pctsectoragricola;
    }
    
    public void setPctsectoragricola(BigDecimal pctsectoragricola) {
        this.pctsectoragricola = pctsectoragricola;
    }
    public BigDecimal getPctentidades() {
        return this.pctentidades;
    }
    
    public void setPctentidades(BigDecimal pctentidades) {
        this.pctentidades = pctentidades;
    }
    public BigDecimal getPctrga() {
        return this.pctrga;
    }
    
    public void setPctrga(BigDecimal pctrga) {
        this.pctrga = pctrga;
    }
    public Date getFecModificacion() {
        return this.fecModificacion;
    }
    
    public void setFecModificacion(Date fecModificacion) {
        this.fecModificacion = fecModificacion;
    }
    public Set<GGEEntidadesHistorico> getGGEEntidadesHistoricos() {
        return this.GGEEntidadesHistoricos;
    }
    
    public void setGGEEntidadesHistoricos(Set<GGEEntidadesHistorico> GGEEntidadesHistoricos) {
        this.GGEEntidadesHistoricos = GGEEntidadesHistoricos;
    }




}


