package com.rsi.agp.dao.tables.comisiones;
// Generated by T-Systems


import java.math.BigDecimal;

public class Retencion  implements java.io.Serializable {

     private Integer anyo;
     private BigDecimal retencion;

    public Retencion() {
    }

    public Retencion(Integer anyo, BigDecimal retencion) {
       this.anyo = anyo;
       this.retencion = retencion;
    }

    public Integer getAnyo() {
        return this.anyo;
    }
    
    public void setAnyo(Integer anyo) {
        this.anyo = anyo;
    }
    public BigDecimal getRetencion() {
        return this.retencion;
    }
    
    public void setRetencion(BigDecimal retencion) {
        this.retencion = retencion;
    }




}