package com.rsi.agp.dao.tables.comisiones;
// Generated 20-oct-2011 10:25:47 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * RgaComisionesPendientes generated by hbm2java
 */
public class RgaComisionesPendientes implements java.io.Serializable {

	private static final long serialVersionUID = -3974905837312504368L;

	private Long id;
	private Cierre cierre;
	private BigDecimal codent;
	private String codcol;
	private BigDecimal codlin;
	private BigDecimal codpln;
	private Date feccar;
	private BigDecimal gaspen;
	private String fase;

	public RgaComisionesPendientes() {
	}

	public RgaComisionesPendientes(Long id, Cierre cierre) {
		this.id = id;
		this.cierre = cierre;
	}

	public RgaComisionesPendientes(Long id, Cierre cierre, BigDecimal codent, String codcol, BigDecimal codlin,
			BigDecimal codpln, Date feccar, BigDecimal gaspen, String fase) {
		this.id = id;
		this.cierre = cierre;
		this.codent = codent;
		this.codcol = codcol;
		this.codlin = codlin;
		this.codpln = codpln;
		this.feccar = feccar;
		this.gaspen = gaspen;
		this.fase = fase;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Cierre getCierre() {
		return this.cierre;
	}

	public void setCierre(Cierre cierre) {
		this.cierre = cierre;
	}

	public BigDecimal getCodent() {
		return this.codent;
	}

	public void setCodent(BigDecimal codent) {
		this.codent = codent;
	}

	public String getCodcol() {
		return this.codcol;
	}

	public void setCodcol(String codcol) {
		this.codcol = codcol;
	}

	public BigDecimal getCodlin() {
		return this.codlin;
	}

	public void setCodlin(BigDecimal codlin) {
		this.codlin = codlin;
	}

	public BigDecimal getCodpln() {
		return this.codpln;
	}

	public void setCodpln(BigDecimal codpln) {
		this.codpln = codpln;
	}

	public Date getFeccar() {
		return this.feccar;
	}

	public void setFeccar(Date feccar) {
		this.feccar = feccar;
	}

	public BigDecimal getGaspen() {
		return this.gaspen;
	}

	public void setGaspen(BigDecimal gaspen) {
		this.gaspen = gaspen;
	}

	public String getFase() {
		return fase;
	}

	public void setFase(String fase) {
		this.fase = fase;
	}
}
