package com.rsi.agp.dao.tables.comisiones;
// Generated 29-sep-2011 9:48:23 by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * RgaComisionesPendientesId generated by hbm2java
 */
public class RgaComisionesPendientesId  implements java.io.Serializable {


     private BigDecimal codent;
     private String codcol;    

    public RgaComisionesPendientesId() {
    }

	public RgaComisionesPendientesId(BigDecimal codent, String codcol) {
       this.codent = codent;
       this.codcol = codcol;      
    }
   
    public BigDecimal getCodent() {
        return this.codent;
    }
    
    public void setCodent(BigDecimal codent) {
        this.codent = codent;
    }
    public String getCodcol() {
        return this.codcol;
    }
    
    public void setCodcol(String codcol) {
        this.codcol = codcol;
    }
    
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RgaComisionesPendientesId) ) return false;
		 RgaComisionesPendientesId castOther = ( RgaComisionesPendientesId ) other; 
         
		 return ( (this.getCodent()==castOther.getCodent()) || ( this.getCodent()!=null && castOther.getCodent()!=null && this.getCodent().equals(castOther.getCodent()) ) )
 && ( (this.getCodcol()==castOther.getCodcol()) || ( this.getCodcol()!=null && castOther.getCodcol()!=null && this.getCodcol().equals(castOther.getCodcol()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodent() == null ? 0 : this.getCodent().hashCode() );
         result = 37 * result + ( getCodcol() == null ? 0 : this.getCodcol().hashCode() );
         return result;
   }   


}


