package com.rsi.agp.dao.tables.renovables;

// Generated by T-Systems

import java.util.HashSet;
import java.util.Set;

import com.rsi.agp.dao.tables.poliza.RelacionEstados;

public class EstadoRenovacionAgroseguro implements java.io.Serializable {

	private static final long serialVersionUID = 4311762127339492140L;
	
	private Long codigo;
	private String descripcion;
	private Set<RelacionEstados> relacionEstadoses = new HashSet<RelacionEstados>(
			0);
	private Set<PolizaRenovable> polizaRenovables = new HashSet<PolizaRenovable>(
			0);
	private Set<PolizaRenovableHistoricoEstados> polizaRenovableHistoricoEstadoses = new HashSet<PolizaRenovableHistoricoEstados>(
			0);

	public EstadoRenovacionAgroseguro() {
	}

	public EstadoRenovacionAgroseguro(Long codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public EstadoRenovacionAgroseguro(
			Long codigo,
			String descripcion,
			Set<RelacionEstados> relacionEstadoses,
			Set<PolizaRenovable> polizaRenovables,
			Set<PolizaRenovableHistoricoEstados> polizaRenovableHistoricoEstadoses) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.relacionEstadoses = relacionEstadoses;
		this.polizaRenovables = polizaRenovables;
		this.polizaRenovableHistoricoEstadoses = polizaRenovableHistoricoEstadoses;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<RelacionEstados> getRelacionEstadoses() {
		return this.relacionEstadoses;
	}

	public void setRelacionEstadoses(Set<RelacionEstados> relacionEstadoses) {
		this.relacionEstadoses = relacionEstadoses;
	}

	public Set<PolizaRenovable> getPolizaRenovables() {
		return this.polizaRenovables;
	}

	public void setPolizaRenovables(Set<PolizaRenovable> polizaRenovables) {
		this.polizaRenovables = polizaRenovables;
	}

	public Set<PolizaRenovableHistoricoEstados> getPolizaRenovableHistoricoEstadoses() {
		return this.polizaRenovableHistoricoEstadoses;
	}

	public void setPolizaRenovableHistoricoEstadoses(
			Set<PolizaRenovableHistoricoEstados> polizaRenovableHistoricoEstadoses) {
		this.polizaRenovableHistoricoEstadoses = polizaRenovableHistoricoEstadoses;
	}

}
