package com.rsi.agp.dao.tables.renovables;
// Generated by T-Systems


import java.util.Date;

public class PolizaRenovableEnvioIBANHistoricoEstados  implements java.io.Serializable {


     private long id;
     private PolizaRenovable polizaRenovable;
     private PolizaRenovableEstadoEnvioIBAN polizaRenovableEstadoEnvioIBAN;
     private String usuario;
     private Date fecha;

    public PolizaRenovableEnvioIBANHistoricoEstados() {
    }

    public PolizaRenovableEnvioIBANHistoricoEstados(long id, PolizaRenovable polizaRenovable, PolizaRenovableEstadoEnvioIBAN polizaRenovableEstadoEnvioIBAN, String usuario, Date fecha) {
       this.id = id;
       this.polizaRenovable = polizaRenovable;
       this.polizaRenovableEstadoEnvioIBAN = polizaRenovableEstadoEnvioIBAN;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public PolizaRenovable getPolizaRenovable() {
        return this.polizaRenovable;
    }
    
    public void setPolizaRenovable(PolizaRenovable polizaRenovable) {
        this.polizaRenovable = polizaRenovable;
    }
    public PolizaRenovableEstadoEnvioIBAN getPolizaRenovableEstadoEnvioIBAN() {
        return this.polizaRenovableEstadoEnvioIBAN;
    }
    
    public void setPolizaRenovableEstadoEnvioIBAN(PolizaRenovableEstadoEnvioIBAN polizaRenovableEstadoEnvioIBAN) {
        this.polizaRenovableEstadoEnvioIBAN = polizaRenovableEstadoEnvioIBAN;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


