package com.rsi.agp.dao.tables.renovables;
// Generated by T-Systems

import java.sql.Clob;
import java.util.Date;

public class SWListaPolizasRenovables implements java.io.Serializable {

	private static final long serialVersionUID = 6939472076043369154L;

	private Long id;
	private Long codlinea;
	private Long codplan;
	private String referencia;
	private transient Clob respuesta;
	private String usuario;
	private Date fecha;

	public SWListaPolizasRenovables() {
		super();
	}

	public SWListaPolizasRenovables(Long id, Long codlinea, Long codplan, String referencia, String usuario,
			Date fecha) {
		this();
		this.id = id;
		this.codlinea = codlinea;
		this.codplan = codplan;
		this.referencia = referencia;
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCodlinea() {
		return this.codlinea;
	}

	public void setCodlinea(Long codlinea) {
		this.codlinea = codlinea;
	}

	public Long getCodplan() {
		return this.codplan;
	}

	public void setCodplan(Long codplan) {
		this.codplan = codplan;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Clob getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(Clob respuesta) {
		this.respuesta = respuesta;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
