package com.rsi.agp.dao.tables.admin;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.Date;

public class CorreoRecordConfirm implements java.io.Serializable {

	private static final long serialVersionUID = 7521135592519112956L;

	private BigDecimal id;
	private Date fecha;
	private String codusuario;
	private String detalle;

	public CorreoRecordConfirm() {
	}

	public CorreoRecordConfirm(BigDecimal id) {
		this.id = id;
	}

	public CorreoRecordConfirm(BigDecimal id, Date fecha, String codusuario, String detalle) {
		this.id = id;
		this.fecha = fecha;
		this.codusuario = codusuario;
		this.detalle = detalle;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCodusuario() {
		return codusuario;
	}

	public void setCodusuario(String codusuario) {
		this.codusuario = codusuario;
	}

	public String getDetalle() {
		return detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

}
