package com.rsi.agp.dao.tables.admin;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

public class HistoricoOperacion  implements java.io.Serializable {


     private BigDecimal id;
     private DatoAsegurado datoAsegurado;
     private String codusuario;
     private Date fecha;
     private Character operacion;

    public HistoricoOperacion() {
    }

	
    public HistoricoOperacion(BigDecimal id, DatoAsegurado datoAsegurado, Date fecha, Character operacion) {
        this.id = id;
        this.datoAsegurado = datoAsegurado;
        this.fecha = fecha;
        this.operacion = operacion;
    }
    public HistoricoOperacion(BigDecimal id, DatoAsegurado datoAsegurado, String codusuario, Date fecha, Character operacion) {
       this.id = id;
       this.datoAsegurado = datoAsegurado;
       this.codusuario = codusuario;
       this.fecha = fecha;
       this.operacion = operacion;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public DatoAsegurado getDatoAsegurado() {
        return this.datoAsegurado;
    }
    
    public void setDatoAsegurado(DatoAsegurado datoAsegurado) {
        this.datoAsegurado = datoAsegurado;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Character getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Character operacion) {
        this.operacion = operacion;
    }




}


