package com.rsi.agp.dao.tables.admin;
// Generated by T-Systems


import java.math.BigDecimal;

public class SocioId  implements java.io.Serializable {


    private String nif;
    private Long idasegurado;

    public SocioId() {
    }

    public SocioId(String nif, Long idasegurado) {
       this.nif = nif;
       this.idasegurado = idasegurado;
    }
   
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public Long getIdasegurado() {
        return this.idasegurado;
    }
    
    public void setIdasegurado(Long idasegurado) {
        this.idasegurado = idasegurado;
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SocioId) ) return false;
		 SocioId castOther = ( SocioId ) other; 
        
		 return ( (this.getNif()==castOther.getNif()) || ( this.getNif()!=null && castOther.getNif()!=null && this.getNif().equals(castOther.getNif()) ) )
&& ( (this.getIdasegurado()==castOther.getIdasegurado()) || ( this.getIdasegurado()!=null && castOther.getIdasegurado()!=null && this.getIdasegurado().equals(castOther.getIdasegurado()) ) );
  }
  
  public int hashCode() {
        int result = 17;
        
        result = 37 * result + ( getNif() == null ? 0 : this.getNif().hashCode() );
        result = 37 * result + ( getIdasegurado() == null ? 0 : this.getIdasegurado().hashCode() );
        return result;
  }   



}


