package com.rsi.agp.dao.tables.admin;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

import com.rsi.agp.dao.tables.commons.Localidad;
import com.rsi.agp.dao.tables.commons.Via;

public class Tomador  implements java.io.Serializable {

	private static final long serialVersionUID = -8816159971558470982L;
	
	private TomadorId id;
    private Localidad localidad;
    private Via via;
    private Entidad entidad;
    private String razonsocial;
    private String domicilio;
    private String numvia;
    private String piso;
    private String bloque;
    private String escalera;
    private BigDecimal codpostal;
    private String telefono;
    private String movil;
    private String email;
    /* PTC. 78845 ** CAMPOS NUEVOS (28.02.2022) ** Inicio */
    private String email2;
    private String email3;
    /* PTC. 78845 ** CAMPOS NUEVOS (28.02.2022) ** Fin */
    private String repreNif;
    private String repreNombre;
    private String repreAp1;
    private String repreAp2;
    private Character envioAPagos;
    private Date fechaModificacion;
    private String usuarioModificacion;

   	public Tomador() {
    	id = new TomadorId();
    	localidad = new Localidad();
    	via = new Via();
    	entidad = new Entidad();
    }
    
    public Tomador(TomadorId id)
    {
    	this.id = id;
    }
	
    public Tomador(TomadorId id, Entidad entidad) {
        this.id = id;
        this.entidad = entidad;
    }
    public Tomador(TomadorId id, Localidad localidad, Via via, Entidad entidad, String razonsocial, String domicilio, String numvia, 
    		String piso, String bloque, String escalera, BigDecimal codpostal, String telefono, String movil, String email, 
    		String email2, String email3, String repreNif, String repreNombre, String repreAp1,
    		String repreAp2, Character envioAPagos) {
        this.id = id;
        this.localidad = localidad;
        this.via = via;
        this.entidad = entidad;
        this.razonsocial = razonsocial;
        this.domicilio = domicilio;
        this.numvia = numvia;
        this.piso = piso;
        this.bloque = bloque;
        this.escalera = escalera;
        this.codpostal = codpostal;
        this.telefono = telefono;
        this.movil = movil;
        this.email = email;
        /* PTC. 78845 ** CAMPOS NUEVOS (01.03.2022) ** Inicio */
        this.email2 = email2;
        this.email3 = email3;
        /* PTC. 78845 ** CAMPOS NUEVOS (01.03.2022) ** Fin */
        this.repreNif = repreNif;
        this.repreNombre = repreNombre;
        this.repreAp1 = repreAp1;
        this.repreAp2 = repreAp2;
        this.envioAPagos = envioAPagos;
        
     }
   
    public TomadorId getId() {
        return this.id;
    }
    
    public void setId(TomadorId id) {
        this.id = id;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Via getVia() {
        return this.via;
    }
    
    public void setVia(Via via) {
        this.via = via;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getNumvia() {
        return this.numvia;
    }
    
    public void setNumvia(String numvia) {
        this.numvia = numvia;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public String getBloque() {
        return this.bloque;
    }
    
    public void setBloque(String bloque) {
        this.bloque = bloque;
    }
    public String getEscalera() {
        return this.escalera;
    }
    
    public void setEscalera(String escalera) {
        this.escalera = escalera;
    }
    public BigDecimal getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(BigDecimal codpostal) {
        this.codpostal = codpostal;
    }
    public String getCodpostalstr() {
        
    	if(codpostal == null)
    		return "";
    	
    	String codPostalStr = codpostal.toString();
        
    	while(codPostalStr.length() < 5 )
    		codPostalStr = "0"+codPostalStr;
        
    	return codPostalStr;
    }
    
    public void setCodpostalstr(String codpostalstr) {
        if(codpostalstr != null && !codpostalstr.isEmpty())
        	this.codpostal = new BigDecimal(codpostalstr);
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMovil() {
        return this.movil;
    }
    
    public void setMovil(String movil) {
        this.movil = movil;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    /* PTC. 78845 ** CAMPOS NUEVOS (01.03.2022) ** Inicio */
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }
    public String getEmail3() {
        return this.email3;
    }
    
    public void setEmail3(String email3) {
        this.email3 = email3;
    }
    /* PTC. 78845 ** CAMPOS NUEVOS (01.03.2022) ** Fin */
    public String getRepreNif() {
        return this.repreNif;
    }
    
    public void setRepreNif(String repreNif) {
        this.repreNif = repreNif;
    }
    public String getRepreNombre() {
        return this.repreNombre;
    }
    
    public void setRepreNombre(String repreNombre) {
        this.repreNombre = repreNombre;
    }
    public String getRepreAp1() {
        return this.repreAp1;
    }
    
    public void setRepreAp1(String repreAp1) {
        this.repreAp1 = repreAp1;
    }
    public String getRepreAp2() {
        return this.repreAp2;
    }
    
    public void setRepreAp2(String repreAp2) {
        this.repreAp2 = repreAp2;
    }

	public Character getEnvioAPagos() {
		return envioAPagos;
	}

	public void setEnvioAPagos(Character envioAPagos) {
		this.envioAPagos = envioAPagos;
	}
	 public Date getFechaModificacion() {
		return fechaModificacion;
	}

	 public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	 public String getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}
}


