package com.rsi.agp.dao.tables.admin;
// Generated by T-Systems


import java.math.BigDecimal;

public class TomadorId  implements java.io.Serializable {


     private BigDecimal codentidad;
     private String ciftomador;

    public TomadorId() {
    }

    public TomadorId(BigDecimal codentidad, String ciftomador) {
       this.codentidad = codentidad;
       this.ciftomador = ciftomador;
    }
   
    public BigDecimal getCodentidad() {
        return this.codentidad;
    }
    
    public void setCodentidad(BigDecimal codentidad) {
        this.codentidad = codentidad;
    }
    public String getCiftomador() {
        return this.ciftomador;
    }
    
    public void setCiftomador(String ciftomador) {
        this.ciftomador = ciftomador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TomadorId) ) return false;
		 TomadorId castOther = ( TomadorId ) other; 
         
		 return ( (this.getCodentidad()==castOther.getCodentidad()) || ( this.getCodentidad()!=null && castOther.getCodentidad()!=null && this.getCodentidad().equals(castOther.getCodentidad()) ) )
 && ( (this.getCiftomador()==castOther.getCiftomador()) || ( this.getCiftomador()!=null && castOther.getCiftomador()!=null && this.getCiftomador().equals(castOther.getCiftomador()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodentidad() == null ? 0 : this.getCodentidad().hashCode() );
         result = 37 * result + ( getCiftomador() == null ? 0 : this.getCiftomador().hashCode() );
         return result;
   }   


}


