package com.rsi.agp.dao.tables.comisiones.recibosEmitidos;
// Generated by T-Systems


import java.math.BigDecimal;

public class ReciboEmitidoApliSubvCCAA  implements java.io.Serializable {


     private Long id;
     private ReciboEmitidoAplicacion reciboEmitidoAplicacion;
     private Character codigo;
     private BigDecimal subvcomunidades;

    public ReciboEmitidoApliSubvCCAA() {
    }

	
    public ReciboEmitidoApliSubvCCAA(Long id, ReciboEmitidoAplicacion reciboEmitidoAplicacion) {
        this.id = id;
        this.reciboEmitidoAplicacion = reciboEmitidoAplicacion;
    }
    public ReciboEmitidoApliSubvCCAA(Long id, ReciboEmitidoAplicacion reciboEmitidoAplicacion, Character codigo, BigDecimal subvcomunidades) {
       this.id = id;
       this.reciboEmitidoAplicacion = reciboEmitidoAplicacion;
       this.codigo = codigo;
       this.subvcomunidades = subvcomunidades;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public ReciboEmitidoAplicacion getReciboEmitidoAplicacion() {
        return this.reciboEmitidoAplicacion;
    }
    
    public void setReciboEmitidoAplicacion(ReciboEmitidoAplicacion reciboEmitidoAplicacion) {
        this.reciboEmitidoAplicacion = reciboEmitidoAplicacion;
    }
    public Character getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Character codigo) {
        this.codigo = codigo;
    }
    public BigDecimal getSubvcomunidades() {
        return this.subvcomunidades;
    }
    
    public void setSubvcomunidades(BigDecimal subvcomunidades) {
        this.subvcomunidades = subvcomunidades;
    }




}


