package com.rsi.agp.dao.tables.comisiones.recibosEmitidos;
// Generated by T-Systems


import java.math.BigDecimal;

public class ReciboEmitidoApliBonRec  implements java.io.Serializable {


     private Long id;
     private ReciboEmitidoAplicacion reciboEmitidoAplicacion;
     private Integer codigo;
     private BigDecimal importe;
     //Campos sacados de la tabla de tipos de bonificaciones/recargos
     private String bonRecTipo;
     private String bonRecDescripcion;

    public ReciboEmitidoApliBonRec() {
    }

    public ReciboEmitidoApliBonRec(Long id, ReciboEmitidoAplicacion reciboEmitidoAplicacion, Integer codigo, BigDecimal importe) {
       this.id = id;
       this.reciboEmitidoAplicacion = reciboEmitidoAplicacion;
       this.codigo = codigo;
       this.importe = importe;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public ReciboEmitidoAplicacion getReciboEmitidoAplicacion() {
        return this.reciboEmitidoAplicacion;
    }
    
    public void setReciboEmitidoAplicacion(ReciboEmitidoAplicacion reciboEmitidoAplicacion) {
        this.reciboEmitidoAplicacion = reciboEmitidoAplicacion;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

	public String getBonRecTipo() {
		return bonRecTipo;
	}

	public void setBonRecTipo(String bonRecTipo) {
		this.bonRecTipo = bonRecTipo;
	}

	public String getBonRecDescripcion() {
		return bonRecDescripcion;
	}

	public void setBonRecDescripcion(String bonRecDescripcion) {
		this.bonRecDescripcion = bonRecDescripcion;
	}
}