package com.rsi.agp.core.executor.gan;
// Generated by T-Systems

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.xml.stream.FactoryConfigurationError;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;

import org.xml.sax.SAXException;

import com.rsi.agp.core.executor.GenericXMLParser;
import com.rsi.agp.core.webapp.util.StringUtils;
import com.rsi.agp.dao.tables.cpl.gan.CodConceptoValorPermitido;
import com.rsi.agp.dao.tables.cpl.gan.CodConceptoValorPermitidoId;

/**
 * Parser tabla 0437: Códigos Conceptos y valores permitidos para la aplicación de tipos Subv.
 * @author U029823
 *
 */
public class CodConceptoValorPermitidoXMLParser extends GenericXMLParser {
	
	public static void main(String[] args){
		
		//TEMPORAL
//		args = new String[4];
//		args[0] = "D:\\borrar\\CodigosConceptosValoresPermitidosSubvenciones.xml";
//		args[1] = "D:\\borrar\\CodigosConceptosValoresPermitidosSubvenciones.csv";
//		args[2] = "181";
//		args[3] = "null";
		//FIN TEMPORAL
		
		if (args.length != 4) {
			System.out.println("Usage: java " + CodConceptoValorPermitidoXMLParser.class.getName()
					+ " <XML that needs to be transformed>" + " <Output file>" + " <LineaseguroId>" + " <dateFormat>");
			System.exit(1);
		}
		try {
			CodConceptoValorPermitidoXMLParser parser = new CodConceptoValorPermitidoXMLParser();
			parser.setTagPrincipal(GenericXMLParser.TAG_RG);
			parser.procesarFichero(args[0], args[1], new Long(args[2]), args[3]);
		} catch (FileNotFoundException e) {
			System.out.println("Error al buscar el fichero el fichero de códigos conceptos y valores permitidos " + e.getMessage());
			e.printStackTrace();
			System.exit(2);
		} catch (SAXException e) {
			System.out.println("Error al crear el XMLReader " + e.getMessage());
			e.printStackTrace();
			System.exit(3);
		} catch (IOException e) {
			System.out.println("Error de entrada/salida al parsear el fichero de códigos conceptos y valores permitidos " + e.getMessage());
			e.printStackTrace();
			System.exit(4);
		} catch (XMLStreamException e) {
			System.out.println("Error al parsear el XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(5);
		} catch (FactoryConfigurationError e) {
			System.out.println("Error al crear el parseador XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(6);
		} catch (Exception e) {
			System.out.println("Error indefinido al parsear el XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(7);
		}
	}
	
	@Override
	protected String generaInsert(Object reg, String dateFormat) {
		CodConceptoValorPermitido registro = (CodConceptoValorPermitido)reg;
		String sql = "";
		sql += registro.getId().getLineaseguroid() + ";";
		sql += StringUtils.nullToString(registro.getId().getCodOrganismo()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodTipoSubvencion()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodconcepto()) + ";";
		sql += StringUtils.nullToString(registro.getId().getValorconcepto()) + ";";
		
		return sql;
	}

	@Override
	protected Object generaRegistro(Object actual, String tag, XMLStreamReader parser, int id, Long lineaseguroid) {
		CodConceptoValorPermitido registro;
		if (actual == null){
			registro = new CodConceptoValorPermitido();
		}
		else{
			registro = (CodConceptoValorPermitido) actual;
		}
		
		if (this.getTagPrincipal().equals(tag)){
			CodConceptoValorPermitidoId idActual = new CodConceptoValorPermitidoId();
			
			idActual.setLineaseguroid(lineaseguroid);
			
			//codOrg
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "codOrg").trim()).equals("")){
				idActual.setCodOrganismo(StringUtils.nullToString(parser.getAttributeValue(null, "codOrg").trim()).charAt(0));
			}
			
			//tipSubv
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "tipSubv")).equals("")){
				idActual.setCodTipoSubvencion(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "tipSubv"))));
			}
			
			//codCpto
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "codCpto")).equals("")){
				idActual.setCodconcepto(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "codCpto"))));
			}
			
			//valCpto
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "valCpto")).equals("")){
				idActual.setValorconcepto(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "valCpto"))));
			}
			
			registro.setId(idActual);
		}
		return registro;
	}
}