package com.rsi.agp.core.executor.gan;
// Generated by T-Systems


import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;

import javax.xml.stream.FactoryConfigurationError;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;

import org.xml.sax.SAXException;

import com.rsi.agp.core.executor.GenericXMLParser;
import com.rsi.agp.core.webapp.util.StringUtils;
import com.rsi.agp.dao.tables.cpl.gan.SuspensionCautelarContrato;
import com.rsi.agp.dao.tables.cpl.gan.SuspensionCautelarContratoId;

/**
 * Parser tabla 0433: Suspensión Cautelar Contratación
 * @author U029823
 *
 */
public class SuspensionCautelarContratoXMLParser extends GenericXMLParser {
	
	public static void main(String[] args){
		
		//TEMPORAL
//		args = new String[4];
//		args[0] = "D:\\borrar\\SuspensionCautelarContratacion.xml";
//		args[1] = "D:\\borrar\\SuspensionCautelarContratacion.csv";
//		args[2] = "181";
//		args[3] = GenericXMLParser.formatoOrigen;
		//FIN TEMPORAL
		
		if (args.length != 4) {
			System.out.println("Usage: java " + SuspensionCautelarContratoXMLParser.class.getName()
					+ " <XML that needs to be transformed>" + " <Output file>" + " <LineaseguroId>" + " <dateFormat>");
			System.exit(1);
		}
		try {
			SuspensionCautelarContratoXMLParser parser = new SuspensionCautelarContratoXMLParser();
			parser.setTagPrincipal(GenericXMLParser.TAG_RG);
			parser.procesarFichero(args[0], args[1], new Long(args[2]), args[3]);
		} catch (FileNotFoundException e) {
			System.out.println("Error al buscar el fichero el fichero de suspensión cautelar " + e.getMessage());
			e.printStackTrace();
			System.exit(2);
		} catch (SAXException e) {
			System.out.println("Error al crear el XMLReader " + e.getMessage());
			e.printStackTrace();
			System.exit(3);
		} catch (IOException e) {
			System.out.println("Error de entrada/salida al parsear el fichero de suspensión cautelar " + e.getMessage());
			e.printStackTrace();
			System.exit(4);
		} catch (XMLStreamException e) {
			System.out.println("Error al parsear el XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(5);
		} catch (FactoryConfigurationError e) {
			System.out.println("Error al crear el parseador XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(6);
		} catch (Exception e) {
			System.out.println("Error indefinido al parsear el XML: " + e.getMessage());
			e.printStackTrace();
			System.exit(7);
		}
	}
	
	@Override
	protected String generaInsert(Object reg, String dateFormat) {
		SimpleDateFormat sdf = new SimpleDateFormat(dateFormat, Locale.US);
		SuspensionCautelarContrato registro = (SuspensionCautelarContrato)reg;
		String sql = "";
		sql += registro.getId().getLineaseguroid() + ";";
		sql += StringUtils.nullToString(registro.getId().getCodmodulo()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodtipocapital()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodespecie()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodregimen()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodgruporaza()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodtipoanimal()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodprovincia()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodcomarca()) + ";";
		sql += StringUtils.nullToString(registro.getId().getCodtermino()) + ";";
		sql += StringUtils.nullToString(registro.getId().getSubtermino()) + ";";
		sql += StringUtils.nullToString(registro.getCodAutoEspecial()) + ";";
		sql += StringUtils.nullToString(registro.getCodConceptoPpal()) + ";";
		sql += StringUtils.nullToString(registro.getCodRiesgoCbto()) + ";";
		sql += StringUtils.nullToString(registro.getRiesgoCbtoEle()) + ";";

		if(registro.getFecSuspensionFin() != null){
			sql += sdf.format(registro.getFecSuspensionFin()) + ";";
		}else{
			sql += ";";
		}
		
		if(registro.getFecSuspensionIni() != null){
			sql += sdf.format(registro.getFecSuspensionIni()) + ";";
		}else{
			sql += ";";
		}
		
		return sql;
	}

	@Override
	protected Object generaRegistro(Object actual, String tag, XMLStreamReader parser, int id, Long lineaseguroid) {
		SimpleDateFormat sdf2 = new SimpleDateFormat(GenericXMLParser.FORMATO_ORIGEN);
		SuspensionCautelarContrato registro;
		if (actual == null){
			registro = new SuspensionCautelarContrato();
		}
		else{
			registro = (SuspensionCautelarContrato) actual;
		}

		SuspensionCautelarContratoId idActual = new SuspensionCautelarContratoId();
		
		if (this.getTagPrincipal().equals(tag)){
			
			idActual.setLineaseguroid(lineaseguroid);

			if (!StringUtils.nullToString(parser.getAttributeValue(null, "mod")).equals("")){
				idActual.setCodmodulo(StringUtils.nullToString(parser.getAttributeValue(null, "mod")).trim());
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "tipCptal")).equals("")){
				idActual.setCodtipocapital(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "tipCptal"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "esp")).equals("")){
				idActual.setCodespecie(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "esp"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "reg")).equals("")){
				idActual.setCodregimen(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "reg"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "grupRaza")).equals("")){
				idActual.setCodgruporaza(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "grupRaza"))));
			}

			if (!StringUtils.nullToString(parser.getAttributeValue(null, "tipAnim")).equals("")){
				idActual.setCodtipoanimal(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "tipAnim"))));
			}			

			if (!StringUtils.nullToString(parser.getAttributeValue(null, "prov").trim()).equals("")){
				idActual.setCodprovincia(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "prov"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "com")).equals("")){
				idActual.setCodcomarca(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "com"))));
			}

			if (!StringUtils.nullToString(parser.getAttributeValue(null, "term")).equals("")){
				idActual.setCodtermino(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "term"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "sterm")).equals("")){
				idActual.setSubtermino(StringUtils.nullToString(parser.getAttributeValue(null, "sterm").trim()).charAt(0));
			}

			//autEsp
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "autEsp")).equals("")){
				registro.setCodAutoEspecial(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "autEsp"))));
			}

			if (!StringUtils.nullToString(parser.getAttributeValue(null, "cPMod")).equals("")){
				registro.setCodConceptoPpal(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "cPMod"))));
			}
			
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "codRCub")).equals("")){
				registro.setCodRiesgoCbto(new Long(StringUtils.nullToString(parser.getAttributeValue(null, "codRCub"))));
			}
			
			//riesgCbtoEleg
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "riesgCbtoEleg")).equals("")){
				registro.setRiesgoCbtoEle(StringUtils.nullToString(parser.getAttributeValue(null, "riesgCbtoEleg").trim()).charAt(0));
			}
			
			//fecFinSusp
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "fecFinSusp")).equals("")){
				try {
					registro.setFecSuspensionFin(sdf2.parse(parser.getAttributeValue(null, "fecFinSusp")));
				} catch (ParseException e) {
					//idActual.setFecSuspensionFin(null);
				}
			}
			
			//fecIniSusp
			if (!StringUtils.nullToString(parser.getAttributeValue(null, "fecIniSusp")).equals("")){
				try {
					registro.setFecSuspensionIni(sdf2.parse(parser.getAttributeValue(null, "fecIniSusp")));
				} catch (ParseException e) {
					//registro.setFecSuspensionIni(null);
				}
			}
		
			registro.setId(idActual);
		}

		return registro;
	}
}