package com.rsi.agp.dao.tables.config;
// Generated by T-Systems

import java.util.HashSet;
import java.util.Set;

public class Pantalla implements java.io.Serializable {

	private static final long serialVersionUID = 666347202163090111L;

	private Long idpantalla;
	private String descpantalla;
	private String objetopantalla;
	private Set<PantallaConfigurable> pantallaConfigurables = new HashSet<PantallaConfigurable>(0);

	public Pantalla() {
	}

	public Pantalla(Long idpantalla, String descpantalla) {
		this.idpantalla = idpantalla;
		this.descpantalla = descpantalla;
	}

	public Pantalla(Long idpantalla, String descpantalla, String objetopantalla,
			Set<PantallaConfigurable> pantallaConfigurables) {
		this.idpantalla = idpantalla;
		this.descpantalla = descpantalla;
		this.objetopantalla = objetopantalla;
		this.pantallaConfigurables = pantallaConfigurables;
	}

	public Long getIdpantalla() {
		return this.idpantalla;
	}

	public void setIdpantalla(Long idpantalla) {
		this.idpantalla = idpantalla;
	}

	public String getDescpantalla() {
		return this.descpantalla;
	}

	public void setDescpantalla(String descpantalla) {
		this.descpantalla = descpantalla;
	}

	public String getObjetopantalla() {
		return this.objetopantalla;
	}

	public void setObjetopantalla(String objetopantalla) {
		this.objetopantalla = objetopantalla;
	}

	public Set<PantallaConfigurable> getPantallaConfigurables() {
		return this.pantallaConfigurables;
	}

	public void setPantallaConfigurables(Set<PantallaConfigurable> pantallaConfigurables) {
		this.pantallaConfigurables = pantallaConfigurables;
	}

}
