package com.rsi.agp.dao.tables.copy;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;

public class PagoPoliza  implements java.io.Serializable {


     private Long id;
     private Poliza poliza;
     private Character formapago;
     private Date fectransferencia;
     private BigDecimal importepago;
     private String bancopago;

    public PagoPoliza() {
    }

	
    public PagoPoliza(Long id, Poliza poliza) {
        this.id = id;
        this.poliza = poliza;
    }
    public PagoPoliza(Long id, Poliza poliza, Character formapago, Date fectransferencia, BigDecimal importepago, String bancopago) {
       this.id = id;
       this.poliza = poliza;
       this.formapago = formapago;
       this.fectransferencia = fectransferencia;
       this.importepago = importepago;
       this.bancopago = bancopago;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public Character getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(Character formapago) {
        this.formapago = formapago;
    }
    public Date getFectransferencia() {
        return this.fectransferencia;
    }
    
    public void setFectransferencia(Date fectransferencia) {
        this.fectransferencia = fectransferencia;
    }
    public BigDecimal getImportepago() {
        return this.importepago;
    }
    
    public void setImportepago(BigDecimal importepago) {
        this.importepago = importepago;
    }
    public String getBancopago() {
        return this.bancopago;
    }
    
    public void setBancopago(String bancopago) {
        this.bancopago = bancopago;
    }




}


