package com.rsi.agp.dao.tables.copy;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class Parcela  implements java.io.Serializable {


     private Long id;
     private Poliza poliza;
     private Integer hoja;
     private Integer numero;
     private String nomparcela;
     private BigDecimal codprovincia;
     private BigDecimal codcomarca;
     private BigDecimal codtermino;
     private Character subtermino;
     private BigDecimal codcultivo;
     private BigDecimal codvariedad;
     private String poligono;
     private String parcela;
     private BigDecimal codprovsigpac;
     private BigDecimal codtermsigpac;
     private BigDecimal agrsigpac;
     private BigDecimal zonasigpac;
     private BigDecimal poligonosigpac;
     private BigDecimal parcelasigpac;
     private BigDecimal recintosigpac;
     private Set<CapitalAsegurado> capitalAsegurados = new HashSet<CapitalAsegurado>(0);

    public Parcela() {
    }

	
    public Parcela(Long id, Poliza poliza, BigDecimal codcultivo, BigDecimal codvariedad) {
        this.id = id;
        this.poliza = poliza;
        this.codcultivo = codcultivo;
        this.codvariedad = codvariedad;
    }
    public Parcela(Long id, Poliza poliza, Integer hoja, Integer numero, String nomparcela, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino, BigDecimal codcultivo, BigDecimal codvariedad, String poligono, String parcela, BigDecimal codprovsigpac, BigDecimal codtermsigpac, BigDecimal agrsigpac, BigDecimal zonasigpac, BigDecimal poligonosigpac, BigDecimal parcelasigpac, BigDecimal recintosigpac, Set<CapitalAsegurado> capitalAsegurados) {
       this.id = id;
       this.poliza = poliza;
       this.hoja = hoja;
       this.numero = numero;
       this.nomparcela = nomparcela;
       this.codprovincia = codprovincia;
       this.codcomarca = codcomarca;
       this.codtermino = codtermino;
       this.subtermino = subtermino;
       this.codcultivo = codcultivo;
       this.codvariedad = codvariedad;
       this.poligono = poligono;
       this.parcela = parcela;
       this.codprovsigpac = codprovsigpac;
       this.codtermsigpac = codtermsigpac;
       this.agrsigpac = agrsigpac;
       this.zonasigpac = zonasigpac;
       this.poligonosigpac = poligonosigpac;
       this.parcelasigpac = parcelasigpac;
       this.recintosigpac = recintosigpac;
       this.capitalAsegurados = capitalAsegurados;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public Integer getHoja() {
        return this.hoja;
    }
    
    public void setHoja(Integer hoja) {
        this.hoja = hoja;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getNomparcela() {
        return this.nomparcela;
    }
    
    public void setNomparcela(String nomparcela) {
        this.nomparcela = nomparcela;
    }
    public BigDecimal getCodprovincia() {
        return this.codprovincia;
    }
    
    public void setCodprovincia(BigDecimal codprovincia) {
        this.codprovincia = codprovincia;
    }
    public BigDecimal getCodcomarca() {
        return this.codcomarca;
    }
    
    public void setCodcomarca(BigDecimal codcomarca) {
        this.codcomarca = codcomarca;
    }
    public BigDecimal getCodtermino() {
        return this.codtermino;
    }
    
    public void setCodtermino(BigDecimal codtermino) {
        this.codtermino = codtermino;
    }
    public Character getSubtermino() {
        return this.subtermino;
    }
    
    public void setSubtermino(Character subtermino) {
        this.subtermino = subtermino;
    }
    public BigDecimal getCodcultivo() {
        return this.codcultivo;
    }
    
    public void setCodcultivo(BigDecimal codcultivo) {
        this.codcultivo = codcultivo;
    }
    public BigDecimal getCodvariedad() {
        return this.codvariedad;
    }
    
    public void setCodvariedad(BigDecimal codvariedad) {
        this.codvariedad = codvariedad;
    }
    public String getPoligono() {
        return this.poligono;
    }
    
    public void setPoligono(String poligono) {
        this.poligono = poligono;
    }
    public String getParcela() {
        return this.parcela;
    }
    
    public void setParcela(String parcela) {
        this.parcela = parcela;
    }
    public BigDecimal getCodprovsigpac() {
        return this.codprovsigpac;
    }
    
    public void setCodprovsigpac(BigDecimal codprovsigpac) {
        this.codprovsigpac = codprovsigpac;
    }
    public BigDecimal getCodtermsigpac() {
        return this.codtermsigpac;
    }
    
    public void setCodtermsigpac(BigDecimal codtermsigpac) {
        this.codtermsigpac = codtermsigpac;
    }
    public BigDecimal getAgrsigpac() {
        return this.agrsigpac;
    }
    
    public void setAgrsigpac(BigDecimal agrsigpac) {
        this.agrsigpac = agrsigpac;
    }
    public BigDecimal getZonasigpac() {
        return this.zonasigpac;
    }
    
    public void setZonasigpac(BigDecimal zonasigpac) {
        this.zonasigpac = zonasigpac;
    }
    public BigDecimal getPoligonosigpac() {
        return this.poligonosigpac;
    }
    
    public void setPoligonosigpac(BigDecimal poligonosigpac) {
        this.poligonosigpac = poligonosigpac;
    }
    public BigDecimal getParcelasigpac() {
        return this.parcelasigpac;
    }
    
    public void setParcelasigpac(BigDecimal parcelasigpac) {
        this.parcelasigpac = parcelasigpac;
    }
    public BigDecimal getRecintosigpac() {
        return this.recintosigpac;
    }
    
    public void setRecintosigpac(BigDecimal recintosigpac) {
        this.recintosigpac = recintosigpac;
    }
    public Set<CapitalAsegurado> getCapitalAsegurados() {
        return this.capitalAsegurados;
    }
    
    public void setCapitalAsegurados(Set<CapitalAsegurado> capitalAsegurados) {
        this.capitalAsegurados = capitalAsegurados;
    }




}


