package com.rsi.agp.dao.tables.rc;
// Generated by T-Systems

import java.util.Date;

public class PolizasHistEstadosRC  implements java.io.Serializable {

	private static final long serialVersionUID = -3874284576839028239L;
	
	private Long id;
     private PolizasRC polizasRC;
     private EstadosRC estadosRC;
     private String codusuario;
     private Date fecha;

    public PolizasHistEstadosRC() {
    }

    public PolizasHistEstadosRC(Long id, PolizasRC polizasRC, EstadosRC estadosRC, String codusuario, Date fecha) {
       this.id = id;
       this.polizasRC = polizasRC;
       this.estadosRC = estadosRC;
       this.codusuario = codusuario;
       this.fecha = fecha;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public PolizasRC getPolizasRC() {
        return this.polizasRC;
    }
    
    public void setPolizasRC(PolizasRC polizasRC) {
        this.polizasRC = polizasRC;
    }
    public EstadosRC getEstadosRC() {
        return this.estadosRC;
    }
    
    public void setEstadosRC(EstadosRC estadosRC) {
        this.estadosRC = estadosRC;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


