-- Petición MoDa: SMD000833 (GDLD-78691)
-- Producto: Seguros
-- Esquema: O02AGPE0
-- Tabla: TB_CVS_PARCELAS

-- ALTER TABLE

ALTER TABLE O02AGPE0.TB_CVS_PARCELAS ADD PARCELA_AGRICOLA NUMBER (5) NULL;
