-- CREATE TABLE
CREATE TABLE O02AGPE0.TP_FAMILIA_SEGURO
(COD_FAMILIA_SEG NUMBER(3) NOT NULL,
DETALLE VARCHAR2(255) NOT NULL)
TABLESPACE AGPTS001_ENC;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TP_FAMILIA_SEGURO ADD CONSTRAINT PK_FAM_FAMILIA_SEGURO PRIMARY KEY (COD_FAMILIA_SEG) USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TP_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TP_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_UPD;