-- CREATE TABLE
CREATE TABLE "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS"
("ID" NUMBER(15) NOT NULL,
"IDPOLIZA" NUMBER(15) NOT NULL,
"FECHA" DATE NOT NULL,
"CODUSUARIO" VARCHAR2(8) NOT NULL,
"XML" CLOB NOT NULL)
TABLESPACE "AGPTS001_ENC";

-- PRIMARY KEY
ALTER TABLE "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS" ADD CONSTRAINT "PK_TB_SW_ASEG_DATOS_MEDIDAS" PRIMARY KEY ("ID") USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS" ADD CONSTRAINT "FK_TB_SW_ASEG_DATOS_MEDIDAS_PO" FOREIGN KEY ("IDPOLIZA") REFERENCES "O02AGPE0"."TB_POLIZAS" ("IDPOLIZA")
ON DELETE CASCADE;



-- UNIQUE INDEX
CREATE UNIQUE INDEX "O02AGPE0"."NX_TB_SW_ASEG_DATOS_MEDIDAS_1" ON "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS" ("IDPOLIZA") TABLESPACE 
AGPIX001_ENC;



-- GRANT SELECT
GRANT SELECT ON "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS" TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON "O02AGPE0"."TB_SW_ASEG_DATOS_MEDIDAS" TO 
ROLE_O02AGPE0_UPD;