-- CREATE TABLE
CREATE TABLE O02AGPE0.TB_DIST_COSTE_PARC_SUBV
(ID NUMBER(15) NOT NULL,
ID_DIST_COSTE_PARCELAS NUMBER(15) NOT NULL,
ORIGEN_SUBV VARCHAR2(1) NOT NULL,
CODORGANISMO VARCHAR2(1) NOT NULL,
CODTIPOSUBV NUMBER(2) NOT NULL,
IMPORTE NUMBER NOT NULL,
PCT_SUBVENCION NUMBER(5, 2) NULL,
VALOR_UNITARIO NUMBER(6, 4) NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_PARC_SUBV ADD CONSTRAINT PK_TB_DIST_COSTE_PARC_SUBV PRIMARY KEY (ID) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_PARC_SUBV ADD CONSTRAINT FK_TB_DIST_COSTE_PARC_SUBV_1 FOREIGN KEY (ID_DIST_COSTE_PARCELAS) REFERENCES O02AGPE0.TB_DIST_COSTE_PARCELAS_2015 (ID);





-- INDEX
CREATE INDEX O02AGPE0.NX_TB_DIST_COSTE_PARC_SUBV_1 ON O02AGPE0.TB_DIST_COSTE_PARC_SUBV (ID_DIST_COSTE_PARCELAS, ORIGEN_SUBV, CODORGANISMO, CODTIPOSUBV) TABLESPACE 
AGPIX001;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TB_DIST_COSTE_PARC_SUBV TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TB_DIST_COSTE_PARC_SUBV TO 
ROLE_O02AGPE0_UPD;

grant select on O02AGPE0.TB_DIST_COSTE_PARC_SUBV to O02AGPE1;