-- CREATE TABLE
CREATE TABLE "O02AGPE0"."TB_AUDIT_CAMBIO_SUBVS"
("ID" NUMBER(15) NOT NULL,
"FECHA" DATE NOT NULL,
"IDPOLIZA" NUMBER(15) NOT NULL,
"CODUSUARIO" VARCHAR2(8) NOT NULL,
"DETALLE" VARCHAR2(255) NOT NULL)
TABLESPACE "AGPTS001_ENC";

-- PRIMARY KEY
ALTER TABLE "O02AGPE0"."TB_AUDIT_CAMBIO_SUBVS" ADD CONSTRAINT "PK_TB_AUDIT_CAMBIO_SUBVS" PRIMARY KEY ("ID") USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;

-- GRANT SELECT
GRANT SELECT ON "O02AGPE0"."TB_AUDIT_CAMBIO_SUBVS" TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON "O02AGPE0"."TB_AUDIT_CAMBIO_SUBVS" TO 
ROLE_O02AGPE0_UPD;