-- CREATE TABLE
CREATE TABLE O02AGPE0.TP_GRUPO_FAMILIA_SEG
(COD_GRUPO_FAMILIA_SEG VARCHAR2(2) NOT NULL,
DETALLE VARCHAR2(255) NOT NULL)
TABLESPACE AGPTS001_ENC;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TP_GRUPO_FAMILIA_SEG ADD CONSTRAINT PK_TP_GRUPO_FAMILIA_SEG PRIMARY KEY (COD_GRUPO_FAMILIA_SEG) USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TP_GRUPO_FAMILIA_SEG TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TP_GRUPO_FAMILIA_SEG TO 
ROLE_O02AGPE0_UPD;