-- CREATE TABLE
CREATE TABLE O02AGPE0.TB_DOC_AGROSEGURO_PERFIL
(ID NUMBER(15) NOT NULL,
ID_DOC_AGRO NUMBER(15) NOT NULL,
IDPERFIL NUMBER(2) NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO_PERFIL ADD CONSTRAINT PK_TB_DOC_AGROSEGURO_PERFIL PRIMARY KEY (ID) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO_PERFIL ADD CONSTRAINT FK_TB_DOC_AGROSEGURO FOREIGN KEY (ID_DOC_AGRO) REFERENCES O02AGPE0.TB_DOC_AGROSEGURO (ID);
-- FOREIGN KEY
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO_PERFIL ADD CONSTRAINT FK_TB_PERFIL FOREIGN KEY (IDPERFIL) REFERENCES O02AGPE0.TB_PERFIL (ID);



-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TB_DOC_AGROSEGURO_PERFIL TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TB_DOC_AGROSEGURO_PERFIL TO 
ROLE_O02AGPE0_UPD;

CREATE SEQUENCE SQ_TB_DOC_AGROSEGURO_PERFIL MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;