-- ALTER TABLE
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO MODIFY NOMBRE VARCHAR2(256);
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO MODIFY DESCRIPCION VARCHAR2(255);
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD CODPLAN NUMBER(4) NULL;
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD CODLINEA NUMBER(3) NULL;
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD CODENTIDAD NUMBER(4) NULL;
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD FECHA_VALIDEZ DATE NULL;
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD CODUSUARIO VARCHAR2(8) NULL;
ALTER TABLE O02AGPE0.TB_DOC_AGROSEGURO ADD FECHA DATE NULL;