-- CREATE TABLE
CREATE TABLE O02AGPE0.TB_DIST_COSTE_EXPL_BR
(ID NUMBER(15) NOT NULL,
ID_DIST_COSTE_EXPLOTACIONES NUMBER(15) NOT NULL,
CODIGO NUMBER(3) NOT NULL,
IMPORTE NUMBER NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_EXPL_BR ADD CONSTRAINT PK_TB_DIST_COSTE_EXPL_BR PRIMARY KEY (ID) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_EXPL_BR ADD CONSTRAINT FK_TB_DIST_COSTE_EXPL_BR_1 FOREIGN KEY (ID_DIST_COSTE_EXPLOTACIONES) REFERENCES O02AGPE0.TB_DIST_COSTE_EXPLOTACIONES (ID);



-- UNIQUE INDEX
CREATE UNIQUE INDEX O02AGPE0.NX_TB_DIST_COSTE_EXPL_BR_1 ON O02AGPE0.TB_DIST_COSTE_EXPL_BR (ID_DIST_COSTE_EXPLOTACIONES, CODIGO) TABLESPACE 
AGPIX001;



-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TB_DIST_COSTE_EXPL_BR TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TB_DIST_COSTE_EXPL_BR TO 
ROLE_O02AGPE0_UPD;

grant select on o02agpe0.TB_DIST_COSTE_EXPL_BR to O02AGPE1;