-- FOREIGN KEY
ALTER TABLE "O02AGPE0"."TB_AUDIT_CAMBIO_SUBVS" ADD CONSTRAINT "FK_TB_AUDIT_CAMBIO_SUBVS_POL" FOREIGN KEY ("IDPOLIZA") REFERENCES "O02AGPE0"."TB_POLIZAS" ("IDPOLIZA")
ON DELETE CASCADE;
   