-- ALTER TABLE
ALTER TABLE O02AGPE0.TB_SUBENTIDADES_MEDIADORAS ADD EMAIL VARCHAR2(50) NULL;
ALTER TABLE O02AGPE0.TB_SUBENTIDADES_MEDIADORAS ADD EMAIL_2 VARCHAR2(50) NULL;
ALTER TABLE O02AGPE0.TB_SUBENTIDADES_MEDIADORAS ADD IND_GASTOS_ADQ NUMBER(1) DEFAULT 0 NOT NULL;