-- CREATE TABLE
CREATE TABLE "O02AGPE0"."TB_SW_ENVIOS_COLECTIVO"
("ID" NUMBER(15) NOT NULL,
"IDCOLECTIVO" NUMBER(15) NOT NULL,
"FECHA" DATE NOT NULL,
"CODUSUARIO" VARCHAR2(8) NOT NULL,
"XML_ENVIO" CLOB NOT NULL,
"XML_RESPUESTA" CLOB NOT NULL)
TABLESPACE "AGPTS001_ENC";

-- PRIMARY KEY
ALTER TABLE "O02AGPE0"."TB_SW_ENVIOS_COLECTIVO" ADD CONSTRAINT "PK_TB_SW_ENVIOS_COLECTIVO" PRIMARY KEY ("ID") USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE "O02AGPE0"."TB_SW_ENVIOS_COLECTIVO" ADD CONSTRAINT "FK_TB_SW_ENVIOS_COLECTIVO_COL" FOREIGN KEY ("IDCOLECTIVO") REFERENCES "O02AGPE0"."TB_COLECTIVOS" ("ID") ON DELETE CASCADE;







-- GRANT SELECT
GRANT SELECT ON "O02AGPE0"."TB_SW_ENVIOS_COLECTIVO" TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON "O02AGPE0"."TB_SW_ENVIOS_COLECTIVO" TO 
ROLE_O02AGPE0_UPD;