-- ALTER TABLE
ALTER TABLE "O02AGPE0"."TB_DIST_COSTE_EXPLOTACIONES" ADD "PRIMACOMERCIAL" NUMBER(11, 2) NULL;
ALTER TABLE "O02AGPE0"."TB_DIST_COSTE_EXPLOTACIONES" ADD "PRIMACOMERCIALNETA" NUMBER(11, 2) NULL;
ALTER TABLE "O02AGPE0"."TB_DIST_COSTE_EXPLOTACIONES" ADD "RECARGOCONSORCIO" NUMBER(11, 2) NULL;
ALTER TABLE "O02AGPE0"."TB_DIST_COSTE_EXPLOTACIONES" ADD "RECIBOPRIMA" NUMBER(11, 2) NULL; 