-- CREATE TABLE
CREATE TABLE O02AGPE0.TP_GRUPO_FAMILIA_SEG
(COD_GRUPO_FAMILIA_SEG VARCHAR2(2) NOT NULL,
DETALLE VARCHAR2(255) NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TP_GRUPO_FAMILIA_SEG ADD CONSTRAINT PK_TP_GRUPO_FAMILIA_SEG PRIMARY KEY (COD_GRUPO_FAMILIA_SEG) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TP_GRUPO_FAMILIA_SEG TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TP_GRUPO_FAMILIA_SEG TO 
ROLE_O02AGPE0_UPD;

-- CREATE TABLE
CREATE TABLE O02AGPE0.TP_FAMILIA_SEGURO
(COD_FAMILIA_SEG NUMBER(3) NOT NULL,
DETALLE VARCHAR2(255) NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TP_FAMILIA_SEGURO ADD CONSTRAINT PK_FAM_FAMILIA_SEGURO PRIMARY KEY (COD_FAMILIA_SEG) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TP_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TP_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_UPD;

-- CREATE TABLE
CREATE TABLE O02AGPE0.LIN_FAMILIA_SEGURO
(COD_GRUPO_FAMILIA_SEG VARCHAR2(2) NOT NULL,
COD_FAMILIA_SEG NUMBER(3) NOT NULL,
CODLINEA NUMBER(3) NOT NULL,
GRUPO_NEGOCIO VARCHAR2(1) NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.LIN_FAMILIA_SEGURO ADD CONSTRAINT PK_LIN_FAMILIA_SEGURO PRIMARY KEY (COD_GRUPO_FAMILIA_SEG, COD_FAMILIA_SEG, CODLINEA, GRUPO_NEGOCIO) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE O02AGPE0.LIN_FAMILIA_SEGURO ADD CONSTRAINT FK_LIN_FAMILIA_SEGURO_FAM FOREIGN KEY (COD_FAMILIA_SEG) REFERENCES O02AGPE0.TP_FAMILIA_SEGURO (COD_FAMILIA_SEG);
-- FOREIGN KEY
ALTER TABLE O02AGPE0.LIN_FAMILIA_SEGURO ADD CONSTRAINT FK_LIN_FAMILIA_SEGURO_GN FOREIGN KEY (GRUPO_NEGOCIO) REFERENCES O02AGPE0.TB_SC_C_GRUPOS_NEGOCIO (GRUPO_NEGOCIO);
-- FOREIGN KEY
ALTER TABLE O02AGPE0.LIN_FAMILIA_SEGURO ADD CONSTRAINT FK_LIN_FAMILIA_SEGURO_GS FOREIGN KEY (COD_GRUPO_FAMILIA_SEG) REFERENCES O02AGPE0.TP_GRUPO_FAMILIA_SEG (COD_GRUPO_FAMILIA_SEG);
-- FOREIGN KEY
ALTER TABLE O02AGPE0.LIN_FAMILIA_SEGURO ADD CONSTRAINT FK_LIN_FAMILIA_SEGURO_LIN FOREIGN KEY (CODLINEA) REFERENCES O02AGPE0.TB_SC_C_LINEAS (CODLINEA);

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.LIN_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.LIN_FAMILIA_SEGURO TO 
ROLE_O02AGPE0_UPD;