-- ALTER TABLE
ALTER  TABLE O02AGPE0.TB_SC_C_ASEG_AUTORIZADOS_G MODIFY CODIGO_REGA NULL;
ALTER  TABLE O02AGPE0.TB_SC_C_ASEG_AUTORIZADOS_G MODIFY NIF_ASEGURADO NULL;

--DROP PK
ALTER TABLE O02AGPE0.TB_SC_C_ASEG_AUTORIZADOS_G DROP CONSTRAINT PK_SC_C_ASEG_AUTO_G; 


-- UNIQUE INDEX
CREATE UNIQUE INDEX O02AGPE0.NX_TB_SC_C_ASEG_AUTORIZA_G_1 ON O02AGPE0.TB_SC_C_ASEG_AUTORIZADOS_G (LINEASEGUROID, CODMODULO, NIF_ASEGURADO, CODIGO_REGA, CODTIPOCAPITAL, CODESPECIE, CODREGIMEN, CODGRUPORAZA, CODTIPOANIMAL, COD_CONCEPTO_PPAL, COD_RIESGO_CBTO, COD_GARANTIZADO, COD_ADAPT_EXPLOT) TABLESPACE 
AGPIX001;