-- CREATE TABLE
CREATE TABLE "O02AGPE0"."TB_AUDIT_CALC_ANEXO_EXT"
("ID" NUMBER(15) NOT NULL,
"CODIGO_INTERNO" VARCHAR2(12) NOT NULL,
"HORA_LLAMADA" DATE NOT NULL,
"REFERENCIA" VARCHAR2(7) NULL,
"PLAN" NUMBER(4) NULL,
"TIPO_POLIZA" VARCHAR2(1) NULL,
"IDCUPON" VARCHAR2(14) NULL,
"CALCULAR_SIT_ACT" NUMBER(1) NULL,
"MODIFICACION_PLZ" CLOB NULL,
"ACUSE_RECIBO" CLOB NULL,
"CALCULO_MODIFICACION" CLOB NULL,
"CALCULO_ORIGINAL" CLOB NULL,
"DIFERENCIAS_COSTE" CLOB NULL,
"RESULTADO" NUMBER(1) NOT NULL,
"MENSAJE" VARCHAR2(1000) NULL,
"SERVICIO" CHAR(20) NOT NULL)
TABLESPACE "AGPTS001_ENC";

-- PRIMARY KEY
ALTER TABLE "O02AGPE0"."TB_AUDIT_CALC_ANEXO_EXT" ADD CONSTRAINT "PK_TB_AUDIT_CALC_ANEXO_EXT" PRIMARY KEY ("ID") USING INDEX TABLESPACE 
AGPIX001_ENC
COMPUTE STATISTICS;









-- GRANT SELECT
GRANT SELECT ON "O02AGPE0"."TB_AUDIT_CALC_ANEXO_EXT" TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON "O02AGPE0"."TB_AUDIT_CALC_ANEXO_EXT" TO 
ROLE_O02AGPE0_UPD;