-- CREATE TABLE
CREATE TABLE O02AGPE0.TB_DIST_COSTE_PARC_BR
(ID NUMBER(15) NOT NULL,
ID_DIST_COSTE_PARCELAS NUMBER(15) NOT NULL,
CODIGO NUMBER(3) NOT NULL,
IMPORTE NUMBER NOT NULL)
TABLESPACE AGPTS001;

-- PRIMARY KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_PARC_BR ADD CONSTRAINT PK_TB_DIST_COSTE_PARC_BR PRIMARY KEY (ID) USING INDEX TABLESPACE 
AGPIX001
COMPUTE STATISTICS;

-- FOREIGN KEY
ALTER TABLE O02AGPE0.TB_DIST_COSTE_PARC_BR ADD CONSTRAINT FK_TB_DIST_COSTE_PARC_BR_1 FOREIGN KEY (ID_DIST_COSTE_PARCELAS) REFERENCES O02AGPE0.TB_DIST_COSTE_PARCELAS_2015 (ID);





-- INDEX
CREATE INDEX O02AGPE0.NX_TB_DIST_COSTE_PARC_BR_1 ON O02AGPE0.TB_DIST_COSTE_PARC_BR (ID_DIST_COSTE_PARCELAS, CODIGO) TABLESPACE 
AGPIX001;

-- GRANT SELECT
GRANT SELECT ON O02AGPE0.TB_DIST_COSTE_PARC_BR TO 
ROLE_O02AGPE0_SEL;

-- GRANT UPDATE
GRANT SELECT, INSERT, UPDATE, DELETE ON O02AGPE0.TB_DIST_COSTE_PARC_BR TO 
ROLE_O02AGPE0_UPD;

grant select on O02AGPE0.TB_DIST_COSTE_PARC_BR to O02AGPE1;