package com.rsi.agp.dao.tables.comisiones.unificado;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class ReciboUnificado  implements java.io.Serializable {


     private Long id;
     private FaseUnificado fase;
     private ColectivoUnificado colectivo;
     private AplicacionUnificado aplicacion;
     private IndividualUnificado individual;
     private Integer linea;
     private Integer recibo;
     private Integer tipo;
     private Integer plan;
     private Set<GrupoNegocioUnificado> grupoNegocios = new HashSet<GrupoNegocioUnificado>(0);
     private Set<AplicacionUnificado> aplicacions = new HashSet<AplicacionUnificado>(0);

    public ReciboUnificado() {
    }

	
    public ReciboUnificado(Long id, Integer recibo) {
        this.id = id;
        this.recibo = recibo;
    }
    public ReciboUnificado(Long id, FaseUnificado fase, ColectivoUnificado colectivo, AplicacionUnificado aplicacion, IndividualUnificado individual, Integer linea, Integer recibo, Integer tipo, Integer plan, Set<GrupoNegocioUnificado> grupoNegocios, Set<AplicacionUnificado> aplicacions) {
       this.id = id;
       this.fase = fase;
       this.colectivo = colectivo;
       this.aplicacion = aplicacion;
       this.individual = individual;
       this.linea = linea;
       this.recibo = recibo;
       this.tipo = tipo;
       this.plan = plan;
       this.grupoNegocios = grupoNegocios;
       this.aplicacions = aplicacions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public FaseUnificado getFase() {
        return this.fase;
    }
    
    public void setFase(FaseUnificado fase) {
        this.fase = fase;
    }
    public ColectivoUnificado getColectivo() {
        return this.colectivo;
    }
    
    public void setColectivo(ColectivoUnificado colectivo) {
        this.colectivo = colectivo;
    }
    public AplicacionUnificado getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(AplicacionUnificado aplicacion) {
        this.aplicacion = aplicacion;
    }
    public IndividualUnificado getIndividual() {
        return this.individual;
    }
    
    public void setIndividual(IndividualUnificado individual) {
        this.individual = individual;
    }
    public Integer getLinea() {
        return this.linea;
    }
    
    public void setLinea(Integer linea) {
        this.linea = linea;
    }
    public Integer getRecibo() {
        return this.recibo;
    }
    
    public void setRecibo(Integer recibo) {
        this.recibo = recibo;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public Integer getPlan() {
        return this.plan;
    }
    
    public void setPlan(Integer plan) {
        this.plan = plan;
    }
    public Set<GrupoNegocioUnificado> getGrupoNegocios() {
        return this.grupoNegocios;
    }
    
    public void setGrupoNegocios(Set<GrupoNegocioUnificado> grupoNegocios) {
        this.grupoNegocios = grupoNegocios;
    }
    public Set<AplicacionUnificado> getAplicacions() {
        return this.aplicacions;
    }
    
    public void setAplicacions(Set<AplicacionUnificado> aplicacions) {
        this.aplicacions = aplicacions;
    }




}


