package com.rsi.agp.dao.tables.poliza.explotaciones.oddv;
// Generated by T-Systems



public class VistaIgpDoGanado  implements java.io.Serializable {


     private VistaIgpDoGanadoId id;

    public VistaIgpDoGanado() {
    }
    
    /**
     * Constructor necesario para los campos distinct de la lupa
     * @param o
     */
    public VistaIgpDoGanado (Object[] o) {
    	VistaIgpDoGanadoId vid= new VistaIgpDoGanadoId();
    	vid.setValorCpto(new Integer (o[0].toString()));
    	vid.setDescripcion(o[1].toString());
    	id=vid;
    	
    }

    public VistaIgpDoGanado(VistaIgpDoGanadoId id) {
       this.id = id;
    }
   
    public VistaIgpDoGanadoId getId() {
        return this.id;
    }
    
    public void setId(VistaIgpDoGanadoId id) {
        this.id = id;
    }




}


