package com.rsi.agp.dao.tables.poliza.explotaciones.oddv;
// Generated by T-Systems



public class VistaAlojamiento  implements java.io.Serializable {


     private VistaAlojamientoId id;

    public VistaAlojamiento() {
    }
    
    public VistaAlojamiento(Object[] o) {
    	VistaAlojamientoId vid= new VistaAlojamientoId();
    	vid.setValorCpto(new Integer (o[0].toString()));
    	vid.setDescripcion(o[1].toString());
    	id=vid;
    }

    public VistaAlojamiento(VistaAlojamientoId id) {
       this.id = id;
    }
   
    public VistaAlojamientoId getId() {
        return this.id;
    }
    
    public void setId(VistaAlojamientoId id) {
        this.id = id;
    }




}


