package com.rsi.agp.dao.tables.poliza.explotaciones.oddv;
// Generated by T-Systems


import java.math.BigDecimal;

public class VistaCalidadProduccionId  implements java.io.Serializable {


     private Integer valorCpto;
     private String descripcion;

    public VistaCalidadProduccionId() {
    }

	
    public VistaCalidadProduccionId(Integer valorCpto) {
        this.valorCpto = valorCpto;
    }
    public VistaCalidadProduccionId(Integer valorCpto, String descripcion) {
       this.valorCpto = valorCpto;
       this.descripcion = descripcion;
    }
   
    public Integer getValorCpto() {
        return this.valorCpto;
    }
    
    public void setValorCpto(Integer valorCpto) {
        this.valorCpto = valorCpto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VistaCalidadProduccionId) ) return false;
		 VistaCalidadProduccionId castOther = ( VistaCalidadProduccionId ) other; 
         
		 return ( (this.getValorCpto()==castOther.getValorCpto()) || ( this.getValorCpto()!=null && castOther.getValorCpto()!=null && this.getValorCpto().equals(castOther.getValorCpto()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getValorCpto() == null ? 0 : this.getValorCpto().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         return result;
   }   


}


