package com.rsi.agp.dao.tables.poliza.explotaciones.oddv;
// Generated by T-Systems



public class VistaEmpresaGestora  implements java.io.Serializable {


     private VistaEmpresaGestoraId id;

    public VistaEmpresaGestora() {
    }

    public VistaEmpresaGestora(VistaEmpresaGestoraId id) {
       this.id = id;
    }
    
    public VistaEmpresaGestora(Object[] o2) {
    	VistaEmpresaGestoraId v2 = new VistaEmpresaGestoraId(new Integer (o2[0].toString()), o2[1].toString(), null, null, null, null, null, null, null, null, null, null);
    	setId(v2);
    }
   
    public VistaEmpresaGestoraId getId() {
        return this.id;
    }
    
    public void setId(VistaEmpresaGestoraId id) {
        this.id = id;
    }




}


