package com.rsi.agp.dao.tables.poliza.explotaciones.oddv;
// Generated by T-Systems



public class VistaTipoGanaderia  implements java.io.Serializable {


     private VistaTipoGanaderiaId id;

    public VistaTipoGanaderia() {
    }
    
    /**
     * Constructor necesario para los campos distinct de la lupa
     * @param o
     */
    public VistaTipoGanaderia (Object[] o) {
    	VistaTipoGanaderiaId vid= new VistaTipoGanaderiaId();
    	vid.setValorCpto(new Integer (o[0].toString()));
    	vid.setDescripcion(o[1].toString());
    	id=vid;
    	
    }

    public VistaTipoGanaderia(VistaTipoGanaderiaId id) {
       this.id = id;
    }
   
    public VistaTipoGanaderiaId getId() {
        return this.id;
    }
    
    public void setId(VistaTipoGanaderiaId id) {
        this.id = id;
    }




}


