package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems

import com.rsi.agp.dao.tables.cgen.Garantizado;
import com.rsi.agp.dao.tables.cgen.TipoRendimiento;
import com.rsi.agp.dao.tables.poliza.Linea;
import java.math.BigDecimal;

public class AsegSubvAdicionalEnesa implements java.io.Serializable {

	private static final long serialVersionUID = 4768387776502849112L;
	
	private AsegSubvAdicionalEnesaId id;
	private Garantizado garantizado;
	private Modulo modulo;
	private Linea linea;
	private TipoRendimiento tipoRendimiento;
	private BigDecimal numanioscontrata;

	public AsegSubvAdicionalEnesa() {
	}

	public AsegSubvAdicionalEnesa(AsegSubvAdicionalEnesaId id, Modulo modulo, Linea linea,
			BigDecimal numanioscontrata) {
		this.id = id;
		this.modulo = modulo;
		this.linea = linea;
		this.numanioscontrata = numanioscontrata;
	}

	public AsegSubvAdicionalEnesa(AsegSubvAdicionalEnesaId id, Garantizado garantizado, Modulo modulo, Linea linea,
			TipoRendimiento tipoRendimiento, BigDecimal numanioscontrata) {
		this.id = id;
		this.garantizado = garantizado;
		this.modulo = modulo;
		this.linea = linea;
		this.tipoRendimiento = tipoRendimiento;
		this.numanioscontrata = numanioscontrata;
	}

	public AsegSubvAdicionalEnesaId getId() {
		return this.id;
	}

	public void setId(AsegSubvAdicionalEnesaId id) {
		this.id = id;
	}

	public Garantizado getGarantizado() {
		return this.garantizado;
	}

	public void setGarantizado(Garantizado garantizado) {
		this.garantizado = garantizado;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Linea getLinea() {
		return this.linea;
	}

	public void setLinea(Linea linea) {
		this.linea = linea;
	}

	public TipoRendimiento getTipoRendimiento() {
		return this.tipoRendimiento;
	}

	public void setTipoRendimiento(TipoRendimiento tipoRendimiento) {
		this.tipoRendimiento = tipoRendimiento;
	}

	public BigDecimal getNumanioscontrata() {
		return this.numanioscontrata;
	}

	public void setNumanioscontrata(BigDecimal numanioscontrata) {
		this.numanioscontrata = numanioscontrata;
	}

}
