package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.CaracteristicaExplotacion;
import com.rsi.agp.dao.tables.poliza.Linea;

public class CondicionesAsociadasTipologiaExplotacion  implements java.io.Serializable {


     private CondicionesAsociadasTipologiaExplotacionId id;
     private CaracteristicaExplotacion caracteristicaExplotacion;
     private Linea linea;

    public CondicionesAsociadasTipologiaExplotacion() {
    }

    public CondicionesAsociadasTipologiaExplotacion(CondicionesAsociadasTipologiaExplotacionId id, CaracteristicaExplotacion caracteristicaExplotacion, Linea linea) {
       this.id = id;
       this.caracteristicaExplotacion = caracteristicaExplotacion;
       this.linea = linea;
    }
   
    public CondicionesAsociadasTipologiaExplotacionId getId() {
        return this.id;
    }
    
    public void setId(CondicionesAsociadasTipologiaExplotacionId id) {
        this.id = id;
    }
    public CaracteristicaExplotacion getCaracteristicaExplotacion() {
        return this.caracteristicaExplotacion;
    }
    
    public void setCaracteristicaExplotacion(CaracteristicaExplotacion caracteristicaExplotacion) {
        this.caracteristicaExplotacion = caracteristicaExplotacion;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }




}


