package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.poliza.Linea;
import java.math.BigDecimal;

public class CondicionesFraccionamiento  implements java.io.Serializable {

	 private static final long serialVersionUID = -8723923911105126380L;
	 
	 private CondicionesFraccionamientoId id;
	 private Modulo modulo;
     private Linea linea;
     private BigDecimal pctRecAval;
     private BigDecimal pctRecFracc;
     private BigDecimal impMinRecAval;

    public CondicionesFraccionamiento() {
    }

	
    public CondicionesFraccionamiento(CondicionesFraccionamientoId id, Modulo modulo, Linea linea) {
        this.id = id;
        this.modulo = modulo;
        this.linea = linea;
    }
    public CondicionesFraccionamiento(CondicionesFraccionamientoId id, Modulo modulo, Linea linea, BigDecimal pctRecAval, BigDecimal pctRecFracc, BigDecimal impMinRecAval) {
       this.id = id;
       this.modulo = modulo;
       this.linea = linea;
       this.pctRecAval = pctRecAval;
       this.pctRecFracc = pctRecFracc;
       this.impMinRecAval = impMinRecAval;
    }
    
    public CondicionesFraccionamientoId getId() {
        return this.id;
    }
    
    public void setId(CondicionesFraccionamientoId id) {
        this.id = id;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public BigDecimal getPctRecAval() {
        return this.pctRecAval;
    }
    
    public void setPctRecAval(BigDecimal pctRecAval) {
        this.pctRecAval = pctRecAval;
    }
    public BigDecimal getPctRecFracc() {
        return this.pctRecFracc;
    }
    
    public void setPctRecFracc(BigDecimal pctRecFracc) {
        this.pctRecFracc = pctRecFracc;
    }
    public BigDecimal getImpMinRecAval() {
        return this.impMinRecAval;
    }
    
    public void setImpMinRecAval(BigDecimal impMinRecAval) {
        this.impMinRecAval = impMinRecAval;
    }


	public Modulo getModulo() {
		return modulo;
	}


	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}




}


