package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems

import java.math.BigDecimal;

public class CultivoId implements java.io.Serializable {

	private static final long serialVersionUID = 3899592249399559192L;

	private java.lang.Long lineaseguroid;
	private BigDecimal codcultivo;

	public CultivoId() {
	}

	public CultivoId(java.lang.Long lineaseguroid, BigDecimal codcultivo) {
		this.lineaseguroid = lineaseguroid;
		this.codcultivo = codcultivo;
	}

	public java.lang.Long getLineaseguroid() {
		return this.lineaseguroid;
	}

	public void setLineaseguroid(java.lang.Long lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	public BigDecimal getCodcultivo() {
		return this.codcultivo;
	}

	public void setCodcultivo(BigDecimal codcultivo) {
		this.codcultivo = codcultivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CultivoId))
			return false;
		CultivoId castOther = (CultivoId) other;

		return ((this.getLineaseguroid() == castOther.getLineaseguroid())
				|| (this.getLineaseguroid() != null && castOther.getLineaseguroid() != null
						&& this.getLineaseguroid().equals(castOther.getLineaseguroid())))
				&& ((this.getCodcultivo() == castOther.getCodcultivo())
						|| (this.getCodcultivo() != null && castOther.getCodcultivo() != null
								&& this.getCodcultivo().equals(castOther.getCodcultivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode());
		result = 37 * result + (getCodcultivo() == null ? 0 : this.getCodcultivo().hashCode());
		return result;
	}

}
