package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.Date;

import com.rsi.agp.dao.tables.cgen.PracticaCultural;
import com.rsi.agp.dao.tables.cgen.TipoCapital;

public class FechaFinGarantia308 implements java.io.Serializable {

	private static final long serialVersionUID = -25571288829354239L;

	private FechaFinGarantiaId id;
	private EstadoFenologico estadoFenologicoByFkFecGarantEstFenD;
	private Modulo modulo;
	private PracticaCultural practicaCultural;
	private EstadoFenologico estadoFenologicoByFkFecGarantEstFenH;
	private Variedad variedad;
	private TipoCapital tipoCapital;
	private BigDecimal codconceptoppalmod;
	private BigDecimal codriesgocubierto;
	private BigDecimal codprovincia;
	private BigDecimal codcomarca;
	private BigDecimal codtermino;
	private Character subtermino;
	private Date fgarantdesde;
	private BigDecimal nummesesdesde;
	private BigDecimal numdiasdesde;
	private Date fgaranthasta;
	private BigDecimal nummeseshasta;
	private BigDecimal numdiashasta;

	public FechaFinGarantia308() {
	}
	
	public FechaFinGarantia308(Object[] o) {
		fgaranthasta = (Date) o[0];
	}

	public FechaFinGarantia308(FechaFinGarantiaId id, EstadoFenologico estadoFenologicoByFkFecGarantEstFenD, Modulo modulo,
			EstadoFenologico estadoFenologicoByFkFecGarantEstFenH, Variedad variedad, BigDecimal codconceptoppalmod,
			BigDecimal codriesgocubierto, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino,
			Character subtermino) {
		this.id = id;
		this.estadoFenologicoByFkFecGarantEstFenD = estadoFenologicoByFkFecGarantEstFenD;
		this.modulo = modulo;
		this.estadoFenologicoByFkFecGarantEstFenH = estadoFenologicoByFkFecGarantEstFenH;
		this.variedad = variedad;
		this.codconceptoppalmod = codconceptoppalmod;
		this.codriesgocubierto = codriesgocubierto;
		this.codprovincia = codprovincia;
		this.codcomarca = codcomarca;
		this.codtermino = codtermino;
		this.subtermino = subtermino;
	}

	public FechaFinGarantia308(FechaFinGarantiaId id, EstadoFenologico estadoFenologicoByFkFecGarantEstFenD, Modulo modulo,
			PracticaCultural practicaCultural, EstadoFenologico estadoFenologicoByFkFecGarantEstFenH, Variedad variedad,
			TipoCapital tipoCapital, BigDecimal codconceptoppalmod, BigDecimal codriesgocubierto,
			BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino,
			Date fgarantdesde, BigDecimal nummesesdesde, BigDecimal numdiasdesde, Date fgaranthasta,
			BigDecimal nummeseshasta, BigDecimal numdiashasta) {
		this.id = id;
		this.estadoFenologicoByFkFecGarantEstFenD = estadoFenologicoByFkFecGarantEstFenD;
		this.modulo = modulo;
		this.practicaCultural = practicaCultural;
		this.estadoFenologicoByFkFecGarantEstFenH = estadoFenologicoByFkFecGarantEstFenH;
		this.variedad = variedad;
		this.tipoCapital = tipoCapital;
		this.codconceptoppalmod = codconceptoppalmod;
		this.codriesgocubierto = codriesgocubierto;
		this.codprovincia = codprovincia;
		this.codcomarca = codcomarca;
		this.codtermino = codtermino;
		this.subtermino = subtermino;
		this.fgarantdesde = fgarantdesde;
		this.nummesesdesde = nummesesdesde;
		this.numdiasdesde = numdiasdesde;
		this.fgaranthasta = fgaranthasta;
		this.nummeseshasta = nummeseshasta;
		this.numdiashasta = numdiashasta;
	}

	public FechaFinGarantiaId getId() {
		return this.id;
	}

	public void setId(FechaFinGarantiaId id) {
		this.id = id;
	}

	public EstadoFenologico getEstadoFenologicoByFkFecGarantEstFenD() {
		return this.estadoFenologicoByFkFecGarantEstFenD;
	}

	public void setEstadoFenologicoByFkFecGarantEstFenD(EstadoFenologico estadoFenologicoByFkFecGarantEstFenD) {
		this.estadoFenologicoByFkFecGarantEstFenD = estadoFenologicoByFkFecGarantEstFenD;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public PracticaCultural getPracticaCultural() {
		return this.practicaCultural;
	}

	public void setPracticaCultural(PracticaCultural practicaCultural) {
		this.practicaCultural = practicaCultural;
	}

	public EstadoFenologico getEstadoFenologicoByFkFecGarantEstFenH() {
		return this.estadoFenologicoByFkFecGarantEstFenH;
	}

	public void setEstadoFenologicoByFkFecGarantEstFenH(EstadoFenologico estadoFenologicoByFkFecGarantEstFenH) {
		this.estadoFenologicoByFkFecGarantEstFenH = estadoFenologicoByFkFecGarantEstFenH;
	}

	public Variedad getVariedad() {
		return this.variedad;
	}

	public void setVariedad(Variedad variedad) {
		this.variedad = variedad;
	}

	public TipoCapital getTipoCapital() {
		return this.tipoCapital;
	}

	public void setTipoCapital(TipoCapital tipoCapital) {
		this.tipoCapital = tipoCapital;
	}

	public BigDecimal getCodconceptoppalmod() {
		return this.codconceptoppalmod;
	}

	public void setCodconceptoppalmod(BigDecimal codconceptoppalmod) {
		this.codconceptoppalmod = codconceptoppalmod;
	}

	public BigDecimal getCodriesgocubierto() {
		return this.codriesgocubierto;
	}

	public void setCodriesgocubierto(BigDecimal codriesgocubierto) {
		this.codriesgocubierto = codriesgocubierto;
	}

	public BigDecimal getCodprovincia() {
		return this.codprovincia;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodcomarca() {
		return this.codcomarca;
	}

	public void setCodcomarca(BigDecimal codcomarca) {
		this.codcomarca = codcomarca;
	}

	public BigDecimal getCodtermino() {
		return this.codtermino;
	}

	public void setCodtermino(BigDecimal codtermino) {
		this.codtermino = codtermino;
	}

	public Character getSubtermino() {
		return this.subtermino;
	}

	public void setSubtermino(Character subtermino) {
		this.subtermino = subtermino;
	}

	public Date getFgarantdesde() {
		return this.fgarantdesde;
	}

	public void setFgarantdesde(Date fgarantdesde) {
		this.fgarantdesde = fgarantdesde;
	}

	public BigDecimal getNummesesdesde() {
		return this.nummesesdesde;
	}

	public void setNummesesdesde(BigDecimal nummesesdesde) {
		this.nummesesdesde = nummesesdesde;
	}

	public BigDecimal getNumdiasdesde() {
		return this.numdiasdesde;
	}

	public void setNumdiasdesde(BigDecimal numdiasdesde) {
		this.numdiasdesde = numdiasdesde;
	}

	public Date getFgaranthasta() {
		return this.fgaranthasta;
	}

	public void setFgaranthasta(Date fgaranthasta) {
		this.fgaranthasta = fgaranthasta;
	}

	public BigDecimal getNummeseshasta() {
		return this.nummeseshasta;
	}

	public void setNummeseshasta(BigDecimal nummeseshasta) {
		this.nummeseshasta = nummeseshasta;
	}

	public BigDecimal getNumdiashasta() {
		return this.numdiashasta;
	}

	public void setNumdiashasta(BigDecimal numdiashasta) {
		this.numdiashasta = numdiashasta;
	}

}
