package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.Date;

import com.rsi.agp.dao.tables.cgen.TipoCapital;

public class FechaRecoleccion implements java.io.Serializable {

	private static final long serialVersionUID = 2248957146682790978L;

	private FechaRecoleccionId id;
	private Modulo modulo;
	private Variedad variedad;
	private TipoCapital tipoCapital;
	private BigDecimal codprovincia;
	private BigDecimal codcomarca;
	private BigDecimal codtermino;
	private Character subtermino;
	private Date frecoldesde;
	private Date frecolhasta;

	public FechaRecoleccion() {
	}

	public FechaRecoleccion(FechaRecoleccionId id, Modulo modulo, Variedad variedad, BigDecimal codprovincia,
			BigDecimal codcomarca, BigDecimal codtermino, Character subtermino) {
		this.id = id;
		this.modulo = modulo;
		this.variedad = variedad;
		this.codprovincia = codprovincia;
		this.codcomarca = codcomarca;
		this.codtermino = codtermino;
		this.subtermino = subtermino;
	}

	public FechaRecoleccion(FechaRecoleccionId id, Modulo modulo, Variedad variedad, TipoCapital tipoCapital,
			BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino,
			Date frecoldesde, Date frecolhasta) {
		this.id = id;
		this.modulo = modulo;
		this.variedad = variedad;
		this.tipoCapital = tipoCapital;
		this.codprovincia = codprovincia;
		this.codcomarca = codcomarca;
		this.codtermino = codtermino;
		this.subtermino = subtermino;
		this.frecoldesde = frecoldesde;
		this.frecolhasta = frecolhasta;
	}

	public FechaRecoleccionId getId() {
		return this.id;
	}

	public void setId(FechaRecoleccionId id) {
		this.id = id;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Variedad getVariedad() {
		return this.variedad;
	}

	public void setVariedad(Variedad variedad) {
		this.variedad = variedad;
	}

	public TipoCapital getTipoCapital() {
		return this.tipoCapital;
	}

	public void setTipoCapital(TipoCapital tipoCapital) {
		this.tipoCapital = tipoCapital;
	}

	public BigDecimal getCodprovincia() {
		return this.codprovincia;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodcomarca() {
		return this.codcomarca;
	}

	public void setCodcomarca(BigDecimal codcomarca) {
		this.codcomarca = codcomarca;
	}

	public BigDecimal getCodtermino() {
		return this.codtermino;
	}

	public void setCodtermino(BigDecimal codtermino) {
		this.codtermino = codtermino;
	}

	public Character getSubtermino() {
		return this.subtermino;
	}

	public void setSubtermino(Character subtermino) {
		this.subtermino = subtermino;
	}

	public Date getFrecoldesde() {
		return this.frecoldesde;
	}

	public void setFrecoldesde(Date frecoldesde) {
		this.frecoldesde = frecoldesde;
	}

	public Date getFrecolhasta() {
		return this.frecolhasta;
	}

	public void setFrecolhasta(Date frecolhasta) {
		this.frecolhasta = frecolhasta;
	}

}
