package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.Alternativa;
import com.rsi.agp.dao.tables.cgen.CaracteristicaExplotacion;
import com.rsi.agp.dao.tables.cgen.CertificadoInstalacion;
import com.rsi.agp.dao.tables.cgen.CicloCultivo;
import com.rsi.agp.dao.tables.cgen.DenominacionOrigen;
import com.rsi.agp.dao.tables.cgen.Destino;
import com.rsi.agp.dao.tables.cgen.GastoSalvamento;
import com.rsi.agp.dao.tables.cgen.HistorialAsegurado;
import com.rsi.agp.dao.tables.cgen.MaterialCubierta;
import com.rsi.agp.dao.tables.cgen.NivelRiesgo;
import com.rsi.agp.dao.tables.cgen.PracticaCultural;
import com.rsi.agp.dao.tables.cgen.ProteccionCultivo;
import com.rsi.agp.dao.tables.cgen.SistemaConduccion;
import com.rsi.agp.dao.tables.cgen.SistemaCultivo;
import com.rsi.agp.dao.tables.cgen.SistemaProduccion;
import com.rsi.agp.dao.tables.cgen.SistemaProteccion;
import com.rsi.agp.dao.tables.cgen.TipoCapital;
import com.rsi.agp.dao.tables.cgen.TipoInstalacion;
import com.rsi.agp.dao.tables.cgen.TipoPlantacion;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class GrupoTasasItem  implements java.io.Serializable {


     private GrupoTasasId id;
     private Modulo modulo;
     private CertificadoInstalacion certificadoInstalacion;
     private TipoInstalacion tipoInstalacion;
     private TipoPlantacion tipoPlantacion;
     private PracticaCultural practicaCultural;
     private Variedad variedad;
     private HistorialAsegurado historialAsegurado;
     private GastoSalvamento gastoSalvamento;
     private NivelRiesgo nivelRiesgo;
     private Destino destino;
     private CaracteristicaExplotacion caracteristicaExplotacion;
     private SistemaCultivo sistemaCultivo;
     private SistemaConduccion sistemaConduccion;
     private SistemaProteccion sistemaProteccion;
     private SistemaProduccion sistemaProduccion;
     private MaterialCubierta materialCubierta;
     private TipoCapital tipoCapital;
     private CicloCultivo cicloCultivo;
     private ProteccionCultivo proteccionCultivo;
     private DenominacionOrigen denominacionOrigen;
     private Alternativa alternativa;
     private BigDecimal edaddesdeestructura;
     private BigDecimal edadhastaestructura;
     private Date fechaRecoleccionDesde;
     private Date fechaRecoleccionHasta;
     private Set<GrupoTasaRiesgo> grupoTasaRiesgos = new HashSet<GrupoTasaRiesgo>(0);

    public GrupoTasasItem() {
    }
    
    public GrupoTasasItem(GrupoTasas grupoTasas) {
    	if (grupoTasas.getId()!=null)
    		this.id = grupoTasas.getId();
    	else	
    		this.id = new GrupoTasasId();
        /***********************************************************/
    	if(grupoTasas.getModulo()!= null)
    		this.modulo = grupoTasas.getModulo();
    	else
    		this.modulo= new Modulo();
        /***********************************************************/
    	if(grupoTasas.getCertificadoInstalacion()!= null)
    		this.certificadoInstalacion = grupoTasas.getCertificadoInstalacion();
    	else
    		this.certificadoInstalacion= new CertificadoInstalacion();
    	/***********************************************************/
    	if(grupoTasas.getTipoInstalacion()!= null)
    		this.tipoInstalacion = grupoTasas.getTipoInstalacion();
    	else
    		this.tipoInstalacion= new TipoInstalacion();
        /***********************************************************/
    	if(grupoTasas.getTipoPlantacion()!= null)
    		this.tipoPlantacion = grupoTasas.getTipoPlantacion();
    	else
    		this.tipoPlantacion = new TipoPlantacion();
    	/***********************************************************/
    	if(grupoTasas.getPracticaCultural()!= null)
    		this.practicaCultural = grupoTasas.getPracticaCultural();
    	else
    		this.practicaCultural = new PracticaCultural();
    	/***********************************************************/
    	if(grupoTasas.getVariedad()!= null)
    		this.variedad = grupoTasas.getVariedad();
    	else
    		this.variedad = new Variedad();
    	/***********************************************************/
    	if(grupoTasas.getHistorialAsegurado()!= null)
    		this.historialAsegurado = grupoTasas.getHistorialAsegurado();
    	else
    		this.historialAsegurado = new HistorialAsegurado();
    	/***********************************************************/
    	if(grupoTasas.getGastoSalvamento()!= null)
    		this.gastoSalvamento = grupoTasas.getGastoSalvamento();
    	else
    		this.gastoSalvamento = new GastoSalvamento();
    	/***********************************************************/
    	if(grupoTasas.getNivelRiesgo()!= null)
    		this.nivelRiesgo = grupoTasas.getNivelRiesgo();
    	else
    		this.nivelRiesgo = new NivelRiesgo();
    	/***********************************************************/
    	if(grupoTasas.getDestino()!= null)
    		this.destino = grupoTasas.getDestino();
    	else
    		this.destino = new Destino();
    	/***********************************************************/
    	if(grupoTasas.getCaracteristicaExplotacion()!= null)
    		this.caracteristicaExplotacion = grupoTasas.getCaracteristicaExplotacion();
    	else
    		this.caracteristicaExplotacion = new CaracteristicaExplotacion();
    	/***********************************************************/
    	if(grupoTasas.getSistemaCultivo()!= null)
    		this.sistemaCultivo = grupoTasas.getSistemaCultivo();
    	else
    		this.sistemaCultivo = new SistemaCultivo();
    	/***********************************************************/
    	if(grupoTasas.getSistemaConduccion()!= null)
    		this.sistemaConduccion = grupoTasas.getSistemaConduccion();
    	else
    		this.sistemaConduccion = new SistemaConduccion();
    	/***********************************************************/
    	if(grupoTasas.getSistemaProteccion()!= null)
    		this.sistemaProteccion = grupoTasas.getSistemaProteccion();
    	else
    		this.sistemaProteccion = new SistemaProteccion();
    	/***********************************************************/
    	if(grupoTasas.getSistemaProduccion()!= null)
    		this.sistemaProduccion = grupoTasas.getSistemaProduccion();
    	else
    		this.sistemaProduccion = new SistemaProduccion();
    	/***********************************************************/
    	if(grupoTasas.getMaterialCubierta()!= null)
    		this.materialCubierta = grupoTasas.getMaterialCubierta();
    	else
    		this.materialCubierta = new MaterialCubierta();
    	/***********************************************************/
    	if(grupoTasas.getTipoCapital()!= null)
    		this.tipoCapital = grupoTasas.getTipoCapital();
    	else
    		this.tipoCapital = new TipoCapital();
    	/***********************************************************/
    	if(grupoTasas.getCicloCultivo()!= null)
    		this.cicloCultivo = grupoTasas.getCicloCultivo();
    	else
    		this.cicloCultivo = new CicloCultivo();
    	/***********************************************************/
    	if(grupoTasas.getProteccionCultivo()!= null)
    		this.proteccionCultivo = grupoTasas.getProteccionCultivo();
    	else
    		this.proteccionCultivo = new ProteccionCultivo();
    	/***********************************************************/
    	if(grupoTasas.getDenominacionOrigen()!= null)
    		this.denominacionOrigen = grupoTasas.getDenominacionOrigen();
    	else
    		this.denominacionOrigen = new DenominacionOrigen();
    	/***********************************************************/
    	if(grupoTasas.getAlternativa()!= null)
    		this.alternativa = grupoTasas.getAlternativa();
    	else
    		this.alternativa = new Alternativa();
    	/***********************************************************/
    	this.edaddesdeestructura = grupoTasas.getEdaddesdeestructura();
        this.edadhastaestructura = grupoTasas.getEdadhastaestructura();
        this.fechaRecoleccionDesde = grupoTasas.getFechaRecoleccionDesde();
        this.fechaRecoleccionHasta = grupoTasas.getFechaRecoleccionHasta();

     }
   
    public GrupoTasasId getId() {
        return this.id;
    }
    
    public void setId(GrupoTasasId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public CertificadoInstalacion getCertificadoInstalacion() {
        return this.certificadoInstalacion;
    }
    
    public void setCertificadoInstalacion(CertificadoInstalacion certificadoInstalacion) {
        this.certificadoInstalacion = certificadoInstalacion;
    }
    public TipoInstalacion getTipoInstalacion() {
        return this.tipoInstalacion;
    }
    
    public void setTipoInstalacion(TipoInstalacion tipoInstalacion) {
        this.tipoInstalacion = tipoInstalacion;
    }
    public TipoPlantacion getTipoPlantacion() {
        return this.tipoPlantacion;
    }
    
    public void setTipoPlantacion(TipoPlantacion tipoPlantacion) {
        this.tipoPlantacion = tipoPlantacion;
    }
    public PracticaCultural getPracticaCultural() {
        return this.practicaCultural;
    }
    
    public void setPracticaCultural(PracticaCultural practicaCultural) {
        this.practicaCultural = practicaCultural;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }
    public HistorialAsegurado getHistorialAsegurado() {
        return this.historialAsegurado;
    }
    
    public void setHistorialAsegurado(HistorialAsegurado historialAsegurado) {
        this.historialAsegurado = historialAsegurado;
    }
    public GastoSalvamento getGastoSalvamento() {
        return this.gastoSalvamento;
    }
    
    public void setGastoSalvamento(GastoSalvamento gastoSalvamento) {
        this.gastoSalvamento = gastoSalvamento;
    }
    public NivelRiesgo getNivelRiesgo() {
        return this.nivelRiesgo;
    }
    
    public void setNivelRiesgo(NivelRiesgo nivelRiesgo) {
        this.nivelRiesgo = nivelRiesgo;
    }
    public Destino getDestino() {
        return this.destino;
    }
    
    public void setDestino(Destino destino) {
        this.destino = destino;
    }
    public CaracteristicaExplotacion getCaracteristicaExplotacion() {
        return this.caracteristicaExplotacion;
    }
    
    public void setCaracteristicaExplotacion(CaracteristicaExplotacion caracteristicaExplotacion) {
        this.caracteristicaExplotacion = caracteristicaExplotacion;
    }
    public SistemaCultivo getSistemaCultivo() {
        return this.sistemaCultivo;
    }
    
    public void setSistemaCultivo(SistemaCultivo sistemaCultivo) {
        this.sistemaCultivo = sistemaCultivo;
    }
    public SistemaConduccion getSistemaConduccion() {
        return this.sistemaConduccion;
    }
    
    public void setSistemaConduccion(SistemaConduccion sistemaConduccion) {
        this.sistemaConduccion = sistemaConduccion;
    }
    public SistemaProteccion getSistemaProteccion() {
        return this.sistemaProteccion;
    }
    
    public void setSistemaProteccion(SistemaProteccion sistemaProteccion) {
        this.sistemaProteccion = sistemaProteccion;
    }
    public SistemaProduccion getSistemaProduccion() {
        return this.sistemaProduccion;
    }
    
    public void setSistemaProduccion(SistemaProduccion sistemaProduccion) {
        this.sistemaProduccion = sistemaProduccion;
    }
    public MaterialCubierta getMaterialCubierta() {
        return this.materialCubierta;
    }
    
    public void setMaterialCubierta(MaterialCubierta materialCubierta) {
        this.materialCubierta = materialCubierta;
    }
    public TipoCapital getTipoCapital() {
        return this.tipoCapital;
    }
    
    public void setTipoCapital(TipoCapital tipoCapital) {
        this.tipoCapital = tipoCapital;
    }
    public CicloCultivo getCicloCultivo() {
        return this.cicloCultivo;
    }
    
    public void setCicloCultivo(CicloCultivo cicloCultivo) {
        this.cicloCultivo = cicloCultivo;
    }
    public ProteccionCultivo getProteccionCultivo() {
        return this.proteccionCultivo;
    }
    
    public void setProteccionCultivo(ProteccionCultivo proteccionCultivo) {
        this.proteccionCultivo = proteccionCultivo;
    }
    public DenominacionOrigen getDenominacionOrigen() {
        return this.denominacionOrigen;
    }
    
    public void setDenominacionOrigen(DenominacionOrigen denominacionOrigen) {
        this.denominacionOrigen = denominacionOrigen;
    }
    public Alternativa getAlternativa() {
        return this.alternativa;
    }
    
    public void setAlternativa(Alternativa alternativa) {
        this.alternativa = alternativa;
    }
    public BigDecimal getEdaddesdeestructura() {
        return this.edaddesdeestructura;
    }
    
    public void setEdaddesdeestructura(BigDecimal edaddesdeestructura) {
        this.edaddesdeestructura = edaddesdeestructura;
    }
    public BigDecimal getEdadhastaestructura() {
        return this.edadhastaestructura;
    }
    
    public void setEdadhastaestructura(BigDecimal edadhastaestructura) {
        this.edadhastaestructura = edadhastaestructura;
    }
    public Date getFechaRecoleccionDesde() {
        return this.fechaRecoleccionDesde;
    }
    
    public void setFechaRecoleccionDesde(Date fechaRecoleccionDesde) {
        this.fechaRecoleccionDesde = fechaRecoleccionDesde;
    }
    public Date getFechaRecoleccionHasta() {
        return this.fechaRecoleccionHasta;
    }
    
    public void setFechaRecoleccionHasta(Date fechaRecoleccionHasta) {
        this.fechaRecoleccionHasta = fechaRecoleccionHasta;
    }
    public Set<GrupoTasaRiesgo> getGrupoTasaRiesgos() {
        return this.grupoTasaRiesgos;
    }
    
    public void setGrupoTasaRiesgos(Set<GrupoTasaRiesgo> grupoTasaRiesgos) {
        this.grupoTasaRiesgos = grupoTasaRiesgos;
    }




}


