package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.CalculoIndemnizacion;
import com.rsi.agp.dao.tables.cgen.CapitalAseguradoElegible;
import com.rsi.agp.dao.tables.cgen.DanioCubierto;
import com.rsi.agp.dao.tables.cgen.Garantizado;
import com.rsi.agp.dao.tables.cgen.MinimoIndemnizableElegible;
import com.rsi.agp.dao.tables.cgen.PctFranquiciaElegible;
import com.rsi.agp.dao.tables.cgen.TipoFranquicia;
import java.math.BigDecimal;
import java.util.Date;

public class GrupoTasaRiesgo  implements java.io.Serializable {


     private GrupoTasaRiesgoId id;
     private GrupoTasas grupoTasas;
     private Garantizado garantizado;
     private PctFranquiciaElegible pctFranquiciaElegible;
     private MinimoIndemnizableElegible minimoIndemnizableElegible;
     private CalculoIndemnizacion calculoIndemnizacion;
     private DanioCubierto danioCubierto;
     private CapitalAseguradoElegible capitalAseguradoElegible;
     private TipoFranquicia tipoFranquicia;
     private RiesgoCubierto riesgoCubierto;
     private BigDecimal duracionmaxgarantdias;
     private BigDecimal diasiniciogarantias;
     private Character estfenfingarantias;
     private Character estfeniniciogarantias;
     private Date fecfingarantias;
     private Date feciniciogarantias;
     private BigDecimal duracionmaxgarantmeses;
     private BigDecimal mesesiniciogarantias;
     private Character riesgocubiertoeleg;
     private BigDecimal conceptoppalmod;

    public GrupoTasaRiesgo() {
    }

	
    public GrupoTasaRiesgo(GrupoTasaRiesgoId id, GrupoTasas grupoTasas, RiesgoCubierto riesgoCubierto, BigDecimal conceptoppalmod) {
        this.id = id;
        this.grupoTasas = grupoTasas;
        this.riesgoCubierto = riesgoCubierto;
        this.conceptoppalmod = conceptoppalmod;
    }
    public GrupoTasaRiesgo(GrupoTasaRiesgoId id, GrupoTasas grupoTasas, Garantizado garantizado, PctFranquiciaElegible pctFranquiciaElegible, MinimoIndemnizableElegible minimoIndemnizableElegible, CalculoIndemnizacion calculoIndemnizacion, DanioCubierto danioCubierto, CapitalAseguradoElegible capitalAseguradoElegible, TipoFranquicia tipoFranquicia, RiesgoCubierto riesgoCubierto, BigDecimal duracionmaxgarantdias, BigDecimal diasiniciogarantias, Character estfenfingarantias, Character estfeniniciogarantias, Date fecfingarantias, Date feciniciogarantias, BigDecimal duracionmaxgarantmeses, BigDecimal mesesiniciogarantias, Character riesgocubiertoeleg, BigDecimal conceptoppalmod) {
       this.id = id;       
       this.grupoTasas = grupoTasas;
       this.garantizado = garantizado;
       this.pctFranquiciaElegible = pctFranquiciaElegible;
       this.minimoIndemnizableElegible = minimoIndemnizableElegible;
       this.calculoIndemnizacion = calculoIndemnizacion;
       this.danioCubierto = danioCubierto;
       this.capitalAseguradoElegible = capitalAseguradoElegible;
       this.tipoFranquicia = tipoFranquicia;
       this.riesgoCubierto = riesgoCubierto;
       this.duracionmaxgarantdias = duracionmaxgarantdias;
       this.diasiniciogarantias = diasiniciogarantias;
       this.estfenfingarantias = estfenfingarantias;
       this.estfeniniciogarantias = estfeniniciogarantias;
       this.fecfingarantias = fecfingarantias;
       this.feciniciogarantias = feciniciogarantias;
       this.duracionmaxgarantmeses = duracionmaxgarantmeses;
       this.mesesiniciogarantias = mesesiniciogarantias;
       this.riesgocubiertoeleg = riesgocubiertoeleg;
       this.conceptoppalmod = conceptoppalmod;
    }
   
    public GrupoTasaRiesgoId getId() {
        return this.id;
    }
    
    public void setId(GrupoTasaRiesgoId id) {
        this.id = id;
    }
    public GrupoTasas getGrupoTasas() {
        return this.grupoTasas;
    }
    
    public void setGrupoTasas(GrupoTasas grupoTasas) {
        this.grupoTasas = grupoTasas;
    }
    public Garantizado getGarantizado() {
        return this.garantizado;
    }
    
    public void setGarantizado(Garantizado garantizado) {
        this.garantizado = garantizado;
    }
    public PctFranquiciaElegible getPctFranquiciaElegible() {
        return this.pctFranquiciaElegible;
    }
    
    public void setPctFranquiciaElegible(PctFranquiciaElegible pctFranquiciaElegible) {
        this.pctFranquiciaElegible = pctFranquiciaElegible;
    }
    public MinimoIndemnizableElegible getMinimoIndemnizableElegible() {
        return this.minimoIndemnizableElegible;
    }
    
    public void setMinimoIndemnizableElegible(MinimoIndemnizableElegible minimoIndemnizableElegible) {
        this.minimoIndemnizableElegible = minimoIndemnizableElegible;
    }
    public CalculoIndemnizacion getCalculoIndemnizacion() {
        return this.calculoIndemnizacion;
    }
    
    public void setCalculoIndemnizacion(CalculoIndemnizacion calculoIndemnizacion) {
        this.calculoIndemnizacion = calculoIndemnizacion;
    }
    public DanioCubierto getDanioCubierto() {
        return this.danioCubierto;
    }
    
    public void setDanioCubierto(DanioCubierto danioCubierto) {
        this.danioCubierto = danioCubierto;
    }
    public CapitalAseguradoElegible getCapitalAseguradoElegible() {
        return this.capitalAseguradoElegible;
    }
    
    public void setCapitalAseguradoElegible(CapitalAseguradoElegible capitalAseguradoElegible) {
        this.capitalAseguradoElegible = capitalAseguradoElegible;
    }
    public TipoFranquicia getTipoFranquicia() {
        return this.tipoFranquicia;
    }
    
    public void setTipoFranquicia(TipoFranquicia tipoFranquicia) {
        this.tipoFranquicia = tipoFranquicia;
    }
    public RiesgoCubierto getRiesgoCubierto() {
        return this.riesgoCubierto;
    }
    
    public void setRiesgoCubierto(RiesgoCubierto riesgoCubierto) {
        this.riesgoCubierto = riesgoCubierto;
    }
    public BigDecimal getDuracionmaxgarantdias() {
        return this.duracionmaxgarantdias;
    }
    
    public void setDuracionmaxgarantdias(BigDecimal duracionmaxgarantdias) {
        this.duracionmaxgarantdias = duracionmaxgarantdias;
    }
    public BigDecimal getDiasiniciogarantias() {
        return this.diasiniciogarantias;
    }
    
    public void setDiasiniciogarantias(BigDecimal diasiniciogarantias) {
        this.diasiniciogarantias = diasiniciogarantias;
    }
    public Character getEstfenfingarantias() {
        return this.estfenfingarantias;
    }
    
    public void setEstfenfingarantias(Character estfenfingarantias) {
        this.estfenfingarantias = estfenfingarantias;
    }
    public Character getEstfeniniciogarantias() {
        return this.estfeniniciogarantias;
    }
    
    public void setEstfeniniciogarantias(Character estfeniniciogarantias) {
        this.estfeniniciogarantias = estfeniniciogarantias;
    }
    public Date getFecfingarantias() {
        return this.fecfingarantias;
    }
    
    public void setFecfingarantias(Date fecfingarantias) {
        this.fecfingarantias = fecfingarantias;
    }
    public Date getFeciniciogarantias() {
        return this.feciniciogarantias;
    }
    
    public void setFeciniciogarantias(Date feciniciogarantias) {
        this.feciniciogarantias = feciniciogarantias;
    }
    public BigDecimal getDuracionmaxgarantmeses() {
        return this.duracionmaxgarantmeses;
    }
    
    public void setDuracionmaxgarantmeses(BigDecimal duracionmaxgarantmeses) {
        this.duracionmaxgarantmeses = duracionmaxgarantmeses;
    }
    public BigDecimal getMesesiniciogarantias() {
        return this.mesesiniciogarantias;
    }
    
    public void setMesesiniciogarantias(BigDecimal mesesiniciogarantias) {
        this.mesesiniciogarantias = mesesiniciogarantias;
    }
    public Character getRiesgocubiertoeleg() {
        return this.riesgocubiertoeleg;
    }
    
    public void setRiesgocubiertoeleg(Character riesgocubiertoeleg) {
        this.riesgocubiertoeleg = riesgocubiertoeleg;
    }
    public BigDecimal getConceptoppalmod() {
        return this.conceptoppalmod;
    }
    
    public void setConceptoppalmod(BigDecimal conceptoppalmod) {
        this.conceptoppalmod = conceptoppalmod;
    }




}


