package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems



public class MascaraRendimientoCaracteristicaEspecifica  implements java.io.Serializable {


     private MascaraRendimientoCaracteristicaEspecificaId id;
     private Modulo modulo;
     private Variedad variedad;

    public MascaraRendimientoCaracteristicaEspecifica() {
    }

    public MascaraRendimientoCaracteristicaEspecifica(MascaraRendimientoCaracteristicaEspecificaId id, Modulo modulo, Variedad variedad) {
       this.id = id;
       this.modulo = modulo;
       this.variedad = variedad;
    }
   
    public MascaraRendimientoCaracteristicaEspecificaId getId() {
        return this.id;
    }
    
    public void setId(MascaraRendimientoCaracteristicaEspecificaId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }




}


