package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems

public class MascaraFechaContrataAgricola implements java.io.Serializable {

	private static final long serialVersionUID = -6272550930443193295L;
	
	private MascaraFechaContrataAgricolaId id;
	private Modulo modulo;
	private Variedad variedad;

	public MascaraFechaContrataAgricola() {
	}

	public MascaraFechaContrataAgricola(MascaraFechaContrataAgricolaId id, Modulo modulo, Variedad variedad) {
		this.id = id;
		this.modulo = modulo;
		this.variedad = variedad;
	}

	public MascaraFechaContrataAgricolaId getId() {
		return this.id;
	}

	public void setId(MascaraFechaContrataAgricolaId id) {
		this.id = id;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Variedad getVariedad() {
		return this.variedad;
	}

	public void setVariedad(Variedad variedad) {
		this.variedad = variedad;
	}

}
