package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import java.math.BigDecimal;

public class MedidaId  implements java.io.Serializable {


     private java.lang.Long lineaseguroid;
     private String nifasegurado;

    public MedidaId() {
    }

    public MedidaId(java.lang.Long lineaseguroid, String nifasegurado) {
       this.lineaseguroid = lineaseguroid;
       this.nifasegurado = nifasegurado;
    }
   
    public java.lang.Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(java.lang.Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getNifasegurado() {
        return this.nifasegurado;
    }
    
    public void setNifasegurado(String nifasegurado) {
        this.nifasegurado = nifasegurado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MedidaId) ) return false;
		 MedidaId castOther = ( MedidaId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getNifasegurado()==castOther.getNifasegurado()) || ( this.getNifasegurado()!=null && castOther.getNifasegurado()!=null && this.getNifasegurado().equals(castOther.getNifasegurado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getNifasegurado() == null ? 0 : this.getNifasegurado().hashCode() );
         return result;
   }   


}


