package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import java.math.BigDecimal;

public class PctComisionEstratosPrimaId  implements java.io.Serializable {


     private BigDecimal id;
     private Long lineaseguroid;

    public PctComisionEstratosPrimaId() {
    }

    public PctComisionEstratosPrimaId(BigDecimal id, Long lineaseguroid) {
       this.id = id;
       this.lineaseguroid = lineaseguroid;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PctComisionEstratosPrimaId) ) return false;
		 PctComisionEstratosPrimaId castOther = ( PctComisionEstratosPrimaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         return result;
   }   


}


