package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import java.math.BigDecimal;

public class PctComisionEstratosPrima  implements java.io.Serializable {


     private PctComisionEstratosPrimaId id;
     private BigDecimal primabasedesde;
     private BigDecimal primabasehasta;
     private BigDecimal pctaplicar;

    public PctComisionEstratosPrima() {
    }

	
    public PctComisionEstratosPrima(PctComisionEstratosPrimaId id, BigDecimal primabasedesde, BigDecimal primabasehasta) {
        this.id = id;
        this.primabasedesde = primabasedesde;
        this.primabasehasta = primabasehasta;
    }
    public PctComisionEstratosPrima(PctComisionEstratosPrimaId id, BigDecimal primabasedesde, BigDecimal primabasehasta, BigDecimal pctaplicar) {
       this.id = id;
       this.primabasedesde = primabasedesde;
       this.primabasehasta = primabasehasta;
       this.pctaplicar = pctaplicar;
    }
   
    public PctComisionEstratosPrimaId getId() {
        return this.id;
    }
    
    public void setId(PctComisionEstratosPrimaId id) {
        this.id = id;
    }
    public BigDecimal getPrimabasedesde() {
        return this.primabasedesde;
    }
    
    public void setPrimabasedesde(BigDecimal primabasedesde) {
        this.primabasedesde = primabasedesde;
    }
    public BigDecimal getPrimabasehasta() {
        return this.primabasehasta;
    }
    
    public void setPrimabasehasta(BigDecimal primabasehasta) {
        this.primabasehasta = primabasehasta;
    }
    public BigDecimal getPctaplicar() {
        return this.pctaplicar;
    }
    
    public void setPctaplicar(BigDecimal pctaplicar) {
        this.pctaplicar = pctaplicar;
    }




}


