package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.poliza.Linea;

public class RelEspeciesSCEspeciesST  implements java.io.Serializable {


     private RelEspeciesSCEspeciesSTId id;
     private Modulo modulo;
     private Variedad variedad;
     private Linea linea;

    public RelEspeciesSCEspeciesST() {
    	super();
     	this.id 				= new RelEspeciesSCEspeciesSTId();
    	this.modulo 			= new Modulo();
    	this.variedad			= new Variedad();
    	this.linea				= new Linea();
    }

    public RelEspeciesSCEspeciesST(RelEspeciesSCEspeciesSTId id, Modulo modulo, Variedad variedad, Linea linea) {
       this.id = id;
       this.modulo = modulo;
       this.variedad = variedad;
       this.linea = linea;
    }
   
    public RelEspeciesSCEspeciesSTId getId() {
        return this.id;
    }
    
    public void setId(RelEspeciesSCEspeciesSTId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }




}


