package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import java.math.BigDecimal;

public class RelRiesgoCubiertoTarificableId  implements java.io.Serializable {


     private java.lang.Long lineaseguroid;
     private String codmodulo;
     private String codriesgotarificable;
     private BigDecimal codriesgocubierto;

    public RelRiesgoCubiertoTarificableId() {
    }

    public RelRiesgoCubiertoTarificableId(java.lang.Long lineaseguroid, String codmodulo, String codriesgotarificable, BigDecimal codriesgocubierto) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.codriesgotarificable = codriesgotarificable;
       this.codriesgocubierto = codriesgocubierto;
    }
   
    public java.lang.Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(java.lang.Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public String getCodriesgotarificable() {
        return this.codriesgotarificable;
    }
    
    public void setCodriesgotarificable(String codriesgotarificable) {
        this.codriesgotarificable = codriesgotarificable;
    }
    public BigDecimal getCodriesgocubierto() {
        return this.codriesgocubierto;
    }
    
    public void setCodriesgocubierto(BigDecimal codriesgocubierto) {
        this.codriesgocubierto = codriesgocubierto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelRiesgoCubiertoTarificableId) ) return false;
		 RelRiesgoCubiertoTarificableId castOther = ( RelRiesgoCubiertoTarificableId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getCodmodulo()==castOther.getCodmodulo()) || ( this.getCodmodulo()!=null && castOther.getCodmodulo()!=null && this.getCodmodulo().equals(castOther.getCodmodulo()) ) )
 && ( ( this.getCodriesgotarificable()!=null && castOther.getCodriesgotarificable()!=null && this.getCodriesgotarificable().equals(castOther.getCodriesgotarificable()) ) )
 && ( (this.getCodriesgocubierto()==castOther.getCodriesgocubierto()) || ( this.getCodriesgocubierto()!=null && castOther.getCodriesgocubierto()!=null && this.getCodriesgocubierto().equals(castOther.getCodriesgocubierto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode() );
         result = 37 * result + ( getCodriesgotarificable() == null ? 0 : this.getCodriesgotarificable().hashCode() );
         result = 37 * result + ( getCodriesgocubierto() == null ? 0 : this.getCodriesgocubierto().hashCode() );
         return result;
   }   


}


