package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.ConceptoPpalModulo;
import java.math.BigDecimal;

public class RendimientosRegistrosParcela  implements java.io.Serializable {


     private RendimientosRegistrosParcelaId id;
     private Modulo modulo;
     private ConceptoPpalModulo conceptoPpalModulo;
     private Variedad variedad;
     private RiesgoCubierto riesgoCubierto;
     private BigDecimal codprovsigpac;
     private BigDecimal codtermsigpac;
     private BigDecimal agrsigpac;
     private BigDecimal zonasigpac;
     private BigDecimal poligonosigpac;
     private BigDecimal parcelasigpac;
     private Character riesgoCubiertoElegido;
     private Character aplicRendimiento;
     private BigDecimal rendimientoPerm;

    public RendimientosRegistrosParcela() {
    	super();
    	this.id = new RendimientosRegistrosParcelaId();
    	this.modulo = new Modulo();
    	this.conceptoPpalModulo = new ConceptoPpalModulo();
    	this.variedad = new Variedad();
    	this.riesgoCubierto = new RiesgoCubierto();
    }

	
    public RendimientosRegistrosParcela(RendimientosRegistrosParcelaId id, Modulo modulo, Variedad variedad, RiesgoCubierto riesgoCubierto, BigDecimal codprovsigpac, BigDecimal codtermsigpac, BigDecimal agrsigpac, BigDecimal zonasigpac, BigDecimal poligonosigpac, BigDecimal parcelasigpac, Character aplicRendimiento, BigDecimal rendimientoPerm) {
        this.id = id;
        this.modulo = modulo;
        this.variedad = variedad;
        this.riesgoCubierto = riesgoCubierto;
        this.codprovsigpac = codprovsigpac;
        this.codtermsigpac = codtermsigpac;
        this.agrsigpac = agrsigpac;
        this.zonasigpac = zonasigpac;
        this.poligonosigpac = poligonosigpac;
        this.parcelasigpac = parcelasigpac;
        this.aplicRendimiento = aplicRendimiento;
        this.rendimientoPerm = rendimientoPerm;
    }
    public RendimientosRegistrosParcela(RendimientosRegistrosParcelaId id, Modulo modulo, ConceptoPpalModulo conceptoPpalModulo, Variedad variedad, RiesgoCubierto riesgoCubierto, BigDecimal codprovsigpac, BigDecimal codtermsigpac, BigDecimal agrsigpac, BigDecimal zonasigpac, BigDecimal poligonosigpac, BigDecimal parcelasigpac, Character riesgoCubiertoElegido, Character aplicRendimiento, BigDecimal rendimientoPerm) {
       this.id = id;
       this.modulo = modulo;
       this.conceptoPpalModulo = conceptoPpalModulo;
       this.variedad = variedad;
       this.riesgoCubierto = riesgoCubierto;
       this.codprovsigpac = codprovsigpac;
       this.codtermsigpac = codtermsigpac;
       this.agrsigpac = agrsigpac;
       this.zonasigpac = zonasigpac;
       this.poligonosigpac = poligonosigpac;
       this.parcelasigpac = parcelasigpac;
       this.riesgoCubiertoElegido = riesgoCubiertoElegido;
       this.aplicRendimiento = aplicRendimiento;
       this.rendimientoPerm = rendimientoPerm;
    }
   
    public RendimientosRegistrosParcelaId getId() {
        return this.id;
    }
    
    public void setId(RendimientosRegistrosParcelaId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public ConceptoPpalModulo getConceptoPpalModulo() {
        return this.conceptoPpalModulo;
    }
    
    public void setConceptoPpalModulo(ConceptoPpalModulo conceptoPpalModulo) {
        this.conceptoPpalModulo = conceptoPpalModulo;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }
    public RiesgoCubierto getRiesgoCubierto() {
        return this.riesgoCubierto;
    }
    
    public void setRiesgoCubierto(RiesgoCubierto riesgoCubierto) {
        this.riesgoCubierto = riesgoCubierto;
    }
    public BigDecimal getCodprovsigpac() {
        return this.codprovsigpac;
    }
    
    public void setCodprovsigpac(BigDecimal codprovsigpac) {
        this.codprovsigpac = codprovsigpac;
    }
    public BigDecimal getCodtermsigpac() {
        return this.codtermsigpac;
    }
    
    public void setCodtermsigpac(BigDecimal codtermsigpac) {
        this.codtermsigpac = codtermsigpac;
    }
    public BigDecimal getAgrsigpac() {
        return this.agrsigpac;
    }
    
    public void setAgrsigpac(BigDecimal agrsigpac) {
        this.agrsigpac = agrsigpac;
    }
    public BigDecimal getZonasigpac() {
        return this.zonasigpac;
    }
    
    public void setZonasigpac(BigDecimal zonasigpac) {
        this.zonasigpac = zonasigpac;
    }
    public BigDecimal getPoligonosigpac() {
        return this.poligonosigpac;
    }
    
    public void setPoligonosigpac(BigDecimal poligonosigpac) {
        this.poligonosigpac = poligonosigpac;
    }
    public BigDecimal getParcelasigpac() {
        return this.parcelasigpac;
    }
    
    public void setParcelasigpac(BigDecimal parcelasigpac) {
        this.parcelasigpac = parcelasigpac;
    }
    public Character getRiesgoCubiertoElegido() {
        return this.riesgoCubiertoElegido;
    }
    
    public void setRiesgoCubiertoElegido(Character riesgoCubiertoElegido) {
        this.riesgoCubiertoElegido = riesgoCubiertoElegido;
    }
    public Character getAplicRendimiento() {
        return this.aplicRendimiento;
    }
    
    public void setAplicRendimiento(Character aplicRendimiento) {
        this.aplicRendimiento = aplicRendimiento;
    }
    public BigDecimal getRendimientoPerm() {
        return this.rendimientoPerm;
    }
    
    public void setRendimientoPerm(BigDecimal rendimientoPerm) {
        this.rendimientoPerm = rendimientoPerm;
    }




}


