package com.rsi.agp.dao.tables.cpl;

import java.math.BigDecimal;
// Generated by T-Systems

public class SubvencionInforme {

	private String organismo;
	private String importe;
	private BigDecimal importe2;

    public SubvencionInforme() {
    }
	
	public SubvencionInforme(String organismo, String importe,BigDecimal importe2){
        this.organismo = organismo;
        this.importe = importe;
        this.importe2 = importe2;
    }

	public String getOrganismo() {
		return organismo;
	}

	public void setOrganismo(String organismo) {
		this.organismo = organismo;
	}

	public String getImporte() {
		return importe;
	}

	public void setImporte(String importe) {
		this.importe = importe;
	}
	
	public BigDecimal getImporte2() {
		return importe2;
	}

	public void setImporte2(BigDecimal importe2) {
		this.importe2 = importe2;
	}
	    
}


