package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.Garantizado;
import com.rsi.agp.dao.tables.cgen.Organismo;
import com.rsi.agp.dao.tables.cgen.TipoRendimiento;
import com.rsi.agp.dao.tables.cgen.TipoSubvencionCCAA;
import com.rsi.agp.dao.tables.org.DiccionarioDatos;
import com.rsi.agp.dao.tables.poliza.SubAseguradoCCAA;
import com.rsi.agp.dao.tables.poliza.SubvParcelaCCAA;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class SubvencionCCAA  implements java.io.Serializable {


     private SubvencionCCAAId id;
     private Garantizado garantizado;
     private Modulo modulo;
     private DiccionarioDatos diccionarioDatos;
     private Variedad variedad;
     private TipoSubvencionCCAA tipoSubvencionCCAA;
     private Organismo organismo;
     private TipoRendimiento tipoRendimiento;
     private BigDecimal codprovincia;
     private BigDecimal codcomarca;
     private BigDecimal codtermino;
     private Character subtermino;
     private BigDecimal tasacoste;
     private Character codbasecalculosubv;
     private BigDecimal datoasocbase;
     private BigDecimal pctsubvindividual;
     private BigDecimal pctsubvcolectivo;
     private BigDecimal valorconcepto;
     private Date fechaentradavigorhasta;
     private Date fechaDesde;
     private Date fechaHasta;
     private Set<SubvParcelaCCAA> subvParcelaCCAAs = new HashSet<SubvParcelaCCAA>(0);
     private Set<SubAseguradoCCAA> subAseguradoCCAAs = new HashSet<SubAseguradoCCAA>(0);

    public SubvencionCCAA() {
    }

	
    public SubvencionCCAA(SubvencionCCAAId id, Modulo modulo, Variedad variedad, TipoSubvencionCCAA tipoSubvencionCCAA, TipoRendimiento tipoRendimiento, Organismo organismo, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino) {
        this.id = id;
        this.modulo = modulo;
        this.variedad = variedad;
        this.tipoSubvencionCCAA = tipoSubvencionCCAA;
        this.tipoRendimiento = tipoRendimiento;
        this.organismo = organismo;
        this.codprovincia = codprovincia;
        this.codcomarca = codcomarca;
        this.codtermino = codtermino;
        this.subtermino = subtermino;
    }
    public SubvencionCCAA(SubvencionCCAAId id, Garantizado garantizado, Modulo modulo, DiccionarioDatos diccionarioDatos, Variedad variedad, TipoSubvencionCCAA tipoSubvencionCCAA, Organismo organismo, TipoRendimiento tipoRendimiento, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino, BigDecimal tasacoste, Character codbasecalculosubv, BigDecimal datoasocbase, BigDecimal pctsubvindividual, BigDecimal pctsubvcolectivo, BigDecimal valorconcepto, Date fechaentradavigorhasta, Date fechaDesde, Date fechaHasta, Set<SubvParcelaCCAA> subvParcelaCCAAs, Set<SubAseguradoCCAA> subAseguradoCCAAs) {
       this.id = id;
       this.garantizado = garantizado;
       this.modulo = modulo;
       this.diccionarioDatos = diccionarioDatos;
       this.variedad = variedad;
       this.tipoSubvencionCCAA = tipoSubvencionCCAA;
       this.organismo = organismo;
       this.tipoRendimiento = tipoRendimiento;
       this.codprovincia = codprovincia;
       this.codcomarca = codcomarca;
       this.codtermino = codtermino;
       this.subtermino = subtermino;
       this.tasacoste = tasacoste;
       this.codbasecalculosubv = codbasecalculosubv;
       this.datoasocbase = datoasocbase;
       this.pctsubvindividual = pctsubvindividual;
       this.pctsubvcolectivo = pctsubvcolectivo;
       this.valorconcepto = valorconcepto;
       this.fechaentradavigorhasta = fechaentradavigorhasta;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.subvParcelaCCAAs = subvParcelaCCAAs;
       this.subAseguradoCCAAs = subAseguradoCCAAs;
    }
   
    public SubvencionCCAAId getId() {
        return this.id;
    }
    
    public void setId(SubvencionCCAAId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Garantizado getGarantizado() {
        return this.garantizado;
    }
    
    public void setGarantizado(Garantizado garantizado) {
        this.garantizado = garantizado;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }
    public TipoSubvencionCCAA getTipoSubvencionCCAA() {
        return this.tipoSubvencionCCAA;
    }
    
    public void setTipoSubvencionCCAA(TipoSubvencionCCAA tipoSubvencionCCAA) {
        this.tipoSubvencionCCAA = tipoSubvencionCCAA;
    }
    public TipoRendimiento getTipoRendimiento() {
        return this.tipoRendimiento;
    }
    
    public void setTipoRendimiento(TipoRendimiento tipoRendimiento) {
        this.tipoRendimiento = tipoRendimiento;
    }
    public Organismo getOrganismo() {
        return this.organismo;
    }
    
    public void setOrganismo(Organismo organismo) {
        this.organismo = organismo;
    }
    public BigDecimal getCodprovincia() {
        return this.codprovincia;
    }
    
    public void setCodprovincia(BigDecimal codprovincia) {
        this.codprovincia = codprovincia;
    }
    public BigDecimal getCodcomarca() {
        return this.codcomarca;
    }
    
    public void setCodcomarca(BigDecimal codcomarca) {
        this.codcomarca = codcomarca;
    }
    public BigDecimal getCodtermino() {
        return this.codtermino;
    }
    
    public void setCodtermino(BigDecimal codtermino) {
        this.codtermino = codtermino;
    }
    public Character getSubtermino() {
        return this.subtermino;
    }
    
    public void setSubtermino(Character subtermino) {
        this.subtermino = subtermino;
    }
    public BigDecimal getTasacoste() {
        return this.tasacoste;
    }
    
    public void setTasacoste(BigDecimal tasacoste) {
        this.tasacoste = tasacoste;
    }
    public Character getCodbasecalculosubv() {
        return this.codbasecalculosubv;
    }
    
    public void setCodbasecalculosubv(Character codbasecalculosubv) {
        this.codbasecalculosubv = codbasecalculosubv;
    }
    public BigDecimal getDatoasocbase() {
        return this.datoasocbase;
    }
    
    public void setDatoasocbase(BigDecimal datoasocbase) {
        this.datoasocbase = datoasocbase;
    }
    public BigDecimal getPctsubvindividual() {
        return this.pctsubvindividual;
    }
    
    public void setPctsubvindividual(BigDecimal pctsubvindividual) {
        this.pctsubvindividual = pctsubvindividual;
    }
    public BigDecimal getPctsubvcolectivo() {
        return this.pctsubvcolectivo;
    }
    
    public void setPctsubvcolectivo(BigDecimal pctsubvcolectivo) {
        this.pctsubvcolectivo = pctsubvcolectivo;
    }
    public BigDecimal getValorconcepto() {
        return this.valorconcepto;
    }
    
    public void setValorconcepto(BigDecimal valorconcepto) {
        this.valorconcepto = valorconcepto;
    }
    public Date getFechaentradavigorhasta() {
        return this.fechaentradavigorhasta;
    }
    
    public void setFechaentradavigorhasta(Date fechaentradavigorhasta) {
        this.fechaentradavigorhasta = fechaentradavigorhasta;
    }
    public Set<SubvParcelaCCAA> getSubvParcelaCCAAs() {
        return this.subvParcelaCCAAs;
    }
    
    public void setSubvParcelaCCAAs(Set<SubvParcelaCCAA> subvParcelaCCAAs) {
        this.subvParcelaCCAAs = subvParcelaCCAAs;
    }
    public Set<SubAseguradoCCAA> getSubAseguradoCCAAs() {
        return this.subAseguradoCCAAs;
    }
    
    public void setSubAseguradoCCAAs(Set<SubAseguradoCCAA> subAseguradoCCAAs) {
        this.subAseguradoCCAAs = subAseguradoCCAAs;
    }

	public Date getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	public Date getFechaHasta() {
		return fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

}


