package com.rsi.agp.dao.tables.cpl;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.Garantizado;
import com.rsi.agp.dao.tables.cgen.TipoRendimiento;
import com.rsi.agp.dao.tables.cgen.TipoSubvencionEnesa;
import com.rsi.agp.dao.tables.org.DiccionarioDatos;
import com.rsi.agp.dao.tables.poliza.SubAseguradoENESA;
import com.rsi.agp.dao.tables.poliza.SubvParcelaENESA;
import com.rsi.agp.dao.tables.poliza.SubvencionSocio;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class SubvencionEnesa  implements java.io.Serializable {


     private SubvencionEnesaId id;
     private Garantizado garantizado;
     private Modulo modulo;
     private DiccionarioDatos diccionarioDatos;
     private Variedad variedad;
     private TipoRendimiento tipoRendimiento;
     private TipoSubvencionEnesa tipoSubvencionEnesa;
     private BigDecimal codprovincia;
     private BigDecimal codcomarca;
     private BigDecimal codtermino;
     private Character subtermino;
     private BigDecimal ratio;
     private Character codbasecalculosubv;
     private BigDecimal datoasocbase;
     private BigDecimal pctsubvindividual;
     private BigDecimal pctsubvcolectivo;
     private BigDecimal valorconcepto;
     private Date fechaentradavigorhasta;
     private Date fechaDesde;
     private Date fechaHasta;
     
     
	private Set<SubAseguradoENESA> subAseguradoENESAs = new HashSet<SubAseguradoENESA>(0);
     private Set<SubvencionSocio> subvencionSocios = new HashSet<SubvencionSocio>(0);
     private Set<SubvParcelaENESA> subvParcelaENESAs = new HashSet<SubvParcelaENESA>(0);

    public SubvencionEnesa() {
    }

	
    public SubvencionEnesa(SubvencionEnesaId id, Modulo modulo, Variedad variedad, TipoRendimiento tipoRendimiento, TipoSubvencionEnesa tipoSubvencionEnesa, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino) {
        this.id = id;
        this.modulo = modulo;
        this.variedad = variedad;
        this.tipoRendimiento = tipoRendimiento;
        this.tipoSubvencionEnesa = tipoSubvencionEnesa;
        this.codprovincia = codprovincia;
        this.codcomarca = codcomarca;
        this.codtermino = codtermino;
        this.subtermino = subtermino;
    }
    public SubvencionEnesa(SubvencionEnesaId id, Garantizado garantizado, Modulo modulo, DiccionarioDatos diccionarioDatos, Variedad variedad, TipoRendimiento tipoRendimiento, TipoSubvencionEnesa tipoSubvencionEnesa, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino, BigDecimal ratio, Character codbasecalculosubv, BigDecimal datoasocbase, BigDecimal pctsubvindividual, BigDecimal pctsubvcolectivo, BigDecimal valorconcepto, Date fechaentradavigorhasta, Date fechaDesde, Date fechaHasta, Set<SubAseguradoENESA> subAseguradoENESAs, Set<SubvencionSocio> subvencionSocios, Set<SubvParcelaENESA> subvParcelaENESAs) {
       this.id = id;
       this.garantizado = garantizado;
       this.modulo = modulo;
       this.diccionarioDatos = diccionarioDatos;
       this.variedad = variedad;
       this.tipoRendimiento = tipoRendimiento;
       this.tipoSubvencionEnesa = tipoSubvencionEnesa;
       this.codprovincia = codprovincia;
       this.codcomarca = codcomarca;
       this.codtermino = codtermino;
       this.subtermino = subtermino;
       this.ratio = ratio;
       this.codbasecalculosubv = codbasecalculosubv;
       this.datoasocbase = datoasocbase;
       this.pctsubvindividual = pctsubvindividual;
       this.pctsubvcolectivo = pctsubvcolectivo;
       this.valorconcepto = valorconcepto;
       this.fechaentradavigorhasta = fechaentradavigorhasta;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.subAseguradoENESAs = subAseguradoENESAs;
       this.subvencionSocios = subvencionSocios;
       this.subvParcelaENESAs = subvParcelaENESAs;
    }
   
    public SubvencionEnesaId getId() {
        return this.id;
    }
    
    public void setId(SubvencionEnesaId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Garantizado getGarantizado() {
        return this.garantizado;
    }
    
    public void setGarantizado(Garantizado garantizado) {
        this.garantizado = garantizado;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public Variedad getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(Variedad variedad) {
        this.variedad = variedad;
    }
    public TipoRendimiento getTipoRendimiento() {
        return this.tipoRendimiento;
    }
    
    public void setTipoRendimiento(TipoRendimiento tipoRendimiento) {
        this.tipoRendimiento = tipoRendimiento;
    }
    public TipoSubvencionEnesa getTipoSubvencionEnesa() {
        return this.tipoSubvencionEnesa;
    }
    
    public void setTipoSubvencionEnesa(TipoSubvencionEnesa tipoSubvencionEnesa) {
        this.tipoSubvencionEnesa = tipoSubvencionEnesa;
    }
    public BigDecimal getCodprovincia() {
        return this.codprovincia;
    }
    
    public void setCodprovincia(BigDecimal codprovincia) {
        this.codprovincia = codprovincia;
    }
    public BigDecimal getCodcomarca() {
        return this.codcomarca;
    }
    
    public void setCodcomarca(BigDecimal codcomarca) {
        this.codcomarca = codcomarca;
    }
    public BigDecimal getCodtermino() {
        return this.codtermino;
    }
    
    public void setCodtermino(BigDecimal codtermino) {
        this.codtermino = codtermino;
    }
    public Character getSubtermino() {
        return this.subtermino;
    }
    
    public void setSubtermino(Character subtermino) {
        this.subtermino = subtermino;
    }
    public BigDecimal getRatio() {
        return this.ratio;
    }
    
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }
    public Character getCodbasecalculosubv() {
        return this.codbasecalculosubv;
    }
    
    public void setCodbasecalculosubv(Character codbasecalculosubv) {
        this.codbasecalculosubv = codbasecalculosubv;
    }
    public BigDecimal getDatoasocbase() {
        return this.datoasocbase;
    }
    
    public void setDatoasocbase(BigDecimal datoasocbase) {
        this.datoasocbase = datoasocbase;
    }
    public BigDecimal getPctsubvindividual() {
        return this.pctsubvindividual;
    }
    
    public void setPctsubvindividual(BigDecimal pctsubvindividual) {
        this.pctsubvindividual = pctsubvindividual;
    }
    public BigDecimal getPctsubvcolectivo() {
        return this.pctsubvcolectivo;
    }
    
    public void setPctsubvcolectivo(BigDecimal pctsubvcolectivo) {
        this.pctsubvcolectivo = pctsubvcolectivo;
    }
    public BigDecimal getValorconcepto() {
        return this.valorconcepto;
    }
    
    public void setValorconcepto(BigDecimal valorconcepto) {
        this.valorconcepto = valorconcepto;
    }
    public Date getFechaentradavigorhasta() {
        return this.fechaentradavigorhasta;
    }
    
    public void setFechaentradavigorhasta(Date fechaentradavigorhasta) {
        this.fechaentradavigorhasta = fechaentradavigorhasta;
    }
    public Set<SubAseguradoENESA> getSubAseguradoENESAs() {
        return this.subAseguradoENESAs;
    }
    
    public void setSubAseguradoENESAs(Set<SubAseguradoENESA> subAseguradoENESAs) {
        this.subAseguradoENESAs = subAseguradoENESAs;
    }
    public Set<SubvencionSocio> getSubvencionSocios() {
        return this.subvencionSocios;
    }
    
    public void setSubvencionSocios(Set<SubvencionSocio> subvencionSocios) {
        this.subvencionSocios = subvencionSocios;
    }
    public Set<SubvParcelaENESA> getSubvParcelaENESAs() {
        return this.subvParcelaENESAs;
    }
    
    public void setSubvParcelaENESAs(Set<SubvParcelaENESA> subvParcelaENESAs) {
        this.subvParcelaENESAs = subvParcelaENESAs;
    }
    
    public Date getFechaDesde() {
		return fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	public Date getFechaHasta() {
		return fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}


}


