package com.rsi.agp.dao.tables.pac;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class PacAsegurados  implements java.io.Serializable {


     private Long id;
     private PacCargas pacCargas;
     private String nifAsegurado;
     private Character discriminante;
     private Set<PacCapAseg> pacCapAsegs = new HashSet<PacCapAseg>(0);
     private Set<PacParcelas> pacParcelases = new HashSet<PacParcelas>(0);
     private Set<PacDatosVariables> pacDatosVariableses = new HashSet<PacDatosVariables>(0);

    public PacAsegurados() {
    }

	
    public PacAsegurados(Long id, PacCargas pacCargas, String nifAsegurado) {
        this.id = id;
        this.pacCargas = pacCargas;
        this.nifAsegurado = nifAsegurado;
    }
    public PacAsegurados(Long id, PacCargas pacCargas, String nifAsegurado, Character discriminante, Set<PacCapAseg> pacCapAsegs, Set<PacParcelas> pacParcelases, Set<PacDatosVariables> pacDatosVariableses) {
       this.id = id;
       this.pacCargas = pacCargas;
       this.nifAsegurado = nifAsegurado;
       this.discriminante = discriminante;
       this.pacCapAsegs = pacCapAsegs;
       this.pacParcelases = pacParcelases;
       this.pacDatosVariableses = pacDatosVariableses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public PacCargas getPacCargas() {
        return this.pacCargas;
    }
    
    public void setPacCargas(PacCargas pacCargas) {
        this.pacCargas = pacCargas;
    }
    public String getNifAsegurado() {
        return this.nifAsegurado;
    }
    
    public void setNifAsegurado(String nifAsegurado) {
        this.nifAsegurado = nifAsegurado;
    }
    public Character getDiscriminante() {
        return this.discriminante;
    }
    
    public void setDiscriminante(Character discriminante) {
        this.discriminante = discriminante;
    }
    public Set<PacCapAseg> getPacCapAsegs() {
        return this.pacCapAsegs;
    }
    
    public void setPacCapAsegs(Set<PacCapAseg> pacCapAsegs) {
        this.pacCapAsegs = pacCapAsegs;
    }
    public Set<PacParcelas> getPacParcelases() {
        return this.pacParcelases;
    }
    
    public void setPacParcelases(Set<PacParcelas> pacParcelases) {
        this.pacParcelases = pacParcelases;
    }
    public Set<PacDatosVariables> getPacDatosVariableses() {
        return this.pacDatosVariableses;
    }
    
    public void setPacDatosVariableses(Set<PacDatosVariables> pacDatosVariableses) {
        this.pacDatosVariableses = pacDatosVariableses;
    }




}


