package com.rsi.agp.dao.tables.pac;
// Generated by T-Systems



public class PacCapAseg  implements java.io.Serializable {


     private PacCapAsegId id;
     private PacParcelas pacParcelas;
     private PacAsegurados pacAsegurados;
     private Integer superficie;
     private Long produccion;

    public PacCapAseg() {
    }

	
    public PacCapAseg(PacCapAsegId id, PacParcelas pacParcelas, PacAsegurados pacAsegurados) {
        this.id = id;
        this.pacParcelas = pacParcelas;
        this.pacAsegurados = pacAsegurados;
    }
    public PacCapAseg(PacCapAsegId id, PacParcelas pacParcelas, PacAsegurados pacAsegurados, Integer superficie, Long produccion) {
       this.id = id;
       this.pacParcelas = pacParcelas;
       this.pacAsegurados = pacAsegurados;
       this.superficie = superficie;
       this.produccion = produccion;
    }
   
    public PacCapAsegId getId() {
        return this.id;
    }
    
    public void setId(PacCapAsegId id) {
        this.id = id;
    }
    public PacParcelas getPacParcelas() {
        return this.pacParcelas;
    }
    
    public void setPacParcelas(PacParcelas pacParcelas) {
        this.pacParcelas = pacParcelas;
    }
    public PacAsegurados getPacAsegurados() {
        return this.pacAsegurados;
    }
    
    public void setPacAsegurados(PacAsegurados pacAsegurados) {
        this.pacAsegurados = pacAsegurados;
    }
    public Integer getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Integer superficie) {
        this.superficie = superficie;
    }
    public Long getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Long produccion) {
        this.produccion = produccion;
    }




}


