package com.rsi.agp.dao.tables.pac;
// Generated by T-Systems



public class PacDatosVariables  implements java.io.Serializable {


     private PacDatosVariablesId id;
     private PacParcelas pacParcelas;
     private PacAsegurados pacAsegurados;
     private String valor;

    public PacDatosVariables() {
    }

	
    public PacDatosVariables(PacDatosVariablesId id, PacParcelas pacParcelas, PacAsegurados pacAsegurados) {
        this.id = id;
        this.pacParcelas = pacParcelas;
        this.pacAsegurados = pacAsegurados;
    }
    public PacDatosVariables(PacDatosVariablesId id, PacParcelas pacParcelas, PacAsegurados pacAsegurados, String valor) {
       this.id = id;
       this.pacParcelas = pacParcelas;
       this.pacAsegurados = pacAsegurados;
       this.valor = valor;
    }
   
    public PacDatosVariablesId getId() {
        return this.id;
    }
    
    public void setId(PacDatosVariablesId id) {
        this.id = id;
    }
    public PacParcelas getPacParcelas() {
        return this.pacParcelas;
    }
    
    public void setPacParcelas(PacParcelas pacParcelas) {
        this.pacParcelas = pacParcelas;
    }
    public PacAsegurados getPacAsegurados() {
        return this.pacAsegurados;
    }
    
    public void setPacAsegurados(PacAsegurados pacAsegurados) {
        this.pacAsegurados = pacAsegurados;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


