package com.rsi.agp.dao.tables.pagos;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class EstadosPago  implements java.io.Serializable {


     private BigDecimal id;
     private String descripcion;
     private Set<EstadosPoliza> estadosPolizas = new HashSet<EstadosPoliza>(0);
     private Set<HistoricoPoliza> historicoPolizas = new HashSet<HistoricoPoliza>(0);

    public EstadosPago() {
    }

	
    public EstadosPago(BigDecimal id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public EstadosPago(BigDecimal id, String descripcion, Set<EstadosPoliza> estadosPolizas, Set<HistoricoPoliza> historicoPolizas) {
       this.id = id;
       this.descripcion = descripcion;
       this.estadosPolizas = estadosPolizas;
       this.historicoPolizas = historicoPolizas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<EstadosPoliza> getEstadosPolizas() {
        return this.estadosPolizas;
    }
    
    public void setEstadosPolizas(Set<EstadosPoliza> estadosPolizas) {
        this.estadosPolizas = estadosPolizas;
    }
    public Set<HistoricoPoliza> getHistoricoPolizas() {
        return this.historicoPolizas;
    }
    
    public void setHistoricoPolizas(Set<HistoricoPoliza> historicoPolizas) {
        this.historicoPolizas = historicoPolizas;
    }




}


