package com.rsi.agp.dao.tables.pagos;
// Generated by T-Systems


import com.rsi.agp.dao.tables.poliza.Poliza;
import java.math.BigDecimal;
import java.util.Date;

public class HistoricoPoliza  implements java.io.Serializable {


     private BigDecimal id;
     private EstadosPago estadosPago;
     private Poliza poliza;
     private EstadosPoliza estadosPoliza;
     private String codusuario;
     private Date fecha;

    public HistoricoPoliza() {
    }

	
    public HistoricoPoliza(BigDecimal id, EstadosPago estadosPago, EstadosPoliza estadosPoliza, Date fecha) {
        this.id = id;
        this.estadosPago = estadosPago;
        this.estadosPoliza = estadosPoliza;
        this.fecha = fecha;
    }
    public HistoricoPoliza(BigDecimal id, EstadosPago estadosPago, Poliza poliza, EstadosPoliza estadosPoliza, String codusuario, Date fecha) {
       this.id = id;
       this.estadosPago = estadosPago;
       this.poliza = poliza;
       this.estadosPoliza = estadosPoliza;
       this.codusuario = codusuario;
       this.fecha = fecha;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public EstadosPago getEstadosPago() {
        return this.estadosPago;
    }
    
    public void setEstadosPago(EstadosPago estadosPago) {
        this.estadosPago = estadosPago;
    }
    public Poliza getPoliza() {
        return this.poliza;
    }
    
    public void setPoliza(Poliza poliza) {
        this.poliza = poliza;
    }
    public EstadosPoliza getEstadosPoliza() {
        return this.estadosPoliza;
    }
    
    public void setEstadosPoliza(EstadosPoliza estadosPoliza) {
        this.estadosPoliza = estadosPoliza;
    }
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


