package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.TipoCapital;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class AseguradoAutorizadoGanado  implements java.io.Serializable {


     private AseguradoAutorizadoGanadoId id;
     private Modulo modulo;
     private RegimenManejo regimenManejo;
     private TiposAnimalGanado tiposAnimalGanado;
     private TipoCapital tipoCapital;
     private GruposRazas gruposRazas;
     private Linea linea;
     private Especie especie;
     private Long codConceptoPpal;
     private Long codRiesgoCbto;
     private Long codGarantizado;
     private Long codAdaptExplot;
     private Long numAnimalesAuto;

     // GDLD-79222 
     private String nifAsegurado;
     private String codigoRega;
     
    public AseguradoAutorizadoGanado() {
    }

	
    public AseguradoAutorizadoGanado(AseguradoAutorizadoGanadoId id, String nifAsegurado, String codigoRega, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, TipoCapital tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie, Long numAnimalesAuto) {
        this.id = id;
        this.nifAsegurado = nifAsegurado;
        this.codigoRega = codigoRega;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tiposAnimalGanado = tiposAnimalGanado;
        this.tipoCapital = tipoCapital;
        this.gruposRazas = gruposRazas;
        this.linea = linea;
        this.especie = especie;
        this.numAnimalesAuto = numAnimalesAuto;
    }
    public AseguradoAutorizadoGanado(AseguradoAutorizadoGanadoId id, String nifAsegurado, String codigoRega, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, TipoCapital tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie, Long codConceptoPpal, Long codRiesgoCbto, Long codGarantizado, Long codAdaptExplot, Long numAnimalesAuto) {
       this.id = id;
       this.nifAsegurado = nifAsegurado;
       this.codigoRega = codigoRega;
       this.modulo = modulo;
       this.regimenManejo = regimenManejo;
       this.tiposAnimalGanado = tiposAnimalGanado;
       this.tipoCapital = tipoCapital;
       this.gruposRazas = gruposRazas;
       this.linea = linea;
       this.especie = especie;
       this.codConceptoPpal = codConceptoPpal;
       this.codRiesgoCbto = codRiesgoCbto;
       this.codGarantizado = codGarantizado;
       this.codAdaptExplot = codAdaptExplot;
       this.numAnimalesAuto = numAnimalesAuto;
    }
   
    public AseguradoAutorizadoGanadoId getId() {
        return this.id;
    }
    
    public void setId(AseguradoAutorizadoGanadoId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TiposAnimalGanado getTiposAnimalGanado() {
        return this.tiposAnimalGanado;
    }
    
    public void setTiposAnimalGanado(TiposAnimalGanado tiposAnimalGanado) {
        this.tiposAnimalGanado = tiposAnimalGanado;
    }
    public TipoCapital getTipoCapital() {
        return this.tipoCapital;
    }
    
    public void setTipoCapital(TipoCapital tipoCapital) {
        this.tipoCapital = tipoCapital;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public Long getCodConceptoPpal() {
        return this.codConceptoPpal;
    }
    
    public void setCodConceptoPpal(Long codConceptoPpal) {
        this.codConceptoPpal = codConceptoPpal;
    }
    public Long getCodRiesgoCbto() {
        return this.codRiesgoCbto;
    }
    
    public void setCodRiesgoCbto(Long codRiesgoCbto) {
        this.codRiesgoCbto = codRiesgoCbto;
    }
    public Long getCodGarantizado() {
        return this.codGarantizado;
    }
    
    public void setCodGarantizado(Long codGarantizado) {
        this.codGarantizado = codGarantizado;
    }
    public Long getCodAdaptExplot() {
        return this.codAdaptExplot;
    }
    
    public void setCodAdaptExplot(Long codAdaptExplot) {
        this.codAdaptExplot = codAdaptExplot;
    }
    public Long getNumAnimalesAuto() {
        return this.numAnimalesAuto;
    }
    
    public void setNumAnimalesAuto(Long numAnimalesAuto) {
        this.numAnimalesAuto = numAnimalesAuto;
    }


	public String getNifAsegurado() {
		return nifAsegurado;
	}


	public void setNifAsegurado(String nifAsegurado) {
		this.nifAsegurado = nifAsegurado;
	}


	public String getCodigoRega() {
		return codigoRega;
	}


	public void setCodigoRega(String codigoRega) {
		this.codigoRega = codigoRega;
	}




}


