package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import java.util.Date;

import com.rsi.agp.dao.tables.cgen.TipoCapital;
import com.rsi.agp.dao.tables.commons.Termino;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class FechaContratacion  implements java.io.Serializable {


     private FechaContratacionId id;
     private Modulo modulo;
     private RegimenManejo regimenManejo;
     private TiposAnimalGanado tiposAnimalGanado;
     private Termino termino;
     private TipoCapital tipoCapital;
     private GruposRazas gruposRazas;
     private Linea linea;
     private Especie especie;
     private Date fecContratIni;
     private Date fecContratFin;
     private Date fecUltimoDiaPago;
     private Long codRiesgoCbtoEleCpm;
     private Long codRiesgoCbtoEleRc;
     private Character riesgoCbtoEleValor;
     private Long codPeriodoGarantiasCpm;
     private Long codPeriodoGarantiasRc;
     private Long valorPeriodoGarantias;

    public FechaContratacion() {
    }

	
    public FechaContratacion(FechaContratacionId id, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, Termino termino, TipoCapital tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie) {
        this.id = id;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tiposAnimalGanado = tiposAnimalGanado;
        this.termino = termino;
        this.tipoCapital = tipoCapital;
        this.gruposRazas = gruposRazas;
        this.linea = linea;
        this.especie = especie;
    }
    public FechaContratacion(FechaContratacionId id, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, Termino termino, TipoCapital tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie, Date fecContratIni, Date fecContratFin, Date fecUltimoDiaPago, Long codRiesgoCbtoEleCpm, Long codRiesgoCbtoEleRc, Character riesgoCbtoEleValor, Long codPeriodoGarantiasCpm, Long codPeriodoGarantiasRc, Long valorPeriodoGarantias) {
       this.id = id;
       this.modulo = modulo;
       this.regimenManejo = regimenManejo;
       this.tiposAnimalGanado = tiposAnimalGanado;
       this.termino = termino;
       this.tipoCapital = tipoCapital;
       this.gruposRazas = gruposRazas;
       this.linea = linea;
       this.especie = especie;
       this.fecContratIni = fecContratIni;
       this.fecContratFin = fecContratFin;
       this.fecUltimoDiaPago = fecUltimoDiaPago;
       this.codRiesgoCbtoEleCpm = codRiesgoCbtoEleCpm;
       this.codRiesgoCbtoEleRc = codRiesgoCbtoEleRc;
       this.riesgoCbtoEleValor = riesgoCbtoEleValor;
       this.codPeriodoGarantiasCpm = codPeriodoGarantiasCpm;
       this.codPeriodoGarantiasRc = codPeriodoGarantiasRc;
       this.valorPeriodoGarantias = valorPeriodoGarantias;
    }
   
    public FechaContratacionId getId() {
        return this.id;
    }
    
    public void setId(FechaContratacionId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TiposAnimalGanado getTiposAnimalGanado() {
        return this.tiposAnimalGanado;
    }
    
    public void setTiposAnimalGanado(TiposAnimalGanado tiposAnimalGanado) {
        this.tiposAnimalGanado = tiposAnimalGanado;
    }
    public Termino getTermino() {
        return this.termino;
    }
    
    public void setTermino(Termino termino) {
        this.termino = termino;
    }
    public TipoCapital getTipoCapital() {
        return this.tipoCapital;
    }
    
    public void setTipoCapital(TipoCapital tipoCapital) {
        this.tipoCapital = tipoCapital;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public Date getFecContratIni() {
        return this.fecContratIni;
    }
    
    public void setFecContratIni(Date fecContratIni) {
        this.fecContratIni = fecContratIni;
    }
    public Date getFecContratFin() {
        return this.fecContratFin;
    }
    
    public void setFecContratFin(Date fecContratFin) {
        this.fecContratFin = fecContratFin;
    }
    public Date getFecUltimoDiaPago() {
        return this.fecUltimoDiaPago;
    }
    
    public void setFecUltimoDiaPago(Date fecUltimoDiaPago) {
        this.fecUltimoDiaPago = fecUltimoDiaPago;
    }
    public Long getCodRiesgoCbtoEleCpm() {
        return this.codRiesgoCbtoEleCpm;
    }
    
    public void setCodRiesgoCbtoEleCpm(Long codRiesgoCbtoEleCpm) {
        this.codRiesgoCbtoEleCpm = codRiesgoCbtoEleCpm;
    }
    public Long getCodRiesgoCbtoEleRc() {
        return this.codRiesgoCbtoEleRc;
    }
    
    public void setCodRiesgoCbtoEleRc(Long codRiesgoCbtoEleRc) {
        this.codRiesgoCbtoEleRc = codRiesgoCbtoEleRc;
    }
    public Character getRiesgoCbtoEleValor() {
        return this.riesgoCbtoEleValor;
    }
    
    public void setRiesgoCbtoEleValor(Character riesgoCbtoEleValor) {
        this.riesgoCbtoEleValor = riesgoCbtoEleValor;
    }
    public Long getCodPeriodoGarantiasCpm() {
        return this.codPeriodoGarantiasCpm;
    }
    
    public void setCodPeriodoGarantiasCpm(Long codPeriodoGarantiasCpm) {
        this.codPeriodoGarantiasCpm = codPeriodoGarantiasCpm;
    }
    public Long getCodPeriodoGarantiasRc() {
        return this.codPeriodoGarantiasRc;
    }
    
    public void setCodPeriodoGarantiasRc(Long codPeriodoGarantiasRc) {
        this.codPeriodoGarantiasRc = codPeriodoGarantiasRc;
    }
    public Long getValorPeriodoGarantias() {
        return this.valorPeriodoGarantias;
    }
    
    public void setValorPeriodoGarantias(Long valorPeriodoGarantias) {
        this.valorPeriodoGarantias = valorPeriodoGarantias;
    }




}

