package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


public class FicheroVinculacionExternaGId  implements java.io.Serializable {


     private Long lineaseguroid;
     private String codmodulo;
     private String grupomedida;
     private Character gruponegocio;
     private Long codespecie;
     private Long cpmriesgocubeleg;
     private Long rcriesgocubeleg;
     private Character valriesgocubeleg;
     private Long cpmpctfranquicia;
     private Long rcpctfranquicia;
     private Long valpctfranquicia;

    public FicheroVinculacionExternaGId() {
    }

    public FicheroVinculacionExternaGId(Long lineaseguroid, String codmodulo, String grupomedida, Character gruponegocio, Long codespecie, Long cpmriesgocubeleg, Long rcriesgocubeleg, Character valriesgocubeleg, Long cpmpctfranquicia, Long rcpctfranquicia, Long valpctfranquicia) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.grupomedida = grupomedida;
       this.gruponegocio = gruponegocio;
       this.codespecie = codespecie;
       this.cpmriesgocubeleg = cpmriesgocubeleg;
       this.rcriesgocubeleg = rcriesgocubeleg;
       this.valriesgocubeleg = valriesgocubeleg;
       this.cpmpctfranquicia = cpmpctfranquicia;
       this.rcpctfranquicia = rcpctfranquicia;
       this.valpctfranquicia = valpctfranquicia;
    }
   
    public Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public String getGrupomedida() {
        return this.grupomedida;
    }
    
    public void setGrupomedida(String grupomedida) {
        this.grupomedida = grupomedida;
    }
    public Character getGruponegocio() {
        return this.gruponegocio;
    }
    
    public void setGruponegocio(Character gruponegocio) {
        this.gruponegocio = gruponegocio;
    }
    public Long getCodespecie() {
        return this.codespecie;
    }
    
    public void setCodespecie(Long codespecie) {
        this.codespecie = codespecie;
    }
    public Long getCpmriesgocubeleg() {
        return this.cpmriesgocubeleg;
    }
    
    public void setCpmriesgocubeleg(Long cpmriesgocubeleg) {
        this.cpmriesgocubeleg = cpmriesgocubeleg;
    }
    public Long getRcriesgocubeleg() {
        return this.rcriesgocubeleg;
    }
    
    public void setRcriesgocubeleg(Long rcriesgocubeleg) {
        this.rcriesgocubeleg = rcriesgocubeleg;
    }
    public Character getValriesgocubeleg() {
        return this.valriesgocubeleg;
    }
    
    public void setValriesgocubeleg(Character valriesgocubeleg) {
        this.valriesgocubeleg = valriesgocubeleg;
    }
    public Long getCpmpctfranquicia() {
        return this.cpmpctfranquicia;
    }
    
    public void setCpmpctfranquicia(Long cpmpctfranquicia) {
        this.cpmpctfranquicia = cpmpctfranquicia;
    }
    public Long getRcpctfranquicia() {
        return this.rcpctfranquicia;
    }
    
    public void setRcpctfranquicia(Long rcpctfranquicia) {
        this.rcpctfranquicia = rcpctfranquicia;
    }
    public Long getValpctfranquicia() {
        return this.valpctfranquicia;
    }
    
    public void setValpctfranquicia(Long valpctfranquicia) {
        this.valpctfranquicia = valpctfranquicia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FicheroVinculacionExternaGId) ) return false;
		 FicheroVinculacionExternaGId castOther = ( FicheroVinculacionExternaGId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getCodmodulo()==castOther.getCodmodulo()) || ( this.getCodmodulo()!=null && castOther.getCodmodulo()!=null && this.getCodmodulo().equals(castOther.getCodmodulo()) ) )
 && ( (this.getGrupomedida()==castOther.getGrupomedida()) || ( this.getGrupomedida()!=null && castOther.getGrupomedida()!=null && this.getGrupomedida().equals(castOther.getGrupomedida()) ) )
 && ( (this.getGruponegocio()==castOther.getGruponegocio()) || ( this.getGruponegocio()!=null && castOther.getGruponegocio()!=null && this.getGruponegocio().equals(castOther.getGruponegocio()) ) )
 && ( (this.getCodespecie()==castOther.getCodespecie()) || ( this.getCodespecie()!=null && castOther.getCodespecie()!=null && this.getCodespecie().equals(castOther.getCodespecie()) ) )
 && ( (this.getCpmriesgocubeleg()==castOther.getCpmriesgocubeleg()) || ( this.getCpmriesgocubeleg()!=null && castOther.getCpmriesgocubeleg()!=null && this.getCpmriesgocubeleg().equals(castOther.getCpmriesgocubeleg()) ) )
 && ( (this.getRcriesgocubeleg()==castOther.getRcriesgocubeleg()) || ( this.getRcriesgocubeleg()!=null && castOther.getRcriesgocubeleg()!=null && this.getRcriesgocubeleg().equals(castOther.getRcriesgocubeleg()) ) )
 && ( (this.getValriesgocubeleg()==castOther.getValriesgocubeleg()) || ( this.getValriesgocubeleg()!=null && castOther.getValriesgocubeleg()!=null && this.getValriesgocubeleg().equals(castOther.getValriesgocubeleg()) ) )
 && ( (this.getCpmpctfranquicia()==castOther.getCpmpctfranquicia()) || ( this.getCpmpctfranquicia()!=null && castOther.getCpmpctfranquicia()!=null && this.getCpmpctfranquicia().equals(castOther.getCpmpctfranquicia()) ) )
 && ( (this.getRcpctfranquicia()==castOther.getRcpctfranquicia()) || ( this.getRcpctfranquicia()!=null && castOther.getRcpctfranquicia()!=null && this.getRcpctfranquicia().equals(castOther.getRcpctfranquicia()) ) )
 && ( (this.getValpctfranquicia()==castOther.getValpctfranquicia()) || ( this.getValpctfranquicia()!=null && castOther.getValpctfranquicia()!=null && this.getValpctfranquicia().equals(castOther.getValpctfranquicia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode() );
         result = 37 * result + ( getGrupomedida() == null ? 0 : this.getGrupomedida().hashCode() );
         result = 37 * result + ( getGruponegocio() == null ? 0 : this.getGruponegocio().hashCode() );
         result = 37 * result + ( getCodespecie() == null ? 0 : this.getCodespecie().hashCode() );
         result = 37 * result + ( getCpmriesgocubeleg() == null ? 0 : this.getCpmriesgocubeleg().hashCode() );
         result = 37 * result + ( getRcriesgocubeleg() == null ? 0 : this.getRcriesgocubeleg().hashCode() );
         result = 37 * result + ( getValriesgocubeleg() == null ? 0 : this.getValriesgocubeleg().hashCode() );
         result = 37 * result + ( getCpmpctfranquicia() == null ? 0 : this.getCpmpctfranquicia().hashCode() );
         result = 37 * result + ( getRcpctfranquicia() == null ? 0 : this.getRcpctfranquicia().hashCode() );
         result = 37 * result + ( getValpctfranquicia() == null ? 0 : this.getValpctfranquicia().hashCode() );
         return result;
   }   


}


