package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import java.math.BigDecimal;

public class GarantiasMedidasId  implements java.io.Serializable {


     private Long lineaseguroid;
     private String codmodulo;
     private BigDecimal cppalMod;
     private BigDecimal codRiesgoCub;

    public GarantiasMedidasId() {
    }

    public GarantiasMedidasId(Long lineaseguroid, String codmodulo, BigDecimal cppalMod, BigDecimal codRiesgoCub) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.cppalMod = cppalMod;
       this.codRiesgoCub = codRiesgoCub;
    }
   
    public Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public BigDecimal getCppalMod() {
        return this.cppalMod;
    }
    
    public void setCppalMod(BigDecimal cppalMod) {
        this.cppalMod = cppalMod;
    }
    public BigDecimal getCodRiesgoCub() {
        return this.codRiesgoCub;
    }
    
    public void setCodRiesgoCub(BigDecimal codRiesgoCub) {
        this.codRiesgoCub = codRiesgoCub;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GarantiasMedidasId) ) return false;
		 GarantiasMedidasId castOther = ( GarantiasMedidasId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getCodmodulo()==castOther.getCodmodulo()) || ( this.getCodmodulo()!=null && castOther.getCodmodulo()!=null && this.getCodmodulo().equals(castOther.getCodmodulo()) ) )
 && ( (this.getCppalMod()==castOther.getCppalMod()) || ( this.getCppalMod()!=null && castOther.getCppalMod()!=null && this.getCppalMod().equals(castOther.getCppalMod()) ) )
 && ( (this.getCodRiesgoCub()==castOther.getCodRiesgoCub()) || ( this.getCodRiesgoCub()!=null && castOther.getCodRiesgoCub()!=null && this.getCodRiesgoCub().equals(castOther.getCodRiesgoCub()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode() );
         result = 37 * result + ( getCppalMod() == null ? 0 : this.getCppalMod().hashCode() );
         result = 37 * result + ( getCodRiesgoCub() == null ? 0 : this.getCodRiesgoCub().hashCode() );
         return result;
   }   


}


