package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.TipoCapital;
import com.rsi.agp.dao.tables.commons.Termino;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.org.DiccionarioDatos;
import com.rsi.agp.dao.tables.poliza.Linea;

public class IncompatibilidadMismaPoliza  implements java.io.Serializable {


     private IncompatibilidadMismaPolizaId id;
     private Modulo modulo;
     private DiccionarioDatos diccionarioDatos;
     private RegimenManejo regimenManejo;
     private TiposAnimalGanado tiposAnimalGanado;
     private DiccionarioDatos diccionarioDatosByCodconceptoInc;
     private Especie especie;
     private RegimenManejo regimenManejoByFkRegimeniIncMismaPol;
     private GruposRazas gruposRazasByFkGruporazaiIncMismaPol;
     private Especie especieByFkEspecieiIncMismaPol;
     private TiposAnimalGanado tiposAnimalGanadoByFkTipoanimaliIncMismaPol;
     private Termino termino;
     private TipoCapital tipoCapital;
     private Termino terminoByFkTerminoiIncMismaPol;
     private Linea linea;
     private GruposRazas gruposRazas;
     private TipoCapital tipoCapitalByCodtipocapitalInc;
     private Long valorconcepto;
     private Long valorconceptoInc;
     private Long nivelAplicacion;

    public IncompatibilidadMismaPoliza() {
    }

	
    public IncompatibilidadMismaPoliza(IncompatibilidadMismaPolizaId id, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, Especie especie, RegimenManejo regimenManejoByFkRegimeniIncMismaPol, GruposRazas gruposRazasByFkGruporazaiIncMismaPol, Especie especieByFkEspecieiIncMismaPol, TiposAnimalGanado tiposAnimalGanadoByFkTipoanimaliIncMismaPol, Termino termino, TipoCapital tipoCapital, Termino terminoByFkTerminoiIncMismaPol, Linea linea, GruposRazas gruposRazas, TipoCapital tipoCapitalByCodtipocapitalInc, Long nivelAplicacion) {
        this.id = id;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tiposAnimalGanado = tiposAnimalGanado;
        this.especie = especie;
        this.regimenManejoByFkRegimeniIncMismaPol = regimenManejoByFkRegimeniIncMismaPol;
        this.gruposRazasByFkGruporazaiIncMismaPol = gruposRazasByFkGruporazaiIncMismaPol;
        this.especieByFkEspecieiIncMismaPol = especieByFkEspecieiIncMismaPol;
        this.tiposAnimalGanadoByFkTipoanimaliIncMismaPol = tiposAnimalGanadoByFkTipoanimaliIncMismaPol;
        this.termino = termino;
        this.tipoCapital = tipoCapital;
        this.terminoByFkTerminoiIncMismaPol = terminoByFkTerminoiIncMismaPol;
        this.linea = linea;
        this.gruposRazas = gruposRazas;
        this.tipoCapitalByCodtipocapitalInc = tipoCapitalByCodtipocapitalInc;
        this.nivelAplicacion = nivelAplicacion;
    }
    public IncompatibilidadMismaPoliza(IncompatibilidadMismaPolizaId id, Modulo modulo, DiccionarioDatos diccionarioDatos, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, DiccionarioDatos diccionarioDatosByCodconceptoInc, Especie especie, RegimenManejo regimenManejoByFkRegimeniIncMismaPol, GruposRazas gruposRazasByFkGruporazaiIncMismaPol, Especie especieByFkEspecieiIncMismaPol, TiposAnimalGanado tiposAnimalGanadoByFkTipoanimaliIncMismaPol, Termino termino, TipoCapital tipoCapital, Termino terminoByFkTerminoiIncMismaPol, Linea linea, GruposRazas gruposRazas, TipoCapital tipoCapitalByCodtipocapitalInc, Long valorconcepto, Long valorconceptoInc, Long nivelAplicacion) {
       this.id = id;
       this.modulo = modulo;
       this.diccionarioDatos = diccionarioDatos;
       this.regimenManejo = regimenManejo;
       this.tiposAnimalGanado = tiposAnimalGanado;
       this.diccionarioDatosByCodconceptoInc = diccionarioDatosByCodconceptoInc;
       this.especie = especie;
       this.regimenManejoByFkRegimeniIncMismaPol = regimenManejoByFkRegimeniIncMismaPol;
       this.gruposRazasByFkGruporazaiIncMismaPol = gruposRazasByFkGruporazaiIncMismaPol;
       this.especieByFkEspecieiIncMismaPol = especieByFkEspecieiIncMismaPol;
       this.tiposAnimalGanadoByFkTipoanimaliIncMismaPol = tiposAnimalGanadoByFkTipoanimaliIncMismaPol;
       this.termino = termino;
       this.tipoCapital = tipoCapital;
       this.terminoByFkTerminoiIncMismaPol = terminoByFkTerminoiIncMismaPol;
       this.linea = linea;
       this.gruposRazas = gruposRazas;
       this.tipoCapitalByCodtipocapitalInc = tipoCapitalByCodtipocapitalInc;
       this.valorconcepto = valorconcepto;
       this.valorconceptoInc = valorconceptoInc;
       this.nivelAplicacion = nivelAplicacion;
    }
   
    public IncompatibilidadMismaPolizaId getId() {
        return this.id;
    }
    
    public void setId(IncompatibilidadMismaPolizaId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TiposAnimalGanado getTiposAnimalGanado() {
        return this.tiposAnimalGanado;
    }
    
    public void setTiposAnimalGanado(TiposAnimalGanado tiposAnimalGanado) {
        this.tiposAnimalGanado = tiposAnimalGanado;
    }
    public DiccionarioDatos getDiccionarioDatosByCodconceptoInc() {
        return this.diccionarioDatosByCodconceptoInc;
    }
    
    public void setDiccionarioDatosByCodconceptoInc(DiccionarioDatos diccionarioDatosByCodconceptoInc) {
        this.diccionarioDatosByCodconceptoInc = diccionarioDatosByCodconceptoInc;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public RegimenManejo getRegimenManejoByFkRegimeniIncMismaPol() {
        return this.regimenManejoByFkRegimeniIncMismaPol;
    }
    
    public void setRegimenManejoByFkRegimeniIncMismaPol(RegimenManejo regimenManejoByFkRegimeniIncMismaPol) {
        this.regimenManejoByFkRegimeniIncMismaPol = regimenManejoByFkRegimeniIncMismaPol;
    }
    public GruposRazas getGruposRazasByFkGruporazaiIncMismaPol() {
        return this.gruposRazasByFkGruporazaiIncMismaPol;
    }
    
    public void setGruposRazasByFkGruporazaiIncMismaPol(GruposRazas gruposRazasByFkGruporazaiIncMismaPol) {
        this.gruposRazasByFkGruporazaiIncMismaPol = gruposRazasByFkGruporazaiIncMismaPol;
    }
    public Especie getEspecieByFkEspecieiIncMismaPol() {
        return this.especieByFkEspecieiIncMismaPol;
    }
    
    public void setEspecieByFkEspecieiIncMismaPol(Especie especieByFkEspecieiIncMismaPol) {
        this.especieByFkEspecieiIncMismaPol = especieByFkEspecieiIncMismaPol;
    }
    public TiposAnimalGanado getTiposAnimalGanadoByFkTipoanimaliIncMismaPol() {
        return this.tiposAnimalGanadoByFkTipoanimaliIncMismaPol;
    }
    
    public void setTiposAnimalGanadoByFkTipoanimaliIncMismaPol(TiposAnimalGanado tiposAnimalGanadoByFkTipoanimaliIncMismaPol) {
        this.tiposAnimalGanadoByFkTipoanimaliIncMismaPol = tiposAnimalGanadoByFkTipoanimaliIncMismaPol;
    }
    public Termino getTermino() {
        return this.termino;
    }
    
    public void setTermino(Termino termino) {
        this.termino = termino;
    }
    public TipoCapital getTipoCapital() {
        return this.tipoCapital;
    }
    
    public void setTipoCapital(TipoCapital tipoCapital) {
        this.tipoCapital = tipoCapital;
    }
    public Termino getTerminoByFkTerminoiIncMismaPol() {
        return this.terminoByFkTerminoiIncMismaPol;
    }
    
    public void setTerminoByFkTerminoiIncMismaPol(Termino terminoByFkTerminoiIncMismaPol) {
        this.terminoByFkTerminoiIncMismaPol = terminoByFkTerminoiIncMismaPol;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public TipoCapital getTipoCapitalByCodtipocapitalInc() {
        return this.tipoCapitalByCodtipocapitalInc;
    }
    
    public void setTipoCapitalByCodtipocapitalInc(TipoCapital tipoCapitalByCodtipocapitalInc) {
        this.tipoCapitalByCodtipocapitalInc = tipoCapitalByCodtipocapitalInc;
    }
    public Long getValorconcepto() {
        return this.valorconcepto;
    }
    
    public void setValorconcepto(Long valorconcepto) {
        this.valorconcepto = valorconcepto;
    }
    public Long getValorconceptoInc() {
        return this.valorconceptoInc;
    }
    
    public void setValorconceptoInc(Long valorconceptoInc) {
        this.valorconceptoInc = valorconceptoInc;
    }
    public Long getNivelAplicacion() {
        return this.nivelAplicacion;
    }
    
    public void setNivelAplicacion(Long nivelAplicacion) {
        this.nivelAplicacion = nivelAplicacion;
    }




}


