package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.TipoCapital;
import com.rsi.agp.dao.tables.cgen.TipoCapitalConGrupoNegocio;
import com.rsi.agp.dao.tables.commons.Termino;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.org.DiccionarioDatos;
import com.rsi.agp.dao.tables.poliza.Linea;

public class MascaraPrecioGanado  implements java.io.Serializable {


     private MascaraPrecioGanadoId id;
     private Modulo modulo;
     private DiccionarioDatos diccionarioDatos;
     private RegimenManejo regimenManejo;
     private TiposAnimalGanado tiposAnimalGanado;
     private Termino termino;
     private TipoCapitalConGrupoNegocio tipoCapital;
     private GruposRazas gruposRazas;
     private Linea linea;
     private Especie especie;

    public MascaraPrecioGanado() {
    }

	
    public MascaraPrecioGanado(MascaraPrecioGanadoId id, Modulo modulo, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, Termino termino, TipoCapitalConGrupoNegocio tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie) {
        this.id = id;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tiposAnimalGanado = tiposAnimalGanado;
        this.termino = termino;
        this.tipoCapital = tipoCapital;
        this.gruposRazas = gruposRazas;
        this.linea = linea;
        this.especie = especie;
    }
    public MascaraPrecioGanado(MascaraPrecioGanadoId id, Modulo modulo, DiccionarioDatos diccionarioDatos, RegimenManejo regimenManejo, TiposAnimalGanado tiposAnimalGanado, Termino termino, TipoCapitalConGrupoNegocio tipoCapital, GruposRazas gruposRazas, Linea linea, Especie especie) {
       this.id = id;
       this.modulo = modulo;
       this.diccionarioDatos = diccionarioDatos;
       this.regimenManejo = regimenManejo;
       this.tiposAnimalGanado = tiposAnimalGanado;
       this.termino = termino;
       this.tipoCapital = tipoCapital;
       this.gruposRazas = gruposRazas;
       this.linea = linea;
       this.especie = especie;
    }
   
    public MascaraPrecioGanadoId getId() {
        return this.id;
    }
    
    public void setId(MascaraPrecioGanadoId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TiposAnimalGanado getTiposAnimalGanado() {
        return this.tiposAnimalGanado;
    }
    
    public void setTiposAnimalGanado(TiposAnimalGanado tiposAnimalGanado) {
        this.tiposAnimalGanado = tiposAnimalGanado;
    }
    public Termino getTermino() {
        return this.termino;
    }
    
    public void setTermino(Termino termino) {
        this.termino = termino;
    }
    public TipoCapitalConGrupoNegocio getTipoCapital() {
        return this.tipoCapital;
    }
    
    public void setTipoCapital(TipoCapitalConGrupoNegocio tipoCapital) {
        this.tipoCapital = tipoCapital;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }




}


