package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


public class NumMinAnimalesColmenasId  implements java.io.Serializable {


     private Long lineaseguroid;
     private String codmodulo;
     private Long codtipocapital;
     private Long codespecie;
     private Long codregimen;
     private Long codgruporaza;
     private Long codtipoanimal;
     
    public NumMinAnimalesColmenasId() {
    }

    public NumMinAnimalesColmenasId(Long lineaseguroid, String codmodulo, Long codtipocapital, Long codespecie, Long codregimen, Long codgruporaza, Long codtipoanimal) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.codtipocapital = codtipocapital;
       this.codespecie = codespecie;
       this.codregimen = codregimen;
       this.codgruporaza = codgruporaza;
       this.codtipoanimal = codtipoanimal;
    }
   
    public Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public Long getCodtipocapital() {
        return this.codtipocapital;
    }
    
    public void setCodtipocapital(Long codtipocapital) {
        this.codtipocapital = codtipocapital;
    }
    public Long getCodespecie() {
        return this.codespecie;
    }
    
    public void setCodespecie(Long codespecie) {
        this.codespecie = codespecie;
    }
    public Long getCodregimen() {
        return this.codregimen;
    }
    
    public void setCodregimen(Long codregimen) {
        this.codregimen = codregimen;
    }
    public Long getCodgruporaza() {
        return this.codgruporaza;
    }
    
    public void setCodgruporaza(Long codgruporaza) {
        this.codgruporaza = codgruporaza;
    }

    public Long getCodtipoanimal() {
    	return codtipoanimal;
    }

    public void setCodtipoanimal(Long codtipoanimal) {
    	this.codtipoanimal = codtipoanimal;
    }   

   @Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	NumMinAnimalesColmenasId other = (NumMinAnimalesColmenasId) obj;
	if (codespecie == null) {
		if (other.codespecie != null)
			return false;
	} else if (!codespecie.equals(other.codespecie))
		return false;
	if (codgruporaza == null) {
		if (other.codgruporaza != null)
			return false;
	} else if (!codgruporaza.equals(other.codgruporaza))
		return false;
	if (codmodulo == null) {
		if (other.codmodulo != null)
			return false;
	} else if (!codmodulo.equals(other.codmodulo))
		return false;
	if (codregimen == null) {
		if (other.codregimen != null)
			return false;
	} else if (!codregimen.equals(other.codregimen))
		return false;
	if (codtipoanimal == null) {
		if (other.codtipoanimal != null)
			return false;
	} else if (!codtipoanimal.equals(other.codtipoanimal))
		return false;
	if (codtipocapital == null) {
		if (other.codtipocapital != null)
			return false;
	} else if (!codtipocapital.equals(other.codtipocapital))
		return false;
	if (lineaseguroid == null) {
		if (other.lineaseguroid != null)
			return false;
	} else if (!lineaseguroid.equals(other.lineaseguroid))
		return false;
	return true;
}
   
   @Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result
			+ ((codespecie == null) ? 0 : codespecie.hashCode());
	result = prime * result
			+ ((codgruporaza == null) ? 0 : codgruporaza.hashCode());
	result = prime * result + ((codmodulo == null) ? 0 : codmodulo.hashCode());
	result = prime * result
			+ ((codregimen == null) ? 0 : codregimen.hashCode());
	result = prime * result
			+ ((codtipoanimal == null) ? 0 : codtipoanimal.hashCode());
	result = prime * result
			+ ((codtipocapital == null) ? 0 : codtipocapital.hashCode());
	result = prime * result
			+ ((lineaseguroid == null) ? 0 : lineaseguroid.hashCode());
	return result;
}


}


