package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import java.math.BigDecimal;

import com.rsi.agp.dao.tables.cgen.TipoCapitalConGrupoNegocio;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class PctValorMaxExplotacion  implements java.io.Serializable {


     private PctValorMaxExplotacionId id;
     private Modulo modulo;
     private RegimenManejo regimenManejo;
     private TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio;
     private GruposRazas gruposRazas;
     private Linea linea;
     private Especie especie;
     private Long codtipoanimal;
     private Long codtipoanimald;
     private BigDecimal valProdMaxExpl;
     private Long numAnimExcep;
     private Long nivelAplicacion;

    public PctValorMaxExplotacion() {
    }

	
    public PctValorMaxExplotacion(PctValorMaxExplotacionId id, Modulo modulo, RegimenManejo regimenManejo, TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio, GruposRazas gruposRazas, Linea linea, Especie especie, BigDecimal valProdMaxExpl, Long numAnimExcep, Long nivelAplicacion) {
        this.id = id;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
        this.gruposRazas = gruposRazas;
        this.linea = linea;
        this.especie = especie;
        this.valProdMaxExpl = valProdMaxExpl;
        this.numAnimExcep = numAnimExcep;
        this.nivelAplicacion = nivelAplicacion;
    }
    public PctValorMaxExplotacion(PctValorMaxExplotacionId id, Modulo modulo, RegimenManejo regimenManejo, TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio, GruposRazas gruposRazas, Linea linea, Especie especie, Long codtipoanimal, Long codtipoanimald, BigDecimal valProdMaxExpl, Long numAnimExcep, Long nivelAplicacion) {
       this.id = id;
       this.modulo = modulo;
       this.regimenManejo = regimenManejo;
       this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
       this.gruposRazas = gruposRazas;
       this.linea = linea;
       this.especie = especie;
       this.codtipoanimal = codtipoanimal;
       this.codtipoanimald = codtipoanimald;
       this.valProdMaxExpl = valProdMaxExpl;
       this.numAnimExcep = numAnimExcep;
       this.nivelAplicacion = nivelAplicacion;
    }
   
    public PctValorMaxExplotacionId getId() {
        return this.id;
    }
    
    public void setId(PctValorMaxExplotacionId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TipoCapitalConGrupoNegocio getTipoCapitalConGrupoNegocio() {
        return this.tipoCapitalConGrupoNegocio;
    }
    
    public void setTipoCapitalConGrupoNegocio(TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio) {
        this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public Long getCodtipoanimal() {
        return this.codtipoanimal;
    }
    
    public void setCodtipoanimal(Long codtipoanimal) {
        this.codtipoanimal = codtipoanimal;
    }
    public Long getCodtipoanimald() {
        return this.codtipoanimald;
    }
    
    public void setCodtipoanimald(Long codtipoanimald) {
        this.codtipoanimald = codtipoanimald;
    }
    public BigDecimal getValProdMaxExpl() {
        return this.valProdMaxExpl;
    }
    
    public void setValProdMaxExpl(BigDecimal valProdMaxExpl) {
        this.valProdMaxExpl = valProdMaxExpl;
    }
    public Long getNumAnimExcep() {
        return this.numAnimExcep;
    }
    
    public void setNumAnimExcep(Long numAnimExcep) {
        this.numAnimExcep = numAnimExcep;
    }
    public Long getNivelAplicacion() {
        return this.nivelAplicacion;
    }
    
    public void setNivelAplicacion(Long nivelAplicacion) {
        this.nivelAplicacion = nivelAplicacion;
    }




}


