package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cgen.TipoCapitalConGrupoNegocio;
import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class RelacionAnimales  implements java.io.Serializable {


     private RelacionAnimalesId id;
     private Modulo modulo;
     private RegimenManejo regimenManejo;
     private TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio;
     private GruposRazas gruposRazas;
     private Linea linea;
     private Especie especie;
     private Long tipoAnimalBase;
     private Long tipoAnimalBaseD;
     private Long tipoAnimalRel;
     private Long tipoAnimalRelD;
     private Long tipoGanaderia;
     private Long pctMinRelBase;
     private Long numAniRelMin;

    public RelacionAnimales() {
    	modulo = new Modulo();
    	regimenManejo = new RegimenManejo();
    	tipoCapitalConGrupoNegocio = new TipoCapitalConGrupoNegocio();
    	gruposRazas = new GruposRazas();
    	linea = new Linea();
    	especie = new Especie();
    }

	
    public RelacionAnimales(RelacionAnimalesId id, Modulo modulo, RegimenManejo regimenManejo, TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio, GruposRazas gruposRazas, Linea linea, Especie especie, Long pctMinRelBase, Long numAniRelMin) {
        this.id = id;
        this.modulo = modulo;
        this.regimenManejo = regimenManejo;
        this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
        this.gruposRazas = gruposRazas;
        this.linea = linea;
        this.especie = especie;
        this.pctMinRelBase = pctMinRelBase;
        this.numAniRelMin = numAniRelMin;
    }
    public RelacionAnimales(RelacionAnimalesId id, Modulo modulo, RegimenManejo regimenManejo, TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio, GruposRazas gruposRazas, Linea linea, Especie especie, Long tipoAnimalBase, Long tipoAnimalBaseD, Long tipoAnimalRel, Long tipoAnimalRelD, Long tipoGanaderia, Long pctMinRelBase, Long numAniRelMin) {
       this.id = id;
       this.modulo = modulo;
       this.regimenManejo = regimenManejo;
       this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
       this.gruposRazas = gruposRazas;
       this.linea = linea;
       this.especie = especie;
       this.tipoAnimalBase = tipoAnimalBase;
       this.tipoAnimalBaseD = tipoAnimalBaseD;
       this.tipoAnimalRel = tipoAnimalRel;
       this.tipoAnimalRelD = tipoAnimalRelD;
       this.tipoGanaderia = tipoGanaderia;
       this.pctMinRelBase = pctMinRelBase;
       this.numAniRelMin = numAniRelMin;
    }
   
    public RelacionAnimalesId getId() {
        return this.id;
    }
    
    public void setId(RelacionAnimalesId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public RegimenManejo getRegimenManejo() {
        return this.regimenManejo;
    }
    
    public void setRegimenManejo(RegimenManejo regimenManejo) {
        this.regimenManejo = regimenManejo;
    }
    public TipoCapitalConGrupoNegocio getTipoCapitalConGrupoNegocio() {
        return this.tipoCapitalConGrupoNegocio;
    }
    
    public void setTipoCapitalConGrupoNegocio(TipoCapitalConGrupoNegocio tipoCapitalConGrupoNegocio) {
        this.tipoCapitalConGrupoNegocio = tipoCapitalConGrupoNegocio;
    }
    public GruposRazas getGruposRazas() {
        return this.gruposRazas;
    }
    
    public void setGruposRazas(GruposRazas gruposRazas) {
        this.gruposRazas = gruposRazas;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public Long getTipoAnimalBase() {
        return this.tipoAnimalBase;
    }
    
    public void setTipoAnimalBase(Long tipoAnimalBase) {
        this.tipoAnimalBase = tipoAnimalBase;
    }
    public Long getTipoAnimalBaseD() {
        return this.tipoAnimalBaseD;
    }
    
    public void setTipoAnimalBaseD(Long tipoAnimalBaseD) {
        this.tipoAnimalBaseD = tipoAnimalBaseD;
    }
    public Long getTipoAnimalRel() {
        return this.tipoAnimalRel;
    }
    
    public void setTipoAnimalRel(Long tipoAnimalRel) {
        this.tipoAnimalRel = tipoAnimalRel;
    }
    public Long getTipoAnimalRelD() {
        return this.tipoAnimalRelD;
    }
    
    public void setTipoAnimalRelD(Long tipoAnimalRelD) {
        this.tipoAnimalRelD = tipoAnimalRelD;
    }
    public Long getTipoGanaderia() {
        return this.tipoGanaderia;
    }
    
    public void setTipoGanaderia(Long tipoGanaderia) {
        this.tipoGanaderia = tipoGanaderia;
    }
    public Long getPctMinRelBase() {
        return this.pctMinRelBase;
    }
    
    public void setPctMinRelBase(Long pctMinRelBase) {
        this.pctMinRelBase = pctMinRelBase;
    }
    public Long getNumAniRelMin() {
        return this.numAniRelMin;
    }
    
    public void setNumAniRelMin(Long numAniRelMin) {
        this.numAniRelMin = numAniRelMin;
    }




}


