package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems

public class RelValConceptXConceptDeduciblesGId  implements java.io.Serializable {


     private Long lineaseguroid;
     private Long numagrupacion;

    public RelValConceptXConceptDeduciblesGId() {
    }

    public RelValConceptXConceptDeduciblesGId(Long lineaseguroid, Long numagrupacion) {
       this.lineaseguroid = lineaseguroid;
       this.numagrupacion = numagrupacion;
    }
   
    public Long getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(Long lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public Long getNumagrupacion() {
        return this.numagrupacion;
    }
    
    public void setNumagrupacion(Long numagrupacion) {
        this.numagrupacion = numagrupacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelValConceptXConceptDeduciblesGId) ) return false;
		 RelValConceptXConceptDeduciblesGId castOther = ( RelValConceptXConceptDeduciblesGId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getNumagrupacion()==castOther.getNumagrupacion()) || ( this.getNumagrupacion()!=null && castOther.getNumagrupacion()!=null && this.getNumagrupacion().equals(castOther.getNumagrupacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getNumagrupacion() == null ? 0 : this.getNumagrupacion().hashCode() );
         return result;
   }   


}


