package com.rsi.agp.dao.tables.cpl.gan;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.poliza.Linea;

public class VinculacionFilasModuloG  implements java.io.Serializable {


     private VinculacionFilasModuloGId id;
     private RiesgoCubiertoModuloGanado riesgoCubiertoModuloGanado;
     private Modulo modulo;
     private Linea linea;

    public VinculacionFilasModuloG() {
    }

    public VinculacionFilasModuloG(VinculacionFilasModuloGId id, RiesgoCubiertoModuloGanado riesgoCubiertoModuloGanado, Modulo modulo, Linea linea) {
       this.id = id;
       this.riesgoCubiertoModuloGanado = riesgoCubiertoModuloGanado;
       this.modulo = modulo;
       this.linea = linea;
    }
   
    public VinculacionFilasModuloGId getId() {
        return this.id;
    }
    
    public void setId(VinculacionFilasModuloGId id) {
        this.id = id;
    }
    public RiesgoCubiertoModuloGanado getRiesgoCubiertoModuloGanado() {
        return this.riesgoCubiertoModuloGanado;
    }
    
    public void setRiesgoCubiertoModuloGanado(RiesgoCubiertoModuloGanado riesgoCubiertoModuloGanado) {
        this.riesgoCubiertoModuloGanado = riesgoCubiertoModuloGanado;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }




}


