package com.rsi.agp.dao.tables.log;
// Generated by T-Systems


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.rsi.agp.dao.tables.poliza.Linea;

public class HistImportaciones  implements java.io.Serializable {


     private Long idhistorico;
    private TipoImportacion tipoImportacion;
    private Linea linea;
    private String ubicacionficheros;
    private Date fechaimport;
    private String estado;
    private String descerror;
    private Set<ImportacionTabla> importacionTablas = new HashSet<ImportacionTabla>(0);

   public HistImportaciones() {	   
   }

	
    public HistImportaciones(Long idhistorico, TipoImportacion tipoImportacion, Linea linea, Date fechaimport, String estado) {
       this.idhistorico = idhistorico;
       this.tipoImportacion = tipoImportacion;
       this.linea = linea;
       this.fechaimport = fechaimport;
       this.estado = estado;
    }
    public HistImportaciones(Long idhistorico, TipoImportacion tipoImportacion, Linea linea, String ubicacionficheros, Date fechaimport, String estado, String descerror, Set<ImportacionTabla> importacionTablas) {
      this.idhistorico = idhistorico;
      this.tipoImportacion = tipoImportacion;
      this.linea = linea;
      this.ubicacionficheros = ubicacionficheros;
      this.fechaimport = fechaimport;
      this.estado = estado;
      this.descerror = descerror;
      this.importacionTablas = importacionTablas;
   }
  
   public Long getIdhistorico() {
       return this.idhistorico;
   }
   
   public void setIdhistorico(Long idhistorico) {
       this.idhistorico = idhistorico;
   }
   public TipoImportacion getTipoImportacion() {
       return this.tipoImportacion;
   }
   
   public void setTipoImportacion(TipoImportacion tipoImportacion) {
       this.tipoImportacion = tipoImportacion;
   }
   public Linea getLinea() {
       return this.linea;
   }
   
   public void setLinea(Linea linea) {
       this.linea = linea;
   }
   public String getUbicacionficheros() {
       return this.ubicacionficheros;
   }
   
   public void setUbicacionficheros(String ubicacionficheros) {
       this.ubicacionficheros = ubicacionficheros;
   }
   public Date getFechaimport() {
       return this.fechaimport;
   }
   
   public void setFechaimport(Date fechaimport) {
       this.fechaimport = fechaimport;
   }
   public String getEstado() {
       return this.estado;
   }
   
   public void setEstado(String estado) {
       this.estado = estado;
   }
    public String getDescerror() {
        return this.descerror;
    }
    
    public void setDescerror(String descerror) {
        this.descerror = descerror;
    }
   public Set<ImportacionTabla> getImportacionTablas() {
       return this.importacionTablas;
   }
   
   public void setImportacionTablas(Set<ImportacionTabla> importacionTablas) {
       this.importacionTablas = importacionTablas;
   }




}


