package com.rsi.agp.dao.tables.comisiones.comisiones;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class ComisionAplicacion  implements java.io.Serializable {


     private Long id;
     private Comision comision;
     private String referencia;
     private BigDecimal dc;
     private Character tiporeferencia;
     private String codinterno;
     private Character anuladarefundida;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String razonsocial;
     private BigDecimal dnPrimabasecalculo;
     private BigDecimal dnGastosextentidad;
     private BigDecimal dnComisiones;
     private BigDecimal dnTotal;
     private BigDecimal drPrimabasecalculo;
     private BigDecimal drGastosextentidad;
     private BigDecimal drComisiones;
     private BigDecimal drTotal;
     private BigDecimal dtPrimabasecalculo;
     private BigDecimal dtGastosextentidad;
     private BigDecimal dtComisiones;
     private BigDecimal dtTotal;
     private BigDecimal dtGastospagados;
     private BigDecimal dtGastospendientes;
     private BigDecimal dn1PrimaComercialNeta;
     private BigDecimal dn1GastosAdminEntidad;
     private BigDecimal dn1GastosAdqEntidad;
     private BigDecimal dn1ComisionesMediador;
     private BigDecimal dn1ComisionesMediadorEnt;
     private BigDecimal dn1ComisionesMediadorEsmed;
     private BigDecimal dn1Total;
     private BigDecimal dr1PrimaComercialNeta;
     private BigDecimal dr1GastosAdminEntidad;
     private BigDecimal dr1GastosAdqEntidad;
     private BigDecimal dr1ComisionesMediador;
     private BigDecimal dr1ComisionesMediadorEnt;
     private BigDecimal dr1ComisionesMediadorEsmed;
     private BigDecimal dr1Total;
     private BigDecimal dt1PrimaComercialNeta;
     private BigDecimal dt1GastosAdminEntidad;
     private BigDecimal dt1GastosAdqEntidad;
     private BigDecimal dt1ComisionesMediador;
     private BigDecimal dt1ComisionesMediadorEnt;
     private BigDecimal dt1ComisionesMediadorEsmed;
     private BigDecimal dt1GastosAdminEntAbon;
     private BigDecimal dt1GastosAdqEntAbon;
     private BigDecimal dt1ComisionesMediadorAbon;
     private BigDecimal dt1ComisMediadorAbonEnt;
     private BigDecimal dt1ComisMediadorAbonEsmed;
     private BigDecimal dt1GastosAdminEntPdte;
     private BigDecimal dt1GastosAdqEntPdte;
     private BigDecimal dt1ComisionesMediadorPdte;
     private BigDecimal dt1ComisMediadorPdteEnt;
     private BigDecimal dt1ComisMediadorPdteEsmed;
     private Set<ComisionAplicacionCondicionParticular> comisionAplicacionCondicionParticulars = new HashSet<ComisionAplicacionCondicionParticular>(0);

    public ComisionAplicacion() {
    }

	
    public ComisionAplicacion(Long id, Comision comision) {
        this.id = id;
        this.comision = comision;
    }
    
    public ComisionAplicacion(Long id, Comision comision, String referencia, BigDecimal dc, Character tiporeferencia, String codinterno, Character anuladarefundida, String nombre, String apellido1, String apellido2, String razonsocial, BigDecimal dnPrimabasecalculo, BigDecimal dnGastosextentidad, BigDecimal dnComisiones, BigDecimal dnTotal, BigDecimal drPrimabasecalculo, BigDecimal drGastosextentidad, BigDecimal drComisiones, BigDecimal drTotal, BigDecimal dtPrimabasecalculo, BigDecimal dtGastosextentidad, BigDecimal dtComisiones, BigDecimal dtTotal, BigDecimal dtGastospagados, BigDecimal dtGastospendientes, BigDecimal dn1PrimaComercialNeta, BigDecimal dn1GastosAdminEntidad, BigDecimal dn1GastosAdqEntidad, BigDecimal dn1ComisionesMediador, BigDecimal dn1ComisionesMediadorEnt, BigDecimal dn1ComisionesMediadorEsmed, BigDecimal dn1Total, BigDecimal dr1PrimaComercialNeta, BigDecimal dr1GastosAdminEntidad, BigDecimal dr1GastosAdqEntidad, BigDecimal dr1ComisionesMediador, BigDecimal dr1ComisionesMediadorEnt, BigDecimal dr1ComisionesMediadorEsmed, BigDecimal dr1Total, BigDecimal dt1PrimaComercialNeta, BigDecimal dt1GastosAdminEntidad, BigDecimal dt1GastosAdqEntidad, BigDecimal dt1ComisionesMediador, BigDecimal dt1ComisionesMediadorEnt, BigDecimal dt1ComisionesMediadorEsmed, BigDecimal dt1GastosAdminEntAbon, BigDecimal dt1GastosAdqEntAbon, BigDecimal dt1ComisionesMediadorAbon, BigDecimal dt1ComisMediadorAbonEnt, BigDecimal dt1ComisMediadorAbonEsmed, BigDecimal dt1GastosAdminEntPdte, BigDecimal dt1GastosAdqEntPdte, BigDecimal dt1ComisionesMediadorPdte, BigDecimal dt1ComisMediadorPdteEnt, BigDecimal dt1ComisMediadorPdteEsmed, Set<ComisionAplicacionCondicionParticular> comisionAplicacionCondicionParticulars) {
       this.id = id;
       this.comision = comision;
       this.referencia = referencia;
       this.dc = dc;
       this.tiporeferencia = tiporeferencia;
       this.codinterno = codinterno;
       this.anuladarefundida = anuladarefundida;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.razonsocial = razonsocial;
       this.dnPrimabasecalculo = dnPrimabasecalculo;
       this.dnGastosextentidad = dnGastosextentidad;
       this.dnComisiones = dnComisiones;
       this.dnTotal = dnTotal;
       this.drPrimabasecalculo = drPrimabasecalculo;
       this.drGastosextentidad = drGastosextentidad;
       this.drComisiones = drComisiones;
       this.drTotal = drTotal;
       this.dtPrimabasecalculo = dtPrimabasecalculo;
       this.dtGastosextentidad = dtGastosextentidad;
       this.dtComisiones = dtComisiones;
       this.dtTotal = dtTotal;
       this.dtGastospagados = dtGastospagados;
       this.dtGastospendientes = dtGastospendientes;
       this.dn1PrimaComercialNeta = dn1PrimaComercialNeta;
       this.dn1GastosAdminEntidad = dn1GastosAdminEntidad;
       this.dn1GastosAdqEntidad = dn1GastosAdqEntidad;
       this.dn1ComisionesMediador = dn1ComisionesMediador;
       this.dn1ComisionesMediadorEnt = dn1ComisionesMediadorEnt;
       this.dn1ComisionesMediadorEsmed = dn1ComisionesMediadorEsmed;
       this.dn1Total = dn1Total;
       this.dr1PrimaComercialNeta = dr1PrimaComercialNeta;
       this.dr1GastosAdminEntidad = dr1GastosAdminEntidad;
       this.dr1GastosAdqEntidad = dr1GastosAdqEntidad;
       this.dr1ComisionesMediador = dr1ComisionesMediador;
       this.dr1ComisionesMediadorEnt = dr1ComisionesMediadorEnt;
       this.dr1ComisionesMediadorEsmed = dr1ComisionesMediadorEsmed;
       this.dr1Total = dr1Total;
       this.dt1PrimaComercialNeta = dt1PrimaComercialNeta;
       this.dt1GastosAdminEntidad = dt1GastosAdminEntidad;
       this.dt1GastosAdqEntidad = dt1GastosAdqEntidad;
       this.dt1ComisionesMediador = dt1ComisionesMediador;
       this.dt1ComisionesMediadorEnt = dt1ComisionesMediadorEnt;
       this.dt1ComisionesMediadorEsmed = dt1ComisionesMediadorEsmed;
       this.dt1GastosAdminEntAbon = dt1GastosAdminEntAbon;
       this.dt1GastosAdqEntAbon = dt1GastosAdqEntAbon;
       this.dt1ComisionesMediadorAbon = dt1ComisionesMediadorAbon;
       this.dt1ComisMediadorAbonEnt = dt1ComisMediadorAbonEnt;
       this.dt1ComisMediadorAbonEsmed = dt1ComisMediadorAbonEsmed;
       this.dt1GastosAdminEntPdte = dt1GastosAdminEntPdte;
       this.dt1GastosAdqEntPdte = dt1GastosAdqEntPdte;
       this.dt1ComisionesMediadorPdte = dt1ComisionesMediadorPdte;
       this.dt1ComisMediadorPdteEnt = dt1ComisMediadorPdteEnt;
       this.dt1ComisMediadorPdteEsmed = dt1ComisMediadorPdteEsmed;
       this.comisionAplicacionCondicionParticulars = comisionAplicacionCondicionParticulars;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Comision getComision() {
        return this.comision;
    }
    
    public void setComision(Comision comision) {
        this.comision = comision;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public BigDecimal getDc() { 
        return this.dc;
    }
    
    public void setDc(BigDecimal dc) {
        this.dc = dc;
    }
    public Character getTiporeferencia() {
        return this.tiporeferencia;
    }
    
    public void setTiporeferencia(Character tiporeferencia) {
        this.tiporeferencia = tiporeferencia;
    }
    public String getCodinterno() {
        return this.codinterno;
    }
    
    public void setCodinterno(String codinterno) {
        this.codinterno = codinterno;
    }
    public Character getAnuladarefundida() {
        return this.anuladarefundida;
    }
    
    public void setAnuladarefundida(Character anuladarefundida) {
        this.anuladarefundida = anuladarefundida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public BigDecimal getDnPrimabasecalculo() {
        return this.dnPrimabasecalculo;
    }
    
    public void setDnPrimabasecalculo(BigDecimal dnPrimabasecalculo) {
        this.dnPrimabasecalculo = dnPrimabasecalculo;
    }
    public BigDecimal getDnGastosextentidad() {
        return this.dnGastosextentidad;
    }
    
    public void setDnGastosextentidad(BigDecimal dnGastosextentidad) {
        this.dnGastosextentidad = dnGastosextentidad;
    }
    public BigDecimal getDnComisiones() {
        return this.dnComisiones;
    }
    
    public void setDnComisiones(BigDecimal dnComisiones) {
        this.dnComisiones = dnComisiones;
    }
    public BigDecimal getDnTotal() {
        return this.dnTotal;
    }
    
    public void setDnTotal(BigDecimal dnTotal) {
        this.dnTotal = dnTotal;
    }
    public BigDecimal getDrPrimabasecalculo() {
        return this.drPrimabasecalculo;
    }
    
    public void setDrPrimabasecalculo(BigDecimal drPrimabasecalculo) {
        this.drPrimabasecalculo = drPrimabasecalculo;
    }
    public BigDecimal getDrGastosextentidad() {
        return this.drGastosextentidad;
    }
    
    public void setDrGastosextentidad(BigDecimal drGastosextentidad) {
        this.drGastosextentidad = drGastosextentidad;
    }
    public BigDecimal getDrComisiones() {
        return this.drComisiones;
    }
    
    public void setDrComisiones(BigDecimal drComisiones) {
        this.drComisiones = drComisiones;
    }
    public BigDecimal getDrTotal() {
        return this.drTotal;
    }
    
    public void setDrTotal(BigDecimal drTotal) {
        this.drTotal = drTotal;
    }
    public BigDecimal getDtPrimabasecalculo() {
        return this.dtPrimabasecalculo;
    }
    
    public void setDtPrimabasecalculo(BigDecimal dtPrimabasecalculo) {
        this.dtPrimabasecalculo = dtPrimabasecalculo;
    }
    public BigDecimal getDtGastosextentidad() {
        return this.dtGastosextentidad;
    }
    
    public void setDtGastosextentidad(BigDecimal dtGastosextentidad) {
        this.dtGastosextentidad = dtGastosextentidad;
    }
    public BigDecimal getDtComisiones() {
        return this.dtComisiones;
    }
    
    public void setDtComisiones(BigDecimal dtComisiones) {
        this.dtComisiones = dtComisiones;
    }
    public BigDecimal getDtTotal() {
        return this.dtTotal;
    }
    
    public void setDtTotal(BigDecimal dtTotal) {
        this.dtTotal = dtTotal;
    }
    public BigDecimal getDtGastospagados() {
        return this.dtGastospagados;
    }
    
    public void setDtGastospagados(BigDecimal dtGastospagados) {
        this.dtGastospagados = dtGastospagados;
    }
    public BigDecimal getDtGastospendientes() {
        return this.dtGastospendientes;
    }
    
    public void setDtGastospendientes(BigDecimal dtGastospendientes) {
        this.dtGastospendientes = dtGastospendientes;
    }
    public Set<ComisionAplicacionCondicionParticular> getComisionAplicacionCondicionParticulars() {
        return this.comisionAplicacionCondicionParticulars;
    }
    
    public void setComisionAplicacionCondicionParticulars(Set<ComisionAplicacionCondicionParticular> comisionAplicacionCondicionParticulars) {
        this.comisionAplicacionCondicionParticulars = comisionAplicacionCondicionParticulars;
    }


	public BigDecimal getDn1PrimaComercialNeta() {
		return dn1PrimaComercialNeta;
	}


	public void setDn1PrimaComercialNeta(BigDecimal dn1PrimaComercialNeta) {
		this.dn1PrimaComercialNeta = dn1PrimaComercialNeta;
	}


	public BigDecimal getDn1GastosAdminEntidad() {
		return dn1GastosAdminEntidad;
	}


	public void setDn1GastosAdminEntidad(BigDecimal dn1GastosAdminEntidad) {
		this.dn1GastosAdminEntidad = dn1GastosAdminEntidad;
	}


	public BigDecimal getDn1GastosAdqEntidad() {
		return dn1GastosAdqEntidad;
	}


	public void setDn1GastosAdqEntidad(BigDecimal dn1GastosAdqEntidad) {
		this.dn1GastosAdqEntidad = dn1GastosAdqEntidad;
	}


	public BigDecimal getDn1ComisionesMediador() {
		return dn1ComisionesMediador;
	}


	public void setDn1ComisionesMediador(BigDecimal dn1ComisionesMediador) {
		this.dn1ComisionesMediador = dn1ComisionesMediador;
	}


	public BigDecimal getDn1Total() {
		return dn1Total;
	}


	public void setDn1Total(BigDecimal dn1Total) {
		this.dn1Total = dn1Total;
	}


	public BigDecimal getDr1PrimaComercialNeta() {
		return dr1PrimaComercialNeta;
	}


	public void setDr1PrimaComercialNeta(BigDecimal dr1PrimaComercialNeta) {
		this.dr1PrimaComercialNeta = dr1PrimaComercialNeta;
	}


	public BigDecimal getDr1GastosAdminEntidad() {
		return dr1GastosAdminEntidad;
	}


	public void setDr1GastosAdminEntidad(BigDecimal dr1GastosAdminEntidad) {
		this.dr1GastosAdminEntidad = dr1GastosAdminEntidad;
	}


	public BigDecimal getDr1GastosAdqEntidad() {
		return dr1GastosAdqEntidad;
	}


	public void setDr1GastosAdqEntidad(BigDecimal dr1GastosAdqEntidad) {
		this.dr1GastosAdqEntidad = dr1GastosAdqEntidad;
	}


	public BigDecimal getDr1ComisionesMediador() {
		return dr1ComisionesMediador;
	}


	public void setDr1ComisionesMediador(BigDecimal dr1ComisionesMediador) {
		this.dr1ComisionesMediador = dr1ComisionesMediador;
	}


	public BigDecimal getDr1Total() {
		return dr1Total;
	}


	public void setDr1Total(BigDecimal dr1Total) {
		this.dr1Total = dr1Total;
	}


	public BigDecimal getDt1PrimaComercialNeta() {
		return dt1PrimaComercialNeta;
	}


	public void setDt1PrimaComercialNeta(BigDecimal dt1PrimaComercialNeta) {
		this.dt1PrimaComercialNeta = dt1PrimaComercialNeta;
	}


	public BigDecimal getDt1GastosAdminEntidad() {
		return dt1GastosAdminEntidad;
	}


	public void setDt1GastosAdminEntidad(BigDecimal dt1GastosAdminEntidad) {
		this.dt1GastosAdminEntidad = dt1GastosAdminEntidad;
	}


	public BigDecimal getDt1GastosAdqEntidad() {
		return dt1GastosAdqEntidad;
	}


	public void setDt1GastosAdqEntidad(BigDecimal dt1GastosAdqEntidad) {
		this.dt1GastosAdqEntidad = dt1GastosAdqEntidad;
	}


	public BigDecimal getDt1ComisionesMediador() {
		return dt1ComisionesMediador;
	}


	public void setDt1ComisionesMediador(BigDecimal dt1ComisionesMediador) {
		this.dt1ComisionesMediador = dt1ComisionesMediador;
	}


	public BigDecimal getDt1GastosAdminEntAbon() {
		return dt1GastosAdminEntAbon;
	}


	public void setDt1GastosAdminEntAbon(BigDecimal dt1GastosAdminEntAbon) {
		this.dt1GastosAdminEntAbon = dt1GastosAdminEntAbon;
	}


	public BigDecimal getDt1GastosAdqEntAbon() {
		return dt1GastosAdqEntAbon;
	}


	public void setDt1GastosAdqEntAbon(BigDecimal dt1GastosAdqEntAbon) {
		this.dt1GastosAdqEntAbon = dt1GastosAdqEntAbon;
	}


	public BigDecimal getDt1ComisionesMediadorAbon() {
		return dt1ComisionesMediadorAbon;
	}


	public void setDt1ComisionesMediadorAbon(BigDecimal dt1ComisionesMediadorAbon) {
		this.dt1ComisionesMediadorAbon = dt1ComisionesMediadorAbon;
	}


	public BigDecimal getDt1GastosAdminEntPdte() {
		return dt1GastosAdminEntPdte;
	}


	public void setDt1GastosAdminEntPdte(BigDecimal dt1GastosAdminEntPdte) {
		this.dt1GastosAdminEntPdte = dt1GastosAdminEntPdte;
	}


	public BigDecimal getDt1GastosAdqEntPdte() {
		return dt1GastosAdqEntPdte;
	}


	public void setDt1GastosAdqEntPdte(BigDecimal dt1GastosAdqEntPdte) {
		this.dt1GastosAdqEntPdte = dt1GastosAdqEntPdte;
	}


	public BigDecimal getDt1ComisionesMediadorPdte() {
		return dt1ComisionesMediadorPdte;
	}


	public void setDt1ComisionesMediadorPdte(BigDecimal dt1ComisionesMediadorPdte) {
		this.dt1ComisionesMediadorPdte = dt1ComisionesMediadorPdte;
	}


	public BigDecimal getDn1ComisionesMediadorEnt() {
		return dn1ComisionesMediadorEnt;
	}


	public void setDn1ComisionesMediadorEnt(BigDecimal dn1ComisionesMediadorEnt) {
		this.dn1ComisionesMediadorEnt = dn1ComisionesMediadorEnt;
	}


	public BigDecimal getDn1ComisionesMediadorEsmed() {
		return dn1ComisionesMediadorEsmed;
	}


	public void setDn1ComisionesMediadorEsmed(BigDecimal dn1ComisionesMediadorEsmed) {
		this.dn1ComisionesMediadorEsmed = dn1ComisionesMediadorEsmed;
	}


	public BigDecimal getDr1ComisionesMediadorEnt() {
		return dr1ComisionesMediadorEnt;
	}


	public void setDr1ComisionesMediadorEnt(BigDecimal dr1ComisionesMediadorEnt) {
		this.dr1ComisionesMediadorEnt = dr1ComisionesMediadorEnt;
	}


	public BigDecimal getDr1ComisionesMediadorEsmed() {
		return dr1ComisionesMediadorEsmed;
	}


	public void setDr1ComisionesMediadorEsmed(BigDecimal dr1ComisionesMediadorEsmed) {
		this.dr1ComisionesMediadorEsmed = dr1ComisionesMediadorEsmed;
	}


	public BigDecimal getDt1ComisionesMediadorEnt() {
		return dt1ComisionesMediadorEnt;
	}


	public void setDt1ComisionesMediadorEnt(BigDecimal dt1ComisionesMediadorEnt) {
		this.dt1ComisionesMediadorEnt = dt1ComisionesMediadorEnt;
	}


	public BigDecimal getDt1ComisionesMediadorEsmed() {
		return dt1ComisionesMediadorEsmed;
	}


	public void setDt1ComisionesMediadorEsmed(BigDecimal dt1ComisionesMediadorEsmed) {
		this.dt1ComisionesMediadorEsmed = dt1ComisionesMediadorEsmed;
	}


	public BigDecimal getDt1ComisMediadorAbonEnt() {
		return dt1ComisMediadorAbonEnt;
	}


	public void setDt1ComisMediadorAbonEnt(BigDecimal dt1ComisMediadorAbonEnt) {
		this.dt1ComisMediadorAbonEnt = dt1ComisMediadorAbonEnt;
	}


	public BigDecimal getDt1ComisMediadorAbonEsmed() {
		return dt1ComisMediadorAbonEsmed;
	}


	public void setDt1ComisMediadorAbonEsmed(BigDecimal dt1ComisMediadorAbonEsmed) {
		this.dt1ComisMediadorAbonEsmed = dt1ComisMediadorAbonEsmed;
	}


	public BigDecimal getDt1ComisMediadorPdteEnt() {
		return dt1ComisMediadorPdteEnt;
	}


	public void setDt1ComisMediadorPdteEnt(BigDecimal dt1ComisMediadorPdteEnt) {
		this.dt1ComisMediadorPdteEnt = dt1ComisMediadorPdteEnt;
	}


	public BigDecimal getDt1ComisMediadorPdteEsmed() {
		return dt1ComisMediadorPdteEsmed;
	}


	public void setDt1ComisMediadorPdteEsmed(BigDecimal dt1ComisMediadorPdteEsmed) {
		this.dt1ComisMediadorPdteEsmed = dt1ComisMediadorPdteEsmed;
	}




}


