package com.rsi.agp.dao.tables.recibos;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cpl.BonificacionRecargo;
import java.math.BigDecimal;

public class ReciboBonificacionRecargo  implements java.io.Serializable {


     private ReciboBonificacionRecargoId id;
     private ReciboPoliza reciboPoliza;
     private BonificacionRecargo bonificacionRecargo;
     private BigDecimal importe;

    public ReciboBonificacionRecargo() {
    	this.id = new ReciboBonificacionRecargoId();
    }

    public ReciboBonificacionRecargo(ReciboBonificacionRecargoId id, ReciboPoliza reciboPoliza, BonificacionRecargo bonificacionRecargo, BigDecimal importe) {
       this.id = id;
       this.reciboPoliza = reciboPoliza;
       this.bonificacionRecargo = bonificacionRecargo;
       this.importe = importe;
    }
   
    public ReciboBonificacionRecargoId getId() {
        return this.id;
    }
    
    public void setId(ReciboBonificacionRecargoId id) {
        this.id = id;
    }
    public ReciboPoliza getReciboPoliza() {
        return this.reciboPoliza;
    }
    
    public void setReciboPoliza(ReciboPoliza reciboPoliza) {
        this.reciboPoliza = reciboPoliza;
    }
    public BonificacionRecargo getBonificacionRecargo() {
        return this.bonificacionRecargo;
    }
    
    public void setBonificacionRecargo(BonificacionRecargo bonificacionRecargo) {
        this.bonificacionRecargo = bonificacionRecargo;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }




}


