package com.rsi.agp.dao.tables.recibos;
// Generated by T-Systems


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.rsi.agp.dao.tables.cgen.TipificacionRecibos;

public class Recibo  implements java.io.Serializable {


     private Long id;
     private TipificacionRecibos tipificacionRecibos;
     private String codfase;
     private String codplan;
     private Date fecemisionrecibo;
     private Integer codlinea;
     private Integer codrecibo;
     private String codigoentidadaseg;
     private String moroso;
     private String refcolectivo;
     private Integer dccolectivo;
     private String nombretomador;
     private String apell1tomador;
     private String apell2tomador;
     private String razonsocialtomador;
     private String viatomador;
     private String numeroviatomador;
     private String localidadtomador;
     private String cptomador;
     private Integer provinciatomador;
     private String pisotomador;
     private String bloquetomador;
     private String escaleratomador;
     private BigDecimal primacomercial;
     private BigDecimal bonificacion;
     private BigDecimal bonifsistproteccion;
     private BigDecimal recargo;
     private BigDecimal dctocolectivo;
     private BigDecimal dctoventanilla;
     private BigDecimal primaneta;
     private BigDecimal consorcio;
     private BigDecimal clea;
     private BigDecimal costeneto;
     private BigDecimal subvenesa;
     private BigDecimal costetomador;
     private BigDecimal pagos;
     private BigDecimal compensaciontomador;
     private BigDecimal compensacionimpagados;
     private BigDecimal liquido;
     private String deudor;
     private String refpoliza;
     private BigDecimal dcpoliza;
     private Set<ReciboDetCompensacion> reciboDetCompensacions = new HashSet<ReciboDetCompensacion>(0);
     private Set<ReciboPoliza> reciboPolizas = new HashSet<ReciboPoliza>(0);
     private Set<ReciboSubv> reciboSubvs = new HashSet<ReciboSubv>(0);

    public Recibo() {
    	tipificacionRecibos = new TipificacionRecibos();
    }

	
    public Recibo(Long id, String codfase, String codplan,Integer codlinea, Integer codrecibo) {
        this.id = id;
        this.codfase = codfase;
        this.codplan = codplan;
        this.codlinea = codlinea;
        this.codrecibo = codrecibo;
    }
    public Recibo(Long id, TipificacionRecibos tipificacionRecibos, String codfase, String codplan, Date fecemisionrecibo, Integer codlinea, Integer codrecibo, String codigoentidadaseg, String moroso, String refcolectivo, Integer dccolectivo, String nombretomador, String apell1tomador, String apell2tomador, String razonsocialtomador, String viatomador, String numeroviatomador, String localidadtomador, String cptomador, Integer provinciatomador, String pisotomador, String bloquetomador, String escaleratomador, BigDecimal primacomercial, BigDecimal bonificacion, BigDecimal bonifsistproteccion, BigDecimal recargo, BigDecimal dctocolectivo, BigDecimal dctoventanilla, BigDecimal primaneta, BigDecimal consorcio, BigDecimal clea, BigDecimal costeneto, BigDecimal subvenesa, BigDecimal costetomador, BigDecimal pagos, BigDecimal compensaciontomador, BigDecimal compensacionimpagados, BigDecimal liquido, String deudor, String refpoliza, BigDecimal dcpoliza, Set<ReciboDetCompensacion> reciboDetCompensacions, Set<ReciboPoliza> reciboPolizas, Set<ReciboSubv> reciboSubvs) {
       this.id = id;
       this.tipificacionRecibos = tipificacionRecibos;
       this.codfase = codfase;
       this.codplan = codplan;
       this.fecemisionrecibo = fecemisionrecibo;
       this.codlinea = codlinea;
       this.codrecibo = codrecibo;
       this.codigoentidadaseg = codigoentidadaseg;
       this.moroso = moroso;
       this.refcolectivo = refcolectivo;
       this.dccolectivo = dccolectivo;
       this.nombretomador = nombretomador;
       this.apell1tomador = apell1tomador;
       this.apell2tomador = apell2tomador;
       this.razonsocialtomador = razonsocialtomador;
       this.viatomador = viatomador;
       this.numeroviatomador = numeroviatomador;
       this.localidadtomador = localidadtomador;
       this.cptomador = cptomador;
       this.provinciatomador = provinciatomador;
       this.pisotomador = pisotomador;
       this.bloquetomador = bloquetomador;
       this.escaleratomador = escaleratomador;
       this.primacomercial = primacomercial;
       this.bonificacion = bonificacion;
       this.bonifsistproteccion = bonifsistproteccion;
       this.recargo = recargo;
       this.dctocolectivo = dctocolectivo;
       this.dctoventanilla = dctoventanilla;
       this.primaneta = primaneta;
       this.consorcio = consorcio;
       this.clea = clea;
       this.costeneto = costeneto;
       this.subvenesa = subvenesa;
       this.costetomador = costetomador;
       this.pagos = pagos;
       this.compensaciontomador = compensaciontomador;
       this.compensacionimpagados = compensacionimpagados;
       this.liquido = liquido;
       this.deudor = deudor;
       this.refpoliza = refpoliza;
       this.dcpoliza = dcpoliza;
       this.reciboDetCompensacions = reciboDetCompensacions;
       this.reciboPolizas = reciboPolizas;
       this.reciboSubvs = reciboSubvs;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCodfase() {
        return this.codfase;
    }
    
    public void setCodfase(String codfase) {
        this.codfase = codfase;
    }
    public String getCodplan() {
        return this.codplan;
    }
    
    public void setCodplan(String codplan) {
        this.codplan = codplan;
    }
    public Date getFecemisionrecibo() {
        return this.fecemisionrecibo;
    }
    
    public void setFecemisionrecibo(Date fecemisionrecibo) {
        this.fecemisionrecibo = fecemisionrecibo;
    }
    public Integer getCodlinea() {
        return this.codlinea;
    }
    
    public void setCodlinea(Integer codlinea) {
        this.codlinea = codlinea;
    }
    public Integer getCodrecibo() {
        return this.codrecibo;
    }
    
    public void setCodrecibo(Integer codrecibo) {
        this.codrecibo = codrecibo;
    }
    public String getCodigoentidadaseg() {
        return this.codigoentidadaseg;
    }
    
    public void setCodigoentidadaseg(String codigoentidadaseg) {
        this.codigoentidadaseg = codigoentidadaseg;
    }
    public String getMoroso() {
        return this.moroso;
    }
    
    public void setMoroso(String moroso) {
        this.moroso = moroso;
    }
    public String getRefcolectivo() {
        return this.refcolectivo;
    }
    
    public void setRefcolectivo(String refcolectivo) {
        this.refcolectivo = refcolectivo;
    }
    public Integer getDccolectivo() {
        return this.dccolectivo;
    }
    
    public void setDccolectivo(Integer dccolectivo) {
        this.dccolectivo = dccolectivo;
    }
    public String getNombretomador() {
        return this.nombretomador;
    }
    
    public void setNombretomador(String nombretomador) {
        this.nombretomador = nombretomador;
    }
    public String getApell1tomador() {
        return this.apell1tomador;
    }
    
    public void setApell1tomador(String apell1tomador) {
        this.apell1tomador = apell1tomador;
    }
    public String getApell2tomador() {
        return this.apell2tomador;
    }
    
    public void setApell2tomador(String apell2tomador) {
        this.apell2tomador = apell2tomador;
    }
    public String getRazonsocialtomador() {
        return this.razonsocialtomador;
    }
    
    public void setRazonsocialtomador(String razonsocialtomador) {
        this.razonsocialtomador = razonsocialtomador;
    }
    public String getViatomador() {
        return this.viatomador;
    }
    
    public void setViatomador(String viatomador) {
        this.viatomador = viatomador;
    }
    public String getNumeroviatomador() {
        return this.numeroviatomador;
    }
    
    public void setNumeroviatomador(String numeroviatomador) {
        this.numeroviatomador = numeroviatomador;
    }
    public String getLocalidadtomador() {
        return this.localidadtomador;
    }
    
    public void setLocalidadtomador(String localidadtomador) {
        this.localidadtomador = localidadtomador;
    }
    public String getCptomador() {
        return this.cptomador;
    }
    
    public void setCptomador(String cptomador) {
        this.cptomador = cptomador;
    }
    public Integer getProvinciatomador() {
        return this.provinciatomador;
    }
    
    public void setProvinciatomador(Integer provinciatomador) {
        this.provinciatomador = provinciatomador;
    }
    public String getPisotomador() {
        return this.pisotomador;
    }
    
    public void setPisotomador(String pisotomador) {
        this.pisotomador = pisotomador;
    }
    public String getBloquetomador() {
        return this.bloquetomador;
    }
    
    public void setBloquetomador(String bloquetomador) {
        this.bloquetomador = bloquetomador;
    }
    public String getEscaleratomador() {
        return this.escaleratomador;
    }
    
    public void setEscaleratomador(String escaleratomador) {
        this.escaleratomador = escaleratomador;
    }
    public BigDecimal getPrimacomercial() {
        return this.primacomercial;
    }
    
    public void setPrimacomercial(BigDecimal primacomercial) {
        this.primacomercial = primacomercial;
    }
    public BigDecimal getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(BigDecimal bonificacion) {
        this.bonificacion = bonificacion;
    }
    public BigDecimal getBonifsistproteccion() {
        return this.bonifsistproteccion;
    }
    
    public void setBonifsistproteccion(BigDecimal bonifsistproteccion) {
        this.bonifsistproteccion = bonifsistproteccion;
    }
    public BigDecimal getRecargo() {
        return this.recargo;
    }
    
    public void setRecargo(BigDecimal recargo) {
        this.recargo = recargo;
    }
    public BigDecimal getDctocolectivo() {
        return this.dctocolectivo;
    }
    
    public void setDctocolectivo(BigDecimal dctocolectivo) {
        this.dctocolectivo = dctocolectivo;
    }
    public BigDecimal getDctoventanilla() {
        return this.dctoventanilla;
    }
    
    public void setDctoventanilla(BigDecimal dctoventanilla) {
        this.dctoventanilla = dctoventanilla;
    }
    public BigDecimal getPrimaneta() {
        return this.primaneta;
    }
    
    public void setPrimaneta(BigDecimal primaneta) {
        this.primaneta = primaneta;
    }
    public BigDecimal getConsorcio() {
        return this.consorcio;
    }
    
    public void setConsorcio(BigDecimal consorcio) {
        this.consorcio = consorcio;
    }
    public BigDecimal getClea() {
        return this.clea;
    }
    
    public void setClea(BigDecimal clea) {
        this.clea = clea;
    }
    public BigDecimal getCosteneto() {
        return this.costeneto;
    }
    
    public void setCosteneto(BigDecimal costeneto) {
        this.costeneto = costeneto;
    }
    public BigDecimal getSubvenesa() {
        return this.subvenesa;
    }
    
    public void setSubvenesa(BigDecimal subvenesa) {
        this.subvenesa = subvenesa;
    }
    public BigDecimal getCostetomador() {
        return this.costetomador;
    }
    
    public void setCostetomador(BigDecimal costetomador) {
        this.costetomador = costetomador;
    }
    public BigDecimal getPagos() {
        return this.pagos;
    }
    
    public void setPagos(BigDecimal pagos) {
        this.pagos = pagos;
    }
    public BigDecimal getCompensaciontomador() {
        return this.compensaciontomador;
    }
    
    public void setCompensaciontomador(BigDecimal compensaciontomador) {
        this.compensaciontomador = compensaciontomador;
    }
    public BigDecimal getCompensacionimpagados() {
        return this.compensacionimpagados;
    }
    
    public void setCompensacionimpagados(BigDecimal compensacionimpagados) {
        this.compensacionimpagados = compensacionimpagados;
    }
    public BigDecimal getLiquido() {
        return this.liquido;
    }
    
    public void setLiquido(BigDecimal liquido) {
        this.liquido = liquido;
    }
    public String getDeudor() {
        return this.deudor;
    }
    
    public void setDeudor(String deudor) {
        this.deudor = deudor;
    }
    public String getRefpoliza() {
        return this.refpoliza;
    }
    
    public void setRefpoliza(String refpoliza) {
        this.refpoliza = refpoliza;
    }
    public BigDecimal getDcpoliza() {
        return this.dcpoliza;
    }
    
    public void setDcpoliza(BigDecimal dcpoliza) {
        this.dcpoliza = dcpoliza;
    }
    public Set<ReciboDetCompensacion> getReciboDetCompensacions() {
        return this.reciboDetCompensacions;
    }
    
    public void setReciboDetCompensacions(Set<ReciboDetCompensacion> reciboDetCompensacions) {
        this.reciboDetCompensacions = reciboDetCompensacions;
    }
    public Set<ReciboPoliza> getReciboPolizas() {
        return this.reciboPolizas;
    }
    
    public void setReciboPolizas(Set<ReciboPoliza> reciboPolizas) {
        this.reciboPolizas = reciboPolizas;
    }
    public Set<ReciboSubv> getReciboSubvs() {
        return this.reciboSubvs;
    }
    
    public void setReciboSubvs(Set<ReciboSubv> reciboSubvs) {
        this.reciboSubvs = reciboSubvs;
    }


	public TipificacionRecibos getTipificacionRecibos() {
		return tipificacionRecibos;
	}


	public void setTipificacionRecibos(TipificacionRecibos tipificacionRecibos) {
		this.tipificacionRecibos = tipificacionRecibos;
	}


    
    
}


