package com.rsi.agp.dao.tables.comisiones.unificado.informes.cierre;

import java.math.BigDecimal;

// Generated by T-Systems



public class InformeDetMediador2015  implements java.io.Serializable {


	private static final long serialVersionUID = 267219077971097965L;
	private Long id;
    private Integer idcierre;
    private Integer entidad;
    private Integer subentidad;
    private String nomentidad;
    private Integer fase;
    private Integer plan;
    private Integer linea;
    private String nomlinea;
    private String referencia;
    private BigDecimal comisionEnt;
    private BigDecimal comisionEsMed;
    private BigDecimal pdteEnt;
    private BigDecimal pdteEsMed;
    
    public InformeDetMediador2015() {
    }

	
    public InformeDetMediador2015(String nomentidad, Integer fase, Integer plan, String nomlinea, String referencia) {
        this.nomentidad = nomentidad;
        this.fase = fase;
        this.plan = plan;
        this.nomlinea = nomlinea;
        this.referencia = referencia;
    }
    public InformeDetMediador2015(Long id, Integer idcierre, Integer entidad, Integer subentidad, String nomentidad, Integer fase, Integer plan, Integer linea, String nomlinea, String referencia, BigDecimal comisionEnt, BigDecimal comisionEsMed, BigDecimal pdteEnt, BigDecimal pdteEsMed) {
       this.id = id;
       this.idcierre = idcierre;
       this.entidad = entidad;
       this.subentidad = subentidad;
       this.nomentidad = nomentidad;
       this.fase = fase;
       this.plan = plan;
       this.linea = linea;
       this.nomlinea = nomlinea;
       this.referencia = referencia;
       this.comisionEnt = comisionEnt;
       this.comisionEsMed = comisionEsMed;
       this.pdteEnt = pdteEnt;
       this.pdteEsMed = pdteEsMed;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getIdcierre() {
        return this.idcierre;
    }
    
    public void setIdcierre(Integer idcierre) {
        this.idcierre = idcierre;
    }
    public Integer getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Integer entidad) {
        this.entidad = entidad;
    }
    public Integer getSubentidad() {
        return this.subentidad;
    }
    
    public void setSubentidad(Integer subentidad) {
        this.subentidad = subentidad;
    }
    public String getNomentidad() {
        return this.nomentidad;
    }
    
    public void setNomentidad(String nomentidad) {
        this.nomentidad = nomentidad;
    }
    public Integer getFase() {
        return this.fase;
    }
    
    public void setFase(Integer fase) {
        this.fase = fase;
    }
    public Integer getPlan() {
        return this.plan;
    }
    
    public void setPlan(Integer plan) {
        this.plan = plan;
    }
    public Integer getLinea() {
        return this.linea;
    }
    
    public void setLinea(Integer linea) {
        this.linea = linea;
    }
    public String getNomlinea() {
        return this.nomlinea;
    }
    
    public void setNomlinea(String nomlinea) {
        this.nomlinea = nomlinea;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public BigDecimal getComisionEnt() {
        return this.comisionEnt;
    }
    
    public void setComisionEnt(BigDecimal comisionEnt) {
        this.comisionEnt = comisionEnt;
    }
    public BigDecimal getComisionEsMed() {
        return this.comisionEsMed;
    }
    
    public void setComisionEsMed(BigDecimal comisionEsMed) {
        this.comisionEsMed = comisionEsMed;
    }
    public BigDecimal getPdteEnt() {
        return this.pdteEnt;
    }
    
    public void setPdteEnt(BigDecimal pdteEnt) {
        this.pdteEnt = pdteEnt;
    }
    public BigDecimal getPdteEsMed() {
        return this.pdteEsMed;
    }
    
    public void setPdteEsMed(BigDecimal pdteEsMed) {
        this.pdteEsMed = pdteEsMed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InformeDetMediador2015) ) return false;
		 InformeDetMediador2015 castOther = ( InformeDetMediador2015 ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIdcierre()==castOther.getIdcierre()) || ( this.getIdcierre()!=null && castOther.getIdcierre()!=null && this.getIdcierre().equals(castOther.getIdcierre()) ) )
 && ( (this.getEntidad()==castOther.getEntidad()) || ( this.getEntidad()!=null && castOther.getEntidad()!=null && this.getEntidad().equals(castOther.getEntidad()) ) )
 && ( (this.getSubentidad()==castOther.getSubentidad()) || ( this.getSubentidad()!=null && castOther.getSubentidad()!=null && this.getSubentidad().equals(castOther.getSubentidad()) ) )
 && ( (this.getNomentidad()==castOther.getNomentidad()) || ( this.getNomentidad()!=null && castOther.getNomentidad()!=null && this.getNomentidad().equals(castOther.getNomentidad()) ) )
 && ( (this.getFase()==castOther.getFase()) || ( this.getFase()!=null && castOther.getFase()!=null && this.getFase().equals(castOther.getFase()) ) )
 && ( (this.getPlan()==castOther.getPlan()) || ( this.getPlan()!=null && castOther.getPlan()!=null && this.getPlan().equals(castOther.getPlan()) ) )
 && ( (this.getLinea()==castOther.getLinea()) || ( this.getLinea()!=null && castOther.getLinea()!=null && this.getLinea().equals(castOther.getLinea()) ) )
 && ( (this.getNomlinea()==castOther.getNomlinea()) || ( this.getNomlinea()!=null && castOther.getNomlinea()!=null && this.getNomlinea().equals(castOther.getNomlinea()) ) )
 && ( (this.getReferencia()==castOther.getReferencia()) || ( this.getReferencia()!=null && castOther.getReferencia()!=null && this.getReferencia().equals(castOther.getReferencia()) ) )
 && ( (this.getComisionEnt()==castOther.getComisionEnt()) || ( this.getComisionEnt()!=null && castOther.getComisionEnt()!=null && this.getComisionEnt().equals(castOther.getComisionEnt()) ) )
 && ( (this.getComisionEsMed()==castOther.getComisionEsMed()) || ( this.getComisionEsMed()!=null && castOther.getComisionEsMed()!=null && this.getComisionEsMed().equals(castOther.getComisionEsMed()) ) )
 && ( (this.getPdteEnt()==castOther.getPdteEnt()) || ( this.getPdteEnt()!=null && castOther.getPdteEnt()!=null && this.getPdteEnt().equals(castOther.getPdteEnt()) ) )
 && ( (this.getPdteEsMed()==castOther.getPdteEsMed()) || ( this.getPdteEsMed()!=null && castOther.getPdteEsMed()!=null && this.getPdteEsMed().equals(castOther.getPdteEsMed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIdcierre() == null ? 0 : this.getIdcierre().hashCode() );
         result = 37 * result + ( getEntidad() == null ? 0 : this.getEntidad().hashCode() );
         result = 37 * result + ( getSubentidad() == null ? 0 : this.getSubentidad().hashCode() );
         result = 37 * result + ( getNomentidad() == null ? 0 : this.getNomentidad().hashCode() );
         result = 37 * result + ( getFase() == null ? 0 : this.getFase().hashCode() );
         result = 37 * result + ( getPlan() == null ? 0 : this.getPlan().hashCode() );
         result = 37 * result + ( getLinea() == null ? 0 : this.getLinea().hashCode() );
         result = 37 * result + ( getNomlinea() == null ? 0 : this.getNomlinea().hashCode() );
         result = 37 * result + ( getReferencia() == null ? 0 : this.getReferencia().hashCode() );
         result = 37 * result + ( getComisionEnt() == null ? 0 : this.getComisionEnt().hashCode() );
         result = 37 * result + ( getComisionEsMed() == null ? 0 : this.getComisionEsMed().hashCode() );
         result = 37 * result + ( getPdteEnt() == null ? 0 : this.getPdteEnt().hashCode() );
         result = 37 * result + ( getPdteEsMed() == null ? 0 : this.getPdteEsMed().hashCode() );
         return result;
   }   


}











