package com.rsi.agp.dao.tables.reduccionCap;
// Generated by T-Systems

import java.sql.Clob;
import java.util.Date;

public class AnexoRCSWComparativas implements java.io.Serializable {

	private static final long serialVersionUID = -8069575048331099246L;

	private long id;
	private ReduccionCapital reduccionCapital;
	private String codusuario;
	private Date fecha;
	private transient Clob envioPlz;
	private transient Clob respuestaPlz;
	private transient Clob envioAnexo;
	private transient Clob respuestaAnexo;

	public AnexoRCSWComparativas() {
		super();
	}

	public AnexoRCSWComparativas(ReduccionCapital reduccionCapital, String codusuario, Date fecha) {
		this();
		this.reduccionCapital = reduccionCapital;
		this.codusuario = codusuario;
		this.fecha = fecha;
	}

	public AnexoRCSWComparativas(long id, ReduccionCapital reduccionCapital, String codusuario, Date fecha) {
		this(reduccionCapital, codusuario, fecha);
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ReduccionCapital getReduccionCapital() {
		return this.reduccionCapital;
	}

	public void setReduccionCapital(ReduccionCapital reduccionCapital) {
		this.reduccionCapital = reduccionCapital;
	}

	public String getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(String codusuario) {
		this.codusuario = codusuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Clob getEnvioPlz() {
		return this.envioPlz;
	}

	public void setEnvioPlz(Clob envioPlz) {
		this.envioPlz = envioPlz;
	}

	public Clob getRespuestaPlz() {
		return this.respuestaPlz;
	}

	public void setRespuestaPlz(Clob respuestaPlz) {
		this.respuestaPlz = respuestaPlz;
	}

	public Clob getEnvioAnexo() {
		return this.envioAnexo;
	}

	public void setEnvioAnexo(Clob envioAnexo) {
		this.envioAnexo = envioAnexo;
	}

	public Clob getRespuestaAnexo() {
		return this.respuestaAnexo;
	}

	public void setRespuestaAnexo(Clob respuestaAnexo) {
		this.respuestaAnexo = respuestaAnexo;
	}
}