package com.rsi.agp.dao.tables.reduccionCap;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class EstadoCuponRC  implements java.io.Serializable {


     private Long id;
     private String estado;
     private Set<CuponRC> cupons = new HashSet<CuponRC>(0);

    public EstadoCuponRC() {
    }

	
    public EstadoCuponRC(Long id, String estado) {
        this.id = id;
        this.estado = estado;
    }
    public EstadoCuponRC(Long id, String estado, Set<CuponRC> cupons) {
       this.id = id;
       this.estado = estado;
       this.cupons = cupons;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<CuponRC> getCupons() {
        return this.cupons;
    }
    
    public void setCupons(Set<CuponRC> cupons) {
        this.cupons = cupons;
    }




}


