package com.rsi.agp.dao.tables.reduccionCap;
// Generated by T-Systems

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.rsi.agp.dao.tables.inc.EstadosInc;
import com.rsi.agp.dao.tables.poliza.Comunicaciones;
import com.rsi.agp.dao.tables.poliza.Poliza;

public class ReduccionCapital implements java.io.Serializable {

	private static final long serialVersionUID = -51602062492899377L;

	private Long id;
	
	private Estado estado;
	private Poliza poliza;
	private Long idCopy;
	private BigDecimal idenvio;
	private Date fechadanios;
	private String codmotivoriesgo;
	private String motivo;
	private transient Clob xml;
	private BigDecimal numAnexo;
	private Date fechaenvio;
	private String usuarioAlta;
	private Date fechaAlta;
	private String usuarioDefinitiva;
	private Date fechaDefinitiva;
	private Set<Parcela> parcelas = new HashSet<Parcela>(0);
	private Date fechafirma;
	private String codModulo;
	// DNF 27/06/2019 P0061431
	
	//P0079361
	private CuponRC cupon;
	private Date fechaEnvioAnexo;
	private EstadosInc estadoAgroseguro;
	private Comunicaciones comunicaciones;
	private Set<EnviosSWConfirmacionRC> enviosSWConfirmacions = new HashSet<EnviosSWConfirmacionRC>(0);
	private Set<RedCapitalSWCalculo> redCapitalSWCalculos = new HashSet<RedCapitalSWCalculo>(0);
	private Set<RedCapitalDistribucionCostes> redCapitalDistribucionCostes = new HashSet<RedCapitalDistribucionCostes>(0);
	//P0079361
	
	public ReduccionCapital() {
		super();
		poliza = new Poliza();
		comunicaciones = new Comunicaciones();
		estado = new Estado();
		//P0079361 dudas por null bbdd
		cupon = new CuponRC();
		//P0079361 prueba fec envio
		//comunicaciones = new Comunicaciones();
		//P0079361 prueba fec envio
		//P0079361 dudas por null bbdd
	}

	public ReduccionCapital(Long id, Estado estado, Poliza poliza, Date fechafirma, Date fechadanios) {
		this();
		this.id = id;
		this.estado = estado;
		this.poliza = poliza;
		this.fechafirma = fechafirma;
		this.fechadanios = fechadanios;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Poliza getPoliza() {
		return this.poliza;
	}

	public void setPoliza(Poliza poliza) {
		this.poliza = poliza;
	}

	public BigDecimal getIdenvio() {
		return this.idenvio;
	}

	public void setIdenvio(BigDecimal idenvio) {
		this.idenvio = idenvio;
	}

	public Date getFechafirma() {
		return this.fechafirma;
	}

	public void setFechafirma(Date fechafirma) {
		this.fechafirma = fechafirma;
	}

	public Date getFechadanios() {
		return this.fechadanios;
	}

	public void setFechadanios(Date fechadanios) {
		this.fechadanios = fechadanios;
	}

	public String getCodmotivoriesgo() {
		return this.codmotivoriesgo;
	}

	public void setCodmotivoriesgo(String codmotivoriesgo) {
		this.codmotivoriesgo = codmotivoriesgo;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public Clob getXml() {
		return this.xml;
	}

	public void setXml(Clob xml) {
		this.xml = xml;
	}

	public Set<Parcela> getParcelas() {
		return this.parcelas;
	}

	public void setParcelas(Set<Parcela> parcelas) {
		this.parcelas = parcelas;
	}

	public Long getIdCopy() {
		return idCopy;
	}

	public void setIdCopy(Long idCopy) {
		this.idCopy = idCopy;
	}

	public BigDecimal getNumAnexo() {
		return numAnexo;
	}

	public void setNumAnexo(BigDecimal numAnexo) {
		this.numAnexo = numAnexo;
	}

	public Date getFechaenvio() {
		return fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	public String getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(String usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getUsuarioDefinitiva() {
		return this.usuarioDefinitiva;
	}

	public void setUsuarioDefinitiva(String usuarioDefinitiva) {
		this.usuarioDefinitiva = usuarioDefinitiva;
	}

	public Date getFechaDefinitiva() {
		return this.fechaDefinitiva;
	}

	public void setFechaDefinitiva(Date fechaDefinitiva) {
		this.fechaDefinitiva = fechaDefinitiva;
	}

	// DNF 27/06/2019 P0061431
	public String getCodModulo() {
		return codModulo;
	}

	public void setCodModulo(String codModulo) {
		this.codModulo = codModulo;
	}

	
	//P0079361
	public CuponRC getCupon() {
		return cupon;
	}

	public void setCupon(CuponRC cupon) {
		this.cupon = cupon;
	}

	public Date getFechaEnvioAnexo() {
		return fechaEnvioAnexo;
	}

	public void setFechaEnvioAnexo(Date fechaEnvioAnexo) {
		this.fechaEnvioAnexo = fechaEnvioAnexo;
	}

	public EstadosInc getEstadoAgroseguro() {
		return estadoAgroseguro;
	}
	
	public Comunicaciones getComunicaciones() {
		return comunicaciones;
	}

	public void setComunicaciones(Comunicaciones comunicaciones) {
		this.comunicaciones = comunicaciones;
	}

	public void setEstadoAgroseguro(EstadosInc estadoAgroseguro) {
		this.estadoAgroseguro = estadoAgroseguro;
	}

	public Set<EnviosSWConfirmacionRC> getEnviosSWConfirmacions() {
		return enviosSWConfirmacions;
	}

	public void setEnviosSWConfirmacions(Set<EnviosSWConfirmacionRC> enviosSWConfirmacions) {
		this.enviosSWConfirmacions = enviosSWConfirmacions;
	}

	public Set<RedCapitalSWCalculo> getRedCapitalSWCalculos() {
		return redCapitalSWCalculos;
	}

	public void setRedCapitalSWCalculos(Set<RedCapitalSWCalculo> redCapitalSWCalculos) {
		this.redCapitalSWCalculos = redCapitalSWCalculos;
	}

	public Set<RedCapitalDistribucionCostes> getRedCapitalDistribucionCostes() {
		return redCapitalDistribucionCostes;
	}

	public void setRedCapitalDistribucionCostes(Set<RedCapitalDistribucionCostes> redCapitalDistribucionCostes) {
		this.redCapitalDistribucionCostes = redCapitalDistribucionCostes;
	}
	//P0079361
	public String toDebugString() {
		String estadoId = (estado != null &&  estado.getIdestado() != null) ? estado.getIdestado().toString() : "N/A";
		String estadoDesc = (estado != null && estado.getDescestado() != null) ? estado.getDescestado() : "N/A";
		
		return "RedcucionCapital [id=" + id + ", estado=" + estadoId + "/" + estadoDesc +"]";
	}
}
