package com.rsi.agp.dao.tables.inc;

// Generated by T-Systems

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class TiposDocInc implements java.io.Serializable {

	private static final long serialVersionUID = 554037838998590192L;

	private BigDecimal iddoctipo;
	private String extension;
	private String mimeType;
	private Set<DocumentosInc> documentosIncs = new HashSet<DocumentosInc>(0);

	public TiposDocInc() {
	}

	public TiposDocInc(BigDecimal iddoctipo, String extension, String mimeType) {
		this.iddoctipo = iddoctipo;
		this.extension = extension;
		this.mimeType = mimeType;
	}

	public TiposDocInc(BigDecimal iddoctipo, String extension, String mimeType,
			Set<DocumentosInc> documentosIncs) {
		this.iddoctipo = iddoctipo;
		this.extension = extension;
		this.mimeType = mimeType;
		this.documentosIncs = documentosIncs;
	}

	public BigDecimal getIddoctipo() {
		return this.iddoctipo;
	}

	public void setIddoctipo(BigDecimal iddoctipo) {
		this.iddoctipo = iddoctipo;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public Set<DocumentosInc> getDocumentosIncs() {
		return this.documentosIncs;
	}

	public void setDocumentosIncs(Set<DocumentosInc> documentosIncs) {
		this.documentosIncs = documentosIncs;
	}

}
