package com.rsi.agp.dao.tables.cvs;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

// Generated by T-Systems

public class CvsCapAseg implements java.io.Serializable {

	private static final long serialVersionUID = 8159832803855121349L;

	private CvsCapAsegId id;
	private CvsParcela cvsParcela;
	private CvsAsegurado cvsAsegurado;
	private BigDecimal superficie;
	private Long produccion;
	private BigDecimal precio;
	private Set<CvsDatoVariable> cvsDatoVariables = new HashSet<CvsDatoVariable>(0);

	public CvsCapAseg() {
	}

	public CvsCapAseg(CvsCapAsegId id, CvsParcela cvsParcela, CvsAsegurado cvsAsegurado) {
		this.id = id;
		this.cvsParcela = cvsParcela;
		this.cvsAsegurado = cvsAsegurado;
	}

	public CvsCapAseg(CvsCapAsegId id, CvsParcela cvsParcela, CvsAsegurado cvsAsegurado, BigDecimal superficie,
			Long produccion, Set<CvsDatoVariable> cvsDatoVariables) {
		this.id = id;
		this.cvsParcela = cvsParcela;
		this.cvsAsegurado = cvsAsegurado;
		this.superficie = superficie;
		this.produccion = produccion;
		this.cvsDatoVariables = cvsDatoVariables;
	}

	public CvsCapAsegId getId() {
		return this.id;
	}

	public void setId(CvsCapAsegId id) {
		this.id = id;
	}

	public BigDecimal getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(BigDecimal superficie) {
		this.superficie = superficie;
	}

	public Long getProduccion() {
		return this.produccion;
	}

	public void setProduccion(Long produccion) {
		this.produccion = produccion;
	}

	public CvsParcela getCvsParcela() {
		return cvsParcela;
	}

	public void setCvsParcela(CvsParcela cvsParcela) {
		this.cvsParcela = cvsParcela;
	}

	public CvsAsegurado getCvsAsegurado() {
		return cvsAsegurado;
	}

	public void setCvsAsegurado(CvsAsegurado cvsAsegurado) {
		this.cvsAsegurado = cvsAsegurado;
	}

	public BigDecimal getPrecio() {
		return precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Set<CvsDatoVariable> getCvsDatoVariables() {
		return cvsDatoVariables;
	}

	public void setCvsDatoVariables(Set<CvsDatoVariable> cvsDatoVariables) {
		this.cvsDatoVariables = cvsDatoVariables;
	}

}
