package com.rsi.agp.dao.tables.cvs;
// Generated by T-Systems

public class CvsCapAsegId implements java.io.Serializable {

	private static final long serialVersionUID = 6445495858396338296L;

	private Long idCvsParcela;
	private Long idCvsAseg;
	private Integer codtipocapital;

	public CvsCapAsegId() {
	}

	public CvsCapAsegId(Long idCvsParcela, Long idCvsAseg, Integer codtipocapital) {
		this.idCvsParcela = idCvsParcela;
		this.idCvsAseg = idCvsAseg;
		this.codtipocapital = codtipocapital;
	}

	public Long getIdCvsParcela() {
		return idCvsParcela;
	}

	public void setIdCvsParcela(Long idCvsParcela) {
		this.idCvsParcela = idCvsParcela;
	}

	public Long getIdCvsAseg() {
		return idCvsAseg;
	}

	public void setIdCvsAseg(Long idCvsAseg) {
		this.idCvsAseg = idCvsAseg;
	}

	public Integer getCodtipocapital() {
		return codtipocapital;
	}

	public void setCodtipocapital(Integer codtipocapital) {
		this.codtipocapital = codtipocapital;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CvsCapAsegId))
			return false;
		CvsCapAsegId castOther = (CvsCapAsegId) other;

		return (this.getIdCvsParcela() == castOther.getIdCvsParcela())
				&& (this.getIdCvsAseg() == castOther.getIdCvsAseg())
				&& (this.getCodtipocapital() == castOther.getCodtipocapital());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCvsParcela() == null ? 0 : this.getIdCvsParcela().hashCode());
		result = 37 * result + (getIdCvsAseg() == null ? 0 : this.getIdCvsAseg().hashCode());
		result = 37 * result + (getCodtipocapital() == null ? 0 : this.getCodtipocapital().hashCode());
		return result;
	}
}
