package com.rsi.agp.dao.tables.cesp;
// Generated by T-Systems


import java.math.BigDecimal;

import com.rsi.agp.dao.tables.cpl.Modulo;
import com.rsi.agp.dao.tables.cpl.RiesgoCubierto;
import com.rsi.agp.dao.tables.poliza.Linea;

public class ModuloCompatibleCe  implements java.io.Serializable {


     private Long id;
     
     private RiesgoCubierto riesgoCubierto;
     private Modulo moduloComplementario;
     private Modulo moduloPrincipal;
     private Linea linea;

    public ModuloCompatibleCe() {
    
    	riesgoCubierto = new RiesgoCubierto();
    	moduloComplementario = new Modulo();
    	moduloPrincipal = new Modulo();
    	linea = new Linea();
    }

    public ModuloCompatibleCe(Long id, RiesgoCubierto riesgoCubierto, Modulo moduloByFkModCompatModuloComp, Modulo moduloByFkModulosCompatModulos, Linea linea) {
        this.id = id;
        this.riesgoCubierto = riesgoCubierto;
        this.moduloComplementario = moduloByFkModCompatModuloComp;
        this.moduloPrincipal = moduloByFkModulosCompatModulos;
        this.linea = linea;
     }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public RiesgoCubierto getRiesgoCubierto() {
        return this.riesgoCubierto;
    }
    
    public void setRiesgoCubierto(RiesgoCubierto riesgoCubierto) {
        this.riesgoCubierto = riesgoCubierto;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }

	public Modulo getModuloComplementario() {
		return moduloComplementario;
	}

	public void setModuloComplementario(Modulo moduloComplementario) {
		this.moduloComplementario = moduloComplementario;
	}

	public Modulo getModuloPrincipal() {
		return moduloPrincipal;
	}

	public void setModuloPrincipal(Modulo moduloPrincipal) {
		this.moduloPrincipal = moduloPrincipal;
	}




}


