package com.rsi.agp.dao.tables.poliza.dc2015;
// Generated by T-Systems

import java.math.BigDecimal;

public class DistCosteParcela2015BonifRec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 330547424105588726L;
	private Long id;
	private DistCosteParcela2015 distCosteParcela2015;
	private BigDecimal codigo;
	private BigDecimal importe;
	private Character tipoBonif;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public DistCosteParcela2015 getDistCosteParcela2015() {
		return distCosteParcela2015;
	}
	public void setDistCosteParcela2015(DistCosteParcela2015 distCosteParcela2015) {
		this.distCosteParcela2015 = distCosteParcela2015;
	}
	public BigDecimal getCodigo() {
		return codigo;
	}
	public void setCodigo(BigDecimal codigo) {
		this.codigo = codigo;
	}
	public BigDecimal getImporte() {
		return importe;
	}
	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}
	public Character getTipoBonif() {
		return tipoBonif;
	}
	public void setTipoBonif(Character tipoBonif) {
		this.tipoBonif = tipoBonif;
	}
	




}
