package com.rsi.agp.dao.tables.poliza.dc2015;
// Generated by T-Systems

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class DistCosteExplotaciones implements java.io.Serializable {

	private static final long serialVersionUID = -2783922781193845688L;
	private Long id;
	private DistribucionCoste2015 distribucionCoste2015;
	private Integer numexplotacion;
	private Integer gruporaza;
	private Integer tipocapital;
	private Integer tipoanimal;
	private BigDecimal tasacomercialbase;
	private BigDecimal tasacomercial;
	private Character gruponegocio;
	private BigDecimal costetomador;
	private BigDecimal primacomercial;
	private BigDecimal primacomercialneta;
	private BigDecimal recargoconsorcio;
	private BigDecimal reciboprima;

	private Set<DistCosteExplotacionesGrupoNegocio> distCosteGns = new HashSet<DistCosteExplotacionesGrupoNegocio>(0);
	private Set<DistCosteExplotacionesSubvencion> distCosteSubvs = new HashSet<DistCosteExplotacionesSubvencion>(0);
	private Set<DistCosteExplotacionesBonifRec> distCosteBonifRecs = new HashSet<DistCosteExplotacionesBonifRec>(0);

	public DistCosteExplotaciones() {
	}

	public DistCosteExplotaciones(Long id, DistribucionCoste2015 distribucionCoste2015, Integer numexplotacion,
			Integer gruporaza, Integer tipocapital, Integer tipoanimal) {
		this.id = id;
		this.distribucionCoste2015 = distribucionCoste2015;
		this.numexplotacion = numexplotacion;
		this.gruporaza = gruporaza;
		this.tipocapital = tipocapital;
		this.tipoanimal = tipoanimal;
	}

	public DistCosteExplotaciones(Long id, DistribucionCoste2015 distribucionCoste2015, Integer numexplotacion,
			Integer gruporaza, Integer tipocapital, Integer tipoanimal, BigDecimal tasacomercialbase,
			BigDecimal tasacomercial, Character gruponegocio, BigDecimal costetomador, BigDecimal primacomercial,
			BigDecimal primacomercialneta, BigDecimal recargoconsorcio, BigDecimal reciboprima) {
		this.id = id;
		this.distribucionCoste2015 = distribucionCoste2015;
		this.numexplotacion = numexplotacion;
		this.gruporaza = gruporaza;
		this.tipocapital = tipocapital;
		this.tipoanimal = tipoanimal;
		this.tasacomercialbase = tasacomercialbase;
		this.tasacomercial = tasacomercial;
		this.gruponegocio = gruponegocio;
		this.costetomador = costetomador;
		this.primacomercial = primacomercial;
		this.primacomercialneta = primacomercialneta;
		this.recargoconsorcio = recargoconsorcio;
		this.reciboprima = reciboprima;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DistribucionCoste2015 getDistribucionCoste2015() {
		return this.distribucionCoste2015;
	}

	public void setDistribucionCoste2015(DistribucionCoste2015 distribucionCoste2015) {
		this.distribucionCoste2015 = distribucionCoste2015;
	}

	public Integer getNumexplotacion() {
		return this.numexplotacion;
	}

	public void setNumexplotacion(Integer numexplotacion) {
		this.numexplotacion = numexplotacion;
	}

	public Integer getGruporaza() {
		return this.gruporaza;
	}

	public void setGruporaza(Integer gruporaza) {
		this.gruporaza = gruporaza;
	}

	public Integer getTipocapital() {
		return this.tipocapital;
	}

	public void setTipocapital(Integer tipocapital) {
		this.tipocapital = tipocapital;
	}

	public Integer getTipoanimal() {
		return this.tipoanimal;
	}

	public void setTipoanimal(Integer tipoanimal) {
		this.tipoanimal = tipoanimal;
	}

	public BigDecimal getTasacomercialbase() {
		return this.tasacomercialbase;
	}

	public void setTasacomercialbase(BigDecimal tasacomercialbase) {
		this.tasacomercialbase = tasacomercialbase;
	}

	public BigDecimal getTasacomercial() {
		return this.tasacomercial;
	}

	public void setTasacomercial(BigDecimal tasacomercial) {
		this.tasacomercial = tasacomercial;
	}

	public Character getGruponegocio() {
		return this.gruponegocio;
	}

	public void setGruponegocio(Character gruponegocio) {
		this.gruponegocio = gruponegocio;
	}

	public BigDecimal getCostetomador() {
		return this.costetomador;
	}

	public void setCostetomador(BigDecimal costetomador) {
		this.costetomador = costetomador;
	}

	public BigDecimal getPrimacomercial() {
		return primacomercial;
	}

	public void setPrimacomercial(BigDecimal primacomercial) {
		this.primacomercial = primacomercial;
	}

	public BigDecimal getPrimacomercialneta() {
		return primacomercialneta;
	}

	public void setPrimacomercialneta(BigDecimal primacomercialneta) {
		this.primacomercialneta = primacomercialneta;
	}

	public BigDecimal getRecargoconsorcio() {
		return recargoconsorcio;
	}

	public void setRecargoconsorcio(BigDecimal recargoconsorcio) {
		this.recargoconsorcio = recargoconsorcio;
	}

	public BigDecimal getReciboprima() {
		return reciboprima;
	}

	public void setReciboprima(BigDecimal reciboprima) {
		this.reciboprima = reciboprima;
	}

	public Set<DistCosteExplotacionesGrupoNegocio> getDistCosteGns() {
		return distCosteGns;
	}

	public void setDistCosteGns(Set<DistCosteExplotacionesGrupoNegocio> distCosteGns) {
		this.distCosteGns = distCosteGns;
	}

	public Set<DistCosteExplotacionesSubvencion> getDistCosteSubvs() {
		return distCosteSubvs;
	}

	public void setDistCosteSubvs(Set<DistCosteExplotacionesSubvencion> distCosteSubvs) {
		this.distCosteSubvs = distCosteSubvs;
	}

	public Set<DistCosteExplotacionesBonifRec> getDistCosteBonifRecs() {
		return distCosteBonifRecs;
	}

	public void setDistCosteBonifRecs(Set<DistCosteExplotacionesBonifRec> distCosteBonifRecs) {
		this.distCosteBonifRecs = distCosteBonifRecs;
	}
}