package com.rsi.agp.dao.tables.poliza.dc2015;
// Generated by T-Systems

import java.math.BigDecimal;

public class DistCosteParcela2015GrupoNegocio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8497121119269593416L;
	private Long id;
	private DistCosteParcela2015 distCosteParcela2015;
	private Character gruponegocio;
	private BigDecimal primacomercial;
	private BigDecimal primacomercialneta;
	private BigDecimal recargoconsorcio;
	private BigDecimal reciboprima;
	private BigDecimal costetomador;
	public BigDecimal getCostetomador() {
		return costetomador;
	}
	public void setCostetomador(BigDecimal costetomador) {
		this.costetomador = costetomador;
	}
	public BigDecimal getReciboprima() {
		return reciboprima;
	}
	public void setReciboprima(BigDecimal reciboprima) {
		this.reciboprima = reciboprima;
	}
	public BigDecimal getRecargoconsorcio() {
		return recargoconsorcio;
	}
	public void setRecargoconsorcio(BigDecimal recargoconsorcio) {
		this.recargoconsorcio = recargoconsorcio;
	}
	public BigDecimal getPrimacomercialneta() {
		return primacomercialneta;
	}
	public void setPrimacomercialneta(BigDecimal primacomercialneta) {
		this.primacomercialneta = primacomercialneta;
	}
	public BigDecimal getPrimacomercial() {
		return primacomercial;
	}
	public void setPrimacomercial(BigDecimal primacomercial) {
		this.primacomercial = primacomercial;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public DistCosteParcela2015 getDistCosteParcela2015() {
		return distCosteParcela2015;
	}
	public void setDistCosteParcela2015(DistCosteParcela2015 distCosteParcela2015) {
		this.distCosteParcela2015 = distCosteParcela2015;
	}
	public Character getGruponegocio() {
		return gruponegocio;
	}
	public void setGruponegocio(Character gruponegocio) {
		this.gruponegocio = gruponegocio;
	}

//Character


}
