package com.rsi.agp.dao.tables.orgDat;
// Generated by T-Systems

import java.math.BigDecimal;

public class VistaSistemaCultivoId implements java.io.Serializable {

	private static final long serialVersionUID = 295128329356420477L;

	private BigDecimal lineaseguroid;
	private String codmodulo;
	private BigDecimal codcultivo;
	private BigDecimal codvariedad;
	private BigDecimal codsistemacultivo;
	private String dessistemacultivo;

	public VistaSistemaCultivoId() {
	}

	public VistaSistemaCultivoId(BigDecimal lineaseguroid, String codmodulo, BigDecimal codcultivo,
			BigDecimal codvariedad, BigDecimal codsistemacultivo, String dessistemacultivo) {
		this.lineaseguroid = lineaseguroid;
		this.codmodulo = codmodulo;
		this.codcultivo = codcultivo;
		this.codvariedad = codvariedad;
		this.codsistemacultivo = codsistemacultivo;
		this.dessistemacultivo = dessistemacultivo;

	}

	public BigDecimal getLineaseguroid() {
		return this.lineaseguroid;
	}

	public void setLineaseguroid(BigDecimal lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	public String getCodmodulo() {
		return this.codmodulo;
	}

	public void setCodmodulo(String codmodulo) {
		this.codmodulo = codmodulo;
	}

	public BigDecimal getCodcultivo() {
		return this.codcultivo;
	}

	public void setCodcultivo(BigDecimal codcultivo) {
		this.codcultivo = codcultivo;
	}

	public BigDecimal getCodvariedad() {
		return this.codvariedad;
	}

	public void setCodvariedad(BigDecimal codvariedad) {
		this.codvariedad = codvariedad;
	}

	public BigDecimal getCodsistemacultivo() {
		return this.codsistemacultivo;
	}

	public void setCodsistemacultivo(BigDecimal codsistemacultivo) {
		this.codsistemacultivo = codsistemacultivo;
	}

	public String getDessistemacultivo() {
		return this.dessistemacultivo;
	}

	public void setDessistemacultivo(String dessistemacultivo) {
		this.dessistemacultivo = dessistemacultivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaSistemaCultivoId))
			return false;
		VistaSistemaCultivoId castOther = (VistaSistemaCultivoId) other;

		return ((this.getLineaseguroid() == castOther.getLineaseguroid())
				|| (this.getLineaseguroid() != null && castOther.getLineaseguroid() != null
						&& this.getLineaseguroid().equals(castOther.getLineaseguroid())))
				&& ((this.getCodmodulo() == castOther.getCodmodulo()) || (this.getCodmodulo() != null
						&& castOther.getCodmodulo() != null && this.getCodmodulo().equals(castOther.getCodmodulo())))
				&& ((this.getCodcultivo() == castOther.getCodcultivo()) || (this.getCodcultivo() != null
						&& castOther.getCodcultivo() != null && this.getCodcultivo().equals(castOther.getCodcultivo())))
				&& ((this.getCodvariedad() == castOther.getCodvariedad())
						|| (this.getCodvariedad() != null && castOther.getCodvariedad() != null
								&& this.getCodvariedad().equals(castOther.getCodvariedad())))
				&& ((this.getCodsistemacultivo() == castOther.getCodsistemacultivo())
						|| (this.getCodsistemacultivo() != null && castOther.getCodsistemacultivo() != null
								&& this.getCodsistemacultivo().equals(castOther.getCodsistemacultivo())))
				&& ((this.getDessistemacultivo() != null && castOther.getDessistemacultivo() != null
						&& this.getDessistemacultivo().equals(castOther.getDessistemacultivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode());
		result = 37 * result + (getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode());
		result = 37 * result + (getCodcultivo() == null ? 0 : this.getCodcultivo().hashCode());
		result = 37 * result + (getCodvariedad() == null ? 0 : this.getCodvariedad().hashCode());
		result = 37 * result + (getCodsistemacultivo() == null ? 0 : this.getCodsistemacultivo().hashCode());
		result = 37 * result + (getDessistemacultivo() == null ? 0 : this.getDessistemacultivo().hashCode());
		return result;
	}

}
