package com.rsi.agp.dao.tables.orgDat;
// Generated by T-Systems

import java.math.BigDecimal;

public class VistaMedidaPreventiva implements java.io.Serializable {

	private static final long serialVersionUID = 8026143780832219578L;

	private VistaMedidaPreventivaId id;

	public VistaMedidaPreventiva() {
	}
	
	public VistaMedidaPreventiva(Object[] o) {
		VistaMedidaPreventivaId vid = new VistaMedidaPreventivaId();
		vid.setCodmedidapreventiva(new BigDecimal(o[0].toString()));
		vid.setDesmedidapreventiva(o[1].toString());
		id = vid;
	}

	public VistaMedidaPreventiva(VistaMedidaPreventivaId id) {
		this.id = id;
	}

	public VistaMedidaPreventivaId getId() {
		return this.id;
	}

	public void setId(VistaMedidaPreventivaId id) {
		this.id = id;
	}

}
