package com.rsi.agp.dao.tables.orgDat;
// Generated by T-Systems

import java.math.BigDecimal;

public class VistaMedidaPreventivaId implements java.io.Serializable {
	
	private static final long serialVersionUID = -1048249216110541442L;
	
	private Long lineaseguroid;
	private String codmodulo;
	private BigDecimal filamodulo;
	private Character elegible;
	private BigDecimal codconceptoppalmod;
	private String desconceptoppalmod;
	private BigDecimal codriesgocubierto;
	private String desriesgocubierto;
	private String codriesgotarificable;
	private String desriesgotarificable;
	private BigDecimal codmedidapreventiva;
	private String desmedidapreventiva;

	public VistaMedidaPreventivaId() {
	}

	public VistaMedidaPreventivaId(Long lineaseguroid, String codmodulo, Character elegible, BigDecimal filamodulo,
			BigDecimal codconceptoppalmod, String desconceptoppalmod, BigDecimal codriesgocubierto,
			String desriesgocubierto, String codriesgotarificable, String desriesgotarificable,
			BigDecimal codmedidapreventiva, String desmedidapreventiva) {
		this.lineaseguroid = lineaseguroid;
		this.codmodulo = codmodulo;
		this.filamodulo = filamodulo;
		this.codconceptoppalmod = codconceptoppalmod;
		this.desconceptoppalmod = desconceptoppalmod;
		this.codriesgocubierto = codriesgocubierto;
		this.desriesgocubierto = desriesgocubierto;
		this.codriesgotarificable = codriesgotarificable;
		this.desriesgotarificable = desriesgotarificable;
		this.codmedidapreventiva = codmedidapreventiva;
		this.desmedidapreventiva = desmedidapreventiva;
		this.elegible = elegible;
	}

	public Long getLineaseguroid() {
		return this.lineaseguroid;
	}

	public void setLineaseguroid(Long lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	public String getCodmodulo() {
		return this.codmodulo;
	}

	public void setCodmodulo(String codmodulo) {
		this.codmodulo = codmodulo;
	}

	public BigDecimal getFilamodulo() {
		return this.filamodulo;
	}

	public void setFilamodulo(BigDecimal filamodulo) {
		this.filamodulo = filamodulo;
	}

	public BigDecimal getCodconceptoppalmod() {
		return this.codconceptoppalmod;
	}

	public void setCodconceptoppalmod(BigDecimal codconceptoppalmod) {
		this.codconceptoppalmod = codconceptoppalmod;
	}

	public String getDesconceptoppalmod() {
		return this.desconceptoppalmod;
	}

	public void setDesconceptoppalmod(String desconceptoppalmod) {
		this.desconceptoppalmod = desconceptoppalmod;
	}

	public BigDecimal getCodriesgocubierto() {
		return this.codriesgocubierto;
	}

	public void setCodriesgocubierto(BigDecimal codriesgocubierto) {
		this.codriesgocubierto = codriesgocubierto;
	}

	public String getDesriesgocubierto() {
		return this.desriesgocubierto;
	}

	public void setDesriesgocubierto(String desriesgocubierto) {
		this.desriesgocubierto = desriesgocubierto;
	}

	public String getCodriesgotarificable() {
		return this.codriesgotarificable;
	}

	public void setCodriesgotarificable(String codriesgotarificable) {
		this.codriesgotarificable = codriesgotarificable;
	}

	public String getDesriesgotarificable() {
		return this.desriesgotarificable;
	}

	public void setDesriesgotarificable(String desriesgotarificable) {
		this.desriesgotarificable = desriesgotarificable;
	}

	public BigDecimal getCodmedidapreventiva() {
		return this.codmedidapreventiva;
	}

	public void setCodmedidapreventiva(BigDecimal codmedidapreventiva) {
		this.codmedidapreventiva = codmedidapreventiva;
	}

	public String getDesmedidapreventiva() {
		return this.desmedidapreventiva;
	}

	public void setDesmedidapreventiva(String desmedidapreventiva) {
		this.desmedidapreventiva = desmedidapreventiva;
	}

	public Character getElegible() {
		return elegible;
	}

	public void setElegible(Character elegible) {
		this.elegible = elegible;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaMedidaPreventivaId))
			return false;
		VistaMedidaPreventivaId castOther = (VistaMedidaPreventivaId) other;

		return ((this.getLineaseguroid() == castOther.getLineaseguroid())
				|| (this.getLineaseguroid() != null && castOther.getLineaseguroid() != null
						&& this.getLineaseguroid().equals(castOther.getLineaseguroid())))
				&& ((this.getCodmodulo() == castOther.getCodmodulo()) || (this.getCodmodulo() != null
						&& castOther.getCodmodulo() != null && this.getCodmodulo().equals(castOther.getCodmodulo())))
				&& ((this.getFilamodulo() == castOther.getFilamodulo()) || (this.getFilamodulo() != null
						&& castOther.getFilamodulo() != null && this.getFilamodulo().equals(castOther.getFilamodulo())))
				&& ((this.getCodconceptoppalmod() == castOther.getCodconceptoppalmod())
						|| (this.getCodconceptoppalmod() != null && castOther.getCodconceptoppalmod() != null
								&& this.getCodconceptoppalmod().equals(castOther.getCodconceptoppalmod())))
				&& ((this.getDesconceptoppalmod() != null && castOther.getDesconceptoppalmod() != null
						&& this.getDesconceptoppalmod().equals(castOther.getDesconceptoppalmod())))
				&& ((this.getCodriesgocubierto() == castOther.getCodriesgocubierto())
						|| (this.getCodriesgocubierto() != null && castOther.getCodriesgocubierto() != null
								&& this.getCodriesgocubierto().equals(castOther.getCodriesgocubierto())))
				&& ((this.getDesriesgocubierto() != null && castOther.getDesriesgocubierto() != null
						&& this.getDesriesgocubierto().equals(castOther.getDesriesgocubierto())))
				&& ((this.getCodriesgotarificable() != null && castOther.getCodriesgotarificable() != null
						&& this.getCodriesgotarificable().equals(castOther.getCodriesgotarificable())))
				&& ((this.getDesriesgotarificable() != null && castOther.getDesriesgotarificable() != null
						&& this.getDesriesgotarificable().equals(castOther.getDesriesgotarificable())))
				&& ((this.getCodmedidapreventiva() == castOther.getCodmedidapreventiva())
						|| (this.getCodmedidapreventiva() != null && castOther.getCodmedidapreventiva() != null
								&& this.getCodmedidapreventiva().equals(castOther.getCodmedidapreventiva())))
				&& ((this.getDesmedidapreventiva() != null && castOther.getDesmedidapreventiva() != null
						&& this.getDesmedidapreventiva().equals(castOther.getDesmedidapreventiva())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode());
		result = 37 * result + (getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode());
		result = 37 * result + (getFilamodulo() == null ? 0 : this.getFilamodulo().hashCode());
		result = 37 * result + (getCodconceptoppalmod() == null ? 0 : this.getCodconceptoppalmod().hashCode());
		result = 37 * result + (getDesconceptoppalmod() == null ? 0 : this.getDesconceptoppalmod().hashCode());
		result = 37 * result + (getCodriesgocubierto() == null ? 0 : this.getCodriesgocubierto().hashCode());
		result = 37 * result + (getDesriesgocubierto() == null ? 0 : this.getDesriesgocubierto().hashCode());
		result = 37 * result + (getCodriesgotarificable() == null ? 0 : this.getCodriesgotarificable().hashCode());
		result = 37 * result + (getDesriesgotarificable() == null ? 0 : this.getDesriesgotarificable().hashCode());
		result = 37 * result + (getCodmedidapreventiva() == null ? 0 : this.getCodmedidapreventiva().hashCode());
		result = 37 * result + (getDesmedidapreventiva() == null ? 0 : this.getDesmedidapreventiva().hashCode());
		return result;
	}

}
