package com.rsi.agp.dao.tables.orgDat;

import java.math.BigDecimal;
// Generated by T-Systems

public class VistaMarcoPlantacion implements java.io.Serializable {

	private static final long serialVersionUID = 2360997679451550598L;

	private VistaMarcoPlantacionId id;
	private BigDecimal codprovincia;
	private BigDecimal codcomarca;
	private BigDecimal codtermino;
	private Character subtermino;

	public VistaMarcoPlantacion() {
	}
	
	public VistaMarcoPlantacion(Object[] o) {
		VistaMarcoPlantacionId vid = new VistaMarcoPlantacionId();
		vid.setCodtipomarcoplantac(new BigDecimal(o[0].toString()));
		vid.setDestipomarcoplantac(o[1].toString());
		id = vid;
	}
	

	public VistaMarcoPlantacion(BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino,
			Character subtermino) {
		this.codprovincia = codprovincia;
		this.codcomarca = codcomarca;
		this.codtermino = codtermino;
		this.subtermino = subtermino;
	}

	public VistaMarcoPlantacion(VistaMarcoPlantacionId id) {
		this.id = id;
	}

	public VistaMarcoPlantacionId getId() {
		return this.id;
	}

	public void setId(VistaMarcoPlantacionId id) {
		this.id = id;
	}

	public BigDecimal getCodprovincia() {
		return codprovincia;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodcomarca() {
		return codcomarca;
	}

	public void setCodcomarca(BigDecimal codcomarca) {
		this.codcomarca = codcomarca;
	}

	public BigDecimal getCodtermino() {
		return codtermino;
	}

	public void setCodtermino(BigDecimal codtermino) {
		this.codtermino = codtermino;
	}

	public Character getSubtermino() {
		return subtermino;
	}

	public void setSubtermino(Character subtermino) {
		this.subtermino = subtermino;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaMarcoPlantacion))
			return false;
		VistaMarcoPlantacion castOther = (VistaMarcoPlantacion) other;

		return ((this.getCodprovincia() == castOther.getCodprovincia()) || (this.getCodprovincia() != null
				&& castOther.getCodprovincia() != null && this.getCodprovincia().equals(castOther.getCodprovincia())))
				&& ((this.getCodcomarca() == castOther.getCodcomarca()) || (this.getCodcomarca() != null
						&& castOther.getCodcomarca() != null && this.getCodcomarca().equals(castOther.getCodcomarca())))
				&& ((this.getCodtermino() == castOther.getCodtermino()) || (this.getCodtermino() != null
						&& castOther.getCodtermino() != null && this.getCodtermino().equals(castOther.getCodtermino())))
				&& ((this.getSubtermino() == castOther.getSubtermino())
						|| (this.getSubtermino() != null && castOther.getSubtermino() != null
								&& this.getSubtermino().equals(castOther.getSubtermino())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodprovincia() == null ? 0 : this.getCodprovincia().hashCode());
		result = 37 * result + (getCodcomarca() == null ? 0 : this.getCodcomarca().hashCode());
		result = 37 * result + (getCodtermino() == null ? 0 : this.getCodtermino().hashCode());
		result = 37 * result + (getSubtermino() == null ? 0 : this.getSubtermino().hashCode());
		return result;
	}

}
