package com.rsi.agp.dao.tables.orgDat;

import java.math.BigDecimal;
// Generated by T-Systems

public class VistaPracticaCultural305 implements java.io.Serializable {

	private static final long serialVersionUID = 1743863054182931321L;

	private VistaPracticaCultural305Id id;
	private BigDecimal codprovincia;
	private BigDecimal codcomarca;
	private BigDecimal codtermino;
	private Character subtermino;
	private BigDecimal codtipocapital;

	public VistaPracticaCultural305() {
	}

	public VistaPracticaCultural305(Object[] o) {
		VistaPracticaCultural305Id vid = new VistaPracticaCultural305Id();
		vid.setCodpracticacultural(new BigDecimal(o[0].toString()));
		vid.setDespracticacultural(o[1].toString());
		id = vid;
	}

	public VistaPracticaCultural305(VistaPracticaCultural305Id id) {
		this.id = id;
	}

	public VistaPracticaCultural305Id getId() {
		return this.id;
	}

	public void setId(VistaPracticaCultural305Id id) {
		this.id = id;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodprovincia() {
		return codprovincia;
	}

	public void setCodcomarca(BigDecimal codcomarca) {
		this.codcomarca = codcomarca;
	}

	public BigDecimal getCodcomarca() {
		return codcomarca;
	}

	public void setCodtermino(BigDecimal codtermino) {
		this.codtermino = codtermino;
	}

	public BigDecimal getCodtermino() {
		return codtermino;
	}

	public void setSubtermino(Character subtermino) {
		this.subtermino = subtermino;
	}

	public Character getSubtermino() {
		return subtermino;
	}

	public void setCodtipocapital(BigDecimal codtipocapital) {
		this.codtipocapital = codtipocapital;
	}

	public BigDecimal getCodtipocapital() {
		return codtipocapital;
	}

}
