package com.rsi.agp.dao.tables.orgDat;

import java.math.BigDecimal;
// Generated 06-jun-2011 12:13:44 by Hibernate Tools 3.3.0.GA

/**
 * VistaRotacion generated by hbm2java
 */
public class VistaRotacion implements java.io.Serializable {

	private static final long serialVersionUID = -486346586308419422L;
	
	private VistaRotacionId id;
	private BigDecimal codprovincia;
	private BigDecimal codcomarca;
	private BigDecimal codtermino;
	private Character subtermino;
	private BigDecimal codtipocapital;

	public VistaRotacion() {
	}
	
	public VistaRotacion(Object[] o) {
		VistaRotacionId vid = new VistaRotacionId();
		vid.setCodrotacion(new BigDecimal(o[0].toString()));
		vid.setDescripcion(o[1].toString());
		id = vid;
	}

	public VistaRotacion(VistaRotacionId id) {
		this.id = id;
	}

	public VistaRotacionId getId() {
		return this.id;
	}

	public void setId(VistaRotacionId id) {
		this.id = id;
	}

	public BigDecimal getCodprovincia() {
		return codprovincia;
	}

	public void setCodprovincia(BigDecimal codprovincia) {
		this.codprovincia = codprovincia;
	}

	public BigDecimal getCodcomarca() {
		return codcomarca;
	}

	public void setCodcomarca(BigDecimal codcomarca) {
		this.codcomarca = codcomarca;
	}

	public BigDecimal getCodtermino() {
		return codtermino;
	}

	public void setCodtermino(BigDecimal codtermino) {
		this.codtermino = codtermino;
	}

	public Character getSubtermino() {
		return subtermino;
	}

	public void setSubtermino(Character subtermino) {
		this.subtermino = subtermino;
	}

	public BigDecimal getCodtipocapital() {
		return codtipocapital;
	}

	public void setCodtipocapital(BigDecimal codtipocapital) {
		this.codtipocapital = codtipocapital;
	}

}
