package com.rsi.agp.dao.tables.orgDat;
// Generated by T-Systems


import java.math.BigDecimal;

public class VistaCodigoReduccionRendimientoId  implements java.io.Serializable {


     private BigDecimal lineaseguroid;
     private String codmodulo;
     private BigDecimal codprovincia;
     private BigDecimal codcomarca;
     private BigDecimal codtermino;
     private Character subtermino;
     private BigDecimal codreducrdto;
     private String desreducrdto;

    public VistaCodigoReduccionRendimientoId() {
    }

    public VistaCodigoReduccionRendimientoId(BigDecimal lineaseguroid, String codmodulo, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino, BigDecimal codreducrdto, String desreducrdto) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.codprovincia = codprovincia;
       this.codcomarca = codcomarca;
       this.codtermino = codtermino;
       this.subtermino = subtermino;
       this.codreducrdto = codreducrdto;
       this.desreducrdto = desreducrdto;
    }
   
    public BigDecimal getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(BigDecimal lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public BigDecimal getCodprovincia() {
        return this.codprovincia;
    }
    
    public void setCodprovincia(BigDecimal codprovincia) {
        this.codprovincia = codprovincia;
    }
    public BigDecimal getCodcomarca() {
        return this.codcomarca;
    }
    
    public void setCodcomarca(BigDecimal codcomarca) {
        this.codcomarca = codcomarca;
    }
    public BigDecimal getCodtermino() {
        return this.codtermino;
    }
    
    public void setCodtermino(BigDecimal codtermino) {
        this.codtermino = codtermino;
    }
    public Character getSubtermino() {
        return this.subtermino;
    }
    
    public void setSubtermino(Character subtermino) {
        this.subtermino = subtermino;
    }
    public BigDecimal getCodreducrdto() {
        return this.codreducrdto;
    }
    
    public void setCodreducrdto(BigDecimal codreducrdto) {
        this.codreducrdto = codreducrdto;
    }
    public String getDesreducrdto() {
        return this.desreducrdto;
    }
    
    public void setDesreducrdto(String desreducrdto) {
        this.desreducrdto = desreducrdto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VistaCodigoReduccionRendimientoId) ) return false;
		 VistaCodigoReduccionRendimientoId castOther = ( VistaCodigoReduccionRendimientoId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getCodmodulo()==castOther.getCodmodulo()) || ( this.getCodmodulo()!=null && castOther.getCodmodulo()!=null && this.getCodmodulo().equals(castOther.getCodmodulo()) ) )
 && ( (this.getCodprovincia()==castOther.getCodprovincia()) || ( this.getCodprovincia()!=null && castOther.getCodprovincia()!=null && this.getCodprovincia().equals(castOther.getCodprovincia()) ) )
 && ( (this.getCodcomarca()==castOther.getCodcomarca()) || ( this.getCodcomarca()!=null && castOther.getCodcomarca()!=null && this.getCodcomarca().equals(castOther.getCodcomarca()) ) )
 && ( (this.getCodtermino()==castOther.getCodtermino()) || ( this.getCodtermino()!=null && castOther.getCodtermino()!=null && this.getCodtermino().equals(castOther.getCodtermino()) ) )
 && ( (this.getSubtermino()==castOther.getSubtermino()) || ( this.getSubtermino()!=null && castOther.getSubtermino()!=null && this.getSubtermino().equals(castOther.getSubtermino()) ) )
 && ( (this.getCodreducrdto()==castOther.getCodreducrdto()) || ( this.getCodreducrdto()!=null && castOther.getCodreducrdto()!=null && this.getCodreducrdto().equals(castOther.getCodreducrdto()) ) )
 && ( (this.getDesreducrdto()!=null && castOther.getDesreducrdto()!=null && this.getDesreducrdto().equals(castOther.getDesreducrdto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode() );
         result = 37 * result + ( getCodprovincia() == null ? 0 : this.getCodprovincia().hashCode() );
         result = 37 * result + ( getCodcomarca() == null ? 0 : this.getCodcomarca().hashCode() );
         result = 37 * result + ( getCodtermino() == null ? 0 : this.getCodtermino().hashCode() );
         result = 37 * result + ( getSubtermino() == null ? 0 : this.getSubtermino().hashCode() );
         result = 37 * result + ( getCodreducrdto() == null ? 0 : this.getCodreducrdto().hashCode() );
         result = 37 * result + ( getDesreducrdto() == null ? 0 : this.getDesreducrdto().hashCode() );
         return result;
   }   


}


