package com.rsi.agp.dao.tables.orgDat;
// Generated by T-Systems

import java.math.BigDecimal;

public class VistaSistemaProduccionId implements java.io.Serializable {

	private static final long serialVersionUID = 7536413349805981603L;

	private Long lineaseguroid;
	private String codmodulo;
	private BigDecimal codcultivo;
	private BigDecimal codvariedad;
	private BigDecimal codsistemaproduccion;
	private String dessistemaproduccion;

	public VistaSistemaProduccionId() {
	}

	public VistaSistemaProduccionId(Long lineaseguroid, String codmodulo, BigDecimal codcultivo, BigDecimal codvariedad,
			BigDecimal codsistemaproduccion, String dessistemaproduccion) {
		this.lineaseguroid = lineaseguroid;
		this.codmodulo = codmodulo;
		this.codcultivo = codcultivo;
		this.codvariedad = codvariedad;
		this.codsistemaproduccion = codsistemaproduccion;
		this.dessistemaproduccion = dessistemaproduccion;
	}

	public Long getLineaseguroid() {
		return this.lineaseguroid;
	}

	public void setLineaseguroid(Long lineaseguroid) {
		this.lineaseguroid = lineaseguroid;
	}

	public String getCodmodulo() {
		return this.codmodulo;
	}

	public void setCodmodulo(String codmodulo) {
		this.codmodulo = codmodulo;
	}

	public BigDecimal getCodcultivo() {
		return this.codcultivo;
	}

	public void setCodcultivo(BigDecimal codcultivo) {
		this.codcultivo = codcultivo;
	}

	public BigDecimal getCodvariedad() {
		return this.codvariedad;
	}

	public void setCodvariedad(BigDecimal codvariedad) {
		this.codvariedad = codvariedad;
	}

	public BigDecimal getCodsistemaproduccion() {
		return this.codsistemaproduccion;
	}

	public void setCodsistemaproduccion(BigDecimal codsistemaproduccion) {
		this.codsistemaproduccion = codsistemaproduccion;
	}

	public String getDessistemaproduccion() {
		return this.dessistemaproduccion;
	}

	public void setDessistemaproduccion(String dessistemaproduccion) {
		this.dessistemaproduccion = dessistemaproduccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaSistemaProduccionId))
			return false;
		VistaSistemaProduccionId castOther = (VistaSistemaProduccionId) other;

		return ((this.getLineaseguroid() == castOther.getLineaseguroid())
				|| (this.getLineaseguroid() != null && castOther.getLineaseguroid() != null
						&& this.getLineaseguroid().equals(castOther.getLineaseguroid())))
				&& ((this.getCodmodulo() == castOther.getCodmodulo()) || (this.getCodmodulo() != null
						&& castOther.getCodmodulo() != null && this.getCodmodulo().equals(castOther.getCodmodulo())))
				&& ((this.getCodcultivo() == castOther.getCodcultivo()) || (this.getCodcultivo() != null
						&& castOther.getCodcultivo() != null && this.getCodcultivo().equals(castOther.getCodcultivo())))
				&& ((this.getCodvariedad() == castOther.getCodvariedad())
						|| (this.getCodvariedad() != null && castOther.getCodvariedad() != null
								&& this.getCodvariedad().equals(castOther.getCodvariedad())))
				&& ((this.getCodsistemaproduccion() == castOther.getCodsistemaproduccion())
						|| (this.getCodsistemaproduccion() != null && castOther.getCodsistemaproduccion() != null
								&& this.getCodsistemaproduccion().equals(castOther.getCodsistemaproduccion())))
				&& ((this.getDessistemaproduccion() != null && castOther.getDessistemaproduccion() != null
						&& this.getDessistemaproduccion().equals(castOther.getDessistemaproduccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode());
		result = 37 * result + (getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode());
		result = 37 * result + (getCodcultivo() == null ? 0 : this.getCodcultivo().hashCode());
		result = 37 * result + (getCodvariedad() == null ? 0 : this.getCodvariedad().hashCode());
		result = 37 * result + (getCodsistemaproduccion() == null ? 0 : this.getCodsistemaproduccion().hashCode());
		result = 37 * result + (getDessistemaproduccion() == null ? 0 : this.getDessistemaproduccion().hashCode());
		return result;
	}

}
