package com.rsi.agp.dao.tables.org;
// Generated by T-Systems


import java.math.BigDecimal;

public class NaturalezaAlternativaId  implements java.io.Serializable {


     private BigDecimal codconcepto;
     private BigDecimal iddocumento;
     private BigDecimal codtiponaturaleza;

    public NaturalezaAlternativaId() {
    }

    public NaturalezaAlternativaId(BigDecimal codconcepto, BigDecimal iddocumento, BigDecimal codtiponaturaleza) {
       this.codconcepto = codconcepto;
       this.iddocumento = iddocumento;
       this.codtiponaturaleza = codtiponaturaleza;
    }
   
    public BigDecimal getCodconcepto() {
        return this.codconcepto;
    }
    
    public void setCodconcepto(BigDecimal codconcepto) {
        this.codconcepto = codconcepto;
    }
    public BigDecimal getIddocumento() {
        return this.iddocumento;
    }
    
    public void setIddocumento(BigDecimal iddocumento) {
        this.iddocumento = iddocumento;
    }
    public BigDecimal getCodtiponaturaleza() {
        return this.codtiponaturaleza;
    }
    
    public void setCodtiponaturaleza(BigDecimal codtiponaturaleza) {
        this.codtiponaturaleza = codtiponaturaleza;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NaturalezaAlternativaId) ) return false;
		 NaturalezaAlternativaId castOther = ( NaturalezaAlternativaId ) other; 
         
		 return ( (this.getCodconcepto()==castOther.getCodconcepto()) || ( this.getCodconcepto()!=null && castOther.getCodconcepto()!=null && this.getCodconcepto().equals(castOther.getCodconcepto()) ) )
 && ( (this.getIddocumento()==castOther.getIddocumento()) || ( this.getIddocumento()!=null && castOther.getIddocumento()!=null && this.getIddocumento().equals(castOther.getIddocumento()) ) )
 && ( (this.getCodtiponaturaleza()==castOther.getCodtiponaturaleza()) || ( this.getCodtiponaturaleza()!=null && castOther.getCodtiponaturaleza()!=null && this.getCodtiponaturaleza().equals(castOther.getCodtiponaturaleza()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodconcepto() == null ? 0 : this.getCodconcepto().hashCode() );
         result = 37 * result + ( getIddocumento() == null ? 0 : this.getIddocumento().hashCode() );
         result = 37 * result + ( getCodtiponaturaleza() == null ? 0 : this.getCodtiponaturaleza().hashCode() );
         return result;
   }   


}


