package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import com.rsi.agp.dao.tables.org.DiccionarioDatos;

public class AdaptacionRiesgo  implements java.io.Serializable {


     private AdaptacionRiesgoId id;
     private DiccionarioDatos diccionarioDatos;
     private String descripcion;
     private Character tipoBonifRecargo;

    public AdaptacionRiesgo() {
    }

	
    public AdaptacionRiesgo(AdaptacionRiesgoId id, DiccionarioDatos diccionarioDatos) {
        this.id = id;
        this.diccionarioDatos = diccionarioDatos;
    }
    public AdaptacionRiesgo(AdaptacionRiesgoId id, DiccionarioDatos diccionarioDatos, String descripcion, Character tipoBonifRecargo) {
       this.id = id;
       this.diccionarioDatos = diccionarioDatos;
       this.descripcion = descripcion;
       this.tipoBonifRecargo = tipoBonifRecargo;
    }
   
    public AdaptacionRiesgoId getId() {
        return this.id;
    }
    
    public void setId(AdaptacionRiesgoId id) {
        this.id = id;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getTipoBonifRecargo() {
        return this.tipoBonifRecargo;
    }
    
    public void setTipoBonifRecargo(Character tipoBonifRecargo) {
        this.tipoBonifRecargo = tipoBonifRecargo;
    }




}


