package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import com.rsi.agp.dao.tables.org.DiccionarioDatos;

public class FactoresIncluidosConceptoPrincipalModulo  implements java.io.Serializable {


     private FactoresIncluidosConceptoPrincipalModuloId id;
     private DiccionarioDatos diccionarioDatos;
     private ConceptoPpalModulo conceptoPpalModulo;

    public FactoresIncluidosConceptoPrincipalModulo() {
    }

    public FactoresIncluidosConceptoPrincipalModulo(FactoresIncluidosConceptoPrincipalModuloId id, DiccionarioDatos diccionarioDatos, ConceptoPpalModulo conceptoPpalModulo) {
       this.id = id;
       this.diccionarioDatos = diccionarioDatos;
       this.conceptoPpalModulo = conceptoPpalModulo;
    }
   
    public FactoresIncluidosConceptoPrincipalModuloId getId() {
        return this.id;
    }
    
    public void setId(FactoresIncluidosConceptoPrincipalModuloId id) {
        this.id = id;
    }
    public DiccionarioDatos getDiccionarioDatos() {
        return this.diccionarioDatos;
    }
    
    public void setDiccionarioDatos(DiccionarioDatos diccionarioDatos) {
        this.diccionarioDatos = diccionarioDatos;
    }
    public ConceptoPpalModulo getConceptoPpalModulo() {
        return this.conceptoPpalModulo;
    }
    
    public void setConceptoPpalModulo(ConceptoPpalModulo conceptoPpalModulo) {
        this.conceptoPpalModulo = conceptoPpalModulo;
    }




}


