package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class GrupoSeguro  implements java.io.Serializable {


     private String codgruposeguro;
     private String desgruposeguro;
     private Set<Riesgo> riesgos = new HashSet<Riesgo>(0);
     private Set<LineaCondicionado> lineaCondicionados = new HashSet<LineaCondicionado>(0);

    public GrupoSeguro() {
    }

	
    public GrupoSeguro(String codgruposeguro, String desgruposeguro) {
        this.codgruposeguro = codgruposeguro;
        this.desgruposeguro = desgruposeguro;
    }
    public GrupoSeguro(String codgruposeguro, String desgruposeguro, Set<Riesgo> riesgos, Set<LineaCondicionado> lineaCondicionados) {
       this.codgruposeguro = codgruposeguro;
       this.desgruposeguro = desgruposeguro;
       this.riesgos = riesgos;
       this.lineaCondicionados = lineaCondicionados;
    }
   
    public String getCodgruposeguro() {
        return this.codgruposeguro;
    }
    
    public void setCodgruposeguro(String codgruposeguro) {
        this.codgruposeguro = codgruposeguro;
    }
    public String getDesgruposeguro() {
        return this.desgruposeguro;
    }
    
    public void setDesgruposeguro(String desgruposeguro) {
        this.desgruposeguro = desgruposeguro;
    }
    public Set<Riesgo> getRiesgos() {
        return this.riesgos;
    }
    
    public void setRiesgos(Set<Riesgo> riesgos) {
        this.riesgos = riesgos;
    }
    public Set<LineaCondicionado> getLineaCondicionados() {
        return this.lineaCondicionados;
    }
    
    public void setLineaCondicionados(Set<LineaCondicionado> lineaCondicionados) {
        this.lineaCondicionados = lineaCondicionados;
    }




}


