package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems

import java.math.BigDecimal;

public class IGP implements java.io.Serializable {

	private static final long serialVersionUID = 8005644390860563944L;

	private BigDecimal codigp;
	private String descripcion;

	public IGP() {
	}

	public IGP(BigDecimal codigp) {
		this.codigp = codigp;
	}

	public IGP(BigDecimal codigp, String descripcion) {
		this.codigp = codigp;
		this.descripcion = descripcion;
	}

	public BigDecimal getCodigp() {
		return this.codigp;
	}

	public void setCodigp(BigDecimal codigp) {
		this.codigp = codigp;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
