package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cpl.GrupoTasaRiesgo;
import com.rsi.agp.dao.tables.cpl.VinculacionValoresModulo;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class MinimoIndemnizableElegible  implements java.io.Serializable {


     private BigDecimal pctminindem;
     private BigDecimal valor;
     private String desminindem;
     private Set<GrupoTasaRiesgo> grupoTasaRiesgos = new HashSet<GrupoTasaRiesgo>(0);
     private Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemnvinc = new HashSet<VinculacionValoresModulo>(0);
     private Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemneleg = new HashSet<VinculacionValoresModulo>(0);

    public MinimoIndemnizableElegible() {
    }

	
    public MinimoIndemnizableElegible(BigDecimal pctminindem, BigDecimal valor, String desminindem) {
        this.pctminindem = pctminindem;
        this.valor = valor;
        this.desminindem = desminindem;
    }
    public MinimoIndemnizableElegible(BigDecimal pctminindem, BigDecimal valor, String desminindem, Set<GrupoTasaRiesgo> grupoTasaRiesgos, Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemnvinc, Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemneleg) {
       this.pctminindem = pctminindem;
       this.valor = valor;
       this.desminindem = desminindem;
       this.grupoTasaRiesgos = grupoTasaRiesgos;
       this.vinculacionValoresModulosForPctminindemnvinc = vinculacionValoresModulosForPctminindemnvinc;
       this.vinculacionValoresModulosForPctminindemneleg = vinculacionValoresModulosForPctminindemneleg;
    }
   
    public BigDecimal getPctminindem() {
        return this.pctminindem;
    }
    
    public void setPctminindem(BigDecimal pctminindem) {
        this.pctminindem = pctminindem;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getDesminindem() {
        return this.desminindem;
    }
    
    public void setDesminindem(String desminindem) {
        this.desminindem = desminindem;
    }
    public Set<GrupoTasaRiesgo> getGrupoTasaRiesgos() {
        return this.grupoTasaRiesgos;
    }
    
    public void setGrupoTasaRiesgos(Set<GrupoTasaRiesgo> grupoTasaRiesgos) {
        this.grupoTasaRiesgos = grupoTasaRiesgos;
    }
    public Set<VinculacionValoresModulo> getVinculacionValoresModulosForPctminindemnvinc() {
        return this.vinculacionValoresModulosForPctminindemnvinc;
    }

    public void setVinculacionValoresModulosForPctminindemnvinc(Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemnvinc) {
        this.vinculacionValoresModulosForPctminindemnvinc = vinculacionValoresModulosForPctminindemnvinc;
    }
    public Set<VinculacionValoresModulo> getVinculacionValoresModulosForPctminindemneleg() {
        return this.vinculacionValoresModulosForPctminindemneleg;
    }
    
    public void setVinculacionValoresModulosForPctminindemneleg(Set<VinculacionValoresModulo> vinculacionValoresModulosForPctminindemneleg) {
        this.vinculacionValoresModulosForPctminindemneleg = vinculacionValoresModulosForPctminindemneleg;
    }




}


