package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cpl.GrupoTasas;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class NumAniosDesdeDescorche  implements java.io.Serializable {


     private BigDecimal codnumaniosdescorche;
     private String desnumaniosdescorche;
     private Set<GrupoTasas> grupoTasases = new HashSet<GrupoTasas>(0);

    public NumAniosDesdeDescorche() {
    }

	
    public NumAniosDesdeDescorche(BigDecimal codnumaniosdescorche, String desnumaniosdescorche) {
        this.codnumaniosdescorche = codnumaniosdescorche;
        this.desnumaniosdescorche = desnumaniosdescorche;
    }
    public NumAniosDesdeDescorche(BigDecimal codnumaniosdescorche, String desnumaniosdescorche, Set<GrupoTasas> grupoTasases) {
       this.codnumaniosdescorche = codnumaniosdescorche;
       this.desnumaniosdescorche = desnumaniosdescorche;
       this.grupoTasases = grupoTasases;
    }
   
    public BigDecimal getCodnumaniosdescorche() {
        return this.codnumaniosdescorche;
    }
    
    public void setCodnumaniosdescorche(BigDecimal codnumaniosdescorche) {
        this.codnumaniosdescorche = codnumaniosdescorche;
    }
    public String getDesnumaniosdescorche() {
        return this.desnumaniosdescorche;
    }
    
    public void setDesnumaniosdescorche(String desnumaniosdescorche) {
        this.desnumaniosdescorche = desnumaniosdescorche;
    }
    public Set<GrupoTasas> getGrupoTasases() {
        return this.grupoTasases;
    }
    
    public void setGrupoTasases(Set<GrupoTasas> grupoTasases) {
        this.grupoTasases = grupoTasases;
    }




}


