package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems

import com.rsi.agp.dao.tables.cpl.GrupoTasas;
import com.rsi.agp.dao.tables.cpl.LimiteRendimiento;
import com.rsi.agp.dao.tables.cpl.Precio;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class SistemaProduccion implements java.io.Serializable {

	private static final long serialVersionUID = -3015620892222605668L;
	
	private BigDecimal codsistemaproduccion;
	private String dessistemaproduccion;
	private Set<Precio> precios = new HashSet<Precio>(0);
	private Set<LimiteRendimiento> limiteRendimientos = new HashSet<LimiteRendimiento>(0);
	private Set<GrupoTasas> grupoTasases = new HashSet<GrupoTasas>(0);

	public SistemaProduccion() {
	}

	public SistemaProduccion(BigDecimal codsistemaproduccion, String dessistemaproduccion) {
		this.codsistemaproduccion = codsistemaproduccion;
		this.dessistemaproduccion = dessistemaproduccion;
	}

	public SistemaProduccion(BigDecimal codsistemaproduccion, String dessistemaproduccion, Set<Precio> precios,
			Set<LimiteRendimiento> limiteRendimientos, Set<GrupoTasas> grupoTasases) {
		this.codsistemaproduccion = codsistemaproduccion;
		this.dessistemaproduccion = dessistemaproduccion;
		this.precios = precios;
		this.limiteRendimientos = limiteRendimientos;
		this.grupoTasases = grupoTasases;
	}

	public BigDecimal getCodsistemaproduccion() {
		return this.codsistemaproduccion;
	}

	public void setCodsistemaproduccion(BigDecimal codsistemaproduccion) {
		this.codsistemaproduccion = codsistemaproduccion;
	}

	public String getDessistemaproduccion() {
		return this.dessistemaproduccion;
	}

	public void setDessistemaproduccion(String dessistemaproduccion) {
		this.dessistemaproduccion = dessistemaproduccion;
	}

	public Set<Precio> getPrecios() {
		return this.precios;
	}

	public void setPrecios(Set<Precio> precios) {
		this.precios = precios;
	}

	public Set<LimiteRendimiento> getLimiteRendimientos() {
		return this.limiteRendimientos;
	}

	public void setLimiteRendimientos(Set<LimiteRendimiento> limiteRendimientos) {
		this.limiteRendimientos = limiteRendimientos;
	}

	public Set<GrupoTasas> getGrupoTasases() {
		return this.grupoTasases;
	}

	public void setGrupoTasases(Set<GrupoTasas> grupoTasases) {
		this.grupoTasases = grupoTasases;
	}

}
