package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import com.rsi.agp.dao.tables.cpl.GrupoTasas;
import com.rsi.agp.dao.tables.cpl.Precio;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class TipoTerreno  implements java.io.Serializable {


     private BigDecimal codtipoterreno;
     private String destipoterreno;
     private Set<GrupoTasas> grupoTasases = new HashSet<GrupoTasas>(0);
     private Set<Precio> precios = new HashSet<Precio>(0);

    public TipoTerreno() {
    }

	
    public TipoTerreno(BigDecimal codtipoterreno, String destipoterreno) {
        this.codtipoterreno = codtipoterreno;
        this.destipoterreno = destipoterreno;
    }
    public TipoTerreno(BigDecimal codtipoterreno, String destipoterreno, Set<GrupoTasas> grupoTasases, Set<Precio> precios) {
       this.codtipoterreno = codtipoterreno;
       this.destipoterreno = destipoterreno;
       this.grupoTasases = grupoTasases;
       this.precios = precios;
    }
   
    public BigDecimal getCodtipoterreno() {
        return this.codtipoterreno;
    }
    
    public void setCodtipoterreno(BigDecimal codtipoterreno) {
        this.codtipoterreno = codtipoterreno;
    }
    public String getDestipoterreno() {
        return this.destipoterreno;
    }
    
    public void setDestipoterreno(String destipoterreno) {
        this.destipoterreno = destipoterreno;
    }
    public Set<GrupoTasas> getGrupoTasases() {
        return this.grupoTasases;
    }
    
    public void setGrupoTasases(Set<GrupoTasas> grupoTasases) {
        this.grupoTasases = grupoTasases;
    }
    public Set<Precio> getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set<Precio> precios) {
        this.precios = precios;
    }




}


