package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import java.util.HashSet;
import java.util.Set;

public class ZonificacionFamilia  implements java.io.Serializable {


     private String codfamilia;
     private String descripcion;
     private Set<ZonificacionSIGPAC> zonificacionSIGPACs = new HashSet<ZonificacionSIGPAC>(0);
     private Set<LineaCondicionado> lineaCondicionados = new HashSet<LineaCondicionado>(0);

    public ZonificacionFamilia() {
    }

	
    public ZonificacionFamilia(String codfamilia, String descripcion) {
        this.codfamilia = codfamilia;
        this.descripcion = descripcion;
    }
    public ZonificacionFamilia(String codfamilia, String descripcion, Set<ZonificacionSIGPAC> zonificacionSIGPACs, Set<LineaCondicionado> lineaCondicionados) {
       this.codfamilia = codfamilia;
       this.descripcion = descripcion;
       this.zonificacionSIGPACs = zonificacionSIGPACs;
       this.lineaCondicionados = lineaCondicionados;
    }
   
    public String getCodfamilia() {
        return this.codfamilia;
    }
    
    public void setCodfamilia(String codfamilia) {
        this.codfamilia = codfamilia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<ZonificacionSIGPAC> getZonificacionSIGPACs() {
        return this.zonificacionSIGPACs;
    }
    
    public void setZonificacionSIGPACs(Set<ZonificacionSIGPAC> zonificacionSIGPACs) {
        this.zonificacionSIGPACs = zonificacionSIGPACs;
    }
    public Set<LineaCondicionado> getLineaCondicionados() {
        return this.lineaCondicionados;
    }
    
    public void setLineaCondicionados(Set<LineaCondicionado> lineaCondicionados) {
        this.lineaCondicionados = lineaCondicionados;
    }




}


