package com.rsi.agp.dao.tables.cgen;
// Generated by T-Systems


import java.math.BigDecimal;

public class ZonificacionFamiliaDetalleId  implements java.io.Serializable {


     private String codfamilia;
     private BigDecimal codlinea;

    public ZonificacionFamiliaDetalleId() {
    }

    public ZonificacionFamiliaDetalleId(String codfamilia, BigDecimal codlinea) {
       this.codfamilia = codfamilia;
       this.codlinea = codlinea;
    }
   
    public String getCodfamilia() {
        return this.codfamilia;
    }
    
    public void setCodfamilia(String codfamilia) {
        this.codfamilia = codfamilia;
    }
    public BigDecimal getCodlinea() {
        return this.codlinea;
    }
    
    public void setCodlinea(BigDecimal codlinea) {
        this.codlinea = codlinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ZonificacionFamiliaDetalleId) ) return false;
		 ZonificacionFamiliaDetalleId castOther = ( ZonificacionFamiliaDetalleId ) other; 
         
		 return ( (this.getCodfamilia()==castOther.getCodfamilia()) || ( this.getCodfamilia()!=null && castOther.getCodfamilia()!=null && this.getCodfamilia().equals(castOther.getCodfamilia()) ) )
 && ( (this.getCodlinea()==castOther.getCodlinea()) || ( this.getCodlinea()!=null && castOther.getCodlinea()!=null && this.getCodlinea().equals(castOther.getCodlinea()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodfamilia() == null ? 0 : this.getCodfamilia().hashCode() );
         result = 37 * result + ( getCodlinea() == null ? 0 : this.getCodlinea().hashCode() );
         return result;
   }   


}


