package com.rsi.agp.dao.tables.commons;
// Generated by T-Systems


import com.rsi.agp.dao.tables.poliza.RelacionOrganismoComunidad;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

public class Comunidad  implements java.io.Serializable {


     private BigDecimal codcomunidad;
     private String nomcomunidad;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);
     private Set<RelacionOrganismoComunidad> relacionOrganismoComunidads = new HashSet<RelacionOrganismoComunidad>(0);

    public Comunidad() {
    }

	
    public Comunidad(BigDecimal codcomunidad, String nomcomunidad) {
        this.codcomunidad = codcomunidad;
        this.nomcomunidad = nomcomunidad;
    }
    public Comunidad(BigDecimal codcomunidad, String nomcomunidad, Set<Provincia> provincias, Set<RelacionOrganismoComunidad> relacionOrganismoComunidads) {
        this.codcomunidad = codcomunidad;
        this.nomcomunidad = nomcomunidad;
        this.provincias = provincias;
        this.relacionOrganismoComunidads = relacionOrganismoComunidads;
     }
   
    public BigDecimal getCodcomunidad() {
        return this.codcomunidad;
    }
    
    public void setCodcomunidad(BigDecimal codcomunidad) {
        this.codcomunidad = codcomunidad;
    }
    public String getNomcomunidad() {
        return this.nomcomunidad;
    }
    
    public void setNomcomunidad(String nomcomunidad) {
        this.nomcomunidad = nomcomunidad;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }
    public Set<RelacionOrganismoComunidad> getRelacionOrganismoComunidads() {
        return this.relacionOrganismoComunidads;
    }
    
    public void setRelacionOrganismoComunidads(Set<RelacionOrganismoComunidad> relacionOrganismoComunidads) {
        this.relacionOrganismoComunidads = relacionOrganismoComunidads;
    }




}


