package com.rsi.agp.dao.tables.commons;
// Generated by T-Systems


import java.math.BigDecimal;

public class VistaTipoCapitalId  implements java.io.Serializable {


     private BigDecimal lineaseguroid;
     private String codmodulo;
     private BigDecimal codcultivo;
     private BigDecimal codvariedad;
     private BigDecimal codprovincia;
     private BigDecimal codcomarca;
     private BigDecimal codtermino;
     private Character subtermino;
     private BigDecimal codtipocapital;
     private String destipocapital;
     private BigDecimal codconcepto;

    public VistaTipoCapitalId() {
    }

	
    public VistaTipoCapitalId(BigDecimal lineaseguroid, String codmodulo, BigDecimal codcultivo, BigDecimal codvariedad, BigDecimal codprovincia, BigDecimal codtermino, Character subtermino, BigDecimal codtipocapital, String destipocapital) {
        this.lineaseguroid = lineaseguroid;
        this.codmodulo = codmodulo;
        this.codcultivo = codcultivo;
        this.codvariedad = codvariedad;
        this.codprovincia = codprovincia;
        this.codtermino = codtermino;
        this.subtermino = subtermino;
        this.codtipocapital = codtipocapital;
        this.destipocapital = destipocapital;
    }
    public VistaTipoCapitalId(BigDecimal lineaseguroid, String codmodulo, BigDecimal codcultivo, BigDecimal codvariedad, BigDecimal codprovincia, BigDecimal codcomarca, BigDecimal codtermino, Character subtermino, BigDecimal codtipocapital, String destipocapital, BigDecimal codconcepto) {
       this.lineaseguroid = lineaseguroid;
       this.codmodulo = codmodulo;
       this.codcultivo = codcultivo;
       this.codvariedad = codvariedad;
       this.codprovincia = codprovincia;
       this.codcomarca = codcomarca;
       this.codtermino = codtermino;
       this.subtermino = subtermino;
       this.codtipocapital = codtipocapital;
       this.destipocapital = destipocapital;
       this.codconcepto = codconcepto;
    }
   
    public BigDecimal getLineaseguroid() {
        return this.lineaseguroid;
    }
    
    public void setLineaseguroid(BigDecimal lineaseguroid) {
        this.lineaseguroid = lineaseguroid;
    }
    public String getCodmodulo() {
        return this.codmodulo;
    }
    
    public void setCodmodulo(String codmodulo) {
        this.codmodulo = codmodulo;
    }
    public BigDecimal getCodcultivo() {
        return this.codcultivo;
    }
    
    public void setCodcultivo(BigDecimal codcultivo) {
        this.codcultivo = codcultivo;
    }
    public BigDecimal getCodvariedad() {
        return this.codvariedad;
    }
    
    public void setCodvariedad(BigDecimal codvariedad) {
        this.codvariedad = codvariedad;
    }
    public BigDecimal getCodprovincia() {
        return this.codprovincia;
    }
    
    public void setCodprovincia(BigDecimal codprovincia) {
        this.codprovincia = codprovincia;
    }
    public BigDecimal getCodcomarca() {
        return this.codcomarca;
    }
    
    public void setCodcomarca(BigDecimal codcomarca) {
        this.codcomarca = codcomarca;
    }
    public BigDecimal getCodtermino() {
        return this.codtermino;
    }
    
    public void setCodtermino(BigDecimal codtermino) {
        this.codtermino = codtermino;
    }
    public Character getSubtermino() {
        return this.subtermino;
    }
    
    public void setSubtermino(Character subtermino) {
        this.subtermino = subtermino;
    }
    public BigDecimal getCodtipocapital() {
        return this.codtipocapital;
    }
    
    public void setCodtipocapital(BigDecimal codtipocapital) {
        this.codtipocapital = codtipocapital;
    }
    public String getDestipocapital() {
        return this.destipocapital;
    }
    
    public void setDestipocapital(String destipocapital) {
        this.destipocapital = destipocapital;
    }
    public BigDecimal getCodconcepto() {
        return this.codconcepto;
    }
    
    public void setCodconcepto(BigDecimal codconcepto) {
        this.codconcepto = codconcepto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VistaTipoCapitalId) ) return false;
		 VistaTipoCapitalId castOther = ( VistaTipoCapitalId ) other; 
         
		 return ( (this.getLineaseguroid()==castOther.getLineaseguroid()) || ( this.getLineaseguroid()!=null && castOther.getLineaseguroid()!=null && this.getLineaseguroid().equals(castOther.getLineaseguroid()) ) )
 && ( (this.getCodmodulo()==castOther.getCodmodulo()) || ( this.getCodmodulo()!=null && castOther.getCodmodulo()!=null && this.getCodmodulo().equals(castOther.getCodmodulo()) ) )
 && ( (this.getCodcultivo()==castOther.getCodcultivo()) || ( this.getCodcultivo()!=null && castOther.getCodcultivo()!=null && this.getCodcultivo().equals(castOther.getCodcultivo()) ) )
 && ( (this.getCodvariedad()==castOther.getCodvariedad()) || ( this.getCodvariedad()!=null && castOther.getCodvariedad()!=null && this.getCodvariedad().equals(castOther.getCodvariedad()) ) )
 && ( (this.getCodprovincia()==castOther.getCodprovincia()) || ( this.getCodprovincia()!=null && castOther.getCodprovincia()!=null && this.getCodprovincia().equals(castOther.getCodprovincia()) ) )
 && ( (this.getCodcomarca()==castOther.getCodcomarca()) || ( this.getCodcomarca()!=null && castOther.getCodcomarca()!=null && this.getCodcomarca().equals(castOther.getCodcomarca()) ) )
 && ( (this.getCodtermino()==castOther.getCodtermino()) || ( this.getCodtermino()!=null && castOther.getCodtermino()!=null && this.getCodtermino().equals(castOther.getCodtermino()) ) )
 && ( (this.getSubtermino()==castOther.getSubtermino()) || ( this.getSubtermino()!=null && castOther.getSubtermino()!=null && this.getSubtermino().equals(castOther.getSubtermino()) ) )
 && ( (this.getCodtipocapital()==castOther.getCodtipocapital()) || ( this.getCodtipocapital()!=null && castOther.getCodtipocapital()!=null && this.getCodtipocapital().equals(castOther.getCodtipocapital()) ) )
 && ( (this.getCodconcepto()==castOther.getCodconcepto()) || ( this.getCodconcepto()!=null && castOther.getCodconcepto()!=null && this.getCodconcepto().equals(castOther.getCodconcepto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLineaseguroid() == null ? 0 : this.getLineaseguroid().hashCode() );
         result = 37 * result + ( getCodmodulo() == null ? 0 : this.getCodmodulo().hashCode() );
         result = 37 * result + ( getCodcultivo() == null ? 0 : this.getCodcultivo().hashCode() );
         result = 37 * result + ( getCodvariedad() == null ? 0 : this.getCodvariedad().hashCode() );
         result = 37 * result + ( getCodprovincia() == null ? 0 : this.getCodprovincia().hashCode() );
         result = 37 * result + ( getCodcomarca() == null ? 0 : this.getCodcomarca().hashCode() );
         result = 37 * result + ( getCodtermino() == null ? 0 : this.getCodtermino().hashCode() );
         result = 37 * result + ( getSubtermino() == null ? 0 : this.getSubtermino().hashCode() );
         result = 37 * result + ( getCodtipocapital() == null ? 0 : this.getCodtipocapital().hashCode() );
         result = 37 * result + ( getDestipocapital() == null ? 0 : this.getDestipocapital().hashCode() );
         result = 37 * result + ( getCodconcepto() == null ? 0 : this.getCodconcepto().hashCode() );
         return result;
   }   


}


