package com.rsi.agp.dao.tables.commons;
// Generated by T-Systems

public class VistaTerminosAsegurable implements java.io.Serializable {

	private static final long serialVersionUID = 4377093909607118150L;

	private VistaTerminosAsegurableId id;

	public VistaTerminosAsegurable() {
	}

	public VistaTerminosAsegurable(VistaTerminosAsegurableId id) {
		this.id = id;
	}

	public VistaTerminosAsegurableId getId() {
		return this.id;
	}

	public void setId(VistaTerminosAsegurableId id) {
		this.id = id;
	}

}
